function results = auditC172sNonlinearTrim()
%AUDITC172SNONLINEARTRIM Audit equilibrium and bounded trim solution.

model = c172sTrimTotalForceData();
source = c172sNonlinear6DofSourceData();
kernel = c172sRigidBody6DofData();
environment = c172sAtmosphereAirDataData();
aero = c172sNearTrimAerodynamicsData();
longitudinal = c172sLongitudinalData();
lateral = c172sLateralDirectionalData();

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR 6-DOF V1 - TRIM/TOTAL-FORCE AUDIT\n');
fprintf('============================================================\n\n');
fprintf('Artifact                               : %s\n',model.artifactRevision);
fprintf('Near-trim aerodynamics                 : %s\n',aero.artifactRevision);
fprintf('Trim target                            : %.0f ft / %.0f KTAS / %.0f lb\n', ...
    model.trim.altitude_m/0.3048,model.trim.TAS_mps/0.514444444444444, ...
    model.kernel.mass_kg*model.kernel.gravity_mps2/4.4482216152605);
fprintf('Propulsion status                      : %s\n\n',model.propulsion.status);

names = {}; messages = {}; passed = [];
record('Source/convention audit revision', ...
    strcmp(model.required.sourceAudit,source.artifactRevision),source.artifactRevision);
record('Rigid-body kernel revision', ...
    strcmp(model.required.rigidBodyKernel,kernel.artifactRevision),kernel.artifactRevision);
record('Atmosphere/air-data revision', ...
    strcmp(model.required.atmosphereAirData,environment.artifactRevision),environment.artifactRevision);
record('Near-trim aerodynamic revision', ...
    strcmp(model.required.nearTrimAerodynamics,aero.artifactRevision),aero.artifactRevision);
record('Frozen plant revisions', ...
    strcmp(model.required.longitudinalPlant,longitudinal.model.version) && ...
    strcmp(model.required.lateralPlant,lateral.model.version), ...
    'Longitudinal Plant V1 and Lateral-Directional Plant V0.1');
record('Released controller regression remains external', ...
    model.required.masterRegressionPasses == 18,'v1.0.0 remains frozen at 18/18');
record('Aerodynamic reference datum qualified', ...
    ~model.referenceAxis.fuselageIncidenceIdentified && ...
    ~model.referenceAxis.absoluteAircraftAlphaClaim, ...
    'alpha=0 is the frozen reference axis, not measured fuselage incidence');
record('Propulsion claim remains one-point only', ...
    ~model.propulsion.speedScheduleImplemented && ...
    ~model.propulsion.altitudeScheduleImplemented && ...
    ~model.propulsion.propellerMapImplemented && ...
    ~model.propulsion.slipstreamImplemented, ...
    'calibrated trim thrust; no propeller or envelope schedule');

guesses = [0,-2,3;0,-2,2;0.65,0.55,0.80];
solutions = cell(1,size(guesses,2));
for k = 1:size(guesses,2)
    guess = [deg2rad(guesses(1,k));deg2rad(guesses(2,k));guesses(3,k)];
    solutions{k} = solveC172sNonlinearTrim(guess,model);
end
s = solutions{1};
unknownMatrix = cell2mat(cellfun(@(x)x.unknowns,solutions,'UniformOutput',false));
record('Bounded solver converges from displaced guesses', ...
    all(cellfun(@(x)x.converged,solutions)),sprintf('%d independent initial guesses',numel(solutions)));
record('Unique trim solution recovered', ...
    max(max(abs(unknownMatrix-unknownMatrix(:,1)))) <= ...
    model.validation.maximumTrimSpread, ...
    sprintf('maximum solution spread %.3g',max(max(abs(unknownMatrix-unknownMatrix(:,1))))));
record('Frozen trim datum recovered', ...
    abs(s.alpha_rad) < 1e-9 && abs(s.elevator_rad) < 1e-9 && ...
    abs(s.throttle-model.propulsion.nominalTrimThrottle) < 1e-9, ...
    sprintf('alpha %.6f deg, elevator %.6f deg, throttle %.6f', ...
    rad2deg(s.alpha_rad),rad2deg(s.elevator_rad),s.throttle));

tf = s.totalForces;
weight = model.kernel.mass_kg*model.kernel.gravity_mps2;
record('Lift balances weight',abs(tf.lift_N-weight) <= ...
    model.validation.maximumForceResidual_N, ...
    sprintf('lift-weight residual %.3g N',tf.lift_N-weight));
record('Thrust balances drag',abs(tf.thrust_N-tf.drag_N) <= ...
    model.validation.maximumForceResidual_N, ...
    sprintf('thrust-drag residual %.3g N',tf.thrust_N-tf.drag_N));
record('Side force and moments balance', ...
    norm([tf.sideForce_N;tf.totalMomentBody_Nm],inf) <= ...
    model.validation.maximumMomentResidual_Nm, ...
    sprintf('maximum residual %.3g',norm([tf.sideForce_N;tf.totalMomentBody_Nm],inf)));
record('Rigid-body equilibrium derivative', ...
    norm(tf.stateDerivative(1:6),inf) <= model.validation.maximumStateDerivative, ...
    sprintf('maximum dynamic derivative %.3g',norm(tf.stateDerivative(1:6),inf)));
record('Horizontal NED trim velocity', ...
    abs(tf.stateDerivative(9)) <= model.validation.maximumStateDerivative && ...
    abs(tf.stateDerivative(7)-model.trim.TAS_mps) <= model.validation.maximumStateDerivative, ...
    sprintf('N/E/D velocity %.6f / %.6f / %.6f m/s',tf.stateDerivative(7:9)));
record('Quaternion remains unit norm',abs(norm(s.state(10:13))-1) < 1e-14, ...
    sprintf('norm error %.3g',abs(norm(s.state(10:13))-1)));
record('Control bounds respected',all(s.controls >= model.controls.lower) && ...
    all(s.controls <= model.controls.upper),'elevator, aileron, rudder and throttle within declared bounds');

low = s.controls; high = s.controls; low(4)=0.25; high(4)=0.75;
lowForce = c172sTrimTotalForces(s.state,low,0,zeros(3,1),zeros(3,1),model);
highForce = c172sTrimTotalForces(s.state,high,0,zeros(3,1),zeros(3,1),model);
record('Throttle produces monotonic positive thrust', ...
    highForce.thrust_N > lowForce.thrust_N && lowForce.thrust_N > 0, ...
    sprintf('thrust %.2f to %.2f N',lowForce.thrust_N,highForce.thrust_N));
record('Propulsion contributes no moment', ...
    norm(tf.propulsiveMomentBody_Nm,inf)==0,'zero provisional propulsive moment');

replay = solveC172sNonlinearTrim(guessesToColumn(guesses(:,1)),model);
record('Deterministic replay',isequaln(s.state,replay.state) && ...
    isequaln(s.controls,replay.controls) && isequaln(s.residual,replay.residual), ...
    'identical initial guess reproduces bitwise-identical trim');
record('Out-of-bounds initial guess rejected',throws(@() ...
    solveC172sNonlinearTrim([deg2rad(20);0;0.5],model), ...
    'solveC172sNonlinearTrim:InitialGuessOutsideBounds'), ...
    'alpha outside V0.1 cannot enter the solver');
record('Out-of-bounds control rejected',throws(@() ...
    c172sTrimTotalForces(s.state,[0;0;0;1.1],0,zeros(3,1),zeros(3,1),model), ...
    'c172sTrimTotalForces:ControlOutsideBounds'), ...
    'throttle above one cannot enter the total-force layer');
weak = model; weak.propulsion.maximumThrustAtTrim_N = 0.5*model.propulsion.trimDrag_N;
record('Underpowered trim configuration rejected',throws(@() ...
    solveC172sNonlinearTrim([0;0;0.9],weak), ...
    'solveC172sNonlinearTrim:NoConvergence'), ...
    'bounded solver cannot hide insufficient maximum thrust');
record('Coefficient scheduling remains disabled', ...
    ~model.validation.coefficientSchedulingIncluded, ...
    'near-trim frozen coefficients only');
record('Stall and post-stall remain disabled', ...
    ~model.validation.stallIncluded && ~aero.envelope.postStallImplemented, ...
    'no departure or spin claim');
record('Full dynamics linearization remains a next gate', ...
    model.validation.fullDynamicsLinearizationDeferred, ...
    'total-force integration precedes independent 13-state Jacobian audit');

fprintf('\nPassed audit cases                     : %d/%d\n',sum(passed),numel(passed));
fprintf('Trim alpha / elevator / throttle       : %.8f deg / %.8f deg / %.8f\n', ...
    rad2deg(s.alpha_rad),rad2deg(s.elevator_rad),s.throttle);
fprintf('Force / moment residual norms          : %.3g N / %.3g N*m\n', ...
    norm(tf.totalForceBody_N+[0;0;weight],inf),norm(tf.totalMomentBody_Nm,inf));
assert(all(passed),'auditC172sNonlinearTrim:AuditFailed', ...
    '%d of %d trim audit cases failed.',sum(~passed),numel(passed));
fprintf('PASS: bounded level-flight trim is unique and deterministic.\n');
fprintf('PASS: lift/weight and thrust/drag equilibrium balances close.\n');
fprintf('PASS: control bounds and an underpowered no-solution case are enforced.\n');
fprintf('NOTE: thrust is calibrated only at the frozen trim datum; no propeller map is claimed.\n');
fprintf('NOTE: full 13-state integration and linearization remain the next stage; this is not aircraft approval.\n');

results = struct('Name',names(:),'Status',num2cell(passed(:)), ...
    'Message',messages(:));

    function record(name,status,message)
        names{end+1} = name; messages{end+1} = message; passed(end+1) = logical(status);
        if status, tag='PASS'; else, tag='FAIL'; end
        fprintf('[%s] %-48s %s\n',tag,name,message);
    end
end

function value = guessesToColumn(row)
value = [deg2rad(row(1));deg2rad(row(2));row(3)];
end

function yes = throws(action,identifier)
yes = false;
try
    action();
catch exception
    yes = strcmp(exception.identifier,identifier);
end
end
