function auditIntegratedAutopilotInterfaces()
%% C172S Integrated Autopilot V1 - interface and scenario audit

clear;
clc;

integration = c172sIntegratedAutopilotData();
manager = c172sAutopilotModeManagerData();
longitudinal = c172sLongitudinalData();
pitchRate = c172sPitchRateDamperData();
pitchAttitude = c172sPitchAttitudeControllerData();
elevator = c172sElevatorActuatorData();
altitude = c172sAltitudeHoldControllerData();
lateral = c172sLateralDirectionalData();
yaw = c172sYawDamperData();
rudder = c172sRudderActuatorData();
aileron = c172sAileronActuatorData();
roll = c172sRollAttitudeControllerData();
headingSensor = c172sHeadingSensorData();
heading = c172sHeadingHoldControllerData();

name = strings(0,1);
detail = strings(0,1);
passed = false(0,1);

record('Frozen Mode Manager revision', ...
    strcmp(manager.artifactRevision,integration.required.modeManager), ...
    manager.artifactRevision);

dependencyChecks = [ ...
    strcmp(longitudinal.model.version,integration.required.longitudinalPlant); ...
    strcmp(pitchRate.version,integration.required.pitchRateDamper); ...
    strcmp(pitchAttitude.version,integration.required.pitchAttitudeController); ...
    strcmp(elevator.integratedLoopVersion,integration.required.pitchLoop); ...
    strcmp(altitude.version,integration.required.altitudeLoop); ...
    strcmp(lateral.model.version,integration.required.lateralPlant); ...
    strcmp(yaw.artifactRevision,integration.required.yawController); ...
    strcmp(rudder.artifactRevision,integration.required.rudderAudit); ...
    strcmp(aileron.artifactRevision,integration.required.aileronAudit); ...
    strcmp(roll.artifactRevision,integration.required.rollController); ...
    strcmp(headingSensor.artifactRevision,integration.required.headingSensorAudit); ...
    strcmp(heading.artifactRevision,integration.required.headingController)];
record('Twelve frozen plant/controller interfaces',all(dependencyChecks), ...
    sprintf('%d/%d dependency identifiers match',sum(dependencyChecks),numel(dependencyChecks)));

record('Common deterministic execution rate', ...
    abs(integration.execution.fixedStep_s-manager.validation.sampleTime_s) < eps && ...
    abs(integration.execution.supervisorRate_s-manager.validation.sampleTime_s) < eps, ...
    sprintf('fixed step and supervisor rate are %.3f s',integration.execution.fixedStep_s));

record('No false six-DOF coupling claim', ...
    ~integration.execution.plantsAreDynamicallyCoupled, ...
    'plants execute simultaneously but remain dynamically uncoupled');

record('Bank-command authority preserved', ...
    integration.requirements.maximumBankCommand_deg == ...
    manager.capture.bankCommandLimit_deg, ...
    sprintf('+/-%.1f deg',integration.requirements.maximumBankCommand_deg));

record('Pitch-command authority preserved', ...
    integration.requirements.maximumPitchCommand_deg == ...
    manager.capture.pitchCommandLimit_deg && ...
    integration.requirements.maximumPitchCommand_deg == altitude.pitchCommandLimit_deg, ...
    sprintf('+/-%.1f deg',integration.requirements.maximumPitchCommand_deg));

record('Simultaneous heading command is in scope', ...
    integration.commands.simultaneousHeadingStep_deg == ...
    heading.validation.commandStep_deg, ...
    sprintf('%.1f deg',integration.commands.simultaneousHeadingStep_deg));

record('Simultaneous altitude command is in scope', ...
    integration.commands.simultaneousAltitudeStep_ft == ...
    altitude.validation.operationalCommand_ft, ...
    sprintf('%.1f ft',integration.commands.simultaneousAltitudeStep_ft));

record('Tracking-pulse contract preserved', ...
    integration.requirements.requireOneSampleTrackingPulse && ...
    manager.transfer.trackingPulseSamples == 1 && ...
    manager.transfer.requestIntegratorTrackingOnEngagement && ...
    manager.transfer.requestIntegratorTrackingOnModeChange, ...
    'one sample on engagement and mode change');

record('Actuator transfer gates are positive and bounded', ...
    integration.requirements.maximumTransferAileronStep_deg > 0 && ...
    integration.requirements.maximumTransferElevatorStep_deg > 0 && ...
    integration.requirements.maximumTransferAileronStep_deg < ...
    aileron.authority.rightWingDown_deg && ...
    integration.requirements.maximumTransferElevatorStep_deg < ...
    elevator.authority.trailingEdgeDown_deg, ...
    sprintf('aileron/elevator <= %.2f/%.2f deg', ...
    integration.requirements.maximumTransferAileronStep_deg, ...
    integration.requirements.maximumTransferElevatorStep_deg));

record('Disconnect release gates are explicit', ...
    integration.requirements.maximumDisconnectAileronStep_deg > 0 && ...
    integration.requirements.maximumDisconnectElevatorStep_deg > 0, ...
    sprintf('aileron/elevator <= %.2f/%.2f deg', ...
    integration.requirements.maximumDisconnectAileronStep_deg, ...
    integration.requirements.maximumDisconnectElevatorStep_deg));

scenarioCount = numel(integration.scenarios);
record('Integrated scenario ledger complete', ...
    scenarioCount >= integration.validation.minimumScenarioCount && ...
    numel(unique(integration.scenarios)) == scenarioCount, ...
    sprintf('%d unique scenarios',scenarioCount));

record('Altitude validation horizon retained', ...
    integration.validation.altitudeStopTime_s >= altitude.validation.stopTime_s, ...
    sprintf('%.0f s',integration.validation.altitudeStopTime_s));

record('Implementation equivalence gate retained', ...
    integration.requirements.maximumImplementationError <= 1.0e-5, ...
    sprintf('maximum error %.1e',integration.requirements.maximumImplementationError));

record('Deterministic replay remains mandatory', ...
    integration.requirements.requireDeterministicReplay && ...
    manager.validation.requireRepeatableTrace, ...
    'reference and executable traces must replay identically');

fprintf('============================================================\n');
fprintf(' C172S INTEGRATED AUTOPILOT V1 - INTERFACE/SCENARIO AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-37s: %s\n','Artifact',integration.artifactRevision);
fprintf('%-37s: %s\n','Mode Manager',manager.artifactRevision);
fprintf('%-37s: %s / %.3f s\n','Solver / fixed step', ...
    integration.execution.solver,integration.execution.fixedStep_s);
fprintf('%-37s: %d\n\n','Declared integrated scenarios',scenarioCount);
for k = 1:numel(passed)
    label = 'PASS';
    if ~passed(k), label = 'FAIL'; end
    fprintf('[%s] %-43s %s\n',label,name(k),detail(k));
end
fprintf('\nPassed audit cases                   : %d/%d\n',sum(passed),numel(passed));

assert(all(passed),'auditIntegratedAutopilotInterfaces:AuditFailed', ...
    '%d of %d interface/scenario gates failed.',sum(~passed),numel(passed));
fprintf('PASS: every frozen dependency and command authority matches.\n');
fprintf('PASS: actuator-level transfer and disconnect gates are explicit.\n');
fprintf('PASS: the integrated executable scenario ledger is complete.\n');
fprintf(['NOTE: this freezes the integration contract; it does not yet ', ...
    'validate the combined executable model.\n']);
fprintf(['NOTE: the plants remain simultaneous but uncoupled single-trim ', ...
    'models; this is not aircraft approval.\n']);

function record(caseName,condition,caseDetail)
name(end+1,1) = string(caseName); %#ok<SAGROW>
passed(end+1,1) = logical(condition); %#ok<SAGROW>
detail(end+1,1) = string(caseDetail); %#ok<SAGROW>
end
end
