function results = auditC172sFlightControlLabBackends()
%AUDITC172SFLIGHTCONTROLLABBACKENDS Qualify the public COMPARE backend.
%
%   This supplemental gate requires Simulink. It runs one non-trivial
%   HEADING/ALTITUDE mission through both public execution paths and checks
%   the frozen 58-signal tolerance plus scenario-level objectives.

model = c172sNonlinearAutopilotClosedLoopData();
lab = c172sFlightControlLabData(model);

% Force the public runner through the same clean-session condition a user
% encounters before any builder or regression script has populated the base
% workspace. Preserve and restore a pre-existing user variable exactly.
baseVariable = 'na1InputSignal';
baseVariableWasDefined = evalin('base', ...
    sprintf('exist(''%s'',''var'') == 1',baseVariable));
if baseVariableWasDefined
    previousBaseValue = evalin('base',baseVariable);
else
    previousBaseValue = [];
end
evalin('base',sprintf('clear(''%s'')',baseVariable));
baseCleanup = onCleanup(@() restoreBaseVariable( ...
    baseVariable,baseVariableWasDefined,previousBaseValue)); %#ok<NASGU>
if bdIsLoaded(lab.execution.simulinkModel)
    close_system(lab.execution.simulinkModel,0);
end

configuration = struct( ...
    'duration_s',20, ...
    'engage',true, ...
    'engageTime_s',0, ...
    'lateralMode','HEADING', ...
    'verticalMode','ALTITUDE', ...
    'headingChange_deg',5, ...
    'altitudeChange_ft',20);
scenario = createC172sFlightControlScenario('custom',configuration,model);
options = struct('ShowPlots',false,'PrintSummary',false, ...
    'ExportResults',false,'ExportFolder','','Backend','COMPARE');
flightRun = runC172sFlightControlScenario(scenario,options,model);
coldStartClean = ~evalin('base', ...
    sprintf('exist(''%s'',''var'') == 1',baseVariable));

names = { ...
    'Cold-start run is workspace-independent'; ...
    'Public COMPARE backend selected'; ...
    'Frozen 58-signal interface compared'; ...
    'Continuous equivalence tolerance passes'; ...
    'Discrete mode and event signals are exact'; ...
    'MATLAB scenario objective passes'; ...
    'Simulink scenario objective passes'; ...
    'Frozen release chain remains identified'};
passed = [ ...
    coldStartClean; ...
    strcmp(flightRun.executionBackend,'COMPARE'); ...
    flightRun.backendComparison.signalCount == 58; ...
    flightRun.backendComparison.maximumAbsoluteError <= ...
        lab.execution.maximumBackendError; ...
    flightRun.backendComparison.discreteSignalsExact; ...
    flightRun.metrics.overallPass; ...
    flightRun.backendComparison.simulinkOverallPass && flightRun.overallPass; ...
    strcmp(flightRun.backendArtifactRevision,model.artifactRevision)];
messages = { ...
    'required model input is scoped and removed after execution'; ...
    flightRun.executionBackend; ...
    sprintf('%d samples x %d signals', ...
        flightRun.backendComparison.sampleCount, ...
        flightRun.backendComparison.signalCount); ...
    sprintf('maximum error %.9g <= %.9g', ...
        flightRun.backendComparison.maximumAbsoluteError, ...
        lab.execution.maximumBackendError); ...
    'engagement, modes, events and protection flags match'; ...
    'reference mission health and objective pass'; ...
    'executable mission health and objective pass'; ...
    model.artifactRevision};

fprintf('============================================================\n');
fprintf(' C172S FLIGHT-CONTROL LAB V1.1 - PUBLIC BACKEND AUDIT\n');
fprintf('============================================================\n\n');
for k = 1:numel(passed)
    tag = 'PASS'; if ~passed(k), tag = 'FAIL'; end
    fprintf('[%s] %-46s %s\n',tag,names{k},messages{k});
end
fprintf('\nPassed public-backend cases          : %d/%d\n', ...
    sum(passed),numel(passed));
results = struct('Name',names,'Status',num2cell(passed), ...
    'Message',messages);
assert(all(passed), ...
    'auditC172sFlightControlLabBackends:BackendAuditFailed', ...
    '%d of %d public-backend cases failed.',sum(~passed),numel(passed));
fprintf('PASS: Simulink is a qualified public execution backend.\n');
fprintf('PASS: all 58 states/diagnostics remain within %.1e.\n', ...
    lab.execution.maximumBackendError);
end

function restoreBaseVariable(name,wasDefined,value)
if wasDefined
    assignin('base',name,value);
else
    evalin('base',sprintf('clear(''%s'')',name));
end
end
