function results = auditC172sNonlinearAutopilotInterfaces()
%AUDITC172SNONLINEARAUTOPILOTINTERFACES Freeze controller/6-DOF mappings.

interface = c172sNonlinearAutopilotInterfaceData();
integration = c172sIntegratedAutopilotData();
manager = c172sAutopilotModeManagerData();
plant = c172sIntegratedNonlinearDynamicsData();
source = c172sNonlinear6DofSourceData();
trimData = c172sTrimTotalForceData();
elevator = c172sElevatorActuatorData();
aileron = c172sAileronActuatorData();
rudder = c172sRudderActuatorData();
trim = solveC172sNonlinearTrim([],plant.trimModel);

names = strings(0,1);
details = strings(0,1);
passed = false(0,1);

record('Frozen Integrated Autopilot revision', ...
    strcmp(interface.required.integratedAutopilot, ...
    integration.artifactRevision),integration.artifactRevision);
record('Frozen Mode Manager revision', ...
    strcmp(interface.required.modeManager,manager.artifactRevision), ...
    manager.artifactRevision);
record('Frozen nonlinear dynamics revision', ...
    strcmp(interface.required.nonlinearDynamics,plant.artifactRevision), ...
    plant.artifactRevision);
record('Frozen source/convention revision', ...
    strcmp(interface.required.sourceConvention,source.artifactRevision), ...
    source.artifactRevision);
record('Released actuator paths remain frozen', ...
    strcmp(interface.required.elevatorLoop,elevator.integratedLoopVersion) && ...
    strcmp(interface.required.aileronAudit,aileron.artifactRevision) && ...
    strcmp(interface.required.rudderAudit,rudder.artifactRevision), ...
    'elevator, aileron and rudder dependency identifiers match');
record('Regression evidence ledger preserved', ...
    interface.required.flightControlRegressionPasses == 18 && ...
    interface.required.nonlinearRegressionPasses == 7 && ...
    interface.required.combinedProjectPasses == 25, ...
    '18/18 controller + 7/7 nonlinear = 25/25 external evidence');

record('Thirteen-state plant contract preserved', ...
    interface.plant.stateCount == 13 && plant.state.count == 13 && ...
    isequal(interface.plant.stateNames(:),plant.state.names(:)), ...
    'u v w p q r, NED position and scalar-first quaternion');
record('Four-control plant contract preserved', ...
    interface.plant.controlCount == 4 && plant.control.count == 4 && ...
    isequal(interface.plant.controlNames(:),plant.control.names(:)), ...
    'elevator, aileron, rudder and throttle ordering matches');
record('Common frozen trim point preserved', ...
    interface.trim.altitude_ft == 4000 && ...
    interface.trim.TAS_KTAS == 110 && ...
    interface.trim.weight_lb == 2550 && ...
    abs(interface.trim.altitude_m-trimData.trim.altitude_m) < 1e-12 && ...
    abs(interface.trim.TAS_mps-trimData.trim.TAS_mps) < 1e-12, ...
    '4000 ft ISA / 110 KTAS / 2550 lb');
record('Common deterministic execution rate', ...
    strcmp(interface.execution.solver,integration.execution.solver) && ...
    interface.execution.fixedStep_s == integration.execution.fixedStep_s && ...
    interface.execution.supervisorSampleTime_s == ...
    manager.validation.sampleTime_s && ...
    interface.execution.controllerSampleTime_s == ...
    manager.validation.sampleTime_s && ...
    interface.execution.fixedStep_s == plant.integration.fixedStep_s, ...
    'ode4 / 0.010 s for plant, controllers and supervisor');

record('Actuator dynamics have one owner', ...
    interface.controls.inputRepresentsActualSurfacePosition && ...
    ~interface.controls.adapterAddsActuatorDynamics && ...
    ~interface.controls.adapterAddsRateLimiting && ...
    ~interface.controls.adapterAddsSaturation, ...
    'released controller stacks own dynamics, rates and limits');
record('Control adapter is identity plus trim', ...
    isequal(interface.controls.surfaceMappingMatrix,eye(3)) && ...
    norm(interface.controls.surfaceTrimOffset_rad,inf) == 0, ...
    'actual controller surfaces map one-to-one at the zero-surface trim');
record('Nonlinear trim control vector recovered', ...
    norm(interface.trim.controlVector-trim.controls,inf) <= ...
    interface.validation.maximumTrimMappingError, ...
    sprintf('[deltaE deltaA deltaR throttle] = [0 0 0 %.2f]', ...
    interface.trim.throttle));

small = deg2rad(0.25);
elevatorControl = mapControls([small;0;0],interface);
aileronControl = mapControls([0;small;0],interface);
rudderControl = mapControls([0;0;small],interface);
record('Elevator sign maps without inversion', ...
    elevatorControl(1) > trim.controls(1), ...
    'positive controller elevator remains trailing-edge down');
record('Aileron sign maps without inversion', ...
    aileronControl(2) > trim.controls(2), ...
    'positive controller aileron remains right-wing-down');
record('Rudder sign maps without inversion', ...
    rudderControl(3) > trim.controls(3), ...
    'positive controller rudder remains nose-right');
record('Throttle ownership remains explicit', ...
    ~interface.controls.autothrottleImplemented && ...
    abs(interface.controls.fixedThrottle-trim.controls(4)) <= ...
    interface.validation.maximumTrimMappingError && ...
    abs(elevatorControl(4)-trim.controls(4)) <= ...
    interface.validation.maximumTrimMappingError, ...
    'fixed one-point throttle 0.65; no autothrottle claim');

authorityMatch = abs(interface.plant.controlLower(1)- ...
    elevator.authority.lowerLimit_rad) < eps && ...
    abs(interface.plant.controlUpper(1)- ...
    elevator.authority.upperLimit_rad) < eps && ...
    abs(interface.plant.controlLower(2)- ...
    aileron.authority.lowerLimit_rad) < eps && ...
    abs(interface.plant.controlUpper(2)- ...
    aileron.authority.upperLimit_rad) < eps && ...
    abs(interface.plant.controlLower(3)- ...
    rudder.authority.lowerLimit_rad) < eps && ...
    abs(interface.plant.controlUpper(3)- ...
    rudder.authority.upperLimit_rad) < eps && ...
    norm(interface.plant.controlLower-trimData.controls.lower,inf) < eps && ...
    norm(interface.plant.controlUpper-trimData.controls.upper,inf) < eps;
record('Automatic surface authorities are compatible',authorityMatch, ...
    'plant and released actuator paths share +/-5-deg bounds');
record('Out-of-bounds surfaces are rejected',throws(@() ...
    mapControls([deg2rad(5.01);0;0],interface), ...
    'auditC172sNonlinearAutopilotInterfaces:SurfaceOutsideBounds'), ...
    'adapter does not silently clip or enlarge actuator authority');

zeroWind = zeros(3,1);
[trimDerivative,~] = c172sIntegratedNonlinearDynamics( ...
    trim.state,trim.controls,zeroWind,zeroWind,plant);
trimFeedback = mapFeedback(trim.state,trimDerivative,zeroWind,zeroWind, ...
    interface,plant);

record('Scalar-first body-to-NED quaternion preserved', ...
    strcmp(interface.plant.quaternionOrder,source.state.quaternionOrder) && ...
    abs(trim.state(10)-1) <= ...
    interface.validation.maximumAngleConversionError && ...
    norm(trim.state(11:13),inf) <= ...
    interface.validation.maximumAngleConversionError, ...
    'trim quaternion [1 0 0 0]');
record('Identity quaternion maps to level attitude', ...
    max(abs([trimFeedback.controller.phi_rad, ...
    trimFeedback.controller.theta_rad, ...
    trimFeedback.controller.psi_rad])) <= ...
    interface.validation.maximumAngleConversionError, ...
    'phi/theta/psi are zero at trim');

testEuler = deg2rad([12;-7;31]);
testState = trim.state;
testState(10:13) = eulerToQuaternion( ...
    testEuler(1),testEuler(2),testEuler(3));
testFeedback = mapFeedback(testState,trimDerivative,zeroWind,zeroWind, ...
    interface,plant);
eulerError = max(abs([testFeedback.controller.phi_rad; ...
    testFeedback.controller.theta_rad; ...
    testFeedback.controller.psi_rad]-testEuler));
record('Quaternion-to-Euler sequence is correct', ...
    eulerError <= interface.validation.maximumAngleConversionError, ...
    sprintf('3-2-1 round-trip error %.3g rad',eulerError));
record('Positive bank sign is preserved', ...
    testFeedback.supervisor.bank_deg > 0, ...
    'positive phi reports right-wing-down bank');
positivePitch = makeAngleFeedback(0,5,0,trim,trimDerivative, ...
    interface,plant);
record('Positive pitch sign is preserved', ...
    positivePitch.pitch_deg > 0, ...
    'positive theta reports nose-up pitch');
positiveHeading = makeAngleFeedback(0,0,5,trim,trimDerivative, ...
    interface,plant);
record('Positive heading sign is preserved', ...
    positiveHeading.heading_deg > 0, ...
    'positive psi reports clockwise/nose-right heading');

negativeHeading = makeAngleFeedback(0,0,-10,trim,trimDerivative, ...
    interface,plant);
largeHeading = makeAngleFeedback(0,0,370,trim,trimDerivative, ...
    interface,plant);
record('Heading normalization is circular', ...
    abs(negativeHeading.heading_deg-350) < ...
    interface.validation.maximumAngleConversionError && ...
    abs(largeHeading.heading_deg-10) < ...
    interface.validation.maximumAngleConversionError, ...
    '-10 deg -> 350 deg and 370 deg -> 10 deg');

record('NED-down altitude sign is preserved', ...
    abs(trimFeedback.supervisor.altitude_ft-4000) <= ...
    interface.validation.maximumUnitConversionError, ...
    'positionDown = -1219.2 m maps to +4000 ft');
climbDerivative = trimDerivative;
climbDerivative(9) = -2.0;
climbFeedback = mapFeedback(trim.state,climbDerivative,zeroWind,zeroWind, ...
    interface,plant);
record('Vertical-speed sign is climb-positive', ...
    climbFeedback.controller.verticalSpeed_mps == 2.0, ...
    'positionDownDot -2 m/s maps to climb +2 m/s');
record('Trim altitude perturbation is zero', ...
    abs(trimFeedback.controller.altitudePerturbation_m) <= ...
    interface.validation.maximumTrimMappingError, ...
    'absolute 4000 ft becomes zero outer-loop perturbation');
record('Trim controller feedback is zero', ...
    max(abs([trimFeedback.controller.q_radps, ...
    trimFeedback.controller.theta_rad, ...
    trimFeedback.controller.verticalSpeed_mps, ...
    trimFeedback.controller.p_radps, ...
    trimFeedback.controller.r_radps, ...
    trimFeedback.controller.phi_rad, ...
    trimFeedback.controller.psi_rad])) <= ...
    interface.validation.maximumTrimMappingError, ...
    'rates, attitudes and vertical speed close at trim');

record('Controller feedback units are frozen', ...
    interface.feedback.controllerCount == 8 && ...
    isequal(interface.feedback.controllerUnits(:), ...
    {'rad/s';'rad';'m';'m/s';'rad/s';'rad/s';'rad';'rad'}), ...
    'inner/outer loops retain rad, rad/s, m and m/s');
record('Supervisor feedback units are frozen', ...
    interface.feedback.supervisorCount == 4 && ...
    abs(trimFeedback.supervisor.altitude_ft- ...
    interface.initialization.altitude_ft) < 1e-10, ...
    'Mode Manager receives bank/pitch/heading deg and absolute altitude ft');
record('Degree/radian conversion is reciprocal', ...
    abs(interface.conversions.radToDeg*interface.conversions.degToRad-1) < ...
    interface.validation.maximumAngleConversionError, ...
    'rad<->deg mapping has unit product');
record('Foot/metre conversion is reciprocal', ...
    abs(interface.conversions.mToFt*interface.conversions.ftToM-1) < ...
    interface.validation.maximumUnitConversionError, ...
    'm<->ft mapping has unit product');

trimCommands = mapCommands([0;0;0;4000],interface);
testCommands = mapCommands([10;-2;370;4100],interface);
record('Supervisor command names are frozen', ...
    interface.commands.count == 4 && ...
    isequal(interface.commands.managerNames(:), ...
    {'bankCommand_deg';'pitchCommand_deg';'headingCommand_deg'; ...
    'altitudeCommand_ft'}), ...
    'Mode Manager degree/foot outputs are explicit');
record('Bank command converts degrees to radians', ...
    abs(testCommands.bankCommand_rad-deg2rad(10)) <= ...
    interface.validation.maximumAngleConversionError, ...
    '10 deg maps to pi/18 rad');
record('Pitch command converts degrees to radians', ...
    abs(testCommands.pitchCommand_rad-deg2rad(-2)) <= ...
    interface.validation.maximumAngleConversionError, ...
    '-2 deg maps without sign inversion');
record('Heading command is normalized in radians', ...
    abs(testCommands.headingCommand_rad-deg2rad(10)) <= ...
    interface.validation.maximumAngleConversionError, ...
    '370 deg maps to 10 deg on the circular heading domain');
record('Altitude command becomes a trim perturbation', ...
    abs(testCommands.altitudeCommandPerturbation_m-30.48) <= ...
    interface.validation.maximumUnitConversionError && ...
    abs(trimCommands.altitudeCommandPerturbation_m) <= ...
    interface.validation.maximumTrimMappingError, ...
    '4100 ft maps to +30.48 m; 4000 ft maps to zero');
record('Command adapter adds no hidden dynamics', ...
    ~interface.commands.adapterAddsFiltering && ...
    interface.commands.enableAndTrackingSignalsPassUnchanged, ...
    'mode enables and one-sample tracking requests retain their owner');
record('Manager attitude commands stay inside monitor bounds', ...
    manager.capture.bankCommandLimit_deg <= ...
    interface.envelope.bank_deg(2) && ...
    manager.capture.pitchCommandLimit_deg <= ...
    interface.envelope.pitch_deg(2), ...
    '20-deg bank and 3-deg pitch commands remain inside V0.1 monitors');
record('Invalid manager command dimensions are rejected',throws(@() ...
    mapCommands(zeros(3,1),interface), ...
    'auditC172sNonlinearAutopilotInterfaces:InvalidCommandInput'), ...
    'command adapter requires bank, pitch, heading and altitude');

record('Wind and gust stay in NED ownership', ...
    ~interface.wind.adapterRotatesWind && ...
    interface.wind.plantAirDataOwnsRotation, ...
    'adapter passes both three-component NED vectors unchanged');
record('Supervisor status ownership remains external', ...
    contains(interface.validity.aileronSaturatedOwner,'aileron') && ...
    contains(interface.validity.elevatorSaturatedOwner,'elevator') && ...
    contains(interface.validity.pilotOverrideOwner,'external'), ...
    'saturation and pilot-override Booleans are not inferred from state');
record('Ideal trim sensor validity closes', ...
    trimFeedback.validity.coreSensorsValid && ...
    trimFeedback.validity.headingValid && ...
    trimFeedback.validity.altitudeValid && ...
    trimFeedback.validity.airDataValid, ...
    'core, heading, altitude and air-data validity are true');
record('Invalid quaternion is rejected',throws(@() ...
    mapFeedback([trim.state(1:9);zeros(4,1)],trimDerivative, ...
    zeroWind,zeroWind,interface,plant), ...
    'auditC172sNonlinearAutopilotInterfaces:InvalidQuaternion'), ...
    'zero-norm attitude cannot enter the adapter');
record('Invalid feedback dimensions are rejected',throws(@() ...
    mapFeedback(trim.state(1:12),trimDerivative,zeroWind,zeroWind, ...
    interface,plant), ...
    'auditC172sNonlinearAutopilotInterfaces:InvalidState'), ...
    'adapter requires 13-state and 13-derivative columns');

record('V0.1 envelope monitor is active at trim', ...
    trimFeedback.monitor.withinV01Envelope, ...
    sprintf('TAS %.3f m/s, alpha %.3g deg, beta %.3g deg', ...
    trimFeedback.monitor.TAS_mps,rad2deg(trimFeedback.monitor.alpha_rad), ...
    rad2deg(trimFeedback.monitor.beta_rad)));
record('Initialization contract matches trim', ...
    abs(interface.initialization.heading_deg- ...
    trimFeedback.supervisor.heading_deg) <= ...
    interface.validation.maximumAngleConversionError && ...
    abs(interface.initialization.altitude_ft- ...
    trimFeedback.supervisor.altitude_ft) <= ...
    interface.validation.maximumUnitConversionError && ...
    norm(mapControls(zeros(3,1),interface)-trim.controls,inf) <= ...
    interface.validation.maximumTrimMappingError, ...
    'trim state, zero released surfaces and throttle 0.65');

replayFeedback = mapFeedback(trim.state,trimDerivative,zeroWind,zeroWind, ...
    interface,plant);
record('Deterministic adapter replay', ...
    interface.execution.requireDeterministicReplay && ...
    interface.validation.requireDeterministicReplay && ...
    isequaln(trimFeedback,replayFeedback), ...
    'identical state, derivative and environment reproduce identical signals');
record('No sensor-imperfection claim is introduced', ...
    contains(interface.assumptions{1},'ideal deterministic'), ...
    'bias, noise, quantization, delay and failures remain outside this adapter');
record('No pilot-force or autothrottle path is invented', ...
    ~interface.controls.pilotSurfaceSummationImplemented && ...
    ~interface.controls.autothrottleImplemented && ...
    interface.controls.pilotOverrideStatusRemainsExternal, ...
    'pilot override is Boolean and throttle remains fixed');
record('Next executable ownership gates are explicit', ...
    interface.validation.nextExecutableMustUseSingleCoupledPlant && ...
    interface.validation.nextExecutableMustPreserveActuatorProtection && ...
    interface.validation.nextExecutableMustPreserveModeManager, ...
    'single nonlinear plant plus frozen protection and supervisor');

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR AUTOPILOT V1 - INTERFACE AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',interface.artifactRevision);
fprintf('%-39s: %s\n','Controller release', ...
    interface.required.flightControlsRelease);
fprintf('%-39s: %s\n','Nonlinear plant release', ...
    interface.required.nonlinearPlantRelease);
fprintf('%-39s: %s / %.3f s\n\n','Solver / fixed step', ...
    interface.execution.solver,interface.execution.fixedStep_s);
for k = 1:numel(passed)
    label = 'PASS';
    if ~passed(k), label = 'FAIL'; end
    fprintf('[%s] %-48s %s\n',label,names(k),details(k));
end
fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));

assert(numel(passed) >= interface.validation.minimumAuditCases, ...
    'auditC172sNonlinearAutopilotInterfaces:IncompleteLedger', ...
    'Only %d interface cases exist; at least %d are required.', ...
    numel(passed),interface.validation.minimumAuditCases);
assert(all(passed), ...
    'auditC172sNonlinearAutopilotInterfaces:AuditFailed', ...
    '%d of %d nonlinear-autopilot interface cases failed.', ...
    sum(~passed),numel(passed));
fprintf('PASS: actuator positions map to the plant without duplicate dynamics.\n');
fprintf('PASS: quaternion/NED states map to all frozen feedback channels.\n');
fprintf('PASS: signs, units, trim offsets, validity and ownership are frozen.\n');
fprintf(['NOTE: this validates the interface contract only; closed-loop ', ...
    'nonlinear performance remains the next executable gate.\n']);
fprintf(['NOTE: V0.1 remains near-trim with one-point thrust and ideal ', ...
    'sensor interfaces; this is not aircraft approval.\n']);

results = struct('Name',cellstr(names),'Status',num2cell(passed), ...
    'Detail',cellstr(details));

    function record(name,status,detail)
        names(end+1,1) = string(name); %#ok<AGROW>
        passed(end+1,1) = logical(status); %#ok<AGROW>
        details(end+1,1) = string(detail); %#ok<AGROW>
    end
end

function controls = mapControls(actualSurface_rad,interface)
if ~(isnumeric(actualSurface_rad) && isreal(actualSurface_rad) && ...
        isequal(size(actualSurface_rad),[3,1]) && ...
        all(isfinite(actualSurface_rad)))
    error('auditC172sNonlinearAutopilotInterfaces:InvalidSurfaceInput', ...
        'Actual surface input must be a finite real 3x1 column.');
end
surface = interface.controls.surfaceTrimOffset_rad+ ...
    interface.controls.surfaceMappingMatrix*actualSurface_rad;
if any(surface < interface.plant.controlLower(1:3)-1e-14) || ...
        any(surface > interface.plant.controlUpper(1:3)+1e-14)
    error('auditC172sNonlinearAutopilotInterfaces:SurfaceOutsideBounds', ...
        'An actual surface position exceeds the frozen plant authority.');
end
controls = [surface;interface.controls.fixedThrottle];
end

function commands = mapCommands(managerCommands,interface)
if ~(isnumeric(managerCommands) && isreal(managerCommands) && ...
        isequal(size(managerCommands),[4,1]) && ...
        all(isfinite(managerCommands)))
    error('auditC172sNonlinearAutopilotInterfaces:InvalidCommandInput', ...
        'Manager command input must be a finite real 4x1 column.');
end
commands.bankCommand_rad = ...
    managerCommands(1)*interface.conversions.degToRad;
commands.pitchCommand_rad = ...
    managerCommands(2)*interface.conversions.degToRad;
commands.headingCommand_rad = mod( ...
    managerCommands(3)*interface.conversions.degToRad,2*pi);
commands.altitudeCommandPerturbation_m = ...
    (managerCommands(4)-interface.trim.altitude_ft)* ...
    interface.conversions.ftToM;
end

function feedback = mapFeedback(state,stateDerivative,steadyWind,gust, ...
    interface,plant)
if ~(isnumeric(state) && isreal(state) && isequal(size(state),[13,1]) && ...
        all(isfinite(state))) || ...
   ~(isnumeric(stateDerivative) && isreal(stateDerivative) && ...
        isequal(size(stateDerivative),[13,1]) && ...
        all(isfinite(stateDerivative)))
    error('auditC172sNonlinearAutopilotInterfaces:InvalidState', ...
        'State and state derivative must be finite real 13x1 columns.');
end
if ~(isnumeric(steadyWind) && isequal(size(steadyWind),[3,1]) && ...
        all(isfinite(steadyWind))) || ...
   ~(isnumeric(gust) && isequal(size(gust),[3,1]) && all(isfinite(gust)))
    error('auditC172sNonlinearAutopilotInterfaces:InvalidWind', ...
        'Steady wind and gust must be finite 3x1 NED columns.');
end

q = state(10:13);
qNorm = norm(q);
if qNorm <= eps || ...
        abs(qNorm-1) > interface.validity.maximumQuaternionNormError
    error('auditC172sNonlinearAutopilotInterfaces:InvalidQuaternion', ...
        'Quaternion norm is outside the frozen interface tolerance.');
end
q = q/qNorm;
[phi,theta,psiRaw] = quaternionToEuler(q);
psi = mod(psiRaw,2*pi);
altitude_m = -state(9);
verticalSpeed_mps = -stateDerivative(9);
air = c172sAtmosphereAirData(state,steadyWind,gust, ...
    plant.trimModel.aerodynamics.airDataModel);

feedback.controller.q_radps = state(5);
feedback.controller.theta_rad = theta;
feedback.controller.altitudePerturbation_m = ...
    altitude_m-interface.trim.altitude_m;
feedback.controller.verticalSpeed_mps = verticalSpeed_mps;
feedback.controller.p_radps = state(4);
feedback.controller.r_radps = state(6);
feedback.controller.phi_rad = phi;
feedback.controller.psi_rad = psi;

feedback.supervisor.bank_deg = rad2deg(phi);
feedback.supervisor.pitch_deg = rad2deg(theta);
feedback.supervisor.heading_deg = mod(rad2deg(psi),360);
feedback.supervisor.altitude_ft = ...
    altitude_m*interface.conversions.mToFt;

feedback.monitor.TAS_mps = air.TAS_mps;
feedback.monitor.alpha_rad = air.alpha_rad;
feedback.monitor.beta_rad = air.beta_rad;
feedback.monitor.quaternionNorm = qNorm;
feedback.monitor.withinV01Envelope = air.valid && ...
    air.TAS_mps >= interface.envelope.V_KTAS(1)*0.514444444444444 && ...
    air.TAS_mps <= interface.envelope.V_KTAS(2)*0.514444444444444 && ...
    air.alpha_rad >= deg2rad(interface.envelope.alpha_deg(1)) && ...
    air.alpha_rad <= deg2rad(interface.envelope.alpha_deg(2)) && ...
    air.beta_rad >= deg2rad(interface.envelope.beta_deg(1)) && ...
    air.beta_rad <= deg2rad(interface.envelope.beta_deg(2)) && ...
    phi >= deg2rad(interface.envelope.bank_deg(1)) && ...
    phi <= deg2rad(interface.envelope.bank_deg(2)) && ...
    theta >= deg2rad(interface.envelope.pitch_deg(1)) && ...
    theta <= deg2rad(interface.envelope.pitch_deg(2));

feedback.validity.coreSensorsValid = all(isfinite(state(4:6))) && ...
    abs(qNorm-1) <= interface.validity.maximumQuaternionNormError;
feedback.validity.headingValid = feedback.validity.coreSensorsValid && ...
    isfinite(psi);
feedback.validity.altitudeValid = isfinite(altitude_m);
feedback.validity.airDataValid = air.valid;
end

function supervisor = makeAngleFeedback(phi_deg,theta_deg,psi_deg,trim, ...
    stateDerivative,interface,plant)
state = trim.state;
state(10:13) = eulerToQuaternion( ...
    deg2rad(phi_deg),deg2rad(theta_deg),deg2rad(psi_deg));
feedback = mapFeedback(state,stateDerivative,zeros(3,1),zeros(3,1), ...
    interface,plant);
supervisor = feedback.supervisor;
end

function q = eulerToQuaternion(phi,theta,psi)
cr = cos(phi/2); sr = sin(phi/2);
cp = cos(theta/2); sp = sin(theta/2);
cy = cos(psi/2); sy = sin(psi/2);
q = [ ...
    cr*cp*cy+sr*sp*sy; ...
    sr*cp*cy-cr*sp*sy; ...
    cr*sp*cy+sr*cp*sy; ...
    cr*cp*sy-sr*sp*cy];
q = q/norm(q);
end

function [phi,theta,psi] = quaternionToEuler(q)
q0 = q(1); q1 = q(2); q2 = q(3); q3 = q(4);
phi = atan2(2*(q0*q1+q2*q3),1-2*(q1^2+q2^2));
argument = 2*(q0*q2-q3*q1);
argument = min(max(argument,-1),1);
theta = asin(argument);
psi = atan2(2*(q0*q3+q1*q2),1-2*(q2^2+q3^2));
end

function yes = throws(action,identifier)
yes = false;
try
    action();
catch exception
    yes = strcmp(exception.identifier,identifier);
end
end
