function results = auditC172sNonlinearAutopilotClosedLoop()
%AUDITC172SNONLINEARAUTOPILOTCLOSEDLOOP Coupled closed-loop MATLAB audit.
%
% This audit connects the frozen Mode Manager and released protected
% controller laws to one coupled nonlinear 13-state research plant. It
% deliberately remains inside the V0.1 near-trim attached-flow boundary.

model = c172sNonlinearAutopilotClosedLoopData();
manager = model.dependencies.manager;
interface = model.dependencies.interface;
plant = model.dependencies.plant;

names = cell(0,1);
passed = false(0,1);
messages = cell(0,1);

record('Frozen nonlinear-autopilot interface revision', ...
    strcmp(model.required.interface,interface.artifactRevision), ...
    interface.artifactRevision);
record('Frozen Mode Manager revision', ...
    strcmp(model.required.modeManager,manager.artifactRevision), ...
    manager.artifactRevision);
record('Frozen nonlinear dynamics revision', ...
    strcmp(model.required.nonlinearDynamics,plant.artifactRevision), ...
    plant.artifactRevision);
record('Controller and plant releases remain external', ...
    strcmp(model.required.controllerRelease,'v1.0.0') && ...
    strcmp(model.required.nonlinearRelease,'v0.1.0'), ...
    'controller v1.0.0 and nonlinear plant v0.1.0 remain frozen');
record('External regression ledger preserved', ...
    model.required.externalRegressionPasses == 25, ...
    '18/18 controller plus 7/7 nonlinear release gates');
record('One coupled aircraft state is retained', ...
    model.state.plantCount == 13 && ...
    isequal(model.state.plantNames,interface.plant.stateNames), ...
    'single 13-state quaternion/NED aircraft');
record('Controller state ownership is explicit', ...
    model.state.controllerCount == 13 && model.state.totalCount == 26 && ...
    numel(unique(struct2array(model.state.index))) == 13, ...
    '13 aircraft plus 13 controller states');
record('Actuator states have exactly one owner', ...
    ~interface.controls.adapterAddsActuatorDynamics && ...
    interface.controls.inputRepresentsActualSurfacePosition, ...
    'released controller positions drive the plant directly');
record('Hybrid execution rate is frozen', ...
    abs(model.execution.fixedStep_s-0.01) < eps && ...
    abs(model.execution.supervisorSampleTime_s-0.01) < eps, ...
    'RK4 and Mode Manager execute at 0.010 s');
record('Accepted sensor delays are retained', ...
    model.delay.yawRateSamples == 1 && ...
    model.delay.rollRateSamples == 1 && ...
    model.delay.bankAngleSamples == 1 && ...
    model.delay.headingSamples == 5, ...
    'r/p/phi delays 1 sample; heading delay 5 samples');
record('One-point throttle ownership is unchanged', ...
    abs(model.trim.controls(4)-0.65) < eps && ...
    ~interface.controls.autothrottleImplemented, ...
    'fixed trim throttle 0.65; no autothrottle');

trim = simulateC172sNonlinearAutopilot(makeScenario('trim',model),model);
capture = simulateC172sNonlinearAutopilot( ...
    makeScenario('capture',model),model);
outerScenario = makeScenario('outer',model);
outer = simulateC172sNonlinearAutopilot(outerScenario,model);
headingFallback = simulateC172sNonlinearAutopilot( ...
    makeScenario('headingFallback',model),model);
altitudeFallback = simulateC172sNonlinearAutopilot( ...
    makeScenario('altitudeFallback',model),model);
disconnect = simulateC172sNonlinearAutopilot( ...
    makeScenario('disconnect',model),model);
override = simulateC172sNonlinearAutopilot( ...
    makeScenario('override',model),model);
aileronSaturation = simulateC172sNonlinearAutopilot( ...
    makeScenario('aileronSaturation',model),model);
elevatorSaturation = simulateC172sNonlinearAutopilot( ...
    makeScenario('elevatorSaturation',model),model);
wind = simulateC172sNonlinearAutopilot(makeScenario('wind',model),model);

dynamicColumns = [1:6,9:13];
trimDynamicError = max(abs(trim.plantState(:,dynamicColumns)- ...
    model.trim.state(dynamicColumns).'),[],'all');
trimSurfaceError = max(abs(trim.control(:,1:3)),[],'all');
record('Disengaged nonlinear trim remains equilibrium', ...
    trimDynamicError <= model.validation.maximumTrimDynamicStateError, ...
    sprintf('maximum non-navigation state error %.3g',trimDynamicError));
record('Disengaged actuator outputs are released', ...
    rad2deg(trimSurfaceError) <= ...
    model.validation.maximumReleasedSurface_deg, ...
    sprintf('maximum surface %.3g deg',rad2deg(trimSurfaceError)));
record('Disengaged supervisor remains OFF/OFF', ...
    ~any(trim.engaged) && ...
    all(trim.lateralMode == manager.codes.lateral.OFF) && ...
    all(trim.verticalMode == manager.codes.vertical.OFF), ...
    'no automatic axis engages without an engage request');
record('Trim quaternion remains normalized', ...
    max(abs(trim.quaternionNorm-1)) <= ...
    model.validation.maximumQuaternionNormError, ...
    sprintf('maximum norm error %.3g',max(abs(trim.quaternionNorm-1))));
record('Trim remains inside the V0.1 envelope',all(trim.withinEnvelope), ...
    sprintf('violation samples %d',sum(~trim.withinEnvelope)));

record('ROLL plus PITCH capture engages both axes', ...
    all(capture.engaged) && ...
    all(capture.lateralMode == manager.codes.lateral.ROLL) && ...
    all(capture.verticalMode == manager.codes.vertical.PITCH), ...
    'default ROLL/PITCH modes remain active');
record('Engagement emits one-sample tracking requests', ...
    capture.rollTrackRequest(1) && capture.pitchTrackRequest(1) && ...
    sum(capture.rollTrackRequest) == 1 && ...
    sum(capture.pitchTrackRequest) == 1, ...
    'one roll and one pitch preload pulse');
captureDynamicError = max(abs(capture.plantState(:,dynamicColumns)- ...
    model.trim.state(dynamicColumns).'),[],'all');
record('Capture-on-engage is bumpless at trim', ...
    captureDynamicError <= model.validation.maximumTrimDynamicStateError, ...
    sprintf('maximum non-navigation state error %.3g',captureDynamicError));

headingTarget = model.validation.headingCommand_deg;
altitudeTarget = interface.trim.altitude_ft+ ...
    model.validation.altitudeCommand_ft;
headingError = abs(rad2deg(wrapAngle( ...
    deg2rad(headingTarget)-outer.euler_rad(end,3))));
altitudeError = abs(altitudeTarget-outer.altitude_ft(end));
record('Simultaneous HEADING plus ALTITUDE remains engaged', ...
    all(outer.engaged) && ...
    all(outer.lateralMode == manager.codes.lateral.HEADING) && ...
    all(outer.verticalMode == manager.codes.vertical.ALTITUDE), ...
    'both outer modes execute on one nonlinear plant');
record('Heading acquisition closes', ...
    headingError <= model.validation.maximumFinalHeadingError_deg, ...
    sprintf('final circular heading error %.6f deg',headingError));
record('Altitude acquisition closes', ...
    altitudeError <= model.validation.maximumFinalAltitudeError_ft, ...
    sprintf('final altitude error %.6f ft',altitudeError));
ratePeaks = max(abs(rad2deg(outer.plantState(:,4:6))),[],1);
record('Coupled rotational axes all respond', ...
    all(ratePeaks >= model.validation.minimumDrivenRate_degps), ...
    sprintf('peak p/q/r %.5f/%.5f/%.5f deg/s',ratePeaks));
surfacePeaks = max(abs(rad2deg(outer.control(:,1:3))),[],1);
record('Automatic surface authorities are respected', ...
    all(surfacePeaks <= 5+ ...
    model.validation.maximumSurfaceLimitTolerance_deg), ...
    sprintf('peak elevator/aileron/rudder %.5f/%.5f/%.5f deg', ...
    surfacePeaks));
surfaceRatePeaks = max(abs(rad2deg(outer.surfaceRate_radps)),[],1);
record('All actuator-rate limits are respected', ...
    surfaceRatePeaks(1) <= 20+ ...
    model.validation.maximumRateLimitTolerance_degps && ...
    surfaceRatePeaks(2) <= 30+ ...
    model.validation.maximumRateLimitTolerance_degps && ...
    surfaceRatePeaks(3) <= 20+ ...
    model.validation.maximumRateLimitTolerance_degps, ...
    sprintf('peak elevator/aileron/rudder rates %.5f/%.5f/%.5f deg/s', ...
    surfaceRatePeaks));
I = model.state.index;
mappedSurfaces = [outer.controllerState(:,I.elevatorActual), ...
    outer.controllerState(:,I.aileronActual), ...
    outer.controllerState(:,I.rudderActual)];
mappingError = max(abs(mappedSurfaces-outer.control(:,1:3)),[],'all');
record('Controller positions map directly to plant',mappingError == 0, ...
    sprintf('maximum surface mapping error %.3g rad',mappingError));
throttleError = max(abs(outer.control(:,4)-model.trim.controls(4)));
record('Throttle remains at its frozen trim value',throttleError == 0, ...
    sprintf('maximum throttle discrepancy %.3g',throttleError));
record('Outer acquisition remains inside V0.1',all(outer.withinEnvelope), ...
    sprintf('violation samples %d',sum(~outer.withinEnvelope)));
outerQuaternionError = max(abs(outer.quaternionNorm-1));
record('Outer acquisition quaternion remains normalized', ...
    outerQuaternionError <= model.validation.maximumQuaternionNormError, ...
    sprintf('maximum norm error %.3g',outerQuaternionError));

record('Confirmed heading loss falls back to ROLL', ...
    headingFallback.engaged(end) && ...
    headingFallback.lateralMode(end) == manager.codes.lateral.ROLL && ...
    headingFallback.verticalMode(end) == manager.codes.vertical.ALTITUDE && ...
    any(headingFallback.eventCode == ...
    manager.codes.event.HEADING_FALLBACK), ...
    'vertical ALTITUDE mode remains active');
record('Heading fallback requests roll tracking', ...
    any(headingFallback.rollTrackRequest & ...
    headingFallback.eventCode == manager.codes.event.HEADING_FALLBACK), ...
    'fallback carries its one-sample roll preload handshake');
record('Confirmed altitude loss falls back to PITCH', ...
    altitudeFallback.engaged(end) && ...
    altitudeFallback.lateralMode(end) == manager.codes.lateral.HEADING && ...
    altitudeFallback.verticalMode(end) == manager.codes.vertical.PITCH && ...
    any(altitudeFallback.eventCode == ...
    manager.codes.event.ALTITUDE_FALLBACK), ...
    'lateral HEADING mode remains active');
record('Altitude fallback requests pitch tracking', ...
    any(altitudeFallback.pitchTrackRequest & ...
    altitudeFallback.eventCode == manager.codes.event.ALTITUDE_FALLBACK), ...
    'fallback carries its one-sample pitch preload handshake');

record('Pilot disconnect releases both axes', ...
    ~disconnect.engaged(end) && ...
    disconnect.lateralMode(end) == manager.codes.lateral.OFF && ...
    disconnect.verticalMode(end) == manager.codes.vertical.OFF && ...
    any(disconnect.eventCode == ...
    manager.codes.event.DISCONNECT_COMMAND), ...
    'pilot disconnect retains global priority');
disconnectResidual = rad2deg(max(abs(disconnect.control(end,1:3))));
record('Pilot disconnect returns surfaces to neutral', ...
    disconnectResidual <= model.validation.maximumReleasedSurface_deg, ...
    sprintf('maximum final surface %.3g deg',disconnectResidual));
record('Pilot override disconnects immediately', ...
    ~override.engaged(end) && any(override.eventCode == ...
    manager.codes.event.DISCONNECT_OVERRIDE), ...
    'pilot override retains immediate global priority');

satDelay = manager.protection.sustainedSaturationDisconnectDelay_s;
record('Sustained aileron status disconnects both axes', ...
    ~aileronSaturation.engaged(end) && ...
    any(aileronSaturation.eventCode == ...
    manager.codes.event.DISCONNECT_SATURATION) && ...
    max(aileronSaturation.aileronSaturationTime_s) >= ...
    satDelay-model.execution.fixedStep_s, ...
    sprintf('maximum confirmation timer %.3f s', ...
    max(aileronSaturation.aileronSaturationTime_s)));
record('Sustained elevator status disconnects both axes', ...
    ~elevatorSaturation.engaged(end) && ...
    any(elevatorSaturation.eventCode == ...
    manager.codes.event.DISCONNECT_SATURATION) && ...
    max(elevatorSaturation.elevatorSaturationTime_s) >= ...
    satDelay-model.execution.fixedStep_s, ...
    sprintf('maximum confirmation timer %.3f s', ...
    max(elevatorSaturation.elevatorSaturationTime_s)));

record('Steady crosswind produces positive sideslip', ...
    max(wind.beta_rad(wind.time_s >= 5 & wind.time_s < 8)) > 0, ...
    sprintf('maximum pre-gust beta %.5f deg', ...
    rad2deg(max(wind.beta_rad(wind.time_s >= 5 & wind.time_s < 8)))));
record('Upward gust produces positive angle of attack', ...
    max(wind.alpha_rad(wind.time_s >= 8 & wind.time_s <= 10)) > 0, ...
    sprintf('maximum gust alpha %.5f deg', ...
    rad2deg(max(wind.alpha_rad(wind.time_s >= 8 & wind.time_s <= 10)))));
record('Wind and gust response remains engaged',all(wind.engaged), ...
    'ROLL/PITCH remains active through the environment sequence');
record('Wind and gust response remains inside V0.1', ...
    all(wind.withinEnvelope), ...
    sprintf('violation samples %d',sum(~wind.withinEnvelope)));
record('Wind and gust response remains finite', ...
    all(isfinite(wind.plantState),'all') && ...
    all(isfinite(wind.controllerState),'all'), ...
    'all aircraft and controller states are finite');

replay = simulateC172sNonlinearAutopilot(outerScenario,model);
record('Deterministic closed-loop replay',isequaln(outer,replay), ...
    'identical requests and environment reproduce a bitwise-identical trace');
badRequest = outerScenario;
badRequest.request = badRequest.request(:,1:end-1);
record('Invalid request dimensions are rejected', ...
    throws(@() simulateC172sNonlinearAutopilot(badRequest,model), ...
    'simulateC172sNonlinearAutopilot:InvalidRequest'), ...
    'the 19-column supervisor request contract is enforced');
badState = makeScenario('trim',model);
badState.initialPlantState = model.trim.state;
badState.initialPlantState(10:13) = 0;
record('Invalid initial quaternion is rejected', ...
    throws(@() simulateC172sNonlinearAutopilot(badState,model), ...
    'simulateC172sNonlinearAutopilot:InvalidQuaternion'), ...
    'zero-norm attitude cannot enter the closed loop');
record('No unsupported capability is introduced', ...
    ~model.policy.retuneController && ...
    ~model.policy.addAerodynamicCrossDerivatives && ...
    ~model.policy.addAutothrottle && ...
    ~model.policy.claimAircraftApproval, ...
    'controller gains, V0.1 aero scope and one-point thrust stay frozen');
record('Minimum audit ledger is complete', ...
    numel(passed) >= model.validation.minimumAuditCases, ...
    sprintf('%d cases recorded',numel(passed)));

fprintf('\n============================================================\n');
fprintf(' C172S NONLINEAR AUTOPILOT V1 - CLOSED-LOOP MATLAB AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',model.artifactRevision);
fprintf('%-39s: %s\n','Controller release',model.required.controllerRelease);
fprintf('%-39s: %s\n','Nonlinear plant release',model.required.nonlinearRelease);
fprintf('%-39s: %d = %d plant + %d controller\n', ...
    'Continuous state count',model.state.totalCount, ...
    model.state.plantCount,model.state.controllerCount);
fprintf('%-39s: %.3f s\n\n','Hybrid fixed step', ...
    model.execution.fixedStep_s);
for k = 1:numel(passed)
    if passed(k), tag = 'PASS'; else, tag = 'FAIL'; end
    fprintf('[%s] %-48s %s\n',tag,names{k},messages{k});
end
fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));
fprintf('Final heading / altitude error         : %.6f deg / %.6f ft\n', ...
    headingError,altitudeError);
fprintf('Peak p / q / r                         : %.5f / %.5f / %.5f deg/s\n', ...
    ratePeaks);

results = struct('Name',names,'Status',num2cell(passed), ...
    'Message',messages);
assert(all(passed), ...
    'auditC172sNonlinearAutopilotClosedLoop:AuditFailed', ...
    '%d of %d nonlinear-autopilot closed-loop cases failed.', ...
    sum(~passed),numel(passed));

fprintf('PASS: one coupled nonlinear aircraft executes under the frozen supervisor.\n');
fprintf('PASS: capture, outer modes, fallbacks, disconnects and protection pass.\n');
fprintf('PASS: wind/gust execution and deterministic replay pass inside V0.1.\n');
fprintf(['NOTE: near-trim coefficients, ideal sensors and one-point thrust remain; ', ...
    'this is not aircraft approval.\n']);

plotEvidence(outer,wind,headingTarget,altitudeTarget);

    function record(name,status,message)
        names{end+1,1} = name;
        passed(end+1,1) = logical(status);
        messages{end+1,1} = message;
    end
end

function scenario = makeScenario(name,model)
dt = model.execution.fixedStep_s;
switch name
    case 'trim'
        stopTime = model.validation.trimDuration_s;
    case 'capture'
        stopTime = model.validation.captureDuration_s;
    case 'outer'
        stopTime = model.validation.outerDuration_s;
    case {'headingFallback','altitudeFallback'}
        stopTime = model.validation.faultDuration_s;
    case {'disconnect','override'}
        stopTime = model.validation.disconnectDuration_s;
    case {'aileronSaturation','elevatorSaturation'}
        stopTime = model.validation.saturationDuration_s;
    case 'wind'
        stopTime = model.validation.windDuration_s;
    otherwise
        error('auditC172sNonlinearAutopilotClosedLoop:UnknownScenario', ...
            'Unknown scenario %s.',name);
end
t = (0:dt:stopTime).';
request = zeros(numel(t),model.input.requestCount);
request(:,4:7) = 1;
request(:,18) = model.dependencies.interface.initialization.heading_deg;
request(:,19) = model.dependencies.interface.trim.altitude_ft;
wind = zeros(numel(t),3);
gust = zeros(numel(t),3);

switch name
    case 'trim'
        % Remain disengaged at the exact nonlinear trim.
    case 'capture'
        request(1,1) = 1;
    case {'outer','headingFallback','altitudeFallback','disconnect','override'}
        request(1,1) = 1;
        request(1,10) = double(model.dependencies.manager.codes.lateral.HEADING);
        request(1,11) = double(model.dependencies.manager.codes.vertical.ALTITUDE);
        request(:,18) = model.validation.headingCommand_deg;
        request(:,19) = model.dependencies.interface.trim.altitude_ft+ ...
            model.validation.altitudeCommand_ft;
        if strcmp(name,'headingFallback')
            request(t >= 8,6) = 0;
        elseif strcmp(name,'altitudeFallback')
            request(t >= 8,7) = 0;
        elseif strcmp(name,'disconnect')
            request(firstIndex(t,8),2) = 1;
        elseif strcmp(name,'override')
            request(firstIndex(t,8),3) = 1;
        end
    case 'aileronSaturation'
        request(1,1) = 1;
        request(t >= 1,8) = 1;
    case 'elevatorSaturation'
        request(1,1) = 1;
        request(t >= 1,9) = 1;
    case 'wind'
        request(1,1) = 1;
        wind(t >= 5,2) = -2.0;
        gust(t >= 8 & t <= 10,3) = -0.5;
end

scenario.name = name;
scenario.time_s = t;
scenario.request = request;
scenario.steadyWindNED_mps = wind;
scenario.gustNED_mps = gust;
end

function index = firstIndex(time,value)
[~,index] = min(abs(time-value));
end

function status = throws(action,identifier)
status = false;
try
    action();
catch exception
    status = strcmp(exception.identifier,identifier);
end
end

function angle = wrapAngle(angle)
angle = mod(angle+pi,2*pi)-pi;
end

function plotEvidence(outer,wind,headingTarget,altitudeTarget)
figure('Name','C172S Nonlinear Autopilot V1 - closed-loop evidence', ...
    'Color','w');
tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
nexttile;
plot(outer.time_s,rad2deg(outer.euler_rad(:,3)),'LineWidth',1.3);
hold on;
yline(headingTarget,'--','Command','LineWidth',1.0);
grid on;
xlabel('Time (s)'); ylabel('Heading (deg)'); title('Heading acquisition');
nexttile;
plot(outer.time_s,outer.altitude_ft,'LineWidth',1.3);
hold on;
yline(altitudeTarget,'--','Command','LineWidth',1.0);
grid on;
xlabel('Time (s)'); ylabel('Altitude (ft)'); title('Altitude acquisition');
nexttile;
plot(outer.time_s,rad2deg(outer.control(:,1:3)),'LineWidth',1.1);
grid on;
xlabel('Time (s)'); ylabel('Surface (deg)');
title('Automatic surface positions');
legend('Elevator','Aileron','Rudder','Location','best');
nexttile;
plot(wind.time_s,rad2deg(wind.alpha_rad),'LineWidth',1.2);
hold on;
plot(wind.time_s,rad2deg(wind.beta_rad),'LineWidth',1.2);
grid on;
xlabel('Time (s)'); ylabel('Angle (deg)'); title('Wind and gust air data');
legend('Alpha','Beta','Location','best');
end
