function results = auditC172sFlightControlLab()
%AUDITC172SFLIGHTCONTROLLAB Validate the public laboratory orchestration.

model = c172sNonlinearAutopilotClosedLoopData();
lab = c172sFlightControlLabData(model);
manager = model.dependencies.manager;
names = cell(0,1);
passed = false(0,1);
messages = cell(0,1);

record('Laboratory artifact revision', ...
    strcmp(lab.artifactRevision, ...
    'C172S-FLIGHT-CONTROL-LAB-V1-MATLAB-R4'),lab.artifactRevision);
record('Frozen closed-loop backend revision', ...
    strcmp(lab.required.closedLoopArtifact,model.artifactRevision), ...
    model.artifactRevision);
record('Frozen interface revision', ...
    strcmp(lab.required.interfaceArtifact, ...
    model.dependencies.interface.artifactRevision), ...
    lab.required.interfaceArtifact);
record('Frozen Mode Manager revision', ...
    strcmp(lab.required.modeManagerArtifact,manager.artifactRevision), ...
    lab.required.modeManagerArtifact);
record('Frozen nonlinear dynamics revision', ...
    strcmp(lab.required.plantArtifact, ...
    model.dependencies.plant.artifactRevision), ...
    lab.required.plantArtifact);
record('Released controller version preserved', ...
    strcmp(lab.required.controllerRelease,'v1.0.0'), ...
    lab.required.controllerRelease);
record('Released nonlinear-plant version preserved', ...
    strcmp(lab.required.nonlinearPlantRelease,'v0.1.0'), ...
    lab.required.nonlinearPlantRelease);
record('Released nonlinear-autopilot version preserved', ...
    strcmp(lab.required.nonlinearAutopilotRelease,'v0.1.0'), ...
    lab.required.nonlinearAutopilotRelease);
record('External regression ledger preserved', ...
    strcmp(lab.required.externalRegressionEvidence,'28/28 PASS'), ...
    lab.required.externalRegressionEvidence);
record('Twenty-six-state backend preserved', ...
    model.state.plantCount == 13 && ...
    model.state.controllerCount == 13 && model.state.totalCount == 26, ...
    '13 plant plus 13 controller states');
record('Frozen execution rate preserved', ...
    lab.execution.fixedStep_s == 0.01 && ...
    lab.execution.fixedStep_s == model.execution.fixedStep_s, ...
    'hybrid fixed-step 0.010 s');
record('Public execution backends are declared', ...
    isequal(lab.execution.backends,{'MATLAB','SIMULINK','COMPARE'}) && ...
    strcmp(lab.execution.defaultBackend,'MATLAB'), ...
    'MATLAB default plus SIMULINK and COMPARE');
record('Public Simulink runner is packaged', ...
    exist(lab.execution.simulinkBackend,'file') == 2 && ...
    exist('c172sNonlinearAutopilotResultMatrix','file') == 2 && ...
    exist('compareC172sNonlinearAutopilotBackends','file') == 2, ...
    'runner, 58-signal packer and comparator present');
record('Backend equivalence tolerance is frozen', ...
    lab.execution.maximumBackendError == 3.0e-7, ...
    'maximum 58-signal difference 3.0e-7');
trimTolerance = 1e-9;
record('Trim datum preserved', ...
    abs(lab.trim.altitude_ft-4000) <= trimTolerance && ...
    abs(lab.trim.TAS_KTAS-110) <= trimTolerance && ...
    abs(lab.trim.weight_lb-2550) <= trimTolerance && ...
    abs(lab.trim.throttle-0.65) <= trimTolerance, ...
    sprintf('%.12g ft / %.12g KTAS / %.12g lb / throttle %.12g', ...
    lab.trim.altitude_ft,lab.trim.TAS_KTAS,lab.trim.weight_lb, ...
    lab.trim.throttle));
record('Custom command boundary is conservative', ...
    isequal(lab.boundary.headingChange_deg,[-10,10]) && ...
    isequal(lab.boundary.altitudeChange_ft,[-50,50]), ...
    '+/-10 deg heading and +/-50 ft altitude changes');
record('Laboratory does not retune releases', ...
    ~lab.policy.modifyControllerRelease && ...
    ~lab.policy.modifyNonlinearPlantRelease && ...
    ~lab.policy.modifyNonlinearAutopilotRelease && ...
    ~lab.policy.retuneControllers, ...
    'all three releases remain frozen');
record('Laboratory does not expand the validated envelope', ...
    ~lab.policy.expandValidatedEnvelope && ...
    ~lab.policy.claimAircraftApproval, ...
    'V0.1 boundary and non-approval statement remain explicit');

presetScenarios = cell(numel(lab.presets.keys),1);
for k = 1:numel(lab.presets.keys)
    presetScenarios{k} = createC172sFlightControlScenario( ...
        lab.presets.keys{k},struct(),model);
    s = presetScenarios{k};
    contractPass = size(s.request,2) == model.input.requestCount && ...
        size(s.request,1) == numel(s.time_s) && ...
        isequal(size(s.steadyWindNED_mps),[numel(s.time_s),3]) && ...
        isequal(size(s.gustNED_mps),[numel(s.time_s),3]) && ...
        max(abs(diff(s.time_s)-model.execution.fixedStep_s)) <= 1e-12 && ...
        strcmp(s.labArtifactRevision,lab.artifactRevision) && ...
        strcmp(s.backendArtifactRevision,model.artifactRevision);
    record(['Preset contract: ' lab.presets.keys{k}],contractPass, ...
        sprintf('%d samples, 19 requests, two NED environment vectors', ...
        numel(s.time_s)));
end

captureScenario = presetScenarios{2};
silentOptions = struct('ShowPlots',false,'PrintSummary',false, ...
    'ExportResults',false,'ExportFolder','');
captureRun = runC172sFlightControlScenario( ...
    captureScenario,silentOptions,model);
capture = captureRun.result;
captureMetrics = captureRun.metrics;
record('Default public execution path is MATLAB', ...
    strcmp(captureRun.executionBackend,'MATLAB') && ...
    strcmp(capture.executionBackend,'MATLAB'), ...
    'omitted Backend option selects the reference executor');
record('ROLL/PITCH preset is named as trim capture', ...
    strcmp(captureScenario.name, ...
    'Bumpless ROLL/PITCH engagement at trim'), ...
    captureScenario.name);
record('No unsupported attitude-selector path is invented', ...
    max(abs(captureScenario.request(:,14:17)),[],'all') == 0, ...
    'reserved/live-feedback request columns remain zero');
record('Trim capture engages ROLL plus PITCH', ...
    captureMetrics.final.engaged && ...
    captureMetrics.final.lateralModeCode == manager.codes.lateral.ROLL && ...
    captureMetrics.final.verticalModeCode == manager.codes.vertical.PITCH, ...
    [captureMetrics.final.lateralMode '/' ...
    captureMetrics.final.verticalMode]);
record('Trim bank/pitch capture is bumpless', ...
    max(abs(capture.control(:,1:3)),[],'all') <= 1e-12 && ...
    max(abs(capture.plantState(:,4:6)),[],'all') <= 1e-12, ...
    'surfaces and body rates remain at numerical zero');
record('Mode-aware ROLL/PITCH objective passes', ...
    captureMetrics.objective.bankCapturePass && ...
    captureMetrics.objective.pitchCapturePass && ...
    captureMetrics.overallPass, ...
    sprintf('bank/pitch errors %.3g / %.3g deg', ...
    captureMetrics.final.bankCaptureError_deg, ...
    captureMetrics.final.pitchCaptureError_deg));

quickScenario = presetScenarios{1};
quick = simulateC172sNonlinearAutopilot(quickScenario,model);
quickMetrics = analyzeC172sFlightControlScenario( ...
    quick,quickScenario,model);
record('Quick demo engages HEADING plus ALTITUDE', ...
    quickMetrics.final.engaged && ...
    quickMetrics.final.lateralModeCode == manager.codes.lateral.HEADING && ...
    quickMetrics.final.verticalModeCode == manager.codes.vertical.ALTITUDE, ...
    [quickMetrics.final.lateralMode '/' quickMetrics.final.verticalMode]);
record('Quick-demo heading acquisition closes', ...
    abs(quickMetrics.final.headingError_deg) <= ...
    lab.analysis.headingTolerance_deg, ...
    sprintf('final error %.6f deg',quickMetrics.final.headingError_deg));
record('Quick-demo altitude acquisition closes', ...
    abs(quickMetrics.final.altitudeError_ft) <= ...
    lab.analysis.altitudeTolerance_ft, ...
    sprintf('final error %.6f ft',quickMetrics.final.altitudeError_ft));
record('Quick-demo trace remains finite',quickMetrics.health.finiteTrace, ...
    sprintf('%d finite samples',quickMetrics.sampleCount));
record('Quick-demo quaternion remains normalized', ...
    quickMetrics.health.quaternionPass, ...
    sprintf('maximum norm error %.3g', ...
    quickMetrics.health.maximumQuaternionNormError));
record('Quick demo remains inside V0.1', ...
    quickMetrics.health.envelopePass, ...
    sprintf('violation samples %d', ...
    quickMetrics.health.envelopeViolationSamples));
record('Quick-demo scenario objective passes', ...
    quickMetrics.objective.pass, ...
    sprintf('heading %.6f deg; altitude %.6f ft', ...
    quickMetrics.final.headingError_deg, ...
    quickMetrics.final.altitudeError_ft));
record('Quick-demo overall result passes',quickMetrics.overallPass, ...
    'health and requested mission objective both pass');

windScenario = presetScenarios{3};
wind = simulateC172sNonlinearAutopilot(windScenario,model);
windMetrics = analyzeC172sFlightControlScenario(wind,windScenario,model);
record('Wind preset maps right crosswind to positive sideslip', ...
    max(wind.beta_rad) > 0, ...
    sprintf('maximum beta %.5f deg',rad2deg(max(wind.beta_rad))));
record('Wind preset maps upward gust to positive angle of attack', ...
    max(wind.alpha_rad) > 0, ...
    sprintf('maximum alpha %.5f deg',rad2deg(max(wind.alpha_rad))));
record('Wind/gust preset remains inside V0.1', ...
    windMetrics.health.envelopePass, ...
    sprintf('violation samples %d', ...
    windMetrics.health.envelopeViolationSamples));

headingScenario = presetScenarios{4};
heading = simulateC172sNonlinearAutopilot(headingScenario,model);
headingMetrics = analyzeC172sFlightControlScenario( ...
    heading,headingScenario,model);
record('Heading-loss preset falls back to ROLL', ...
    headingMetrics.final.engaged && ...
    headingMetrics.final.lateralModeCode == manager.codes.lateral.ROLL && ...
    headingMetrics.final.verticalModeCode == manager.codes.vertical.ALTITUDE, ...
    [headingMetrics.final.lateralMode '/' ...
    headingMetrics.final.verticalMode]);
record('Heading-loss event is recorded', ...
    any(heading.eventCode == manager.codes.event.HEADING_FALLBACK), ...
    'HEADING_FALLBACK appears in the public event ledger');

disconnectScenario = presetScenarios{6};
disconnect = simulateC172sNonlinearAutopilot(disconnectScenario,model);
disconnectMetrics = analyzeC172sFlightControlScenario( ...
    disconnect,disconnectScenario,model);
releasedSurface_deg = max(abs(rad2deg(disconnect.control(end,1:3))));
record('Disconnect preset releases the autopilot', ...
    ~disconnectMetrics.final.engaged && ...
    disconnectMetrics.final.lateralModeCode == manager.codes.lateral.OFF && ...
    disconnectMetrics.final.verticalModeCode == manager.codes.vertical.OFF, ...
    'final mode OFF/OFF');
record('Disconnect event is recorded', ...
    any(disconnect.eventCode == manager.codes.event.DISCONNECT_COMMAND), ...
    'DISCONNECT_COMMAND appears in the public event ledger');
record('Disconnect returns surfaces to neutral', ...
    releasedSurface_deg <= model.validation.maximumReleasedSurface_deg, ...
    sprintf('final maximum surface %.3g deg',releasedSurface_deg));

offOptions = presetScenarios{8}.configuration;
offOptions.duration_s = 10;
offOptions.gustStart_s = 5;
offScenario = createC172sFlightControlScenario( ...
    'autopilot-off',offOptions,model);
off = simulateC172sNonlinearAutopilot(offScenario,model);
offMetrics = analyzeC172sFlightControlScenario(off,offScenario,model);
record('Autopilot-off preset remains disengaged', ...
    ~any(off.engaged) && ~offMetrics.final.engaged, ...
    'no automatic axis engages');
record('Autopilot-off surfaces remain neutral', ...
    max(abs(off.control(:,1:3)),[],'all') <= 1e-12, ...
    'elevator, aileron and rudder remain released');

replayScenario = presetScenarios{2};
replayA = simulateC172sNonlinearAutopilot(replayScenario,model);
replayB = simulateC172sNonlinearAutopilot(replayScenario,model);
record('Laboratory deterministic replay', ...
    isequal(replayA.plantState,replayB.plantState) && ...
    isequal(replayA.controllerState,replayB.controllerState) && ...
    isequal(replayA.control,replayB.control) && ...
    isequal(replayA.eventCode,replayB.eventCode), ...
    'identical scenario reproduces a bitwise-identical trace');

record('Unknown preset is rejected',throws(@() ...
    createC172sFlightControlScenario('not-a-preset',struct(),model), ...
    'createC172sFlightControlScenario:UnknownPreset'), ...
    'unsupported preset cannot enter the backend');
record('Out-of-bound heading change is rejected',throws(@() ...
    createC172sFlightControlScenario('custom', ...
    struct('headingChange_deg',10.01),model), ...
    'createC172sFlightControlScenario:OutsideBoundary'), ...
    'custom heading change is bounded');
record('Out-of-bound altitude change is rejected',throws(@() ...
    createC172sFlightControlScenario('custom', ...
    struct('altitudeChange_ft',50.01),model), ...
    'createC172sFlightControlScenario:OutsideBoundary'), ...
    'custom altitude change is bounded');
record('Invalid event/mode combination is rejected',throws(@() ...
    createC172sFlightControlScenario('custom', ...
    struct('lateralMode','ROLL','eventType','HEADING-LOSS'),model), ...
    'createC172sFlightControlScenario:IncompatibleEvent'), ...
    'heading loss cannot masquerade as a ROLL-mode fallback');
record('Unknown run option is rejected',throws(@() ...
    runC172sFlightControlScenario(replayScenario, ...
    struct('UnknownOption',true),model), ...
    'runC172sFlightControlScenario:UnknownOption'), ...
    'public run options are frozen');
record('Unknown execution backend is rejected',throws(@() ...
    runC172sFlightControlScenario(replayScenario, ...
    struct('Backend','NOT-A-BACKEND'),model), ...
    'runC172sFlightControlScenario:InvalidBackend'), ...
    'only MATLAB, SIMULINK and COMPARE are accepted');

fprintf('============================================================\n');
fprintf(' C172S FLIGHT DYNAMICS/AUTOPILOT LAB V1.1 - MATLAB AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',lab.artifactRevision);
fprintf('%-39s: %s\n','Frozen backend',model.artifactRevision);
fprintf('%-39s: %s\n','External regression evidence', ...
    lab.required.externalRegressionEvidence);
fprintf('%-39s: %d\n\n','Preset scenarios',numel(lab.presets.keys));
for k = 1:numel(passed)
    if passed(k), tag = 'PASS'; else, tag = 'FAIL'; end
    fprintf('[%s] %-48s %s\n',tag,names{k},messages{k});
end
fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));

results = struct('Name',names,'Status',num2cell(passed), ...
    'Message',messages);
assert(numel(passed) >= lab.validation.minimumAuditCases, ...
    'auditC172sFlightControlLab:IncompleteLedger', ...
    'Only %d laboratory cases exist; at least %d are required.', ...
    numel(passed),lab.validation.minimumAuditCases);
assert(numel(passed) == lab.validation.expectedAuditCases, ...
    'auditC172sFlightControlLab:LedgerSizeChanged', ...
    'Expected %d laboratory cases; found %d.', ...
    lab.validation.expectedAuditCases,numel(passed));
assert(all(passed),'auditC172sFlightControlLab:AuditFailed', ...
    '%d of %d flight-control laboratory cases failed.', ...
    sum(~passed),numel(passed));
fprintf('PASS: the public scenario API operates the frozen 28/28 backend.\n');
fprintf('PASS: presets, custom boundaries, metrics, events and replay pass.\n');
fprintf('PASS: MATLAB, SIMULINK and COMPARE public contracts are present.\n');
fprintf(['NOTE: the laboratory remains a near-trim research simulation ', ...
    'with ideal sensors and one-point throttle; not aircraft approval.\n']);

    function record(name,status,message)
        names{end+1,1} = name; %#ok<AGROW>
        passed(end+1,1) = logical(status); %#ok<AGROW>
        messages{end+1,1} = message; %#ok<AGROW>
    end
end

function status = throws(action,identifier)
status = false;
try
    action();
catch exception
    status = strcmp(exception.identifier,identifier);
end
end
