function results = auditC172sNonlinear6DofSources()
%% C172S nonlinear 6-DOF V1 - source and convention audit

clear;
clc;

contract = c172sNonlinear6DofSourceData();
longitudinal = c172sLongitudinalData();
lateral = c172sLateralDirectionalData();

name = strings(0,1);
detail = strings(0,1);
passed = false(0,1);

record('Frozen longitudinal revision', ...
    strcmp(longitudinal.model.version,contract.required.longitudinalPlant), ...
    longitudinal.model.version);
record('Frozen lateral revision', ...
    strcmp(lateral.model.version,contract.required.lateralPlant), ...
    lateral.model.version);
record('Released controller stack remains external', ...
    ~contract.policy.modifyFrozenRelease && ...
    contract.required.masterRegressionPasses == 18, ...
    'v1.0.0 remains frozen at 18/18');

sameTrim = longitudinal.trim.pressureAltitude_ft == ...
    contract.trim.pressureAltitude_ft && ...
    lateral.trim.pressureAltitude_ft == contract.trim.pressureAltitude_ft && ...
    longitudinal.trim.V_KTAS == contract.trim.V_KTAS && ...
    lateral.trim.V_KTAS == contract.trim.V_KTAS && ...
    longitudinal.trim.weight_lb == contract.trim.weight_lb && ...
    lateral.trim.weight_lb == contract.trim.weight_lb;
record('Common frozen validation point',sameTrim, ...
    sprintf('%.0f ft ISA, %.0f KTAS, %.0f lb, flaps %.0f deg', ...
    contract.trim.pressureAltitude_ft,contract.trim.V_KTAS, ...
    contract.trim.weight_lb,contract.trim.flap_deg));

record('Thirteen-state rigid-body contract', ...
    contract.state.count == 13 && ...
    numel(contract.state.names) == 13 && ...
    numel(unique(contract.state.names)) == 13, ...
    'u v w p q r, NED position, scalar-first quaternion');
record('Internal SI contract',strcmp(contract.units.internal,'SI'), ...
    'm, s, kg, rad, N and N*m internally');
record('Right-handed body axes fixed', ...
    strcmp(contract.axes.x,'forward') && ...
    strcmp(contract.axes.y,'right wing') && ...
    strcmp(contract.axes.z,'down'), ...
    'x forward, y right, z down');
record('NED altitude mapping fixed', ...
    strcmp(contract.axes.navigation,'NED') && ...
    contains(contract.axes.altitudeDefinition,'-positionDown_m'), ...
    'altitude is negative NED down position');
record('Quaternion convention fixed', ...
    strcmp(contract.state.quaternionOrder,'scalar-first body-to-NED'), ...
    contract.state.quaternionOrder);

qTest = [cos(pi/8),0,sin(pi/8),0];
record('Quaternion unit-norm invariant', ...
    abs(sum(qTest.^2)-1) <= ...
    contract.validation.maximumQuaternionNormError, ...
    sprintf('test norm error %.3g',abs(sum(qTest.^2)-1)));

record('Elevator sign matches frozen plant', ...
    contract.controls.expectedSigns.Cm_deltaE < 0 && ...
    longitudinal.aero.Cm_deltaE < 0 && ...
    contains(longitudinal.model.inputName,'TE_down_positive'), ...
    'trailing-edge-down gives negative nose-up pitching moment');
record('Aileron sign matches frozen plant', ...
    contract.controls.expectedSigns.Cl_deltaA > 0 && ...
    lateral.aero.Cl_deltaA > 0 && ...
    contains(lateral.model.inputNames{1},'rightWingDown'), ...
    'positive command produces positive right-wing-down roll moment');
record('Rudder sign matches frozen plant', ...
    contract.controls.expectedSigns.Cn_deltaR > 0 && ...
    lateral.aero.Cn_deltaR > 0 && ...
    contains(lateral.model.inputNames{2},'noseRight'), ...
    'positive command produces positive nose-right yaw moment');

record('Angular-rate normalizations preserved', ...
    strcmp(contract.normalization.pHat,'p*b/(2*V)') && ...
    strcmp(contract.normalization.qHat,'q*cBar/(2*V)') && ...
    strcmp(contract.normalization.rHat,'r*b/(2*V)'), ...
    'pHat/rHat use span; qHat uses mean aerodynamic chord');
record('Aerodynamic derivatives are per radian', ...
    strcmp(contract.normalization.derivativeAngles,'per radian'), ...
    'no degree-scaled derivatives enter the force/moment model');

tiers = {contract.sources.tier};
record('Evidence hierarchy complete', ...
    all(ismember(contract.evidence.acceptanceOrder,unique(tiers))) && ...
    numel(contract.sources) >= contract.validation.minimumSourceCount, ...
    sprintf('%d sources span evidence tiers A through D', ...
    numel(contract.sources)));
record('Every source has traceability metadata', ...
    all(~cellfun(@isempty,{contract.sources.url})) && ...
    all(~cellfun(@isempty,{contract.sources.locator})) && ...
    all(~cellfun(@isempty,{contract.sources.reuse})), ...
    'URL, exact locator and reuse qualification are populated');

nasaIndex = find(strcmp({contract.sources.id},'NASA-CR-168912'),1);
record('NASA flight-test variant identified', ...
    ~isempty(nasaIndex) && ...
    contains(contract.sources(nasaIndex).variant,'1974 C172M') && ...
    strcmp(contract.sources(nasaIndex).tier,'B'), ...
    '1974 C172M N12800; transferable evidence, not direct C172S truth');
record('NASA maneuver tables located correctly', ...
    contains(contract.sources(nasaIndex).qualification,'Tables 6.3 and 6.4') && ...
    contains(contract.sources(nasaIndex).qualification,'pp. 97-98'), ...
    '35 maneuver estimates reside in report Tables 6.3/6.4');
record('Composite NASA coefficient row quarantined', ...
    numel(contract.rejected.geminiCompositeNASAValues) == 9 && ...
    contains(contract.rejected.reason,'shall not enter V0.1') && ...
    ~strcmp(contract.rejected.NASAReportPageClaim, ...
    contract.rejected.correctNASAReportTables), ...
    'unverified one-row transcription is explicitly rejected');

record('Kasnakoglu provenance is not overstated', ...
    contains(lateral.model.primarySource,'Kasnakoglu') && ...
    contains(contract.sources(4).qualification,'not a C172S flight-test'), ...
    'published analytical/simulation source remains Tier C');
record('UIUC and JSBSim remain subordinate', ...
    strcmp(contract.sources(5).tier,'C') && ...
    strcmp(contract.sources(6).tier,'D') && ...
    contains(contract.sources(5).qualification,'shape only') && ...
    contains(contract.sources(6).qualification,'not certified'), ...
    'candidate shapes and architecture cannot override measured anchors');

I = [lateral.inertia.Ixx_kgm2,0,-lateral.inertia.Ixz_kgm2; ...
     0,lateral.inertia.Iyy_kgm2,0; ...
     -lateral.inertia.Ixz_kgm2,0,lateral.inertia.Izz_kgm2];
record('Provisional inertia tensor is positive definite', ...
    all(eig(I) > 0) && norm(I-I.','fro') < eps, ...
    sprintf('minimum eigenvalue %.2f kg*m^2',min(eig(I))));
record('Inertia uncertainty remains explicit', ...
    contract.massProperties.uncertaintyFraction >= 0.20 && ...
    strcmp(contract.massProperties.IxzStatus,'open validation item') && ...
    contract.massProperties.requireWeightCGSchedule, ...
    'nominal tensor is provisional; weight/CG schedule and Ixz remain open');

record('Attached-flow V0.1 envelope is bounded', ...
    contract.envelope.V_KTAS(1) > 0 && ...
    contract.envelope.V_KTAS(2) > contract.envelope.V_KTAS(1) && ...
    contract.envelope.alpha_deg(1) < 0 && ...
    contract.envelope.alpha_deg(2) <= 10 && ...
    contract.envelope.flap_deg == 0 && ...
    contract.envelope.projectAssumption, ...
    sprintf('%.0f-%.0f KTAS, alpha %.0f to %.0f deg, flaps up', ...
    contract.envelope.V_KTAS,contract.envelope.alpha_deg));
record('Stall and spin claims remain disabled', ...
    ~contract.envelope.stallValidated && ...
    ~contract.envelope.postStallValidated && ...
    ~contract.envelope.spinValidated, ...
    'no validated stall, departure or spin claim');
record('Model is not labeled aircraft truth', ...
    ~contract.policy.claimTruthModel && ...
    ~contract.policy.claimAircraftApproval && ...
    contains(contract.policy.researchPlantName,'Research Validation Plant'), ...
    contract.policy.researchPlantName);

record('Equations may precede final aero database', ...
    contract.readiness.readyForEquationsOfMotion && ...
    ~contract.readiness.readyForFinalAeroDatabase, ...
    'rigid-body kernel may proceed; final coefficient schedules may not');
record('Mandatory next-gate ledger complete', ...
    numel(contract.nextGates) >= ...
    contract.validation.minimumNextGateCount && ...
    numel(unique(contract.nextGates)) == numel(contract.nextGates), ...
    sprintf('%d unique gates block unsupported expansion', ...
    numel(contract.nextGates)));
record('Frozen linearization matching is mandatory', ...
    contract.validation.maximumFrozenLinearizationRelativeError <= 1.0e-6, ...
    sprintf('relative Jacobian error <= %.1e', ...
    contract.validation.maximumFrozenLinearizationRelativeError));
record('Deterministic replay remains mandatory', ...
    contract.validation.requireDeterministicReplay, ...
    'identical states and inputs must reproduce identical traces');

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR 6-DOF V1 - SOURCE/CONVENTION AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',contract.artifactRevision);
fprintf('%-39s: %s\n','Research plant',contract.policy.researchPlantName);
fprintf('%-39s: %s / %d states\n','Frame / state count', ...
    contract.axes.navigation,contract.state.count);
fprintf('%-39s: %.0f ft / %.0f KTAS / %.0f lb\n', ...
    'Initial validation point',contract.trim.pressureAltitude_ft, ...
    contract.trim.V_KTAS,contract.trim.weight_lb);
fprintf('%-39s: %d\n\n','Source records',numel(contract.sources));

for k = 1:numel(passed)
    label = 'PASS';
    if ~passed(k), label = 'FAIL'; end
    fprintf('[%s] %-45s %s\n',label,name(k),detail(k));
end

fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));

results = struct('Name',cellstr(name),'Status',num2cell(passed), ...
    'Detail',cellstr(detail));

assert(all(passed),'auditC172sNonlinear6DofSources:AuditFailed', ...
    '%d of %d source/convention gates failed.',sum(~passed),numel(passed));
fprintf('PASS: the 13-state SI/NED convention and all control signs are frozen.\n');
fprintf('PASS: the released linear plants remain the mandatory trim anchors.\n');
fprintf('PASS: source tiers and unsupported-data quarantine are explicit.\n');
fprintf('PASS: the rigid-body kernel may proceed within the V0.1 claim boundary.\n');
fprintf(['NOTE: coefficient schedules, propulsion and mass properties remain ', ...
    'provisional until their listed gates pass.\n']);
fprintf(['NOTE: stall, post-stall and spin behavior are outside V0.1; this ', ...
    'is not aircraft approval.\n']);

function record(caseName,condition,caseDetail)
name(end+1,1) = string(caseName); %#ok<AGROW>
passed(end+1,1) = logical(condition); %#ok<AGROW>
detail(end+1,1) = string(caseDetail); %#ok<AGROW>
end
end
