%% C172S Autopilot Mode Manager V1 - MATLAB logic and source audit
% Artifact: AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1

clear;
clc;

manager = c172sAutopilotModeManagerData();
dt = manager.validation.sampleTime_s;
base = nominalInput(manager);
dependencyCount = auditFrozenDependencies(manager);

caseName = strings(0,1);
caseStatus = false(0,1);
caseDetail = strings(0,1);

%% 1. Disengaged release

[state,out] = c172sAutopilotModeManagerStep([],base,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'Disengaged outputs released', ...
    ~out.engaged && out.lateralMode == manager.codes.lateral.OFF && ...
    out.verticalMode == manager.codes.vertical.OFF && ...
    out.bankCommand_deg == 0.0 && out.pitchCommand_deg == 0.0, ...
    'OFF/OFF with zero automatic attitude commands');

%% 2. Default stabilized engagement and capture

u = base;
u.engageRequest = true;
u.bank_deg = 4.0;
u.pitch_deg = 1.25;
[state,out] = c172sAutopilotModeManagerStep(state,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Default ROLL plus PITCH engagement', ...
    out.engaged && out.rollModeEnable && out.pitchModeEnable && ...
    out.bankCommand_deg == 0.0 && ...
    abs(out.pitchCommand_deg-1.25) <= ...
    manager.validation.maximumReferenceCaptureError_deg && ...
    out.rollIntegratorTrackRequest && ...
    out.pitchIntegratorTrackRequest, ...
    'Sub-6-deg bank commands wings level; pitch is captured');

%% 2b. Supervisory attitude-command authority

u = base;
u.engageRequest = true;
u.bank_deg = 25.0;
u.pitch_deg = 5.0;
[~,limitedCaptureOut] = ...
    c172sAutopilotModeManagerStep([],u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Captured attitude references are bounded', ...
    limitedCaptureOut.bankCommand_deg == ...
    manager.capture.bankCommandLimit_deg && ...
    limitedCaptureOut.pitchCommand_deg == ...
    manager.capture.pitchCommandLimit_deg, ...
    'ROLL/PITCH capture respects the declared supervisory authorities');

%% 3. Engagement rejection while not stabilized

u = base;
u.engageRequest = true;
u.trimStable = false;
[~,outRejected] = c172sAutopilotModeManagerStep([],u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'Unstable engagement rejected', ...
    ~outRejected.engaged && ...
    outRejected.eventCode == manager.codes.event.ENGAGE_REJECTED, ...
    'trimStable=false leaves both axes OFF');

%% 4. Direct outer-mode engagement

u = base;
u.engageRequest = true;
u.lateralModeRequest = manager.codes.lateral.HEADING;
u.verticalModeRequest = manager.codes.vertical.ALTITUDE;
u.selectedHeading_deg = 370.0;
u.selectedAltitude_ft = 4250.0;
[outerState,outerOut] = ...
    c172sAutopilotModeManagerStep([],u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Direct HEADING plus ALTITUDE engagement', ...
    outerOut.headingModeEnable && outerOut.altitudeModeEnable && ...
    abs(outerOut.headingCommand_deg-10.0) <= ...
    manager.validation.maximumHeadingNormalizationError_deg && ...
    outerOut.altitudeCommand_ft == 4250.0, ...
    'Selected heading normalized to 010 deg; altitude held at 4250 ft');

%% 5. Mode exclusivity and inner-mode capture

u = base;
u.bank_deg = -12.0;
u.pitch_deg = -1.5;
u.lateralModeRequest = manager.codes.lateral.ROLL;
u.verticalModeRequest = manager.codes.vertical.PITCH;
[innerState,innerOut] = ...
    c172sAutopilotModeManagerStep(outerState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Outer-to-inner bumpless mode transfer', ...
    innerOut.rollModeEnable && ~innerOut.headingModeEnable && ...
    innerOut.pitchModeEnable && ~innerOut.altitudeModeEnable && ...
    innerOut.bankCommand_deg == -12.0 && ...
    innerOut.pitchCommand_deg == -1.5 && ...
    innerOut.rollIntegratorTrackRequest && ...
    innerOut.pitchIntegratorTrackRequest, ...
    'Actual bank/pitch captured with one-sample tracking requests');

%% 5b. Invalid outer-mode requests

u = base;
u.headingValid = false;
u.altitudeValid = false;
u.lateralModeRequest = manager.codes.lateral.HEADING;
u.verticalModeRequest = manager.codes.vertical.ALTITUDE;
[~,rejectedModeOut] = ...
    c172sAutopilotModeManagerStep(innerState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Invalid outer-mode requests are rejected', ...
    rejectedModeOut.rollModeEnable && rejectedModeOut.pitchModeEnable && ...
    rejectedModeOut.eventCode == manager.codes.event.MODE_REJECTED, ...
    'Current safe inner modes remain active when outer sources are invalid');

%% 6. Active reference updates and circular normalization

u = base;
u.lateralModeRequest = manager.codes.lateral.HEADING;
u.verticalModeRequest = manager.codes.vertical.ALTITUDE;
u.selectedHeading_deg = 350.0;
u.selectedAltitude_ft = 4100.0;
[referenceState,~] = ...
    c172sAutopilotModeManagerStep(innerState,u,manager,dt);
u = base;
u.updateHeadingReference = true;
u.updateAltitudeReference = true;
u.selectedHeading_deg = -10.0;
u.selectedAltitude_ft = 4300.0;
[referenceState,referenceOut] = ...
    c172sAutopilotModeManagerStep(referenceState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'Active outer references updated', ...
    referenceOut.headingModeEnable && referenceOut.altitudeModeEnable && ...
    referenceOut.headingCommand_deg == 350.0 && ...
    referenceOut.altitudeCommand_ft == 4300.0, ...
    '-10 deg normalizes to 350 deg without changing active modes');

%% 7. Heading-source transient immunity and confirmed fallback

u = base;
u.headingValid = false;
shortSamples = thresholdSamples( ...
    manager.protection.outerSensorFallbackDelay_s,dt)-1;
transientState = referenceState;
for k = 1:shortSamples
    [transientState,transientOut] = ...
        c172sAutopilotModeManagerStep(transientState,u,manager,dt);
end
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'Transient heading fault rejected', ...
    transientOut.headingModeEnable, ...
    'HEADING remains active before the confirmation interval');

[~,headingFallbackOut] = ...
    c172sAutopilotModeManagerStep(transientState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Confirmed heading fault falls back to ROLL', ...
    headingFallbackOut.rollModeEnable && ...
    headingFallbackOut.eventCode == ...
    manager.codes.event.HEADING_FALLBACK && ...
    headingFallbackOut.rollIntegratorTrackRequest, ...
    'Only the lateral outer loop degrades; autopilot remains engaged');

%% 8. Altitude-source transient immunity and confirmed fallback

u = base;
u.altitudeValid = false;
altitudeState = referenceState;
for k = 1:shortSamples
    [altitudeState,altitudeTransientOut] = ...
        c172sAutopilotModeManagerStep(altitudeState,u,manager,dt);
end
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'Transient altitude fault rejected', ...
    altitudeTransientOut.altitudeModeEnable, ...
    'ALTITUDE remains active before the confirmation interval');

[~,altitudeFallbackOut] = ...
    c172sAutopilotModeManagerStep(altitudeState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Confirmed altitude fault falls back to PITCH', ...
    altitudeFallbackOut.pitchModeEnable && ...
    altitudeFallbackOut.eventCode == ...
    manager.codes.event.ALTITUDE_FALLBACK && ...
    altitudeFallbackOut.pitchIntegratorTrackRequest, ...
    'Only the vertical outer loop degrades; autopilot remains engaged');

%% 9. Explicit pilot disconnect

u = base;
u.disconnectRequest = true;
[~,disconnectOut] = ...
    c172sAutopilotModeManagerStep(referenceState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,'A/P DISC has immediate priority', ...
    ~disconnectOut.engaged && disconnectOut.disconnectToneRequest && ...
    disconnectOut.eventCode == ...
    manager.codes.event.DISCONNECT_COMMAND, ...
    'Both axes release in the request sample');

%% 10. Pilot override disconnect

u = base;
u.pilotOverride = true;
[~,overrideOut] = ...
    c172sAutopilotModeManagerStep(referenceState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Pilot override disconnects both axes', ...
    ~overrideOut.engaged && overrideOut.disconnectToneRequest && ...
    overrideOut.eventCode == ...
    manager.codes.event.DISCONNECT_OVERRIDE, ...
    'Over-power/override input owns priority over mode requests');

%% 11. Core-sensor transient immunity and confirmed disconnect

u = base;
u.coreSensorsValid = false;
coreState = referenceState;
coreShort = thresholdSamples( ...
    manager.protection.coreSensorDisconnectDelay_s,dt)-1;
for k = 1:coreShort
    [coreState,coreTransientOut] = ...
        c172sAutopilotModeManagerStep(coreState,u,manager,dt);
end
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Transient core-sensor fault rejected', ...
    coreTransientOut.engaged, ...
    'No disconnect before the confirmation interval');

[~,coreDisconnectOut] = ...
    c172sAutopilotModeManagerStep(coreState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Confirmed core-sensor fault disconnects', ...
    ~coreDisconnectOut.engaged && ...
    coreDisconnectOut.eventCode == ...
    manager.codes.event.DISCONNECT_CORE_SENSOR, ...
    'Core attitude/rate sensing loss releases both axes');

%% 12. Saturation transient immunity and sustained disconnect

u = base;
u.aileronSaturated = true;
saturationState = referenceState;
saturationShort = thresholdSamples( ...
    manager.protection.sustainedSaturationDisconnectDelay_s,dt)-1;
for k = 1:saturationShort
    [saturationState,saturationTransientOut] = ...
        c172sAutopilotModeManagerStep(saturationState,u,manager,dt);
end
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Transient actuator saturation tolerated', ...
    saturationTransientOut.engaged, ...
    'A short protection-limit encounter does not nuisance-disconnect');

[~,saturationDisconnectOut] = ...
    c172sAutopilotModeManagerStep(saturationState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Sustained actuator saturation disconnects', ...
    ~saturationDisconnectOut.engaged && ...
    saturationDisconnectOut.eventCode == ...
    manager.codes.event.DISCONNECT_SATURATION, ...
    'Either axis reaching the dwell threshold releases both axes');

%% 13. Abnormal-attitude logic stress

u = base;
u.bank_deg = manager.protection.maximumAbsoluteBank_deg + 0.1;
[~,attitudeOut] = ...
    c172sAutopilotModeManagerStep(referenceState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Abnormal-attitude protection disconnects', ...
    ~attitudeOut.engaged && attitudeOut.eventCode == ...
    manager.codes.event.DISCONNECT_ATTITUDE, ...
    'Logic stress exceeds the declared project bank threshold');

%% 14. Disconnect priority over simultaneous mode request

u = base;
u.disconnectRequest = true;
u.lateralModeRequest = manager.codes.lateral.ROLL;
u.verticalModeRequest = manager.codes.vertical.PITCH;
[~,priorityOut] = ...
    c172sAutopilotModeManagerStep(referenceState,u,manager,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Disconnect priority is deterministic', ...
    ~priorityOut.engaged && ...
    priorityOut.eventCode == manager.codes.event.DISCONNECT_COMMAND && ...
    ~priorityOut.rollModeEnable && ~priorityOut.pitchModeEnable, ...
    'Simultaneous lower-priority mode requests are ignored');

%% 15. Deterministic replay

traceA = deterministicTrace(manager,base,dt);
traceB = deterministicTrace(manager,base,dt);
[caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail, ...
    'Deterministic replay is bitwise identical', ...
    isequaln(traceA,traceB), ...
    'Explicit state produces identical mode/event/reference traces');

%% Consolidated assertions and report

assert(numel(caseStatus) >= manager.validation.minimumAuditCases, ...
    'auditAutopilotModeManager:InsufficientCoverage', ...
    'The audit contains fewer cases than the declared minimum.');
assert(all(caseStatus), ...
    'auditAutopilotModeManager:AuditFailure', ...
    'One or more Autopilot Mode Manager V1 audit cases failed.');

results = table(caseName,caseStatus,caseDetail, ...
    'VariableNames',{'Case','Pass','Detail'});
assignin('base','autopilotModeManagerV1AuditResults',results);
assignin('base','autopilotModeManagerV1Configuration',manager);

fprintf('============================================================\n');
fprintf(' C172S AUTOPILOT MODE MANAGER V1 - MATLAB LOGIC AUDIT\n');
fprintf('============================================================\n\n');
fprintf('Artifact                             : %s\n', ...
    manager.artifactRevision);
fprintf('Default lateral / vertical modes     : ROLL / PITCH\n');
fprintf('Lateral modes                        : OFF, ROLL, HEADING\n');
fprintf('Vertical modes                       : OFF, PITCH, ALTITUDE\n');
fprintf('Frozen dependency interfaces audited : %d\n',dependencyCount);
fprintf('Supervisor sample time               : %.3f s\n',dt);
fprintf('Outer-sensor fallback confirmation   : %.3f s\n', ...
    manager.protection.outerSensorFallbackDelay_s);
fprintf('Core-sensor disconnect confirmation  : %.3f s\n', ...
    manager.protection.coreSensorDisconnectDelay_s);
fprintf('Sustained-saturation disconnect      : %.2f s\n', ...
    manager.protection.sustainedSaturationDisconnectDelay_s);
fprintf('Logic-stress bank / pitch thresholds : %.1f / %.1f deg\n\n', ...
    manager.protection.maximumAbsoluteBank_deg, ...
    manager.protection.maximumAbsolutePitch_deg);

for k = 1:height(results)
    fprintf('[PASS] %-47s %s\n', ...
        char(results.Case(k)),char(results.Detail(k)));
end

fprintf('\nPassed audit cases                   : %d/%d\n', ...
    sum(results.Pass),height(results));
fprintf('PASS: default capture and two-axis mode exclusivity are correct.\n');
fprintf('PASS: attitude-mode transfers emit both integrator-tracking handshakes.\n');
fprintf('PASS: outer-source loss degrades safely to the corresponding inner mode.\n');
fprintf('PASS: pilot, core-sensor, saturation and attitude disconnect priorities pass.\n');
fprintf('PASS: deterministic replay produces an identical supervisory trace.\n');
fprintf(['NOTE: this is a supervisory-logic/source audit against frozen ', ...
    'project interfaces; executable Simulink integration remains the ', ...
    'next stage.\n']);
fprintf(['NOTE: thresholds and timers remain explicit project assumptions; ', ...
    'this is not aircraft approval.\n']);

%% Local audit helpers

function input = nominalInput(manager)
input.engageRequest = false;
input.disconnectRequest = false;
input.pilotOverride = false;
input.trimStable = true;
input.coreSensorsValid = true;
input.headingValid = true;
input.altitudeValid = true;
input.aileronSaturated = false;
input.elevatorSaturated = false;
input.lateralModeRequest = manager.codes.lateral.OFF;
input.verticalModeRequest = manager.codes.vertical.OFF;
input.updateHeadingReference = false;
input.updateAltitudeReference = false;
input.bank_deg = 0.0;
input.pitch_deg = 0.0;
input.heading_deg = 0.0;
input.altitude_ft = 4000.0;
input.selectedHeading_deg = 0.0;
input.selectedAltitude_ft = 4000.0;
end

function count = auditFrozenDependencies(manager)
longitudinal = c172sLongitudinalData();
pitchRate = c172sPitchRateDamperData();
pitchAttitude = c172sPitchAttitudeControllerData();
elevator = c172sElevatorActuatorData();
altitude = c172sAltitudeHoldControllerData();
lateral = c172sLateralDirectionalData();
yaw = c172sYawDamperData();
rudder = c172sRudderActuatorData();
aileron = c172sAileronActuatorData();
roll = c172sRollAttitudeControllerData();
headingSensor = c172sHeadingSensorData();
heading = c172sHeadingHoldControllerData();

checks = [ ...
    strcmp(longitudinal.model.version,manager.required.longitudinalPlant); ...
    strcmp(pitchRate.version,manager.required.pitchRateDamper); ...
    strcmp(pitchAttitude.version, ...
        manager.required.pitchAttitudeController); ...
    strcmp(elevator.integratedLoopVersion,manager.required.pitchLoop); ...
    strcmp(altitude.version,manager.required.altitudeLoop); ...
    strcmp(lateral.model.version,manager.required.lateralPlant); ...
    strcmp(yaw.artifactRevision,manager.required.yawController); ...
    strcmp(rudder.artifactRevision,manager.required.rudderAudit); ...
    strcmp(aileron.artifactRevision,manager.required.aileronAudit); ...
    strcmp(roll.artifactRevision,manager.required.rollController); ...
    strcmp(headingSensor.artifactRevision, ...
        manager.required.headingSensorAudit); ...
    strcmp(heading.artifactRevision,manager.required.headingController)];

assert(all(checks), ...
    'auditAutopilotModeManager:FrozenDependencyMismatch', ...
    ['At least one frozen controller, actuator, sensor or plant ', ...
     'dependency does not match the Mode Manager V1 ledger.']);
count = numel(checks);
end

function count = thresholdSamples(threshold_s,dt)
count = ceil(threshold_s/dt-1.0e-12);
end

function trace = deterministicTrace(manager,base,dt)
state = [];
trace = zeros(240,8);
for k = 1:size(trace,1)
    input = base;
    if k == 2
        input.engageRequest = true;
    end
    if k == 20
        input.lateralModeRequest = manager.codes.lateral.HEADING;
        input.selectedHeading_deg = 45.0;
    end
    if k == 40
        input.verticalModeRequest = manager.codes.vertical.ALTITUDE;
        input.selectedAltitude_ft = 4100.0;
    end
    if k >= 80 && k < 90
        input.headingValid = false;
        input.bank_deg = 8.0;
    end
    if k >= 120
        input.elevatorSaturated = true;
    end
    [state,output] = ...
        c172sAutopilotModeManagerStep(state,input,manager,dt);
    trace(k,:) = [double(output.engaged), ...
        double(output.lateralMode),double(output.verticalMode), ...
        output.bankCommand_deg,output.pitchCommand_deg, ...
        output.headingCommand_deg,output.altitudeCommand_ft, ...
        double(output.eventCode)];
end
end

function [caseName,caseStatus,caseDetail] = addCase( ...
    caseName,caseStatus,caseDetail,name,passed,detail)
caseName(end+1,1) = string(name); %#ok<AGROW>
caseStatus(end+1,1) = logical(passed); %#ok<AGROW>
caseDetail(end+1,1) = string(detail); %#ok<AGROW>
end
