function results = auditC172sAtmosphereAirData()
%% C172S nonlinear 6-DOF V1 - atmosphere, wind and air-data audit

clear;
clc;

airModel = c172sAtmosphereAirDataData();
source = c172sNonlinear6DofSourceData();
kernel = c172sRigidBody6DofData();
longitudinal = c172sLongitudinalData();

name = strings(0,1);
detail = strings(0,1);
passed = false(0,1);
zeroWind = zeros(3,1);

record('Source/convention audit revision', ...
    strcmp(airModel.required.sourceAudit,source.artifactRevision), ...
    source.artifactRevision);
record('Rigid-body kernel revision', ...
    strcmp(airModel.required.rigidBodyKernel,kernel.artifactRevision), ...
    kernel.artifactRevision);
record('Released controller regression remains external', ...
    airModel.required.masterRegressionPasses == 18, ...
    'v1.0.0 remains frozen at 18/18');
record('Aerodynamics and propulsion remain excluded', ...
    ~airModel.validation.aerodynamicsIncluded && ...
    ~airModel.validation.propulsionIncluded, ...
    'environment layer computes no aircraft force or moment');

xSeaLevel = levelState(0.0,0.0);
seaLevel = c172sAtmosphereAirData( ...
    xSeaLevel,zeroWind,zeroWind,airModel);
seaError = max(abs([ ...
    seaLevel.temperature_K-airModel.constants.T0_K; ...
    seaLevel.pressure_Pa-airModel.constants.p0_Pa; ...
    seaLevel.density_kgpm3-airModel.constants.rho0_kgpm3]));
record('ISA sea-level reference', ...
    seaError <= airModel.validation.maximumISAAbsoluteError, ...
    sprintf('T %.2f K, p %.1f Pa, rho %.4f kg/m^3', ...
    seaLevel.temperature_K,seaLevel.pressure_Pa,seaLevel.density_kgpm3));

xTrim = levelState(airModel.trim.altitude_m,airModel.trim.V_mps);
trim = c172sAtmosphereAirData(xTrim,zeroWind,zeroWind,airModel);
trimEnvironmentError = max(abs([ ...
    trim.temperature_K-airModel.trim.temperature_K; ...
    trim.pressure_Pa-airModel.trim.pressure_Pa; ...
    trim.density_kgpm3-airModel.trim.rho_kgpm3; ...
    trim.dynamicPressure_Pa-airModel.trim.qbar_Pa]));
record('Frozen 4000-ft ISA environment recovered', ...
    trimEnvironmentError <= airModel.validation.maximumISAAbsoluteError, ...
    sprintf('maximum atmosphere/qbar discrepancy %.3g',trimEnvironmentError));
record('Frozen 110-KTAS air state recovered', ...
    abs(trim.TAS_mps-airModel.trim.V_mps) <= 1.0e-12 && ...
    abs(trim.alpha_rad) <= 1.0e-12 && abs(trim.beta_rad) <= 1.0e-12, ...
    sprintf('TAS %.6f m/s, alpha/beta 0/0 rad',trim.TAS_mps));

xAltitude = xTrim;
xAltitude(9) = -2000.0;
altitudeCase = c172sAtmosphereAirData( ...
    xAltitude,zeroWind,zeroWind,airModel);
record('NED-down altitude sign', ...
    altitudeCase.altitude_m == 2000.0, ...
    'positionDown = -2000 m produces altitude +2000 m');
record('Atmospheric monotonicity with altitude', ...
    altitudeCase.temperature_K < seaLevel.temperature_K && ...
    altitudeCase.pressure_Pa < seaLevel.pressure_Pa && ...
    altitudeCase.density_kgpm3 < seaLevel.density_kgpm3, ...
    'temperature, pressure and density decrease through the troposphere');
record('Speed of sound and viscosity are physical', ...
    trim.speedOfSound_mps > trim.TAS_mps && ...
    trim.dynamicViscosity_Pas > 0 && trim.Reynolds > 0, ...
    sprintf('a %.3f m/s, mu %.4g Pa*s, Re %.3g', ...
    trim.speedOfSound_mps,trim.dynamicViscosity_Pas,trim.Reynolds));

headwind = c172sAtmosphereAirData( ...
    xTrim,[-10;0;0],zeroWind,airModel);
tailwind = c172sAtmosphereAirData( ...
    xTrim,[10;0;0],zeroWind,airModel);
record('Headwind and tailwind signs', ...
    abs(headwind.TAS_mps-(airModel.trim.V_mps+10)) <= 1.0e-12 && ...
    abs(tailwind.TAS_mps-(airModel.trim.V_mps-10)) <= 1.0e-12, ...
    'northward aircraft: negative-N wind raises TAS; positive-N wind lowers TAS');

crosswind = c172sAtmosphereAirData( ...
    xTrim,[0;-8;0],zeroWind,airModel);
expectedBeta = atan2(8,airModel.trim.V_mps);
record('Crosswind sideslip sign', ...
    crosswind.beta_rad > 0 && ...
    abs(crosswind.beta_rad-expectedBeta) <= ...
    airModel.validation.maximumAngleError_rad, ...
    sprintf('wind from right produces beta +%.5f rad',crosswind.beta_rad));

verticalGust = c172sAtmosphereAirData( ...
    xTrim,zeroWind,[0;0;-5],airModel);
expectedAlpha = atan2(5,airModel.trim.V_mps);
record('Vertical-gust angle-of-attack sign', ...
    verticalGust.alpha_rad > 0 && ...
    abs(verticalGust.alpha_rad-expectedAlpha) <= ...
    airModel.validation.maximumAngleError_rad, ...
    sprintf('upward air-mass gust produces alpha +%.5f rad', ...
    verticalGust.alpha_rad));

xYaw = xTrim;
xYaw(10:13) = axisAngleQuaternion([0;0;1],pi/2);
yawWind = c172sAtmosphereAirData(xYaw,[0;10;0],zeroWind,airModel);
record('Wind transforms through aircraft attitude', ...
    norm(yawWind.velocityGroundNED_mps-[0;airModel.trim.V_mps;0],inf) ...
    <= airModel.validation.maximumKinematicError && ...
    abs(yawWind.TAS_mps-(airModel.trim.V_mps-10)) <= 1.0e-11, ...
    '+90-deg yaw makes positive-east wind a tailwind');

combined = c172sAtmosphereAirData( ...
    xTrim,[2;-3;1],[-5;7;-4],airModel);
record('Steady wind and gust superposition', ...
    norm(combined.windNED_mps-[-3;4;-3],inf) <= 1.0e-15 && ...
    norm(combined.velocityAirNED_mps- ...
    (combined.velocityGroundNED_mps-combined.windNED_mps),inf) <= 1.0e-15, ...
    'total wind is the exact vector sum of steady wind and gust');

qbarExpected = 0.5*trim.density_kgpm3*trim.TAS_mps^2;
record('Dynamic-pressure definition', ...
    abs(trim.dynamicPressure_Pa-qbarExpected) <= 1.0e-12, ...
    sprintf('qbar %.6f Pa',trim.dynamicPressure_Pa));
record('Mach and equivalent-airspeed definitions', ...
    abs(trim.Mach-trim.TAS_mps/trim.speedOfSound_mps) <= 1.0e-15 && ...
    abs(trim.EAS_mps-trim.TAS_mps*sqrt( ...
    trim.density_kgpm3/airModel.constants.rho0_kgpm3)) <= 1.0e-14, ...
    sprintf('Mach %.5f, EAS %.5f m/s',trim.Mach,trim.EAS_mps));

delta = 1.0e-3;
xPlus = xTrim; xPlus(1) = xPlus(1)+delta;
xMinus = xTrim; xMinus(1) = xMinus(1)-delta;
plus = c172sAtmosphereAirData(xPlus,zeroWind,zeroWind,airModel);
minus = c172sAtmosphereAirData(xMinus,zeroWind,zeroWind,airModel);
dQbar_dV = (plus.dynamicPressure_Pa-minus.dynamicPressure_Pa)/(2*delta);
expected_dQbar_dV = trim.density_kgpm3*trim.TAS_mps;
record('Dynamic-pressure numerical derivative', ...
    relativeError(dQbar_dV,expected_dQbar_dV) <= ...
    airModel.validation.maximumDerivativeRelativeError, ...
    sprintf('dqbar/dV %.6f Pa*s/m',dQbar_dV));

xWPlus = xTrim; xWPlus(3) = delta;
xWMinus = xTrim; xWMinus(3) = -delta;
wPlus = c172sAtmosphereAirData(xWPlus,zeroWind,zeroWind,airModel);
wMinus = c172sAtmosphereAirData(xWMinus,zeroWind,zeroWind,airModel);
dAlpha_dW = (wPlus.alpha_rad-wMinus.alpha_rad)/(2*delta);
expected_dAlpha_dW = 1/airModel.trim.V_mps;
record('Angle-of-attack numerical derivative', ...
    relativeError(dAlpha_dW,expected_dAlpha_dW) <= ...
    airModel.validation.maximumDerivativeRelativeError, ...
    sprintf('dalpha/dw %.8f s/m',dAlpha_dW));

almostPureSide = levelState(0.0,0.0);
almostPureSide(2) = 30.0;
almostPureSide(1) = 1.0e-12;
side = c172sAtmosphereAirData( ...
    almostPureSide,zeroWind,zeroWind,airModel);
record('Sideslip inverse-trig argument is bounded', ...
    isfinite(side.beta_rad) && abs(side.beta_rad) <= pi/2, ...
    sprintf('finite beta %.8f rad',side.beta_rad));

reverseFlow = levelState(0.0,-20.0);
reverse = c172sAtmosphereAirData( ...
    reverseFlow,zeroWind,zeroWind,airModel);
record('Angle of attack uses atan2', ...
    abs(abs(reverse.alpha_rad)-pi) <= 1.0e-12, ...
    sprintf('negative u preserves quadrant: alpha %.8f rad',reverse.alpha_rad));

cancelled = c172sAtmosphereAirData( ...
    xTrim,[airModel.trim.V_mps;0;0],zeroWind,airModel);
lowSpeedVector = [cancelled.TAS_mps;cancelled.dynamicPressure_Pa; ...
    cancelled.Mach;cancelled.Reynolds;cancelled.alpha_rad;cancelled.beta_rad];
record('Low-airspeed protection', ...
    ~cancelled.valid && all(isfinite(lowSpeedVector)) && ...
    all(lowSpeedVector == 0), ...
    'wind cancellation returns finite zero air data and valid=false');

replay1 = c172sAtmosphereAirData( ...
    xYaw,[1;-2;3],[0.5;0.25;-0.75],airModel);
replay2 = c172sAtmosphereAirData( ...
    xYaw,[1;-2;3],[0.5;0.25;-0.75],airModel);
record('Deterministic replay', ...
    airModel.validation.requireDeterministicReplay && isequal(replay1,replay2), ...
    'identical state, wind and gust reproduce bitwise-identical outputs');

record('Invalid state dimension rejected', ...
    expectError(@() c172sAtmosphereAirData( ...
    zeros(12,1),zeroWind,zeroWind,airModel)), ...
    '12-state input is rejected');
record('Invalid wind dimension rejected', ...
    expectError(@() c172sAtmosphereAirData( ...
    xTrim,zeros(2,1),zeroWind,airModel)), ...
    'wind must be a three-component NED column vector');

badQuaternion = xTrim;
badQuaternion(10:13) = 0;
record('Invalid quaternion rejected', ...
    expectError(@() c172sAtmosphereAirData( ...
    badQuaternion,zeroWind,zeroWind,airModel)), ...
    'zero-norm attitude quaternion is rejected');

badAltitude = xTrim;
badAltitude(9) = -(airModel.atmosphere.maximumGeopotentialAltitude_m+1);
record('Atmosphere-domain violation rejected', ...
    expectError(@() c172sAtmosphereAirData( ...
    badAltitude,zeroWind,zeroWind,airModel)), ...
    'altitudes outside the declared ISA troposphere domain are rejected');

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR 6-DOF V1 - ATMOSPHERE/AIR-DATA AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',airModel.artifactRevision);
fprintf('%-39s: %s\n','Rigid-body kernel',airModel.required.rigidBodyKernel);
fprintf('%-39s: %s\n','Atmosphere',airModel.atmosphere.model);
fprintf('%-39s: %.0f ft / %.0f KTAS\n\n','Frozen trim recovery', ...
    airModel.trim.pressureAltitude_ft,airModel.trim.V_KTAS);

for k = 1:numel(passed)
    label = 'PASS';
    if ~passed(k), label = 'FAIL'; end
    fprintf('[%s] %-47s %s\n',label,name(k),detail(k));
end
fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));

results = struct('Name',cellstr(name),'Status',num2cell(passed), ...
    'Detail',cellstr(detail));
assert(all(passed),'auditC172sAtmosphereAirData:AuditFailed', ...
    '%d of %d atmosphere/air-data gates failed.',sum(~passed),numel(passed));
fprintf('PASS: ISA atmosphere and the frozen 4000-ft trim environment match.\n');
fprintf('PASS: NED wind/gust transforms and air-relative velocity signs pass.\n');
fprintf('PASS: TAS, EAS, alpha, beta, qbar, Mach and Reynolds calculations pass.\n');
fprintf('PASS: low-speed protection, domain rejection and replay gates pass.\n');
fprintf(['NOTE: this layer computes environmental and air-data quantities only; ', ...
    'aerodynamic forces remain unimplemented.\n']);
fprintf('NOTE: this is an educational research model, not aircraft approval.\n');

function record(caseName,condition,caseDetail)
name(end+1,1) = string(caseName); %#ok<AGROW>
passed(end+1,1) = logical(condition); %#ok<AGROW>
detail(end+1,1) = string(caseDetail); %#ok<AGROW>
end
end

function state = levelState(altitude_m,forwardSpeed_mps)
state = zeros(13,1);
state(1) = forwardSpeed_mps;
state(9) = -altitude_m;
state(10) = 1.0;
end

function quaternion = axisAngleQuaternion(axis,angle_rad)
axis = axis/norm(axis);
quaternion = [cos(angle_rad/2);axis*sin(angle_rad/2)];
end

function error = relativeError(actual,expected)
error = abs(actual-expected)/max(abs(expected),eps);
end

function passed = expectError(action)
passed = false;
try
    action();
catch
    passed = true;
end
end
