function results = auditC172sRigidBody6DofEom()
%% C172S nonlinear 6-DOF V1 - rigid-body kernel audit

clear;
clc;

kernel = c172sRigidBody6DofData();
source = c172sNonlinear6DofSourceData();
longitudinal = c172sLongitudinalData();
lateral = c172sLateralDirectionalData();

name = strings(0,1);
detail = strings(0,1);
passed = false(0,1);

record('Source/convention audit revision', ...
    strcmp(kernel.required.sourceAudit,source.artifactRevision), ...
    source.artifactRevision);
record('Frozen plant anchors preserved', ...
    strcmp(longitudinal.model.version,kernel.required.longitudinalPlant) && ...
    strcmp(lateral.model.version,kernel.required.lateralPlant), ...
    'Longitudinal Plant V1 and Lateral-Directional Plant V0.1');
record('Released controller regression remains external', ...
    kernel.required.masterRegressionPasses == 18, ...
    'v1.0.0 remains frozen at 18/18');

inertia = kernel.inertia.matrix_kgm2;
record('Mass and inertia are physically admissible', ...
    kernel.mass_kg > 0 && ...
    norm(inertia-inertia.','fro') < eps && all(eig(inertia) > 0), ...
    sprintf('mass %.3f kg; minimum inertia eigenvalue %.2f kg*m^2', ...
    kernel.mass_kg,min(eig(inertia))));
record('Aerodynamics and propulsion are excluded', ...
    ~kernel.validation.aerodynamicsIncluded && ...
    ~kernel.validation.propulsionIncluded && ...
    ~kernel.validation.actuatorsIncluded, ...
    'kernel accepts prescribed non-gravitational force and moment only');

xLevel = zeros(13,1);
xLevel(10) = 1.0;
zero3 = zeros(3,1);
[levelDerivative,levelAux] = ...
    c172sRigidBody6DofEom(xLevel,zero3,zero3,kernel);
record('Gravity sign in level body axes', ...
    vectorError(levelDerivative(1:3),[0;0;kernel.gravity_mps2]) <= ...
    kernel.validation.maximumStaticDerivativeError, ...
    sprintf('free-fall body acceleration [%.4f %.4f %.4f] m/s^2', ...
    levelDerivative(1:3)));

supportForce = [0;0;-kernel.mass_kg*kernel.gravity_mps2];
supportedDerivative = ...
    c172sRigidBody6DofEom(xLevel,supportForce,zero3,kernel);
record('Level support force balances gravity', ...
    norm(supportedDerivative(1:6),inf) <= ...
    kernel.validation.maximumStaticDerivativeError, ...
    'Fz = -m*g produces zero translational acceleration');

xPitch90 = xLevel;
xPitch90(10:13) = axisAngleQuaternion([0;1;0],pi/2);
pitchDerivative = c172sRigidBody6DofEom(xPitch90,zero3,zero3,kernel);
record('Gravity rotates correctly into body axes', ...
    vectorError(pitchDerivative(1:3),[-kernel.gravity_mps2;0;0]) <= ...
    2.0e-12, ...
    '+90-deg pitch maps NED-down gravity to negative body x');

xYaw90 = xLevel;
xYaw90(1) = 25.0;
xYaw90(10:13) = axisAngleQuaternion([0;0;1],pi/2);
yawDerivative = c172sRigidBody6DofEom(xYaw90,zero3,zero3,kernel);
record('Body-to-NED position kinematics', ...
    vectorError(yawDerivative(7:9),[0;25;0]) <= 1.0e-12, ...
    '+90-deg yaw maps body-forward velocity to NED east');

zeroGravity = kernel;
zeroGravity.gravity_mps2 = 0.0;
xCoriolis = xLevel;
xCoriolis(1) = 40.0;
xCoriolis(6) = 0.2;
coriolisDerivative = ...
    c172sRigidBody6DofEom(xCoriolis,zero3,zero3,zeroGravity);
record('Rotating-body transport term sign', ...
    vectorError(coriolisDerivative(1:3),[0;-8;0]) <= 1.0e-12, ...
    '-omega cross velocity gives vDot = -r*u');

forceCases = eye(3)*100.0;
forceSignPass = true;
for axis = 1:3
    derivative = c172sRigidBody6DofEom( ...
        xLevel,forceCases(:,axis),zero3,zeroGravity);
    expected = zeros(3,1);
    expected(axis) = 100.0/kernel.mass_kg;
    forceSignPass = forceSignPass && ...
        vectorError(derivative(1:3),expected) <= 1.0e-14;
end
record('Body-force axis signs',forceSignPass, ...
    '+Fx/+Fy/+Fz produce +uDot/+vDot/+wDot');

momentCases = eye(3)*100.0;
momentSignPass = true;
for axis = 1:3
    derivative = c172sRigidBody6DofEom( ...
        xLevel,zero3,momentCases(:,axis),zeroGravity);
    momentSignPass = momentSignPass && derivative(3+axis) > 0 && ...
        norm(derivative(4:6)-inertia\momentCases(:,axis),inf) <= 1.0e-14;
end
record('Body-moment axis signs',momentSignPass, ...
    '+L/+M/+N produce +pDot/+qDot/+rDot');

coupledModel = zeroGravity;
coupledModel.inertia.matrix_kgm2 = ...
    kernel.validation.coupledTestInertia_kgm2;
coupledDerivative = c172sRigidBody6DofEom( ...
    xLevel,zero3,[100;0;0],coupledModel);
record('Nonzero Ixz inertial coupling', ...
    coupledDerivative(4) > 0 && coupledDerivative(6) > 0 && ...
    abs(coupledDerivative(5)) <= 1.0e-14, ...
    'positive roll moment produces coupled positive pDot and rDot');

xQuaternion = xLevel;
xQuaternion(4:6) = [0.31;-0.22;0.17];
xQuaternion(10:13) = normalizeQuaternion([0.81;0.22;-0.31;0.41]);
quaternionDerivative = c172sRigidBody6DofEom( ...
    xQuaternion,zero3,zero3,zeroGravity);
normRate = 2*xQuaternion(10:13).'*quaternionDerivative(10:13);
record('Continuous quaternion norm invariant', ...
    abs(normRate) <= 1.0e-15, ...
    sprintf('d(q''q)/dt = %.3g',normRate));

xSingular = xLevel;
xSingular(4:6) = [0.2;-0.1;0.3];
xSingular(10:13) = axisAngleQuaternion([0;1;0],deg2rad(89.999999));
singularDerivative = c172sRigidBody6DofEom( ...
    xSingular,zero3,zero3,zeroGravity);
record('Euler-singularity-free attitude kinematics', ...
    all(isfinite(singularDerivative)) && ...
    norm(singularDerivative(10:13)) > 0, ...
    'quaternion derivative remains finite at pitch 89.999999 deg');

freeFallTime = 3.0;
xFreeFall = integrateRK4(xLevel,zero3,zero3,kernel,0.01,freeFallTime);
expectedFreeFall = xLevel;
expectedFreeFall(3) = kernel.gravity_mps2*freeFallTime;
expectedFreeFall(9) = 0.5*kernel.gravity_mps2*freeFallTime^2;
freeFallError = norm(xFreeFall-expectedFreeFall,inf);
record('Free-fall analytical trajectory', ...
    freeFallError <= kernel.validation.maximumFreeFallError, ...
    sprintf('maximum state error %.3g',freeFallError));

xStraight = xLevel;
xStraight(1:3) = [32;-4;2];
xStraight(10:13) = axisAngleQuaternion([0;0;1],deg2rad(37));
straightTime = 6.0;
[~,straightAux] = ...
    c172sRigidBody6DofEom(xStraight,zero3,zero3,zeroGravity);
xStraightFinal = integrateRK4( ...
    xStraight,zero3,zero3,zeroGravity,0.01,straightTime);
expectedPosition = straightAux.bodyToNED*xStraight(1:3)*straightTime;
record('Zero-force inertial straight-line motion', ...
    norm(xStraightFinal(7:9)-expectedPosition,inf) <= 2.0e-10 && ...
    norm(xStraightFinal(1:6)-xStraight(1:6),inf) <= 1.0e-12, ...
    'constant inertial velocity integrates to the analytical NED position');

xTorqueFree = xLevel;
xTorqueFree(1:3) = [31;-3;2];
xTorqueFree(4:6) = [0.21;-0.17;0.13];
xTorqueFree(10:13) = normalizeQuaternion([0.91;0.13;-0.24;0.29]);
[~,initialAux] = ...
    c172sRigidBody6DofEom(xTorqueFree,zero3,zero3,zeroGravity);
initialLinearMomentumNED = ...
    zeroGravity.mass_kg*initialAux.bodyToNED*xTorqueFree(1:3);
initialAngularMomentumNED = ...
    initialAux.bodyToNED*initialAux.angularMomentumBody_kgm2ps;
initialEnergy = initialAux.translationalKineticEnergy_J + ...
    initialAux.rotationalKineticEnergy_J;
xTorqueFreeFinal = integrateRK4( ...
    xTorqueFree,zero3,zero3,zeroGravity,0.002,8.0);
[~,finalAux] = c172sRigidBody6DofEom( ...
    xTorqueFreeFinal,zero3,zero3,zeroGravity);
finalLinearMomentumNED = ...
    zeroGravity.mass_kg*finalAux.bodyToNED*xTorqueFreeFinal(1:3);
finalAngularMomentumNED = ...
    finalAux.bodyToNED*finalAux.angularMomentumBody_kgm2ps;
finalEnergy = finalAux.translationalKineticEnergy_J + ...
    finalAux.rotationalKineticEnergy_J;
linearMomentumError = relativeError( ...
    finalLinearMomentumNED,initialLinearMomentumNED);
angularMomentumError = relativeError( ...
    finalAngularMomentumNED,initialAngularMomentumNED);
energyError = abs(finalEnergy-initialEnergy)/initialEnergy;
record('Torque-free linear momentum conservation', ...
    linearMomentumError <= ...
    kernel.validation.maximumConservationRelativeError, ...
    sprintf('relative error %.3g',linearMomentumError));
record('Torque-free angular momentum conservation', ...
    angularMomentumError <= ...
    kernel.validation.maximumConservationRelativeError, ...
    sprintf('relative error %.3g',angularMomentumError));
record('Torque-free kinetic-energy conservation', ...
    energyError <= kernel.validation.maximumConservationRelativeError, ...
    sprintf('relative error %.3g',energyError));

xSpin = xLevel;
xSpin(6) = 0.7;
spinTime = 4.0;
xCoarse = integrateRK4(xSpin,zero3,zero3,zeroGravity,0.10,spinTime);
xFine = integrateRK4(xSpin,zero3,zero3,zeroGravity,0.05,spinTime);
exactQuaternion = axisAngleQuaternion([0;0;1],0.7*spinTime);
coarseError = quaternionDistance(xCoarse(10:13),exactQuaternion);
fineError = quaternionDistance(xFine(10:13),exactQuaternion);
rk4Ratio = coarseError/max(fineError,eps);
record('RK4 fourth-order convergence', ...
    rk4Ratio >= kernel.validation.minimumRK4ErrorRatio && ...
    fineError <= kernel.validation.maximumFineRK4AttitudeError_rad, ...
    sprintf('coarse/fine error ratio %.2f; fine error %.3g rad', ...
    rk4Ratio,fineError));

xReplay1 = integrateRK4( ...
    xTorqueFree,zero3,zero3,zeroGravity,0.01,2.0);
xReplay2 = integrateRK4( ...
    xTorqueFree,zero3,zero3,zeroGravity,0.01,2.0);
record('Deterministic replay', ...
    kernel.validation.requireDeterministicReplay && isequal(xReplay1,xReplay2), ...
    'identical initial state and inputs produce bitwise-identical state');

record('Invalid state dimension rejected', ...
    expectError(@() c172sRigidBody6DofEom( ...
    zeros(12,1),zero3,zero3,kernel)), ...
    '12-state input cannot enter the 13-state kernel');

badMass = kernel;
badMass.mass_kg = 0.0;
record('Invalid mass rejected', ...
    expectError(@() c172sRigidBody6DofEom( ...
    xLevel,zero3,zero3,badMass)), ...
    'zero or negative mass is rejected');

badInertia = kernel;
badInertia.inertia.matrix_kgm2 = diag([1,1,-1]);
record('Invalid inertia rejected', ...
    expectError(@() c172sRigidBody6DofEom( ...
    xLevel,zero3,zero3,badInertia)), ...
    'non-positive-definite inertia tensor is rejected');

badQuaternion = xLevel;
badQuaternion(10:13) = 0.0;
record('Invalid quaternion rejected', ...
    expectError(@() c172sRigidBody6DofEom( ...
    badQuaternion,zero3,zero3,kernel)), ...
    'zero-norm quaternion is rejected');

nonUnitQuaternion = xLevel;
nonUnitQuaternion(10) = 1.02;
record('Materially non-unit quaternion rejected', ...
    expectError(@() c172sRigidBody6DofEom( ...
    nonUnitQuaternion,zero3,zero3,kernel)), ...
    'quaternion norm errors above 0.01 are rejected');

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR 6-DOF V1 - RIGID-BODY KERNEL AUDIT\n');
fprintf('============================================================\n\n');
fprintf('%-39s: %s\n','Artifact',kernel.artifactRevision);
fprintf('%-39s: %s\n','Source/convention audit',kernel.required.sourceAudit);
fprintf('%-39s: %.3f kg\n','Provisional mass',kernel.mass_kg);
fprintf('%-39s: %.4f m/s^2\n','Gravity',kernel.gravity_mps2);
fprintf('%-39s: %d\n\n','State count',kernel.state.count);

for k = 1:numel(passed)
    label = 'PASS';
    if ~passed(k), label = 'FAIL'; end
    fprintf('[%s] %-47s %s\n',label,name(k),detail(k));
end
fprintf('\nPassed audit cases                     : %d/%d\n', ...
    sum(passed),numel(passed));

results = struct('Name',cellstr(name),'Status',num2cell(passed), ...
    'Detail',cellstr(detail));
assert(all(passed),'auditC172sRigidBody6DofEom:AuditFailed', ...
    '%d of %d rigid-body gates failed.',sum(~passed),numel(passed));
fprintf('PASS: translational, rotational, NED and quaternion equations pass.\n');
fprintf('PASS: gravity, force, moment and inertial-coupling signs are correct.\n');
fprintf('PASS: conservation, RK4 convergence and deterministic replay pass.\n');
fprintf('PASS: invalid mass, inertia, state and quaternion inputs are rejected.\n');
fprintf(['NOTE: this validates the aircraft-independent rigid-body kernel; ', ...
    'aerodynamics and propulsion are not yet implemented.\n']);
fprintf(['NOTE: mass properties remain provisional and this is not aircraft ', ...
    'approval.\n']);

function record(caseName,condition,caseDetail)
name(end+1,1) = string(caseName); %#ok<AGROW>
passed(end+1,1) = logical(condition); %#ok<AGROW>
detail(end+1,1) = string(caseDetail); %#ok<AGROW>
end
end

function finalState = integrateRK4( ...
    initialState,forceBody,momentBody,model,step_s,stopTime_s)
steps = round(stopTime_s/step_s);
if abs(steps*step_s-stopTime_s) > 10*eps(max(1,stopTime_s))
    error('auditC172sRigidBody6DofEom:NonIntegralHorizon', ...
        'stopTime_s must be an integer number of steps.');
end
state = initialState;
for k = 1:steps
    k1 = c172sRigidBody6DofEom(state,forceBody,momentBody,model);
    k2 = c172sRigidBody6DofEom( ...
        state+0.5*step_s*k1,forceBody,momentBody,model);
    k3 = c172sRigidBody6DofEom( ...
        state+0.5*step_s*k2,forceBody,momentBody,model);
    k4 = c172sRigidBody6DofEom( ...
        state+step_s*k3,forceBody,momentBody,model);
    state = state+(step_s/6)*(k1+2*k2+2*k3+k4);
    state(10:13) = normalizeQuaternion(state(10:13));
end
finalState = state;
end

function quaternion = axisAngleQuaternion(axis,angle_rad)
axis = axis/norm(axis);
quaternion = [cos(angle_rad/2);axis*sin(angle_rad/2)];
end

function quaternion = normalizeQuaternion(quaternion)
quaternion = quaternion/norm(quaternion);
end

function error_rad = quaternionDistance(left,right)
left = normalizeQuaternion(left);
right = normalizeQuaternion(right);
% Chord distance retains resolution when acos(dot) rounds to zero. Twice
% the minimum antipodal chord is the small-angle rotation error in radians.
error_rad = 2*min(norm(left-right),norm(left+right));
end

function error = vectorError(actual,expected)
error = norm(actual-expected,inf);
end

function error = relativeError(actual,expected)
error = norm(actual-expected)/max(norm(expected),eps);
end

function passed = expectError(action)
passed = false;
try
    action();
catch
    passed = true;
end
end
