function modelName = buildC172sYawDamperActuatorSimulink(forceRebuild)
%BUILDC172SYAWDAMPERACTUATORSIMULINK Build the protected Yaw Damper V2 model.
%
%   MODELNAME = BUILDC172SYAWDAMPERACTUATORSIMULINK() creates or opens
%   C172S_YawDamper_V2_Actuator.slx in the current folder.
%
%   MODELNAME = BUILDC172SYAWDAMPERACTUATORSIMULINK(true) overwrites only
%   the generated SLX model. It does not alter the frozen Yaw Damper V1,
%   Plant V0.1, or actuator/source-audit MATLAB artifacts.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_YawDamper_V2_Actuator';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize frozen dependencies and selected V2 assumptions

yd2Data = c172sLateralDirectionalData();
[~,yd2Plant] = c172sLateralDirectionalPlant(yd2Data);
yd2Controller = c172sYawDamperData();
yd2Actuator = c172sRudderActuatorData();
assertDependencies(yd2Data,yd2Controller,yd2Actuator);
assignModelVariables(yd2Data,yd2Plant,yd2Controller,yd2Actuator);

if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end

if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure executable model

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','30', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Rebuild immutable data before each simulation but preserve checker
% overrides of commands, initial conditions and deterministic noise.
initCode = [ ...
    'yd2Data = c172sLateralDirectionalData();' newline ...
    '[~,yd2Plant] = c172sLateralDirectionalPlant(yd2Data);' newline ...
    'yd2Controller = c172sYawDamperData();' newline ...
    'yd2Actuator = c172sRudderActuatorData();' newline ...
    'if ~strcmp(yd2Data.model.version,yd2Actuator.requiredPlantVersion), error(''Yaw Damper V2 plant dependency mismatch.''); end' newline ...
    'if ~strcmp(yd2Controller.artifactRevision,yd2Actuator.requiredYawDamperRevision), error(''Yaw Damper V2 controller dependency mismatch.''); end' newline ...
    'if ~strcmp(yd2Actuator.artifactRevision,''YD-V2-AUDIT-MATLAB-R1''), error(''Yaw Damper V2 audit revision mismatch.''); end' newline ...
    'A_yd2 = yd2Plant.A; B_yd2 = yd2Plant.B;' newline ...
    'C_yd2 = yd2Plant.C; D_yd2 = yd2Plant.D;' newline ...
    'Kr_yd2 = yd2Controller.rudderGain_s;' newline ...
    'Tw_yd2 = yd2Controller.washoutTimeConstant_s;' newline ...
    'Ts_yd2 = yd2Actuator.sensor.filterTimeConstant_s;' newline ...
    'tauActuator_yd2 = yd2Actuator.dynamics.timeConstant_s;' newline ...
    'delaySampleTime_yd2 = yd2Actuator.sensor.nominalDelay_s;' newline ...
    'autoRudderLower_yd2_rad = yd2Actuator.authority.lowerLimit_rad;' newline ...
    'autoRudderUpper_yd2_rad = yd2Actuator.authority.upperLimit_rad;' newline ...
    'rateLower_yd2_radps = -deg2rad(yd2Actuator.dynamics.rateLimit_degps);' newline ...
    'rateUpper_yd2_radps = deg2rad(yd2Actuator.dynamics.rateLimit_degps);' newline ...
    'totalRudderLower_yd2_rad = yd2Actuator.physicalTravel.lowerLimit_rad;' newline ...
    'totalRudderUpper_yd2_rad = yd2Actuator.physicalTravel.upperLimit_rad;' newline ...
    'if ~exist(''deltaACommand_yd2_rad'',''var''), deltaACommand_yd2_rad = deg2rad(1.0); end' newline ...
    'if ~exist(''deltaRCommand_yd2_rad'',''var''), deltaRCommand_yd2_rad = deg2rad(1.0); end' newline ...
    'if ~exist(''noiseAmplitude_yd2_radps'',''var''), noiseAmplitude_yd2_radps = 0.0; end' newline ...
    'if ~exist(''noiseFrequency_yd2_radps'',''var''), noiseFrequency_yd2_radps = 50.0; end' newline ...
    'if ~exist(''x0_yd2'',''var''), x0_yd2 = zeros(5,1); end' newline ...
    'if ~exist(''rDelay0_yd2_radps'',''var''), rDelay0_yd2_radps = x0_yd2(3); end' newline ...
    'if ~exist(''rSensor0_yd2_radps'',''var''), rSensor0_yd2_radps = 0.0; end' newline ...
    'if ~exist(''xw0_yd2_radps'',''var''), xw0_yd2_radps = 0.0; end' newline ...
    'if ~exist(''deltaRAuto0_yd2_rad'',''var''), deltaRAuto0_yd2_rad = 0.0; end'];
set_param(modelName,'InitFcn',initCode);

%% Pilot-command pulses

add_block('simulink/Sources/Step',[modelName '/Aileron Pulse Start'], ...
    'Time','0','Before','0','After','deltaACommand_yd2_rad', ...
    'SampleTime','0','Position',[35 160 105 190]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse End'], ...
    'Time','1','Before','0','After','-deltaACommand_yd2_rad', ...
    'SampleTime','0','Position',[35 205 105 235]);
add_block('simulink/Math Operations/Sum',[modelName '/Aileron Pilot Command'], ...
    'Inputs','++','Position',[145 175 175 225]);

add_block('simulink/Sources/Step',[modelName '/Rudder Pulse Start'], ...
    'Time','5','Before','0','After','deltaRCommand_yd2_rad', ...
    'SampleTime','0','Position',[35 420 105 450]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse End'], ...
    'Time','6','Before','0','After','-deltaRCommand_yd2_rad', ...
    'SampleTime','0','Position',[35 465 105 495]);
add_block('simulink/Math Operations/Sum',[modelName '/Rudder Pilot Command'], ...
    'Inputs','++','Position',[145 435 175 485]);

%% Plant and protected yaw-damper path

add_block('simulink/Signal Routing/Mux',[modelName '/Control Mux'], ...
    'Inputs','2','Position',[245 270 250 390]);
add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Lateral-Directional Plant'], ...
    'A','A_yd2','B','B_yd2','C','C_yd2','D','D_yd2','X0','x0_yd2', ...
    'Position',[320 290 520 370]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','5','Position',[575 235 580 435]);

% The fixed 0.01-s solver and 0.01-s Unit Delay implement the selected
% nominal pure sensor/processing delay exactly at the model sample grid.
add_block('simulink/Discrete/Unit Delay',[modelName '/Nominal Pure Delay'], ...
    'SampleTime','delaySampleTime_yd2', ...
    'InitialCondition','rDelay0_yd2_radps', ...
    'Position',[650 285 750 325]);
add_block('simulink/Sources/Sine Wave',[modelName '/Deterministic Sensor Noise'], ...
    'Amplitude','noiseAmplitude_yd2_radps','Bias','0', ...
    'Frequency','noiseFrequency_yd2_radps','Phase','0','SampleTime','0', ...
    'Position',[650 355 750 395]);
add_block('simulink/Math Operations/Sum',[modelName '/Sensor Input Sum'], ...
    'Inputs','++','Position',[795 305 825 365]);
add_block('simulink/Continuous/State-Space',[modelName '/Yaw-Rate Sensor Filter'], ...
    'A','-1/Ts_yd2','B','1/Ts_yd2','C','1','D','0', ...
    'X0','rSensor0_yd2_radps','Position',[865 310 990 360]);

% xwDot = (rSensor-xw)/Tw and output = rSensor-xw.
add_block('simulink/Continuous/State-Space',[modelName '/Yaw-Rate Washout'], ...
    'A','-1/Tw_yd2','B','1/Tw_yd2','C','-1','D','1', ...
    'X0','xw0_yd2_radps','Position',[1030 310 1155 360]);
add_block('simulink/Math Operations/Gain',[modelName '/Automatic Rudder Gain'], ...
    'Gain','-Kr_yd2','Position',[1195 315 1280 355]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Automatic Rudder Position Limit'], ...
    'LowerLimit','autoRudderLower_yd2_rad', ...
    'UpperLimit','autoRudderUpper_yd2_rad', ...
    'Position',[1320 305 1455 365]);

add_block('simulink/Math Operations/Sum',[modelName '/Servo Position Error'], ...
    'Inputs','+-','Position',[1495 310 1525 360]);
add_block('simulink/Math Operations/Gain',[modelName '/Servo Inverse Time Constant'], ...
    'Gain','1/tauActuator_yd2','Position',[1565 315 1670 355]);
add_block('simulink/Discontinuities/Saturation',[modelName '/Servo Rate Limit'], ...
    'LowerLimit','rateLower_yd2_radps','UpperLimit','rateUpper_yd2_radps', ...
    'Position',[1710 305 1815 365]);
add_block('simulink/Continuous/Integrator',[modelName '/Automatic Rudder Actuator'], ...
    'InitialCondition','deltaRAuto0_yd2_rad','Position',[1855 310 1890 360]);

add_block('simulink/Math Operations/Sum',[modelName '/Raw Total Rudder'], ...
    'Inputs','++','Position',[1940 405 1970 455]);
add_block('simulink/Discontinuities/Saturation',[modelName '/Physical Rudder Hard Stop'], ...
    'LowerLimit','totalRudderLower_yd2_rad', ...
    'UpperLimit','totalRudderUpper_yd2_rad', ...
    'Position',[2010 395 2145 465]);

%% Executable connections

add_line(modelName,'Aileron Pulse Start/1','Aileron Pilot Command/1','autorouting','on');
add_line(modelName,'Aileron Pulse End/1','Aileron Pilot Command/2','autorouting','on');
add_line(modelName,'Rudder Pulse Start/1','Rudder Pilot Command/1','autorouting','on');
add_line(modelName,'Rudder Pulse End/1','Rudder Pilot Command/2','autorouting','on');

connectNamed(modelName,'Aileron Pilot Command/1','Control Mux/1', ...
    'deltaA pilot, right-wing-down positive');
connectNamed(modelName,'Physical Rudder Hard Stop/1','Control Mux/2', ...
    'deltaR total protected, nose-right positive');
connectNamed(modelName,'Control Mux/1','C172S Lateral-Directional Plant/1', ...
    'u = [deltaA pilot, deltaR total protected]');
connectNamed(modelName,'C172S Lateral-Directional Plant/1','State Demux/1', ...
    'x = [beta p r phi psi]');
connectNamed(modelName,'State Demux/3','Nominal Pure Delay/1','true yaw rate');
connectNamed(modelName,'Nominal Pure Delay/1','Sensor Input Sum/1','delayed yaw rate');
connectNamed(modelName,'Deterministic Sensor Noise/1','Sensor Input Sum/2', ...
    'sensor noise');
connectNamed(modelName,'Sensor Input Sum/1','Yaw-Rate Sensor Filter/1', ...
    'noisy delayed yaw rate');
connectNamed(modelName,'Yaw-Rate Sensor Filter/1','Yaw-Rate Washout/1', ...
    'filtered yaw rate');
connectNamed(modelName,'Yaw-Rate Washout/1','Automatic Rudder Gain/1', ...
    'washout yaw rate');
connectNamed(modelName,'Automatic Rudder Gain/1', ...
    'Automatic Rudder Position Limit/1','raw automatic rudder');
connectNamed(modelName,'Automatic Rudder Position Limit/1', ...
    'Servo Position Error/1','position-limited rudder command');
connectNamed(modelName,'Automatic Rudder Actuator/1', ...
    'Servo Position Error/2','actual automatic rudder');
connectNamed(modelName,'Servo Position Error/1','Servo Inverse Time Constant/1', ...
    'servo position error');
connectNamed(modelName,'Servo Inverse Time Constant/1','Servo Rate Limit/1', ...
    'raw servo rate');
connectNamed(modelName,'Servo Rate Limit/1','Automatic Rudder Actuator/1', ...
    'limited servo rate');
connectNamed(modelName,'Rudder Pilot Command/1','Raw Total Rudder/1', ...
    'pilot rudder');
connectNamed(modelName,'Automatic Rudder Actuator/1','Raw Total Rudder/2', ...
    'automatic rudder');
connectNamed(modelName,'Raw Total Rudder/1','Physical Rudder Hard Stop/1', ...
    'raw pilot plus automatic rudder');

%% Verification signals (fixed order used by independent checker)

signalSources = { ...
    'State Demux/1','yd2_beta','Beta'; ...
    'State Demux/2','yd2_p','p'; ...
    'State Demux/3','yd2_r','r'; ...
    'State Demux/4','yd2_phi','Phi'; ...
    'State Demux/5','yd2_psi','Psi'; ...
    'Aileron Pilot Command/1','yd2_deltaA_pilot','Aileron Pilot'; ...
    'Rudder Pilot Command/1','yd2_deltaR_pilot','Rudder Pilot'; ...
    'Nominal Pure Delay/1','yd2_r_delayed','Delayed r'; ...
    'Deterministic Sensor Noise/1','yd2_sensor_noise','Sensor Noise'; ...
    'Sensor Input Sum/1','yd2_sensor_input','Sensor Input'; ...
    'Yaw-Rate Sensor Filter/1','yd2_r_sensor','Filtered r'; ...
    'Yaw-Rate Washout/1','yd2_r_washout','Washout r'; ...
    'Automatic Rudder Gain/1','yd2_deltaR_raw','Raw Auto Rudder'; ...
    'Automatic Rudder Position Limit/1','yd2_deltaR_position','Position Command'; ...
    'Automatic Rudder Actuator/1','yd2_deltaR_actual','Actual Auto Rudder'; ...
    'Servo Inverse Time Constant/1','yd2_rate_raw','Raw Servo Rate'; ...
    'Servo Rate Limit/1','yd2_rate_limited','Limited Servo Rate'; ...
    'Raw Total Rudder/1','yd2_deltaR_total_raw','Raw Total Rudder'; ...
    'Physical Rudder Hard Stop/1','yd2_deltaR_total','Protected Total Rudder'};

for k = 1:size(signalSources,1)
    addGlobalGoto(modelName,[signalSources{k,3} ' Tag'], ...
        signalSources{k,2},[2190 120 + 27*k 2310 140 + 27*k]);
end

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[2370 300 2525 370]);
clearDefaultSubsystem(verificationPath);
for k = 1:size(signalSources,1)
    yPosition = 20 + 31*(k - 1);
    addFrom(verificationPath,signalSources{k,3},signalSources{k,2}, ...
        [25 yPosition 155 yPosition + 18]);
end
add_block('simulink/Signal Routing/Mux',[verificationPath '/Signal Mux'], ...
    'Inputs',num2str(size(signalSources,1)), ...
    'Position',[220 10 225 610]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[285 295 315 315]);
for k = 1:size(signalSources,1)
    add_line(verificationPath,[signalSources{k,3} '/1'], ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Protected Closed-Loop Signals'], ...
    'Port','1','Position',[2580 320 2610 340]);
add_line(modelName,'Verification Signals/1','Protected Closed-Loop Signals/1', ...
    'autorouting','on');

% Feed the global tags after all corresponding From blocks exist.
for k = 1:size(signalSources,1)
    branchTo(modelName,signalSources{k,1},[signalSources{k,3} ' Tag/1']);
end

%% Traceability, compile and save

try
    note = Simulink.Annotation(modelName,[ ...
        'Yaw Damper V2 - protected implementation of YD-V1-MATLAB-R2' newline ...
        '10-ms pure delay -> 20-ms sensor filter -> 1-s washout -> -0.280-s gain' newline ...
        '+/-5-deg automatic authority; tau = 0.050 s; +/-20-deg/s servo rate' newline ...
        '+/-16-deg total-rudder hard stop; positive yaw/rudder are nose-right' newline ...
        'Actuator and sensor values are explicit project assumptions, not identified C172S hardware data']);
    note.Position = [35 25 1160 125];
catch
    % Annotation appearance is not part of executable equivalence.
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runYawDamperActuatorSimulinkCheck to validate Yaw Damper V2.\n');

end

function assertDependencies(data,controller,actuator)
assert(strcmp(data.model.version,actuator.requiredPlantVersion), ...
    'Yaw Damper V2 plant dependency mismatch.');
assert(strcmp(controller.artifactRevision, ...
    actuator.requiredYawDamperRevision), ...
    'Yaw Damper V2 controller dependency mismatch.');
assert(strcmp(actuator.artifactRevision,'YD-V2-AUDIT-MATLAB-R1'), ...
    'Yaw Damper V2 requires audit artifact YD-V2-AUDIT-MATLAB-R1.');
assert(controller.feedbackSign == -1.0, ...
    'Yaw Damper V2 requires negative yaw-rate feedback.');
assert(abs(actuator.sensor.nominalDelay_s - 0.010) < 1.0e-12, ...
    'The V2 baseline requires the audited 10-ms nominal delay.');
end

function assignModelVariables(data,plant,controller,actuator)
assignin('base','yd2Data',data);
assignin('base','yd2Plant',plant);
assignin('base','yd2Controller',controller);
assignin('base','yd2Actuator',actuator);
assignin('base','A_yd2',plant.A);
assignin('base','B_yd2',plant.B);
assignin('base','C_yd2',plant.C);
assignin('base','D_yd2',plant.D);
assignin('base','Kr_yd2',controller.rudderGain_s);
assignin('base','Tw_yd2',controller.washoutTimeConstant_s);
assignin('base','Ts_yd2',actuator.sensor.filterTimeConstant_s);
assignin('base','tauActuator_yd2',actuator.dynamics.timeConstant_s);
assignin('base','delaySampleTime_yd2',actuator.sensor.nominalDelay_s);
assignin('base','autoRudderLower_yd2_rad',actuator.authority.lowerLimit_rad);
assignin('base','autoRudderUpper_yd2_rad',actuator.authority.upperLimit_rad);
assignin('base','rateLower_yd2_radps', ...
    -deg2rad(actuator.dynamics.rateLimit_degps));
assignin('base','rateUpper_yd2_radps', ...
    deg2rad(actuator.dynamics.rateLimit_degps));
assignin('base','totalRudderLower_yd2_rad', ...
    actuator.physicalTravel.lowerLimit_rad);
assignin('base','totalRudderUpper_yd2_rad', ...
    actuator.physicalTravel.upperLimit_rad);
assignin('base','deltaACommand_yd2_rad',0.0);
assignin('base','deltaRCommand_yd2_rad',0.0);
assignin('base','noiseAmplitude_yd2_radps',0.0);
assignin('base','noiseFrequency_yd2_radps',50.0);
assignin('base','x0_yd2',zeros(5,1));
assignin('base','rDelay0_yd2_radps',0.0);
assignin('base','rSensor0_yd2_radps',0.0);
assignin('base','xw0_yd2_radps',0.0);
assignin('base','deltaRAuto0_yd2_rad',0.0);
end

function clearDefaultSubsystem(path)
lines = find_system(path,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(path,'SearchDepth',1,'Type','Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end
