function modelName = buildC172sNonlinear6DofSimulink(forceRebuild)
%BUILDC172SNONLINEAR6DOFSIMULINK Generate executable nonlinear V0.1 plant.

arguments
    forceRebuild (1,1) logical = false
end
modelName='C172S_Nonlinear6Dof_V1'; modelFile=fullfile(pwd,[modelName '.slx']);
model=c172sIntegratedNonlinearDynamicsData(); trim=solveC172sNonlinearTrim([],model.trimModel);
assignin('base','n6Model',model); assignin('base','n6InitialState',trim.state);
assignin('base','n6InputSignal',[0 trim.controls.' zeros(1,6);2 trim.controls.' zeros(1,6)]);
if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelFile)&&~forceRebuild
    load_system(modelFile); open_system(modelName); return
end
if isfile(modelFile), delete(modelFile); end
load_system('simulink'); new_system(modelName); open_system(modelName);
set_param(modelName,'SolverType','Fixed-step','Solver','ode4','FixedStep','0.01', ...
    'StartTime','0','StopTime','2','SaveTime','on','TimeSaveName','tout', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Array');
set_param(modelName,'InitFcn',[ ...
    'n6Model=c172sIntegratedNonlinearDynamicsData();' newline ...
    'if ~exist(''n6InitialState'',''var''), n6InitialState=solveC172sNonlinearTrim([],n6Model.trimModel).state; end' newline ...
    'if ~exist(''n6InputSignal'',''var''), error(''n6InputSignal is required.''); end']);

add_block('simulink/Sources/From Workspace',[modelName '/Controls Wind and Gust'], ...
    'VariableName','n6InputSignal','Interpolate','off', ...
    'OutputAfterFinalValue','Holding final value','SampleTime','0', ...
    'Position',[55 245 230 285]);
add_block('simulink/Continuous/Integrator',[modelName '/13 State Integrator'], ...
    'InitialCondition','n6InitialState','Position',[610 150 650 190]);
plantPath=[modelName '/Independent Nonlinear 6DOF Plant'];
add_block('simulink/User-Defined Functions/MATLAB Function',plantPath, ...
    'Position',[310 105 535 330]);
root=sfroot; chart=root.find('-isa','Stateflow.EMChart','Path',plantPath);
assert(~isempty(chart),'Generated MATLAB Function chart was not found.');
chart.Script=executablePlantCode(model);
setChartDataSize(chart,'x','[13 1]');
setChartDataSize(chart,'input','[10 1]');
setChartDataSize(chart,'xdot','[13 1]');
setChartDataSize(chart,'signals','[10 1]');
set_param(modelName,'SimulationCommand','update');
add_block('simulink/Signal Routing/Mux',[modelName '/Verification Mux'], ...
    'Inputs','2','Position',[735 145 740 255]);
add_block('simulink/Sinks/Out1',[modelName '/Verification Signals'], ...
    'Port','1','Position',[825 190 855 210]);
add_line(modelName,'13 State Integrator/1','Independent Nonlinear 6DOF Plant/1','autorouting','on');
add_line(modelName,'Controls Wind and Gust/1','Independent Nonlinear 6DOF Plant/2','autorouting','on');
add_line(modelName,'Independent Nonlinear 6DOF Plant/1','13 State Integrator/1','autorouting','on');
add_line(modelName,'13 State Integrator/1','Verification Mux/1','autorouting','on');
add_line(modelName,'Independent Nonlinear 6DOF Plant/2','Verification Mux/2','autorouting','on');
add_line(modelName,'Verification Mux/1','Verification Signals/1','autorouting','on');
try
    note=Simulink.Annotation(modelName,sprintf([ ...
        'C172S NONLINEAR 6-DOF RESEARCH PLANT V0.1\n' ...
        '13 states + 10 diagnostics = 23 verification signals\n' ...
        'Independent executable equations; ode4, 10-ms fixed step\n' ...
        'Attached-flow near-trim coefficients and one-point thrust only']));
    note.Position=[45 20 875 80];
catch
end
set_param(modelName,'SimulationCommand','update'); save_system(modelName,modelFile);
close_system(modelName,0); load_system(modelFile); open_system(modelName);
fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runNonlinear6DofSimulinkCheck to validate Nonlinear 6-DOF V1.\n');
end

function setChartDataSize(chart,dataName,sizeText)
data=chart.find('-isa','Stateflow.Data','Name',dataName);
assert(numel(data)==1,'Unable to identify chart data "%s".',dataName);
data.Props.Array.Size=sizeText;
end

function code=executablePlantCode(model)
m=model.trimModel.kernel.mass_kg; g=model.trimModel.kernel.gravity_mps2;
I=model.trimModel.kernel.inertia.matrix_kgm2; a=model.trimModel.aerodynamics;
c=a.airDataModel.constants; S=a.geometry.S_m2; b=a.geometry.b_m; cb=a.geometry.cBar_m;
lon=a.longitudinal.aero; lat=a.lateral.aero;
fmt=@(x)sprintf('%.17g',x);
lines={ ...
'function [xdot,signals] = plant(x,input)';'%#codegen'; ...
'xdot=zeros(13,1); signals=zeros(10,1);'; ...
'control=input(1:4); wind=input(5:7)+input(8:10);'; ...
'[f0,~,~,~,~,~,~,~,airVelocity,windBody]=evaluate(x,control,wind,0.0);'; ...
'[f1,~,~,~,~,~,~,~,~,~]=evaluate(x,control,wind,1.0);'; ...
'omega=x(4:6); a0=f0(1:3)+cross(omega,windBody); a1=f1(1:3)+cross(omega,windBody);'; ...
'r0=alphaRate(airVelocity,a0); r1=alphaRate(airVelocity,a1); alphaDot=r0/(1-(r1-r0));'; ...
'[xdot,F,M,TAS,alpha,beta,~,~,~,~]=evaluate(x,control,wind,alphaDot);'; ...
'signals=[alphaDot;F;M;TAS;alpha;beta];';'end'; ...
'function rate=alphaRate(v,a)';'rate=(v(1)*a(3)-v(3)*a(1))/(v(1)^2+v(3)^2);';'end'; ...
'function [xdot,F,M,TAS,alpha,beta,rho,C,airVelocity,windBody]=evaluate(x,u,wind,alphaDot)'; ...
sprintf('mass=%s; gravity=%s;',fmt(m),fmt(g)); ...
sprintf('I=[%s %s %s;%s %s %s;%s %s %s];',fmt(I(1,1)),fmt(I(1,2)),fmt(I(1,3)),fmt(I(2,1)),fmt(I(2,2)),fmt(I(2,3)),fmt(I(3,1)),fmt(I(3,2)),fmt(I(3,3))); ...
'q=x(10:13); q=q/sqrt(sum(q.^2)); q0=q(1);q1=q(2);q2=q(3);q3=q(4);'; ...
'C=[q0^2+q1^2-q2^2-q3^2,2*(q1*q2-q0*q3),2*(q1*q3+q0*q2);2*(q1*q2+q0*q3),q0^2-q1^2+q2^2-q3^2,2*(q2*q3-q0*q1);2*(q1*q3-q0*q2),2*(q2*q3+q0*q1),q0^2-q1^2-q2^2+q3^2];'; ...
'windBody=C''*wind; airVelocity=x(1:3)-windBody; TAS=sqrt(sum(airVelocity.^2));'; ...
'alpha=atan2(airVelocity(3),airVelocity(1)); beta=asin(min(1,max(-1,airVelocity(2)/TAS)));'; ...
sprintf('temperature=%s-%s*(-x(9)); pressure=%s*(temperature/%s)^(%s/(%s*%s)); rho=pressure/(%s*temperature);',fmt(c.T0_K),fmt(c.lapse_Kpm),fmt(c.p0_Pa),fmt(c.T0_K),fmt(c.g_mps2),fmt(c.Rair_JpkgK),fmt(c.lapse_Kpm),fmt(c.Rair_JpkgK)); ...
sprintf('qbarS=0.5*rho*TAS^2*%s; pHat=x(4)*%s/(2*TAS); qHat=x(5)*%s/(2*TAS); rHat=x(6)*%s/(2*TAS); adHat=alphaDot*%s/(2*TAS);',fmt(S),fmt(b),fmt(cb),fmt(b),fmt(cb)); ...
sprintf('CL=%s+%s*alpha+%s*qHat+%s*adHat+%s*u(1);',fmt(a.trim.CL),fmt(lon.CL_alpha),fmt(lon.CL_q),fmt(lon.CL_alphaDot),fmt(lon.CL_deltaE)); ...
sprintf('CD=%s+%s*alpha;',fmt(a.trim.CD),fmt(lon.CD_alpha)); ...
sprintf('CY=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);',fmt(lat.CY_beta),fmt(lat.CY_p),fmt(lat.CY_r),fmt(lat.CY_deltaA),fmt(lat.CY_deltaR)); ...
sprintf('Cl=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);',fmt(lat.Cl_beta),fmt(lat.Cl_p),fmt(lat.Cl_r),fmt(lat.Cl_deltaA),fmt(lat.Cl_deltaR)); ...
sprintf('Cm=%s*alpha+%s*qHat+%s*adHat+%s*u(1);',fmt(lon.Cm_alpha),fmt(lon.Cm_q),fmt(lon.Cm_alphaDot),fmt(lon.Cm_deltaE)); ...
sprintf('Cn=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);',fmt(lat.Cn_beta),fmt(lat.Cn_p),fmt(lat.Cn_r),fmt(lat.Cn_deltaA),fmt(lat.Cn_deltaR)); ...
sprintf('L=qbarS*CL;D=qbarS*CD;Y=qbarS*CY; thrust=u(4)*%s;',fmt(model.trimModel.propulsion.maximumThrustAtTrim_N)); ...
'Fa=[-D*cos(alpha)+L*sin(alpha);Y;-D*sin(alpha)-L*cos(alpha)]; F=Fa+thrust*[cos(alpha);0;sin(alpha)];'; ...
sprintf('M=[qbarS*%s*Cl;qbarS*%s*Cm;qbarS*%s*Cn];',fmt(b),fmt(cb),fmt(b)); ...
'omega=x(4:6); gravityBody=C''*[0;0;gravity]; vdot=F/mass+gravityBody-cross(omega,x(1:3));'; ...
'H=I*omega; odot=I\(M-cross(omega,H)); pdot=C*x(1:3);'; ...
'qv=q(2:4); Q=[-qv'';q0*eye(3)+[0 -qv(3) qv(2);qv(3) 0 -qv(1);-qv(2) qv(1) 0]]; qdot=0.5*Q*omega;'; ...
'xdot=[vdot;odot;pdot;qdot];';'end'};
code=strjoin(lines,newline);
end
