function modelName = buildC172sHeadingHoldSimulink(forceRebuild)
%BUILDC172SHEADINGHOLDSIMULINK Build protected Heading Hold V1.
%
%   MODELNAME = BUILDC172SHEADINGHOLDSIMULINK() creates or opens
%   C172S_HeadingHold_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SHEADINGHOLDSIMULINK(true) overwrites only
%   the generated SLX file. Frozen Plant V0.1, Yaw Damper V2,
%   Roll-Attitude Hold V1 and every source-audit artifact are unaltered.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_HeadingHold_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize frozen dependencies and selected assumptions

hh1Data = c172sLateralDirectionalData();
[~,hh1Plant] = c172sLateralDirectionalPlant(hh1Data);
hh1YawController = c172sYawDamperData();
hh1RudderActuator = c172sRudderActuatorData();
hh1RollController = c172sRollAttitudeControllerData();
hh1AileronActuator = c172sAileronActuatorData();
hh1HeadingSensor = c172sHeadingSensorData();
hh1HeadingController = c172sHeadingHoldControllerData();
assertDependencies(hh1Data,hh1YawController,hh1RudderActuator, ...
    hh1RollController,hh1AileronActuator,hh1HeadingSensor, ...
    hh1HeadingController);
assignModelVariables(hh1Data,hh1Plant,hh1YawController, ...
    hh1RudderActuator,hh1RollController,hh1AileronActuator, ...
    hh1HeadingSensor,hh1HeadingController);

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure executable model

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','100', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Immutable definitions are rebuilt before each run. SimulationInput/base-
% workspace overrides of commands, initial conditions, noise and the
% anti-windup switch are deliberately preserved.
initCode = [ ...
    'hh1Data = c172sLateralDirectionalData();' newline ...
    '[~,hh1Plant] = c172sLateralDirectionalPlant(hh1Data);' newline ...
    'hh1YawController = c172sYawDamperData();' newline ...
    'hh1RudderActuator = c172sRudderActuatorData();' newline ...
    'hh1RollController = c172sRollAttitudeControllerData();' newline ...
    'hh1AileronActuator = c172sAileronActuatorData();' newline ...
    'hh1HeadingSensor = c172sHeadingSensorData();' newline ...
    'hh1HeadingController = c172sHeadingHoldControllerData();' newline ...
    'if ~strcmp(hh1Data.model.version,hh1HeadingController.requiredPlantVersion), error(''HH V1 plant dependency mismatch.''); end' newline ...
    'if ~strcmp(hh1YawController.artifactRevision,hh1HeadingController.requiredYawDamperRevision), error(''HH V1 yaw-controller dependency mismatch.''); end' newline ...
    'if ~strcmp(hh1RudderActuator.artifactRevision,hh1HeadingController.requiredRudderAuditRevision), error(''HH V1 rudder-audit dependency mismatch.''); end' newline ...
    'if ~strcmp(hh1AileronActuator.artifactRevision,hh1HeadingController.requiredAileronAuditRevision), error(''HH V1 aileron-audit dependency mismatch.''); end' newline ...
    'if ~strcmp(hh1RollController.artifactRevision,hh1HeadingController.requiredRollControllerRevision), error(''HH V1 roll-controller dependency mismatch.''); end' newline ...
    'if ~strcmp(hh1HeadingSensor.artifactRevision,hh1HeadingController.requiredHeadingSensorRevision), error(''HH V1 heading-sensor dependency mismatch.''); end' newline ...
    'A_hh1 = hh1Plant.A; B_hh1 = hh1Plant.B;' newline ...
    'C_hh1 = hh1Plant.C; D_hh1 = hh1Plant.D;' newline ...
    'Kphi_hh1 = hh1RollController.bankProportionalGain;' newline ...
    'Ki_hh1 = hh1RollController.bankIntegralGain_per_s;' newline ...
    'Kp_hh1 = hh1RollController.rollRateGain_s;' newline ...
    'Tcmd_hh1 = hh1RollController.commandFilterTimeConstant_s;' newline ...
    'Kr_hh1 = hh1YawController.rudderGain_s;' newline ...
    'Tw_hh1 = hh1YawController.washoutTimeConstant_s;' newline ...
    'TsRudder_hh1 = hh1RudderActuator.sensor.filterTimeConstant_s;' newline ...
    'tauRudder_hh1 = hh1RudderActuator.dynamics.timeConstant_s;' newline ...
    'TsRoll_hh1 = hh1AileronActuator.sensor.filterTimeConstant_s;' newline ...
    'tauAileron_hh1 = hh1AileronActuator.dynamics.timeConstant_s;' newline ...
    'Tt_hh1 = hh1AileronActuator.antiWindup.trackingTimeConstant_s;' newline ...
    'delaySampleTime_hh1 = hh1AileronActuator.sensor.nominalDelay_s;' newline ...
    'Kpsi_hh1 = hh1HeadingController.headingErrorGain;' newline ...
    'TsHeading_hh1 = hh1HeadingSensor.filterTimeConstant_s;' newline ...
    'headingDelaySampleTime_hh1 = hh1HeadingSensor.nominalDelay_s/5;' newline ...
    'bankCommandLower_hh1_rad = -deg2rad(hh1HeadingController.bankCommandAuthority_deg);' newline ...
    'bankCommandUpper_hh1_rad = deg2rad(hh1HeadingController.bankCommandAuthority_deg);' newline ...
    'autoAileronLower_hh1_rad = hh1AileronActuator.authority.lowerLimit_rad;' newline ...
    'autoAileronUpper_hh1_rad = hh1AileronActuator.authority.upperLimit_rad;' newline ...
    'aileronRateLower_hh1_radps = -deg2rad(hh1AileronActuator.dynamics.rateLimit_degps);' newline ...
    'aileronRateUpper_hh1_radps = deg2rad(hh1AileronActuator.dynamics.rateLimit_degps);' newline ...
    'totalAileronLower_hh1_rad = hh1AileronActuator.physicalTravel.lowerLimit_rad;' newline ...
    'totalAileronUpper_hh1_rad = hh1AileronActuator.physicalTravel.upperLimit_rad;' newline ...
    'autoRudderLower_hh1_rad = hh1RudderActuator.authority.lowerLimit_rad;' newline ...
    'autoRudderUpper_hh1_rad = hh1RudderActuator.authority.upperLimit_rad;' newline ...
    'rudderRateLower_hh1_radps = -deg2rad(hh1RudderActuator.dynamics.rateLimit_degps);' newline ...
    'rudderRateUpper_hh1_radps = deg2rad(hh1RudderActuator.dynamics.rateLimit_degps);' newline ...
    'totalRudderLower_hh1_rad = hh1RudderActuator.physicalTravel.lowerLimit_rad;' newline ...
    'totalRudderUpper_hh1_rad = hh1RudderActuator.physicalTravel.upperLimit_rad;' newline ...
    'if ~exist(''headingCommand_hh1_rad'',''var''), headingCommand_hh1_rad = deg2rad(30); end' newline ...
    'if ~exist(''headingBias_hh1_rad'',''var''), headingBias_hh1_rad = 0; end' newline ...
    'if ~exist(''headingNoiseAmplitude_hh1_rad'',''var''), headingNoiseAmplitude_hh1_rad = 0; end' newline ...
    'if ~exist(''headingNoiseFrequency_hh1_radps'',''var''), headingNoiseFrequency_hh1_radps = 0.8; end' newline ...
    'if ~exist(''pilotAileronBias_hh1_rad'',''var''), pilotAileronBias_hh1_rad = 0; end' newline ...
    'if ~exist(''pilotAileronPulse_hh1_rad'',''var''), pilotAileronPulse_hh1_rad = 0; end' newline ...
    'if ~exist(''pilotRudderBias_hh1_rad'',''var''), pilotRudderBias_hh1_rad = 0; end' newline ...
    'if ~exist(''pilotRudderPulse_hh1_rad'',''var''), pilotRudderPulse_hh1_rad = 0; end' newline ...
    'if ~exist(''aileronPulseStart_hh1_s'',''var''), aileronPulseStart_hh1_s = 5; end' newline ...
    'if ~exist(''aileronPulseEnd_hh1_s'',''var''), aileronPulseEnd_hh1_s = 6; end' newline ...
    'if ~exist(''rudderPulseStart_hh1_s'',''var''), rudderPulseStart_hh1_s = 5; end' newline ...
    'if ~exist(''rudderPulseEnd_hh1_s'',''var''), rudderPulseEnd_hh1_s = 6; end' newline ...
    'if ~exist(''pNoiseAmplitude_hh1_radps'',''var''), pNoiseAmplitude_hh1_radps = 0; end' newline ...
    'if ~exist(''pNoiseFrequency_hh1_radps'',''var''), pNoiseFrequency_hh1_radps = 50; end' newline ...
    'if ~exist(''phiNoiseAmplitude_hh1_rad'',''var''), phiNoiseAmplitude_hh1_rad = 0; end' newline ...
    'if ~exist(''phiNoiseFrequency_hh1_radps'',''var''), phiNoiseFrequency_hh1_radps = 5; end' newline ...
    'if ~exist(''yawNoiseAmplitude_hh1_radps'',''var''), yawNoiseAmplitude_hh1_radps = 0; end' newline ...
    'if ~exist(''yawNoiseFrequency_hh1_radps'',''var''), yawNoiseFrequency_hh1_radps = 50; end' newline ...
    'if ~exist(''antiWindupEnable_hh1'',''var''), antiWindupEnable_hh1 = 1; end' newline ...
    'if ~exist(''x0_hh1'',''var''), x0_hh1 = zeros(5,1); end' newline ...
    'if ~exist(''rDelay0_hh1_radps'',''var''), rDelay0_hh1_radps = x0_hh1(3); end' newline ...
    'if ~exist(''pDelay0_hh1_radps'',''var''), pDelay0_hh1_radps = x0_hh1(2); end' newline ...
    'if ~exist(''phiDelay0_hh1_rad'',''var''), phiDelay0_hh1_rad = x0_hh1(4); end' newline ...
    'if ~exist(''rSensor0_hh1_radps'',''var''), rSensor0_hh1_radps = 0; end' newline ...
    'if ~exist(''xw0_hh1_radps'',''var''), xw0_hh1_radps = 0; end' newline ...
    'if ~exist(''deltaRAuto0_hh1_rad'',''var''), deltaRAuto0_hh1_rad = 0; end' newline ...
    'if ~exist(''pSensor0_hh1_radps'',''var''), pSensor0_hh1_radps = 0; end' newline ...
    'if ~exist(''phiSensor0_hh1_rad'',''var''), phiSensor0_hh1_rad = 0; end' newline ...
    'if ~exist(''psiDelay0_hh1_rad'',''var''), psiDelay0_hh1_rad = x0_hh1(5); end' newline ...
    'if ~exist(''psiSensor0_hh1_rad'',''var''), psiSensor0_hh1_rad = x0_hh1(5)+headingBias_hh1_rad; end' newline ...
    'if ~exist(''xi0_hh1_rad_s'',''var''), xi0_hh1_rad_s = 0; end' newline ...
    'if ~exist(''deltaAAuto0_hh1_rad'',''var''), deltaAAuto0_hh1_rad = 0; end' newline ...
    'if ~exist(''filteredCommand0_hh1_rad'',''var''), filteredCommand0_hh1_rad = 0; end'];
set_param(modelName,'InitFcn',initCode);

%% Heading command and pilot inputs

add_block('simulink/Sources/Step',[modelName '/Heading Command'], ...
    'Time','0','Before','0','After','headingCommand_hh1_rad', ...
    'SampleTime','0','Position',[35 115 115 145]);
add_block('simulink/Continuous/State-Space',[modelName '/Command Filter'], ...
    'A','-1/Tcmd_hh1','B','1/Tcmd_hh1','C','1','D','0', ...
    'X0','filteredCommand0_hh1_rad', ...
    'Position',[470 105 585 155]);

add_block('simulink/Sources/Constant',[modelName '/Aileron Bias'], ...
    'Value','pilotAileronBias_hh1_rad','Position',[35 260 105 290]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse Start'], ...
    'Time','aileronPulseStart_hh1_s','Before','0', ...
    'After','pilotAileronPulse_hh1_rad','SampleTime','0', ...
    'Position',[35 305 105 335]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse End'], ...
    'Time','aileronPulseEnd_hh1_s','Before','0', ...
    'After','-pilotAileronPulse_hh1_rad','SampleTime','0', ...
    'Position',[35 350 105 380]);
add_block('simulink/Math Operations/Sum',[modelName '/Pilot Aileron'], ...
    'Inputs','+++','Position',[155 285 185 355]);

add_block('simulink/Sources/Constant',[modelName '/Rudder Bias'], ...
    'Value','pilotRudderBias_hh1_rad','Position',[35 535 105 565]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse Start'], ...
    'Time','rudderPulseStart_hh1_s','Before','0', ...
    'After','pilotRudderPulse_hh1_rad','SampleTime','0', ...
    'Position',[35 580 105 610]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse End'], ...
    'Time','rudderPulseEnd_hh1_s','Before','0', ...
    'After','-pilotRudderPulse_hh1_rad','SampleTime','0', ...
    'Position',[35 625 105 655]);
add_block('simulink/Math Operations/Sum',[modelName '/Pilot Rudder'], ...
    'Inputs','+++','Position',[155 560 185 630]);

%% Plant and protected controller subsystems

add_block('simulink/Math Operations/Sum',[modelName '/Raw Total Aileron'], ...
    'Inputs','++','Position',[1020 285 1050 335]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Physical Aileron Hard Stop'], ...
    'LowerLimit','totalAileronLower_hh1_rad', ...
    'UpperLimit','totalAileronUpper_hh1_rad', ...
    'Position',[1095 275 1235 345]);
add_block('simulink/Math Operations/Sum',[modelName '/Raw Total Rudder'], ...
    'Inputs','++','Position',[1020 555 1050 605]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Physical Rudder Hard Stop'], ...
    'LowerLimit','totalRudderLower_hh1_rad', ...
    'UpperLimit','totalRudderUpper_hh1_rad', ...
    'Position',[1095 545 1235 615]);
add_block('simulink/Signal Routing/Mux',[modelName '/Control Mux'], ...
    'Inputs','2','Position',[1280 365 1285 515]);
add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Lateral-Directional Plant'], ...
    'A','A_hh1','B','B_hh1','C','C_hh1','D','D_hh1', ...
    'X0','x0_hh1','Position',[1340 400 1545 480]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','5','Position',[1595 330 1600 550]);

headingPath = [modelName '/Heading Sensor and Outer Loop'];
add_block('simulink/Ports & Subsystems/Subsystem',headingPath, ...
    'Position',[150 70 425 190]);
buildHeadingSubsystem(headingPath);

rollPath = [modelName '/Frozen Protected Roll-Attitude Hold V1'];
add_block('simulink/Ports & Subsystems/Subsystem',rollPath, ...
    'Position',[630 135 945 380]);
buildRollSubsystem(rollPath);

yawPath = [modelName '/Frozen Protected Yaw Damper V2'];
add_block('simulink/Ports & Subsystems/Subsystem',yawPath, ...
    'Position',[630 500 945 650]);
buildYawSubsystem(yawPath);

%% Executable top-level connections

connectNamed(modelName,'Heading Command/1', ...
    'Heading Sensor and Outer Loop/1','selected heading');
connectNamed(modelName,'Heading Sensor and Outer Loop/1', ...
    'Command Filter/1','limited bank command');
connectNamed(modelName,'Command Filter/1', ...
    'Frozen Protected Roll-Attitude Hold V1/1','filtered bank command');

add_line(modelName,'Aileron Bias/1','Pilot Aileron/1','autorouting','on');
add_line(modelName,'Aileron Pulse Start/1','Pilot Aileron/2','autorouting','on');
add_line(modelName,'Aileron Pulse End/1','Pilot Aileron/3','autorouting','on');
add_line(modelName,'Rudder Bias/1','Pilot Rudder/1','autorouting','on');
add_line(modelName,'Rudder Pulse Start/1','Pilot Rudder/2','autorouting','on');
add_line(modelName,'Rudder Pulse End/1','Pilot Rudder/3','autorouting','on');

connectNamed(modelName,'Pilot Aileron/1','Raw Total Aileron/1', ...
    'pilot aileron');
connectNamed(modelName,'Frozen Protected Roll-Attitude Hold V1/1', ...
    'Raw Total Aileron/2','automatic aileron');
connectNamed(modelName,'Raw Total Aileron/1','Physical Aileron Hard Stop/1', ...
    'raw total aileron');
connectNamed(modelName,'Physical Aileron Hard Stop/1','Control Mux/1', ...
    'protected total aileron');

connectNamed(modelName,'Pilot Rudder/1','Raw Total Rudder/1', ...
    'pilot rudder');
connectNamed(modelName,'Frozen Protected Yaw Damper V2/1', ...
    'Raw Total Rudder/2','automatic rudder');
connectNamed(modelName,'Raw Total Rudder/1','Physical Rudder Hard Stop/1', ...
    'raw total rudder');
connectNamed(modelName,'Physical Rudder Hard Stop/1','Control Mux/2', ...
    'protected total rudder');

connectNamed(modelName,'Control Mux/1', ...
    'C172S Lateral-Directional Plant/1', ...
    'u = [deltaA total, deltaR total]');
connectNamed(modelName,'C172S Lateral-Directional Plant/1','State Demux/1', ...
    'x = [beta p r phi psi]');
connectNamed(modelName,'State Demux/2', ...
    'Frozen Protected Roll-Attitude Hold V1/2','true roll rate');
connectNamed(modelName,'State Demux/4', ...
    'Frozen Protected Roll-Attitude Hold V1/3','true bank angle');
connectNamed(modelName,'State Demux/3', ...
    'Frozen Protected Yaw Damper V2/1','true yaw rate');
connectNamed(modelName,'State Demux/5', ...
    'Heading Sensor and Outer Loop/2','true heading');

%% Verification signals (fixed order used by independent checker)

signalSources = { ...
    'State Demux/1','hh1_beta','Beta'; ...                            % 1
    'State Demux/2','hh1_p','p'; ...                                 % 2
    'State Demux/3','hh1_r','r'; ...                                 % 3
    'State Demux/4','hh1_phi','Phi'; ...                              % 4
    'State Demux/5','hh1_psi','Psi'; ...                              % 5
    'Heading Sensor and Outer Loop/2','hh1_heading_command', ...
        'Heading Command Signal'; ...                                % 6
    'Heading Sensor and Outer Loop/3','hh1_psi_delayed', ...
        'Delayed Psi'; ...                                           % 7
    'Heading Sensor and Outer Loop/4','hh1_heading_bias', ...
        'Heading Bias'; ...                                          % 8
    'Heading Sensor and Outer Loop/5','hh1_heading_noise', ...
        'Heading Noise'; ...                                         % 9
    'Heading Sensor and Outer Loop/6','hh1_heading_input', ...
        'Heading Sensor Input'; ...                                  % 10
    'Heading Sensor and Outer Loop/7','hh1_heading_sensor', ...
        'Filtered Heading'; ...                                      % 11
    'Heading Sensor and Outer Loop/8','hh1_heading_difference', ...
        'Raw Heading Difference'; ...                                % 12
    'Heading Sensor and Outer Loop/9','hh1_heading_error', ...
        'Wrapped Heading Error'; ...                                 % 13
    'Heading Sensor and Outer Loop/10','hh1_bank_command_raw', ...
        'Raw Bank Command'; ...                                      % 14
    'Heading Sensor and Outer Loop/1','hh1_bank_command_limited', ...
        'Limited Bank Command'; ...                                  % 15
    'Command Filter/1','hh1_bank_command_filtered', ...
        'Filtered Bank Command'; ...                                 % 16
    'Pilot Aileron/1','hh1_aileron_pilot','Pilot Aileron Signal'; ... % 17
    'Pilot Rudder/1','hh1_rudder_pilot','Pilot Rudder Signal'; ...   % 18
    'Frozen Protected Yaw Damper V2/2','hh1_r_delayed','Delayed r'; ... % 19
    'Frozen Protected Yaw Damper V2/3','hh1_r_noise','Yaw Noise'; ... % 20
    'Frozen Protected Yaw Damper V2/4','hh1_r_input','Yaw Sensor Input'; ... % 21
    'Frozen Protected Yaw Damper V2/5','hh1_r_sensor','Filtered r'; ... % 22
    'Frozen Protected Yaw Damper V2/6','hh1_r_washout','Washout r'; ... % 23
    'Frozen Protected Yaw Damper V2/7','hh1_rudder_raw','Raw Auto Rudder'; ... % 24
    'Frozen Protected Yaw Damper V2/8','hh1_rudder_pos', ...
        'Rudder Position Command'; ...                               % 25
    'Frozen Protected Yaw Damper V2/1','hh1_rudder_actual', ...
        'Actual Auto Rudder'; ...                                    % 26
    'Frozen Protected Yaw Damper V2/9','hh1_rudder_rate_raw', ...
        'Raw Rudder Rate'; ...                                      % 27
    'Frozen Protected Yaw Damper V2/10','hh1_rudder_rate', ...
        'Limited Rudder Rate'; ...                                  % 28
    'Raw Total Rudder/1','hh1_rudder_total_raw', ...
        'Raw Total Rudder Signal'; ...                              % 29
    'Physical Rudder Hard Stop/1','hh1_rudder_total', ...
        'Total Rudder Signal'; ...                                  % 30
    'Frozen Protected Roll-Attitude Hold V1/2','hh1_p_delayed', ...
        'Delayed p'; ...                                            % 31
    'Frozen Protected Roll-Attitude Hold V1/3','hh1_p_noise', ...
        'Roll-Rate Noise'; ...                                      % 32
    'Frozen Protected Roll-Attitude Hold V1/4','hh1_p_input', ...
        'Roll-Rate Sensor Input'; ...                               % 33
    'Frozen Protected Roll-Attitude Hold V1/5','hh1_p_sensor', ...
        'Filtered p'; ...                                           % 34
    'Frozen Protected Roll-Attitude Hold V1/6','hh1_phi_delayed', ...
        'Delayed Phi'; ...                                          % 35
    'Frozen Protected Roll-Attitude Hold V1/7','hh1_phi_noise', ...
        'Bank-Angle Noise'; ...                                     % 36
    'Frozen Protected Roll-Attitude Hold V1/8','hh1_phi_input', ...
        'Bank-Angle Sensor Input'; ...                              % 37
    'Frozen Protected Roll-Attitude Hold V1/9','hh1_phi_sensor', ...
        'Filtered Phi'; ...                                         % 38
    'Frozen Protected Roll-Attitude Hold V1/10','hh1_bank_error', ...
        'Bank Error'; ...                                           % 39
    'Frozen Protected Roll-Attitude Hold V1/11','hh1_proportional', ...
        'Proportional Contribution'; ...                            % 40
    'Frozen Protected Roll-Attitude Hold V1/12','hh1_xi', ...
        'Integrator State'; ...                                     % 41
    'Frozen Protected Roll-Attitude Hold V1/13','hh1_integral', ...
        'Integral Contribution'; ...                                % 42
    'Frozen Protected Roll-Attitude Hold V1/14', ...
        'hh1_roll_rate_feedback','Roll-Rate Contribution'; ...      % 43
    'Frozen Protected Roll-Attitude Hold V1/15','hh1_aileron_unsat', ...
        'Unsaturated Aileron'; ...                                  % 44
    'Frozen Protected Roll-Attitude Hold V1/16','hh1_aileron_pos', ...
        'Aileron Position Command'; ...                             % 45
    'Frozen Protected Roll-Attitude Hold V1/1','hh1_aileron_actual', ...
        'Actual Auto Aileron'; ...                                  % 46
    'Frozen Protected Roll-Attitude Hold V1/17', ...
        'hh1_aileron_rate_raw','Raw Aileron Rate'; ...              % 47
    'Frozen Protected Roll-Attitude Hold V1/18','hh1_aileron_rate', ...
        'Limited Aileron Rate'; ...                                 % 48
    'Frozen Protected Roll-Attitude Hold V1/19','hh1_aileron_track', ...
        'Tracking Aileron'; ...                                     % 49
    'Frozen Protected Roll-Attitude Hold V1/20','hh1_aw_correction', ...
        'Anti-Windup Correction'; ...                               % 50
    'Raw Total Aileron/1','hh1_aileron_total_raw', ...
        'Raw Total Aileron Signal'; ...                             % 51
    'Physical Aileron Hard Stop/1','hh1_aileron_total', ...
        'Total Aileron Signal'};                                    % 52

for k = 1:size(signalSources,1)
    x = 1660 + 155*mod(k-1,4);
    y = 40 + 31*floor((k-1)/4);
    addGlobalGoto(modelName,[signalSources{k,3} ' Tag'], ...
        signalSources{k,2},[x y x+125 y+18]);
end

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[2310 365 2470 435]);
clearDefaultSubsystem(verificationPath);
for k = 1:size(signalSources,1)
    y = 20 + 29*(k-1);
    addFrom(verificationPath,signalSources{k,3},signalSources{k,2}, ...
        [25 y 175 y+18]);
end
add_block('simulink/Signal Routing/Mux',[verificationPath '/Signal Mux'], ...
    'Inputs',num2str(size(signalSources,1)), ...
    'Position',[240 10 245 1510]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[305 745 335 765]);
for k = 1:size(signalSources,1)
    add_line(verificationPath,[signalSources{k,3} '/1'], ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Protected Closed-Loop Signals'], ...
    'Port','1','Position',[2525 390 2555 410]);
add_line(modelName,'Verification Signals/1', ...
    'Protected Closed-Loop Signals/1','autorouting','on');

for k = 1:size(signalSources,1)
    branchTo(modelName,signalSources{k,1},[signalSources{k,3} ' Tag/1']);
end

%% Traceability, compile and save

try
    note = Simulink.Annotation(modelName,[ ...
        'Heading Hold V1 - protected implementation of HH-V1-MATLAB-R1' newline ...
        'phiCmd = sat(0.575*atan2(sin(ePsi),cos(ePsi)),+/-20 deg)' newline ...
        '50-ms heading delay; 100-ms heading filter; frozen protected RAH V1 and YD V2' newline ...
        '+/-20-deg bank command; +/-5-deg auto aileron; +/-30-deg/s; +/-14-deg hard stop' newline ...
        'Servo, sensor and automatic-authority values are project assumptions, not identified hardware data']);
    note.Position = [35 20 1320 115];
catch
    % Annotation appearance is not part of executable equivalence.
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runHeadingHoldSimulinkCheck to validate Heading Hold V1.\n');

end

function buildHeadingSubsystem(path)
clearDefaultSubsystem(path);

addInport(path,'Heading Command',1,[25 55 55 75]);
addInport(path,'True Psi',2,[25 185 55 205]);

previousBlock = 'True Psi/1';
for k = 1:5
    blockName = sprintf('Heading Pure Delay %d',k);
    x = 95+105*(k-1);
    add_block('simulink/Discrete/Unit Delay',[path '/' blockName], ...
        'SampleTime','headingDelaySampleTime_hh1', ...
        'InitialCondition','psiDelay0_hh1_rad', ...
        'Position',[x 175 x+75 215]);
    add_line(path,previousBlock,[blockName '/1'],'autorouting','on');
    previousBlock = [blockName '/1'];
end

add_block('simulink/Sources/Constant',[path '/Heading Bias'], ...
    'Value','headingBias_hh1_rad','Position',[420 265 500 295]);
add_block('simulink/Sources/Sine Wave',[path '/Heading Sensor Noise'], ...
    'Amplitude','headingNoiseAmplitude_hh1_rad','Bias','0', ...
    'Frequency','headingNoiseFrequency_hh1_radps','Phase','0', ...
    'SampleTime','0','Position',[420 330 520 370]);
add_block('simulink/Math Operations/Sum',[path '/Heading Sensor Input Sum'], ...
    'Inputs','+++','Position',[585 185 615 275]);
add_block('simulink/Continuous/State-Space',[path '/Heading Sensor Filter'], ...
    'A','-1/TsHeading_hh1','B','1/TsHeading_hh1','C','1','D','0', ...
    'X0','psiSensor0_hh1_rad','Position',[670 205 790 255]);
add_block('simulink/Math Operations/Sum',[path '/Raw Heading Difference'], ...
    'Inputs','+-','Position',[845 50 875 110]);
add_block('simulink/User-Defined Functions/Fcn',[path '/Circular Error'], ...
    'Expr','atan2(sin(u),cos(u))','Position',[930 55 1065 105]);
add_block('simulink/Math Operations/Gain',[path '/Heading Gain Kpsi'], ...
    'Gain','Kpsi_hh1','Position',[1120 60 1225 100]);
add_block('simulink/Discontinuities/Saturation', ...
    [path '/Bank Command Limit'], ...
    'LowerLimit','bankCommandLower_hh1_rad', ...
    'UpperLimit','bankCommandUpper_hh1_rad', ...
    'Position',[1280 50 1420 110]);

add_line(path,previousBlock,'Heading Sensor Input Sum/1','autorouting','on');
add_line(path,'Heading Bias/1','Heading Sensor Input Sum/2', ...
    'autorouting','on');
add_line(path,'Heading Sensor Noise/1','Heading Sensor Input Sum/3', ...
    'autorouting','on');
add_line(path,'Heading Sensor Input Sum/1','Heading Sensor Filter/1', ...
    'autorouting','on');
add_line(path,'Heading Command/1','Raw Heading Difference/1', ...
    'autorouting','on');
add_line(path,'Heading Sensor Filter/1','Raw Heading Difference/2', ...
    'autorouting','on');
add_line(path,'Raw Heading Difference/1','Circular Error/1', ...
    'autorouting','on');
add_line(path,'Circular Error/1','Heading Gain Kpsi/1','autorouting','on');
add_line(path,'Heading Gain Kpsi/1','Bank Command Limit/1', ...
    'autorouting','on');

headingOutputs = { ...
    'Bank Command Limit/1','Limited Bank Command'; ...
    'Heading Command/1','Command Signal'; ...
    previousBlock,'Delayed Psi'; ...
    'Heading Bias/1','Bias Signal'; ...
    'Heading Sensor Noise/1','Noise Signal'; ...
    'Heading Sensor Input Sum/1','Sensor Input'; ...
    'Heading Sensor Filter/1','Filtered Heading'; ...
    'Raw Heading Difference/1','Raw Difference'; ...
    'Circular Error/1','Wrapped Error'; ...
    'Heading Gain Kpsi/1','Raw Bank Command'};
for k = 1:size(headingOutputs,1)
    y = 35+42*(k-1);
    addOutport(path,headingOutputs{k,2},k,[1500 y 1530 y+20]);
    add_line(path,headingOutputs{k,1},[headingOutputs{k,2} '/1'], ...
        'autorouting','on');
end
end

function buildRollSubsystem(path)
clearDefaultSubsystem(path);

addInport(path,'Filtered Command',1,[25 50 55 70]);
addInport(path,'True p',2,[25 190 55 210]);
addInport(path,'True Phi',3,[25 510 55 530]);

add_block('simulink/Discrete/Unit Delay',[path '/p Pure Delay'], ...
    'SampleTime','delaySampleTime_hh1', ...
    'InitialCondition','pDelay0_hh1_radps', ...
    'Position',[95 175 190 215]);
add_block('simulink/Sources/Sine Wave',[path '/p Sensor Noise'], ...
    'Amplitude','pNoiseAmplitude_hh1_radps','Bias','0', ...
    'Frequency','pNoiseFrequency_hh1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 255 190 295]);
add_block('simulink/Math Operations/Sum',[path '/p Sensor Input Sum'], ...
    'Inputs','++','Position',[235 190 265 250]);
add_block('simulink/Continuous/State-Space',[path '/p Sensor Filter'], ...
    'A','-1/TsRoll_hh1','B','1/TsRoll_hh1','C','1','D','0', ...
    'X0','pSensor0_hh1_radps','Position',[310 195 420 245]);
add_block('simulink/Math Operations/Gain',[path '/Roll-Rate Gain -Kp'], ...
    'Gain','-Kp_hh1','Position',[470 200 575 240]);

add_block('simulink/Discrete/Unit Delay',[path '/Phi Pure Delay'], ...
    'SampleTime','delaySampleTime_hh1', ...
    'InitialCondition','phiDelay0_hh1_rad', ...
    'Position',[95 495 190 535]);
add_block('simulink/Sources/Sine Wave',[path '/Phi Sensor Noise'], ...
    'Amplitude','phiNoiseAmplitude_hh1_rad','Bias','0', ...
    'Frequency','phiNoiseFrequency_hh1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 575 190 615]);
add_block('simulink/Math Operations/Sum',[path '/Phi Sensor Input Sum'], ...
    'Inputs','++','Position',[235 510 265 570]);
add_block('simulink/Continuous/State-Space',[path '/Phi Sensor Filter'], ...
    'A','-1/TsRoll_hh1','B','1/TsRoll_hh1','C','1','D','0', ...
    'X0','phiSensor0_hh1_rad','Position',[310 515 420 565]);
add_block('simulink/Math Operations/Sum',[path '/Bank Error'], ...
    'Inputs','+-','Position',[470 45 500 85]);
add_block('simulink/Math Operations/Gain',[path '/Bank Proportional Gain Kphi'], ...
    'Gain','Kphi_hh1','Position',[550 40 655 80]);

add_block('simulink/Math Operations/Sum',[path '/Integrator Input'], ...
    'Inputs','++','Position',[550 455 580 505]);
add_block('simulink/Continuous/Integrator',[path '/Error Integrator'], ...
    'InitialCondition','xi0_hh1_rad_s','Position',[625 460 655 500]);
add_block('simulink/Math Operations/Gain',[path '/Bank Integral Gain Ki'], ...
    'Gain','Ki_hh1','Position',[705 460 795 500]);

add_block('simulink/Math Operations/Sum',[path '/Unsaturated Aileron Command'], ...
    'Inputs','+++','Position',[845 185 875 265]);
add_block('simulink/Discontinuities/Saturation', ...
    [path '/Automatic Aileron Position Limit'], ...
    'LowerLimit','autoAileronLower_hh1_rad', ...
    'UpperLimit','autoAileronUpper_hh1_rad', ...
    'Position',[925 195 1065 255]);
add_block('simulink/Math Operations/Sum',[path '/Aileron Servo Position Error'], ...
    'Inputs','+-','Position',[1115 200 1145 250]);
add_block('simulink/Math Operations/Gain',[path '/Aileron Servo Inverse Tau'], ...
    'Gain','1/tauAileron_hh1','Position',[1190 205 1295 245]);
add_block('simulink/Discontinuities/Saturation',[path '/Aileron Servo Rate Limit'], ...
    'LowerLimit','aileronRateLower_hh1_radps', ...
    'UpperLimit','aileronRateUpper_hh1_radps', ...
    'Position',[1340 195 1470 255]);
add_block('simulink/Continuous/Integrator',[path '/Automatic Aileron Actuator'], ...
    'InitialCondition','deltaAAuto0_hh1_rad', ...
    'Position',[1520 205 1550 245]);

% Rate-aware tracking value: deltaATrack = deltaAActual + tauA*limitedRate.
add_block('simulink/Math Operations/Gain',[path '/Limited Rate Times Tau'], ...
    'Gain','tauAileron_hh1','Position',[1345 370 1470 410]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Aileron'], ...
    'Inputs','++','Position',[1520 355 1550 415]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Error'], ...
    'Inputs','+-','Position',[1115 455 1145 505]);
add_block('simulink/Math Operations/Gain',[path '/Anti-Windup Scale'], ...
    'Gain','1/(Ki_hh1*Tt_hh1)','Position',[1190 460 1325 500]);
add_block('simulink/Math Operations/Gain',[path '/Anti-Windup Enable'], ...
    'Gain','antiWindupEnable_hh1','Position',[1370 460 1490 500]);

add_line(path,'True p/1','p Pure Delay/1','autorouting','on');
add_line(path,'p Pure Delay/1','p Sensor Input Sum/1','autorouting','on');
add_line(path,'p Sensor Noise/1','p Sensor Input Sum/2','autorouting','on');
add_line(path,'p Sensor Input Sum/1','p Sensor Filter/1','autorouting','on');
add_line(path,'p Sensor Filter/1','Roll-Rate Gain -Kp/1','autorouting','on');

add_line(path,'True Phi/1','Phi Pure Delay/1','autorouting','on');
add_line(path,'Phi Pure Delay/1','Phi Sensor Input Sum/1','autorouting','on');
add_line(path,'Phi Sensor Noise/1','Phi Sensor Input Sum/2','autorouting','on');
add_line(path,'Phi Sensor Input Sum/1','Phi Sensor Filter/1','autorouting','on');
add_line(path,'Filtered Command/1','Bank Error/1','autorouting','on');
add_line(path,'Phi Sensor Filter/1','Bank Error/2','autorouting','on');
add_line(path,'Bank Error/1','Bank Proportional Gain Kphi/1','autorouting','on');
add_line(path,'Bank Error/1','Integrator Input/1','autorouting','on');
add_line(path,'Integrator Input/1','Error Integrator/1','autorouting','on');
add_line(path,'Error Integrator/1','Bank Integral Gain Ki/1','autorouting','on');

add_line(path,'Bank Proportional Gain Kphi/1', ...
    'Unsaturated Aileron Command/1','autorouting','on');
add_line(path,'Bank Integral Gain Ki/1', ...
    'Unsaturated Aileron Command/2','autorouting','on');
add_line(path,'Roll-Rate Gain -Kp/1', ...
    'Unsaturated Aileron Command/3','autorouting','on');
add_line(path,'Unsaturated Aileron Command/1', ...
    'Automatic Aileron Position Limit/1','autorouting','on');
add_line(path,'Automatic Aileron Position Limit/1', ...
    'Aileron Servo Position Error/1','autorouting','on');
add_line(path,'Automatic Aileron Actuator/1', ...
    'Aileron Servo Position Error/2','autorouting','on');
add_line(path,'Aileron Servo Position Error/1', ...
    'Aileron Servo Inverse Tau/1','autorouting','on');
add_line(path,'Aileron Servo Inverse Tau/1', ...
    'Aileron Servo Rate Limit/1','autorouting','on');
add_line(path,'Aileron Servo Rate Limit/1', ...
    'Automatic Aileron Actuator/1','autorouting','on');

add_line(path,'Aileron Servo Rate Limit/1', ...
    'Limited Rate Times Tau/1','autorouting','on');
add_line(path,'Automatic Aileron Actuator/1', ...
    'Tracking Aileron/1','autorouting','on');
add_line(path,'Limited Rate Times Tau/1','Tracking Aileron/2','autorouting','on');
add_line(path,'Tracking Aileron/1','Tracking Error/1','autorouting','on');
add_line(path,'Unsaturated Aileron Command/1', ...
    'Tracking Error/2','autorouting','on');
add_line(path,'Tracking Error/1','Anti-Windup Scale/1','autorouting','on');
add_line(path,'Anti-Windup Scale/1','Anti-Windup Enable/1','autorouting','on');
add_line(path,'Anti-Windup Enable/1','Integrator Input/2','autorouting','on');

rollOutputs = { ...
    'Automatic Aileron Actuator/1','Automatic Aileron'; ...
    'p Pure Delay/1','Delayed p'; ...
    'p Sensor Noise/1','p Noise'; ...
    'p Sensor Input Sum/1','p Sensor Input'; ...
    'p Sensor Filter/1','Filtered p'; ...
    'Phi Pure Delay/1','Delayed Phi'; ...
    'Phi Sensor Noise/1','Phi Noise'; ...
    'Phi Sensor Input Sum/1','Phi Sensor Input'; ...
    'Phi Sensor Filter/1','Filtered Phi'; ...
    'Bank Error/1','Bank Error Signal'; ...
    'Bank Proportional Gain Kphi/1','Proportional Contribution'; ...
    'Error Integrator/1','Integrator State Signal'; ...
    'Bank Integral Gain Ki/1','Integral Contribution'; ...
    'Roll-Rate Gain -Kp/1','Roll-Rate Contribution'; ...
    'Unsaturated Aileron Command/1','Unsaturated Aileron'; ...
    'Automatic Aileron Position Limit/1','Aileron Position Command'; ...
    'Aileron Servo Inverse Tau/1','Raw Aileron Rate'; ...
    'Aileron Servo Rate Limit/1','Limited Aileron Rate'; ...
    'Tracking Aileron/1','Tracking Aileron Signal'; ...
    'Anti-Windup Enable/1','Anti-Windup Correction'};
for k = 1:size(rollOutputs,1)
    y = 35 + 38*(k-1);
    addOutport(path,rollOutputs{k,2},k,[1640 y 1670 y+20]);
    add_line(path,rollOutputs{k,1},[rollOutputs{k,2} '/1'], ...
        'autorouting','on');
end
end

function buildYawSubsystem(path)
clearDefaultSubsystem(path);
addInport(path,'True r',1,[25 150 55 170]);
add_block('simulink/Discrete/Unit Delay',[path '/r Pure Delay'], ...
    'SampleTime','delaySampleTime_hh1', ...
    'InitialCondition','rDelay0_hh1_radps', ...
    'Position',[95 135 190 175]);
add_block('simulink/Sources/Sine Wave',[path '/Yaw Sensor Noise'], ...
    'Amplitude','yawNoiseAmplitude_hh1_radps','Bias','0', ...
    'Frequency','yawNoiseFrequency_hh1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 225 190 265]);
add_block('simulink/Math Operations/Sum',[path '/Yaw Sensor Input Sum'], ...
    'Inputs','++','Position',[235 150 265 210]);
add_block('simulink/Continuous/State-Space',[path '/Yaw-Rate Sensor Filter'], ...
    'A','-1/TsRudder_hh1','B','1/TsRudder_hh1','C','1','D','0', ...
    'X0','rSensor0_hh1_radps','Position',[315 155 430 205]);
add_block('simulink/Continuous/State-Space',[path '/Yaw-Rate Washout'], ...
    'A','-1/Tw_hh1','B','1/Tw_hh1','C','-1','D','1', ...
    'X0','xw0_hh1_radps','Position',[480 155 595 205]);
add_block('simulink/Math Operations/Gain',[path '/Automatic Rudder Gain'], ...
    'Gain','-Kr_hh1','Position',[645 160 745 200]);
add_block('simulink/Discontinuities/Saturation', ...
    [path '/Automatic Rudder Position Limit'], ...
    'LowerLimit','autoRudderLower_hh1_rad', ...
    'UpperLimit','autoRudderUpper_hh1_rad', ...
    'Position',[795 150 930 210]);
add_block('simulink/Math Operations/Sum',[path '/Rudder Servo Position Error'], ...
    'Inputs','+-','Position',[980 155 1010 205]);
add_block('simulink/Math Operations/Gain',[path '/Rudder Servo Inverse Tau'], ...
    'Gain','1/tauRudder_hh1','Position',[1060 160 1170 200]);
add_block('simulink/Discontinuities/Saturation',[path '/Rudder Servo Rate Limit'], ...
    'LowerLimit','rudderRateLower_hh1_radps', ...
    'UpperLimit','rudderRateUpper_hh1_radps', ...
    'Position',[1220 150 1350 210]);
add_block('simulink/Continuous/Integrator',[path '/Automatic Rudder Actuator'], ...
    'InitialCondition','deltaRAuto0_hh1_rad', ...
    'Position',[1400 160 1430 200]);

add_line(path,'True r/1','r Pure Delay/1','autorouting','on');
add_line(path,'r Pure Delay/1','Yaw Sensor Input Sum/1','autorouting','on');
add_line(path,'Yaw Sensor Noise/1','Yaw Sensor Input Sum/2','autorouting','on');
add_line(path,'Yaw Sensor Input Sum/1','Yaw-Rate Sensor Filter/1','autorouting','on');
add_line(path,'Yaw-Rate Sensor Filter/1','Yaw-Rate Washout/1','autorouting','on');
add_line(path,'Yaw-Rate Washout/1','Automatic Rudder Gain/1','autorouting','on');
add_line(path,'Automatic Rudder Gain/1', ...
    'Automatic Rudder Position Limit/1','autorouting','on');
add_line(path,'Automatic Rudder Position Limit/1', ...
    'Rudder Servo Position Error/1','autorouting','on');
add_line(path,'Automatic Rudder Actuator/1', ...
    'Rudder Servo Position Error/2','autorouting','on');
add_line(path,'Rudder Servo Position Error/1', ...
    'Rudder Servo Inverse Tau/1','autorouting','on');
add_line(path,'Rudder Servo Inverse Tau/1', ...
    'Rudder Servo Rate Limit/1','autorouting','on');
add_line(path,'Rudder Servo Rate Limit/1', ...
    'Automatic Rudder Actuator/1','autorouting','on');

yawOutputs = { ...
    'Automatic Rudder Actuator/1','Automatic Rudder'; ...
    'r Pure Delay/1','Delayed r'; ...
    'Yaw Sensor Noise/1','Yaw Noise'; ...
    'Yaw Sensor Input Sum/1','Yaw Sensor Input'; ...
    'Yaw-Rate Sensor Filter/1','Filtered r'; ...
    'Yaw-Rate Washout/1','Washout r'; ...
    'Automatic Rudder Gain/1','Raw Automatic Rudder'; ...
    'Automatic Rudder Position Limit/1','Rudder Position Command'; ...
    'Rudder Servo Inverse Tau/1','Raw Rudder Rate'; ...
    'Rudder Servo Rate Limit/1','Limited Rudder Rate'};
for k = 1:size(yawOutputs,1)
    y = 35 + 40*(k-1);
    addOutport(path,yawOutputs{k,2},k,[1520 y 1550 y+20]);
    add_line(path,yawOutputs{k,1},[yawOutputs{k,2} '/1'], ...
        'autorouting','on');
end
end

function assertDependencies(data,yawController,rudder,rollController, ...
    aileron,headingSensor,headingController)
assert(strcmp(data.model.version,headingController.requiredPlantVersion), ...
    'Heading Hold V1 plant dependency mismatch.');
assert(strcmp(yawController.artifactRevision, ...
    headingController.requiredYawDamperRevision), ...
    'Heading Hold V1 yaw-controller dependency mismatch.');
assert(strcmp(rudder.artifactRevision, ...
    headingController.requiredRudderAuditRevision), ...
    'Heading Hold V1 rudder-audit dependency mismatch.');
assert(strcmp(aileron.artifactRevision, ...
    headingController.requiredAileronAuditRevision), ...
    'Heading Hold V1 aileron-audit dependency mismatch.');
assert(strcmp(rollController.artifactRevision, ...
    headingController.requiredRollControllerRevision), ...
    'Heading Hold V1 roll-controller dependency mismatch.');
assert(strcmp(headingSensor.artifactRevision, ...
    headingController.requiredHeadingSensorRevision), ...
    'Heading Hold V1 heading-sensor dependency mismatch.');
assert(abs(aileron.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms roll delay.');
assert(abs(rudder.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms yaw delay.');
assert(abs(headingSensor.nominalDelay_s-0.050) < 1.0e-12, ...
    'The executable baseline requires the audited 50-ms heading delay.');
assert(abs(headingController.bankCommandAuthority_deg- ...
    rollController.commandAuthority.rightWingDown_deg) < 1.0e-12, ...
    'Heading Hold V1 must reuse the frozen RAH bank authority.');
end

function assignModelVariables(data,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController)
assignin('base','hh1Data',data);
assignin('base','hh1Plant',plant);
assignin('base','hh1YawController',yawController);
assignin('base','hh1RudderActuator',rudder);
assignin('base','hh1RollController',rollController);
assignin('base','hh1AileronActuator',aileron);
assignin('base','hh1HeadingSensor',headingSensor);
assignin('base','hh1HeadingController',headingController);
assignin('base','A_hh1',plant.A);
assignin('base','B_hh1',plant.B);
assignin('base','C_hh1',plant.C);
assignin('base','D_hh1',plant.D);
assignin('base','Kphi_hh1',rollController.bankProportionalGain);
assignin('base','Ki_hh1',rollController.bankIntegralGain_per_s);
assignin('base','Kp_hh1',rollController.rollRateGain_s);
assignin('base','Tcmd_hh1',rollController.commandFilterTimeConstant_s);
assignin('base','Kr_hh1',yawController.rudderGain_s);
assignin('base','Tw_hh1',yawController.washoutTimeConstant_s);
assignin('base','TsRudder_hh1',rudder.sensor.filterTimeConstant_s);
assignin('base','tauRudder_hh1',rudder.dynamics.timeConstant_s);
assignin('base','TsRoll_hh1',aileron.sensor.filterTimeConstant_s);
assignin('base','tauAileron_hh1',aileron.dynamics.timeConstant_s);
assignin('base','Tt_hh1',aileron.antiWindup.trackingTimeConstant_s);
assignin('base','delaySampleTime_hh1',aileron.sensor.nominalDelay_s);
assignin('base','headingDelaySampleTime_hh1', ...
    headingSensor.nominalDelay_s/5);
assignin('base','Kpsi_hh1',headingController.headingErrorGain);
assignin('base','TsHeading_hh1',headingSensor.filterTimeConstant_s);
assignin('base','bankCommandLower_hh1_rad', ...
    -deg2rad(headingController.bankCommandAuthority_deg));
assignin('base','bankCommandUpper_hh1_rad', ...
    deg2rad(headingController.bankCommandAuthority_deg));
assignin('base','autoAileronLower_hh1_rad',aileron.authority.lowerLimit_rad);
assignin('base','autoAileronUpper_hh1_rad',aileron.authority.upperLimit_rad);
assignin('base','aileronRateLower_hh1_radps', ...
    -deg2rad(aileron.dynamics.rateLimit_degps));
assignin('base','aileronRateUpper_hh1_radps', ...
    deg2rad(aileron.dynamics.rateLimit_degps));
assignin('base','totalAileronLower_hh1_rad', ...
    aileron.physicalTravel.lowerLimit_rad);
assignin('base','totalAileronUpper_hh1_rad', ...
    aileron.physicalTravel.upperLimit_rad);
assignin('base','autoRudderLower_hh1_rad',rudder.authority.lowerLimit_rad);
assignin('base','autoRudderUpper_hh1_rad',rudder.authority.upperLimit_rad);
assignin('base','rudderRateLower_hh1_radps', ...
    -deg2rad(rudder.dynamics.rateLimit_degps));
assignin('base','rudderRateUpper_hh1_radps', ...
    deg2rad(rudder.dynamics.rateLimit_degps));
assignin('base','totalRudderLower_hh1_rad', ...
    rudder.physicalTravel.lowerLimit_rad);
assignin('base','totalRudderUpper_hh1_rad', ...
    rudder.physicalTravel.upperLimit_rad);

assignin('base','headingCommand_hh1_rad', ...
    deg2rad(headingController.validation.commandStep_deg));
assignin('base','headingBias_hh1_rad',0.0);
assignin('base','headingNoiseAmplitude_hh1_rad',0.0);
assignin('base','headingNoiseFrequency_hh1_radps', ...
    headingSensor.noiseFrequency_radps);
assignin('base','pilotAileronBias_hh1_rad',0.0);
assignin('base','pilotAileronPulse_hh1_rad',0.0);
assignin('base','pilotRudderBias_hh1_rad',0.0);
assignin('base','pilotRudderPulse_hh1_rad',0.0);
assignin('base','aileronPulseStart_hh1_s',5.0);
assignin('base','aileronPulseEnd_hh1_s',6.0);
assignin('base','rudderPulseStart_hh1_s',5.0);
assignin('base','rudderPulseEnd_hh1_s',6.0);
assignin('base','pNoiseAmplitude_hh1_radps',0.0);
assignin('base','pNoiseFrequency_hh1_radps',50.0);
assignin('base','phiNoiseAmplitude_hh1_rad',0.0);
assignin('base','phiNoiseFrequency_hh1_radps',5.0);
assignin('base','yawNoiseAmplitude_hh1_radps',0.0);
assignin('base','yawNoiseFrequency_hh1_radps',50.0);
assignin('base','antiWindupEnable_hh1',1.0);
assignin('base','x0_hh1',zeros(5,1));
assignin('base','rDelay0_hh1_radps',0.0);
assignin('base','pDelay0_hh1_radps',0.0);
assignin('base','phiDelay0_hh1_rad',0.0);
assignin('base','rSensor0_hh1_radps',0.0);
assignin('base','xw0_hh1_radps',0.0);
assignin('base','deltaRAuto0_hh1_rad',0.0);
assignin('base','pSensor0_hh1_radps',0.0);
assignin('base','phiSensor0_hh1_rad',0.0);
assignin('base','psiDelay0_hh1_rad',0.0);
assignin('base','psiSensor0_hh1_rad',0.0);
assignin('base','xi0_hh1_rad_s',0.0);
assignin('base','deltaAAuto0_hh1_rad',0.0);
assignin('base','filteredCommand0_hh1_rad',0.0);
end

function clearDefaultSubsystem(path)
lines = find_system(path,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(path,'SearchDepth',1,'Type','Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end
end

function addInport(systemName,blockName,port,position)
add_block('simulink/Ports & Subsystems/In1',[systemName '/' blockName], ...
    'Port',num2str(port),'Position',position);
end

function addOutport(systemName,blockName,port,position)
add_block('simulink/Ports & Subsystems/Out1',[systemName '/' blockName], ...
    'Port',num2str(port),'Position',position);
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end
