function modelName = buildC172sPitchAttitudeActuatorSimulink(forceRebuild)
%BUILDC172SPITCHATTITUDEACTUATORSIMULINK Build protected attitude-hold V2.
%
%   The generated model adds position authority, rate-limited first-order
%   actuator dynamics and rate-aware back-calculation anti-windup to the
%   validated pitch-attitude architecture.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_PitchAttitudeHold_V2_Actuator';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize model variables

pa2Data = c172sLongitudinalData();
[~,pa2Plant] = c172sLongitudinalPlant(pa2Data);
pa2Controller = c172sPitchAttitudeControllerData();
pa2Actuator = c172sElevatorActuatorData();

assignModelVariables(pa2Data,pa2Plant,pa2Controller,pa2Actuator);

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the model

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step','Solver','ode4','FixedStep','0.001', ...
    'StartTime','0','StopTime','60','SaveTime','on','TimeSaveName','tout', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Array');

initCode = [ ...
    'pa2Data = c172sLongitudinalData();' newline ...
    '[~,pa2Plant] = c172sLongitudinalPlant(pa2Data);' newline ...
    'pa2Controller = c172sPitchAttitudeControllerData();' newline ...
    'pa2Actuator = c172sElevatorActuatorData();' newline ...
    'A_pa2 = pa2Plant.A; B_pa2 = pa2Plant.B;' newline ...
    'C_pa2 = pa2Plant.C; D_pa2 = pa2Plant.D;' newline ...
    'Kp_pa2 = pa2Controller.Kp_radPerRad;' newline ...
    'Ki_pa2_per_s = pa2Controller.Ki_radPerRadPerS;' newline ...
    'Kq_pa2_s = pa2Actuator.integration.Kq_s;' newline ...
    'tauCommand_pa2_s = pa2Controller.commandFilterTimeConstant_s;' newline ...
    'tauActuator_pa2_s = pa2Actuator.dynamics.timeConstant_s;' newline ...
    'Tt_pa2_s = pa2Actuator.antiWindup.trackingTimeConstant_s;' newline ...
    'deltaELower_pa2_rad = pa2Actuator.authority.lowerLimit_rad;' newline ...
    'deltaEUpper_pa2_rad = pa2Actuator.authority.upperLimit_rad;' newline ...
    'deltaERate_pa2_radps = deg2rad(pa2Actuator.dynamics.rateLimit_degps);' newline ...
    'if ~exist(''thetaCommand_pa2_rad'',''var''), thetaCommand_pa2_rad = deg2rad(pa2Actuator.validation.commandStep_deg); end' newline ...
    'if ~exist(''antiWindupEnable_pa2'',''var''), antiWindupEnable_pa2 = 1.0; end' newline ...
    'if ~exist(''x0_pa2'',''var''), x0_pa2 = zeros(4,1); end' newline ...
    'if ~exist(''xi0_pa2'',''var''), xi0_pa2 = 0.0; end' newline ...
    'if ~exist(''deltaE0_pa2'',''var''), deltaE0_pa2 = 0.0; end'];
set_param(modelName,'InitFcn',initCode);

%% Main control architecture

add_block('simulink/Sources/Step',[modelName '/Pitch-Attitude Command'], ...
    'Time','0','Before','0','After','thetaCommand_pa2_rad', ...
    'SampleTime','0','Position',[35 150 105 180]);
add_block('simulink/Continuous/Transfer Fcn',[modelName '/Command Filter'], ...
    'Numerator','1','Denominator','[tauCommand_pa2_s 1]', ...
    'Position',[145 142 255 188]);
add_block('simulink/Math Operations/Sum',[modelName '/Attitude Error'], ...
    'Inputs','+-','Position',[305 147 335 183]);
add_block('simulink/Math Operations/Gain',[modelName '/Proportional Gain -Kp'], ...
    'Gain','-Kp_pa2','Position',[390 95 495 130]);
add_block('simulink/Math Operations/Sum',[modelName '/Integrator Input'], ...
    'Inputs','++','Position',[385 220 415 260]);
add_block('simulink/Continuous/Integrator',[modelName '/Error Integrator'], ...
    'InitialCondition','xi0_pa2','Position',[455 225 485 255]);
add_block('simulink/Math Operations/Gain',[modelName '/Integral Gain -Ki'], ...
    'Gain','-Ki_pa2_per_s','Position',[525 222 630 258]);
add_block('simulink/Math Operations/Sum',[modelName '/PI Elevator Command'], ...
    'Inputs','++','Position',[675 140 705 180]);
add_block('simulink/Math Operations/Gain',[modelName '/Pitch-Rate Gain Kq'], ...
    'Gain','Kq_pa2_s','Position',[585 335 690 370]);
add_block('simulink/Math Operations/Sum',[modelName '/Unsaturated Total Command'], ...
    'Inputs','++','Position',[760 140 790 180]);

actuatorPath = [modelName '/Actuator and Anti-Windup'];
add_block('simulink/Ports & Subsystems/Subsystem',actuatorPath, ...
    'Position',[845 125 985 195]);
buildActuatorSubsystem(actuatorPath);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Longitudinal Plant'], ...
    'A','A_pa2','B','B_pa2','C','C_pa2','D','D_pa2','X0','x0_pa2', ...
    'Position',[1040 125 1210 195]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','4','Position',[1260 95 1265 225]);

%% Global signal tags and feedback access

tagDefinitions = { ...
    'Command Tag','pa2_command',[45 235 125 255]; ...
    'Filtered Command Tag','pa2_filtered',[165 235 270 255]; ...
    'Integrator Tag','pa2_xi',[455 285 530 305]; ...
    'PI Command Tag','pa2_pi',[675 220 750 240]; ...
    'q Contribution Tag','pa2_q_contribution',[700 335 820 355]; ...
    'Unsaturated Command Tag','pa2_unsat',[770 220 885 240]; ...
    'Position Command Tag','pa2_position_command',[875 270 1010 290]; ...
    'Actual Elevator Tag','pa2_actual',[1020 255 1115 275]; ...
    'Elevator Rate Tag','pa2_rate',[1020 300 1115 320]; ...
    'Anti-Windup Tag','pa2_aw',[850 335 940 355]; ...
    'u Tag','pa2_u',[1295 80 1355 100]; ...
    'alpha Tag','pa2_alpha',[1295 115 1355 135]; ...
    'q Tag','pa2_q',[1295 150 1355 170]; ...
    'theta Tag','pa2_theta',[1295 185 1355 205]};
for k = 1:size(tagDefinitions,1)
    addGlobalGoto(modelName,tagDefinitions{k,1},tagDefinitions{k,2}, ...
        tagDefinitions{k,3});
end

addFrom(modelName,'Theta Feedback','pa2_theta',[250 205 305 225]);
addFrom(modelName,'q Feedback','pa2_q',[510 340 565 360]);
addFrom(modelName,'Anti-Windup Feedback','pa2_aw',[300 275 385 295]);

%% Verification and display subsystems

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[1410 105 1550 175]);
clearDefaultSubsystem(verificationPath);
verificationTags = {'pa2_u','pa2_alpha','pa2_q','pa2_theta', ...
    'pa2_filtered','pa2_xi','pa2_pi','pa2_q_contribution','pa2_unsat', ...
    'pa2_position_command','pa2_actual','pa2_rate','pa2_aw'};
verificationNames = {'u','alpha','q','theta','Filtered Command', ...
    'Integrator State','PI Command','q Contribution','Unsaturated Command', ...
    'Position Command','Actual Elevator','Elevator Rate','AW Correction'};
for k = 1:numel(verificationTags)
    yPosition = 25 + 35*(k - 1);
    addFrom(verificationPath,verificationNames{k},verificationTags{k}, ...
        [25 yPosition 145 yPosition + 20]);
end
add_block('simulink/Signal Routing/Mux',[verificationPath '/Signal Mux'], ...
    'Inputs',num2str(numel(verificationTags)), ...
    'Position',[220 15 225 470]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[280 235 310 255]);
for k = 1:numel(verificationTags)
    add_line(verificationPath,sprintf('%s/1',verificationNames{k}), ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Closed-Loop Signals'], ...
    'Port','1','Position',[1605 130 1635 150]);
add_line(modelName,'Verification Signals/1','Closed-Loop Signals/1', ...
    'autorouting','on');

displayPath = [modelName '/Display Scopes'];
add_block('simulink/Ports & Subsystems/Subsystem',displayPath, ...
    'Position',[1410 260 1550 325]);
clearDefaultSubsystem(displayPath);
buildDisplaySubsystem(displayPath);

%% Connect the main diagram

connectNamed(modelName,'Pitch-Attitude Command/1','Command Filter/1', ...
    'theta command rad');
connectNamed(modelName,'Command Filter/1','Attitude Error/1', ...
    'filtered theta command rad');
connectNamed(modelName,'Theta Feedback/1','Attitude Error/2', ...
    'theta feedback rad');
connectNamed(modelName,'Attitude Error/1','Proportional Gain -Kp/1', ...
    'e theta rad');
add_line(modelName,'Attitude Error/1','Integrator Input/1','autorouting','on');
add_line(modelName,'Anti-Windup Feedback/1','Integrator Input/2', ...
    'autorouting','on');
add_line(modelName,'Integrator Input/1','Error Integrator/1','autorouting','on');
add_line(modelName,'Error Integrator/1','Integral Gain -Ki/1','autorouting','on');
add_line(modelName,'Proportional Gain -Kp/1','PI Elevator Command/1', ...
    'autorouting','on');
add_line(modelName,'Integral Gain -Ki/1','PI Elevator Command/2', ...
    'autorouting','on');
add_line(modelName,'q Feedback/1','Pitch-Rate Gain Kq/1','autorouting','on');
add_line(modelName,'PI Elevator Command/1','Unsaturated Total Command/1', ...
    'autorouting','on');
add_line(modelName,'Pitch-Rate Gain Kq/1','Unsaturated Total Command/2', ...
    'autorouting','on');
connectNamed(modelName,'Unsaturated Total Command/1', ...
    'Actuator and Anti-Windup/1','delta e unsaturated rad');
connectNamed(modelName,'Actuator and Anti-Windup/1', ...
    'C172S Longitudinal Plant/1','delta e actual rad');
connectNamed(modelName,'C172S Longitudinal Plant/1','State Demux/1', ...
    'x = [u alpha q theta]');

% Local branches into the signal-tag network.
branchTo(modelName,'Pitch-Attitude Command/1','Command Tag/1');
branchTo(modelName,'Command Filter/1','Filtered Command Tag/1');
branchTo(modelName,'Error Integrator/1','Integrator Tag/1');
branchTo(modelName,'PI Elevator Command/1','PI Command Tag/1');
branchTo(modelName,'Pitch-Rate Gain Kq/1','q Contribution Tag/1');
branchTo(modelName,'Unsaturated Total Command/1','Unsaturated Command Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/2','Anti-Windup Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/3','Position Command Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/1','Actual Elevator Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/4','Elevator Rate Tag/1');
stateTagBlockNames = {'u Tag','alpha Tag','q Tag','theta Tag'};
for k = 1:4
    branchTo(modelName,sprintf('State Demux/%d',k), ...
        [stateTagBlockNames{k} '/1']);
end

%% Diagram note and save

try
    note = Simulink.Annotation(modelName, ...
        ['Pitch-Attitude Hold V2: actuator and anti-windup protection' newline ...
         'Kp = Ki = 0.450; actuator-integrated Kq = 0.120 s' newline ...
         'tau = 0.035 s; rate = 20 deg/s; automatic authority = +/-5 deg' newline ...
         'Actuator parameters are provisional engineering assumptions']);
    note.Position = [35 25 900 105];
catch
end

save_system(modelName,modelFile);
open_system(modelName);
fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runPitchAttitudeActuatorSimulinkCheck to validate V2.\n');

end

function assignModelVariables(data,plant,controller,actuator)
assignin('base','pa2Data',data);
assignin('base','pa2Plant',plant);
assignin('base','pa2Controller',controller);
assignin('base','pa2Actuator',actuator);
assignin('base','A_pa2',plant.A);
assignin('base','B_pa2',plant.B);
assignin('base','C_pa2',plant.C);
assignin('base','D_pa2',plant.D);
assignin('base','Kp_pa2',controller.Kp_radPerRad);
assignin('base','Ki_pa2_per_s',controller.Ki_radPerRadPerS);
assignin('base','Kq_pa2_s',actuator.integration.Kq_s);
assignin('base','tauCommand_pa2_s',controller.commandFilterTimeConstant_s);
assignin('base','tauActuator_pa2_s',actuator.dynamics.timeConstant_s);
assignin('base','Tt_pa2_s',actuator.antiWindup.trackingTimeConstant_s);
assignin('base','deltaELower_pa2_rad',actuator.authority.lowerLimit_rad);
assignin('base','deltaEUpper_pa2_rad',actuator.authority.upperLimit_rad);
assignin('base','deltaERate_pa2_radps', ...
    deg2rad(actuator.dynamics.rateLimit_degps));
assignin('base','thetaCommand_pa2_rad', ...
    deg2rad(actuator.validation.commandStep_deg));
assignin('base','antiWindupEnable_pa2',1.0);
assignin('base','x0_pa2',zeros(4,1));
assignin('base','xi0_pa2',0.0);
assignin('base','deltaE0_pa2',0.0);
end

function buildActuatorSubsystem(path)
clearDefaultSubsystem(path);
add_block('simulink/Sources/In1',[path '/Unsaturated Command'], ...
    'Port','1','Position',[25 70 55 90]);
add_block('simulink/Discontinuities/Saturation',[path '/Position Authority'], ...
    'UpperLimit','deltaEUpper_pa2_rad','LowerLimit','deltaELower_pa2_rad', ...
    'Position',[95 60 145 100]);
add_block('simulink/Math Operations/Sum',[path '/Position Error'], ...
    'Inputs','+-','Position',[185 63 215 97]);
add_block('simulink/Math Operations/Gain',[path '/Raw Rate'], ...
    'Gain','1/tauActuator_pa2_s','Position',[255 60 345 100]);
add_block('simulink/Discontinuities/Saturation',[path '/Rate Limit'], ...
    'UpperLimit','deltaERate_pa2_radps','LowerLimit','-deltaERate_pa2_radps', ...
    'Position',[385 60 435 100]);
add_block('simulink/Continuous/Integrator',[path '/Actual Elevator'], ...
    'InitialCondition','deltaE0_pa2','Position',[485 65 515 95]);
add_block('simulink/Math Operations/Gain',[path '/Reachable Increment'], ...
    'Gain','tauActuator_pa2_s','Position',[385 175 480 205]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Reference'], ...
    'Inputs','++','Position',[535 145 565 185]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Mismatch'], ...
    'Inputs','+-','Position',[615 108 645 142]);
add_block('simulink/Math Operations/Gain',[path '/Back Calculation'], ...
    'Gain','antiWindupEnable_pa2/(Ki_pa2_per_s*Tt_pa2_s)', ...
    'Position',[690 105 835 145]);

add_block('simulink/Sinks/Out1',[path '/Actual'], ...
    'Port','1','Position',[885 65 915 85]);
add_block('simulink/Sinks/Out1',[path '/AW Correction'], ...
    'Port','2','Position',[885 115 915 135]);
add_block('simulink/Sinks/Out1',[path '/Position Command'], ...
    'Port','3','Position',[885 165 915 185]);
add_block('simulink/Sinks/Out1',[path '/Limited Rate'], ...
    'Port','4','Position',[885 215 915 235]);

add_line(path,'Unsaturated Command/1','Position Authority/1','autorouting','on');
add_line(path,'Position Authority/1','Position Error/1','autorouting','on');
add_line(path,'Position Error/1','Raw Rate/1','autorouting','on');
add_line(path,'Raw Rate/1','Rate Limit/1','autorouting','on');
add_line(path,'Rate Limit/1','Actual Elevator/1','autorouting','on');
add_line(path,'Actual Elevator/1','Position Error/2','autorouting','on');
add_line(path,'Rate Limit/1','Reachable Increment/1','autorouting','on');
add_line(path,'Actual Elevator/1','Tracking Reference/1','autorouting','on');
add_line(path,'Reachable Increment/1','Tracking Reference/2','autorouting','on');
add_line(path,'Unsaturated Command/1','Tracking Mismatch/1','autorouting','on');
add_line(path,'Tracking Reference/1','Tracking Mismatch/2','autorouting','on');
add_line(path,'Tracking Mismatch/1','Back Calculation/1','autorouting','on');
add_line(path,'Actual Elevator/1','Actual/1','autorouting','on');
add_line(path,'Back Calculation/1','AW Correction/1','autorouting','on');
add_line(path,'Position Authority/1','Position Command/1','autorouting','on');
add_line(path,'Rate Limit/1','Limited Rate/1','autorouting','on');
end

function buildDisplaySubsystem(path)
tags = {'pa2_command','pa2_filtered','pa2_theta','pa2_unsat', ...
    'pa2_position_command','pa2_actual','pa2_rate','pa2_aw'};
names = {'Command','Filtered Command','Theta','Unsaturated Command', ...
    'Position Command','Actual Elevator','Elevator Rate','AW Correction'};
for k = 1:numel(tags)
    addFrom(path,names{k},tags{k},[25 25+45*(k-1) 145 45+45*(k-1)]);
end
for k = 1:6
    add_block('simulink/Math Operations/Gain', ...
        [path sprintf('/To deg %d',k)],'Gain','180/pi', ...
        'Position',[180 20+45*(k-1) 250 50+45*(k-1)]);
    add_line(path,sprintf('%s/1',names{k}),sprintf('To deg %d/1',k), ...
        'autorouting','on');
end
add_block('simulink/Signal Routing/Mux',[path '/Attitude Mux'], ...
    'Inputs','3','Position',[300 15 305 145]);
add_block('simulink/Sinks/Scope',[path '/Attitude Scope'], ...
    'Position',[365 65 415 95]);
for k = 1:3
    add_line(path,sprintf('To deg %d/1',k),sprintf('Attitude Mux/%d',k), ...
        'autorouting','on');
end
add_line(path,'Attitude Mux/1','Attitude Scope/1','autorouting','on');
add_block('simulink/Signal Routing/Mux',[path '/Elevator Mux'], ...
    'Inputs','3','Position',[300 150 305 280]);
add_block('simulink/Sinks/Scope',[path '/Elevator Scope'], ...
    'Position',[365 200 415 230]);
for k = 4:6
    add_line(path,sprintf('To deg %d/1',k),sprintf('Elevator Mux/%d',k-3), ...
        'autorouting','on');
end
add_line(path,'Elevator Mux/1','Elevator Scope/1','autorouting','on');
add_block('simulink/Math Operations/Gain',[path '/Rate to deg'], ...
    'Gain','180/pi','Position',[180 290 250 320]);
add_block('simulink/Math Operations/Gain',[path '/AW to deg'], ...
    'Gain','180/pi','Position',[180 335 250 365]);
add_block('simulink/Signal Routing/Mux',[path '/Protection Mux'], ...
    'Inputs','2','Position',[300 285 305 370]);
add_block('simulink/Sinks/Scope',[path '/Protection Scope'], ...
    'Position',[365 320 415 350]);
add_line(path,'Elevator Rate/1','Rate to deg/1','autorouting','on');
add_line(path,'AW Correction/1','AW to deg/1','autorouting','on');
add_line(path,'Rate to deg/1','Protection Mux/1','autorouting','on');
add_line(path,'AW to deg/1','Protection Mux/2','autorouting','on');
add_line(path,'Protection Mux/1','Protection Scope/1','autorouting','on');
end

function clearDefaultSubsystem(path)
try
    delete_line(path,'In1/1','Out1/1');
catch
end
if getSimulinkBlockHandle([path '/In1']) ~= -1
    delete_block([path '/In1']);
end
if getSimulinkBlockHandle([path '/Out1']) ~= -1
    delete_block([path '/Out1']);
end
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end