function modelName = buildC172sRollAttitudeHoldSimulink(forceRebuild)
%BUILDC172SROLLATTITUDEHOLDSIMULINK Build protected roll-attitude hold V1.
%
%   MODELNAME = BUILDC172SROLLATTITUDEHOLDSIMULINK() creates or opens
%   C172S_RollAttitudeHold_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SROLLATTITUDEHOLDSIMULINK(true) overwrites only
%   the generated SLX file. Frozen Plant V0.1, Yaw Damper V2 and MATLAB
%   roll-controller/source-audit artifacts are not altered.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_RollAttitudeHold_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize frozen dependencies and selected assumptions

rah1Data = c172sLateralDirectionalData();
[~,rah1Plant] = c172sLateralDirectionalPlant(rah1Data);
rah1YawController = c172sYawDamperData();
rah1RudderActuator = c172sRudderActuatorData();
rah1Controller = c172sRollAttitudeControllerData();
rah1AileronActuator = c172sAileronActuatorData();
assertDependencies(rah1Data,rah1YawController,rah1RudderActuator, ...
    rah1Controller,rah1AileronActuator);
assignModelVariables(rah1Data,rah1Plant,rah1YawController, ...
    rah1RudderActuator,rah1Controller,rah1AileronActuator);

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure executable model

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','40', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Immutable definitions are rebuilt before each run. SimulationInput/base-
% workspace overrides of commands, initial conditions, noise and the
% anti-windup switch are deliberately preserved.
initCode = [ ...
    'rah1Data = c172sLateralDirectionalData();' newline ...
    '[~,rah1Plant] = c172sLateralDirectionalPlant(rah1Data);' newline ...
    'rah1YawController = c172sYawDamperData();' newline ...
    'rah1RudderActuator = c172sRudderActuatorData();' newline ...
    'rah1Controller = c172sRollAttitudeControllerData();' newline ...
    'rah1AileronActuator = c172sAileronActuatorData();' newline ...
    'if ~strcmp(rah1Data.model.version,rah1Controller.requiredPlantVersion), error(''RAH V1 plant dependency mismatch.''); end' newline ...
    'if ~strcmp(rah1YawController.artifactRevision,rah1Controller.requiredYawDamperRevision), error(''RAH V1 yaw-controller dependency mismatch.''); end' newline ...
    'if ~strcmp(rah1RudderActuator.artifactRevision,rah1Controller.requiredRudderAuditRevision), error(''RAH V1 rudder-audit dependency mismatch.''); end' newline ...
    'if ~strcmp(rah1AileronActuator.artifactRevision,rah1Controller.requiredAileronAuditRevision), error(''RAH V1 aileron-audit dependency mismatch.''); end' newline ...
    'A_rah1 = rah1Plant.A; B_rah1 = rah1Plant.B;' newline ...
    'C_rah1 = rah1Plant.C; D_rah1 = rah1Plant.D;' newline ...
    'Kphi_rah1 = rah1Controller.bankProportionalGain;' newline ...
    'Ki_rah1 = rah1Controller.bankIntegralGain_per_s;' newline ...
    'Kp_rah1 = rah1Controller.rollRateGain_s;' newline ...
    'Tcmd_rah1 = rah1Controller.commandFilterTimeConstant_s;' newline ...
    'Kr_rah1 = rah1YawController.rudderGain_s;' newline ...
    'Tw_rah1 = rah1YawController.washoutTimeConstant_s;' newline ...
    'TsRudder_rah1 = rah1RudderActuator.sensor.filterTimeConstant_s;' newline ...
    'tauRudder_rah1 = rah1RudderActuator.dynamics.timeConstant_s;' newline ...
    'TsRoll_rah1 = rah1AileronActuator.sensor.filterTimeConstant_s;' newline ...
    'tauAileron_rah1 = rah1AileronActuator.dynamics.timeConstant_s;' newline ...
    'Tt_rah1 = rah1AileronActuator.antiWindup.trackingTimeConstant_s;' newline ...
    'delaySampleTime_rah1 = rah1AileronActuator.sensor.nominalDelay_s;' newline ...
    'bankCommandLower_rah1_rad = rah1Controller.commandAuthority.lowerLimit_rad;' newline ...
    'bankCommandUpper_rah1_rad = rah1Controller.commandAuthority.upperLimit_rad;' newline ...
    'autoAileronLower_rah1_rad = rah1AileronActuator.authority.lowerLimit_rad;' newline ...
    'autoAileronUpper_rah1_rad = rah1AileronActuator.authority.upperLimit_rad;' newline ...
    'aileronRateLower_rah1_radps = -deg2rad(rah1AileronActuator.dynamics.rateLimit_degps);' newline ...
    'aileronRateUpper_rah1_radps = deg2rad(rah1AileronActuator.dynamics.rateLimit_degps);' newline ...
    'totalAileronLower_rah1_rad = rah1AileronActuator.physicalTravel.lowerLimit_rad;' newline ...
    'totalAileronUpper_rah1_rad = rah1AileronActuator.physicalTravel.upperLimit_rad;' newline ...
    'autoRudderLower_rah1_rad = rah1RudderActuator.authority.lowerLimit_rad;' newline ...
    'autoRudderUpper_rah1_rad = rah1RudderActuator.authority.upperLimit_rad;' newline ...
    'rudderRateLower_rah1_radps = -deg2rad(rah1RudderActuator.dynamics.rateLimit_degps);' newline ...
    'rudderRateUpper_rah1_radps = deg2rad(rah1RudderActuator.dynamics.rateLimit_degps);' newline ...
    'totalRudderLower_rah1_rad = rah1RudderActuator.physicalTravel.lowerLimit_rad;' newline ...
    'totalRudderUpper_rah1_rad = rah1RudderActuator.physicalTravel.upperLimit_rad;' newline ...
    'if ~exist(''bankCommand_rah1_rad'',''var''), bankCommand_rah1_rad = deg2rad(10); end' newline ...
    'if ~exist(''pilotAileronBias_rah1_rad'',''var''), pilotAileronBias_rah1_rad = 0; end' newline ...
    'if ~exist(''pilotAileronPulse_rah1_rad'',''var''), pilotAileronPulse_rah1_rad = 0; end' newline ...
    'if ~exist(''pilotRudderBias_rah1_rad'',''var''), pilotRudderBias_rah1_rad = 0; end' newline ...
    'if ~exist(''pilotRudderPulse_rah1_rad'',''var''), pilotRudderPulse_rah1_rad = 0; end' newline ...
    'if ~exist(''aileronPulseStart_rah1_s'',''var''), aileronPulseStart_rah1_s = 5; end' newline ...
    'if ~exist(''aileronPulseEnd_rah1_s'',''var''), aileronPulseEnd_rah1_s = 6; end' newline ...
    'if ~exist(''rudderPulseStart_rah1_s'',''var''), rudderPulseStart_rah1_s = 5; end' newline ...
    'if ~exist(''rudderPulseEnd_rah1_s'',''var''), rudderPulseEnd_rah1_s = 6; end' newline ...
    'if ~exist(''pNoiseAmplitude_rah1_radps'',''var''), pNoiseAmplitude_rah1_radps = 0; end' newline ...
    'if ~exist(''pNoiseFrequency_rah1_radps'',''var''), pNoiseFrequency_rah1_radps = 50; end' newline ...
    'if ~exist(''phiNoiseAmplitude_rah1_rad'',''var''), phiNoiseAmplitude_rah1_rad = 0; end' newline ...
    'if ~exist(''phiNoiseFrequency_rah1_radps'',''var''), phiNoiseFrequency_rah1_radps = 5; end' newline ...
    'if ~exist(''yawNoiseAmplitude_rah1_radps'',''var''), yawNoiseAmplitude_rah1_radps = 0; end' newline ...
    'if ~exist(''yawNoiseFrequency_rah1_radps'',''var''), yawNoiseFrequency_rah1_radps = 50; end' newline ...
    'if ~exist(''antiWindupEnable_rah1'',''var''), antiWindupEnable_rah1 = 1; end' newline ...
    'if ~exist(''x0_rah1'',''var''), x0_rah1 = zeros(5,1); end' newline ...
    'if ~exist(''rDelay0_rah1_radps'',''var''), rDelay0_rah1_radps = x0_rah1(3); end' newline ...
    'if ~exist(''pDelay0_rah1_radps'',''var''), pDelay0_rah1_radps = x0_rah1(2); end' newline ...
    'if ~exist(''phiDelay0_rah1_rad'',''var''), phiDelay0_rah1_rad = x0_rah1(4); end' newline ...
    'if ~exist(''rSensor0_rah1_radps'',''var''), rSensor0_rah1_radps = 0; end' newline ...
    'if ~exist(''xw0_rah1_radps'',''var''), xw0_rah1_radps = 0; end' newline ...
    'if ~exist(''deltaRAuto0_rah1_rad'',''var''), deltaRAuto0_rah1_rad = 0; end' newline ...
    'if ~exist(''pSensor0_rah1_radps'',''var''), pSensor0_rah1_radps = 0; end' newline ...
    'if ~exist(''phiSensor0_rah1_rad'',''var''), phiSensor0_rah1_rad = 0; end' newline ...
    'if ~exist(''xi0_rah1_rad_s'',''var''), xi0_rah1_rad_s = 0; end' newline ...
    'if ~exist(''deltaAAuto0_rah1_rad'',''var''), deltaAAuto0_rah1_rad = 0; end' newline ...
    'if ~exist(''filteredCommand0_rah1_rad'',''var''), filteredCommand0_rah1_rad = 0; end'];
set_param(modelName,'InitFcn',initCode);

%% Bank command and pilot inputs

add_block('simulink/Sources/Step',[modelName '/Bank Command'], ...
    'Time','0','Before','0','After','bankCommand_rah1_rad', ...
    'SampleTime','0','Position',[35 115 105 145]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Bank Command Limit'], ...
    'LowerLimit','bankCommandLower_rah1_rad', ...
    'UpperLimit','bankCommandUpper_rah1_rad', ...
    'Position',[150 105 275 155]);
add_block('simulink/Continuous/State-Space',[modelName '/Command Filter'], ...
    'A','-1/Tcmd_rah1','B','1/Tcmd_rah1','C','1','D','0', ...
    'X0','filteredCommand0_rah1_rad', ...
    'Position',[320 105 435 155]);

add_block('simulink/Sources/Constant',[modelName '/Aileron Bias'], ...
    'Value','pilotAileronBias_rah1_rad','Position',[35 260 105 290]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse Start'], ...
    'Time','aileronPulseStart_rah1_s','Before','0', ...
    'After','pilotAileronPulse_rah1_rad','SampleTime','0', ...
    'Position',[35 305 105 335]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse End'], ...
    'Time','aileronPulseEnd_rah1_s','Before','0', ...
    'After','-pilotAileronPulse_rah1_rad','SampleTime','0', ...
    'Position',[35 350 105 380]);
add_block('simulink/Math Operations/Sum',[modelName '/Pilot Aileron'], ...
    'Inputs','+++','Position',[155 285 185 355]);

add_block('simulink/Sources/Constant',[modelName '/Rudder Bias'], ...
    'Value','pilotRudderBias_rah1_rad','Position',[35 535 105 565]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse Start'], ...
    'Time','rudderPulseStart_rah1_s','Before','0', ...
    'After','pilotRudderPulse_rah1_rad','SampleTime','0', ...
    'Position',[35 580 105 610]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse End'], ...
    'Time','rudderPulseEnd_rah1_s','Before','0', ...
    'After','-pilotRudderPulse_rah1_rad','SampleTime','0', ...
    'Position',[35 625 105 655]);
add_block('simulink/Math Operations/Sum',[modelName '/Pilot Rudder'], ...
    'Inputs','+++','Position',[155 560 185 630]);

%% Plant and protected controller subsystems

add_block('simulink/Math Operations/Sum',[modelName '/Raw Total Aileron'], ...
    'Inputs','++','Position',[1020 285 1050 335]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Physical Aileron Hard Stop'], ...
    'LowerLimit','totalAileronLower_rah1_rad', ...
    'UpperLimit','totalAileronUpper_rah1_rad', ...
    'Position',[1095 275 1235 345]);
add_block('simulink/Math Operations/Sum',[modelName '/Raw Total Rudder'], ...
    'Inputs','++','Position',[1020 555 1050 605]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Physical Rudder Hard Stop'], ...
    'LowerLimit','totalRudderLower_rah1_rad', ...
    'UpperLimit','totalRudderUpper_rah1_rad', ...
    'Position',[1095 545 1235 615]);
add_block('simulink/Signal Routing/Mux',[modelName '/Control Mux'], ...
    'Inputs','2','Position',[1280 365 1285 515]);
add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Lateral-Directional Plant'], ...
    'A','A_rah1','B','B_rah1','C','C_rah1','D','D_rah1', ...
    'X0','x0_rah1','Position',[1340 400 1545 480]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','5','Position',[1595 330 1600 550]);

rollPath = [modelName '/Protected Roll Controller and Aileron'];
add_block('simulink/Ports & Subsystems/Subsystem',rollPath, ...
    'Position',[555 135 870 380]);
buildRollSubsystem(rollPath);

yawPath = [modelName '/Frozen Protected Yaw Damper V2'];
add_block('simulink/Ports & Subsystems/Subsystem',yawPath, ...
    'Position',[555 500 870 650]);
buildYawSubsystem(yawPath);

%% Executable top-level connections

connectNamed(modelName,'Bank Command/1','Bank Command Limit/1', ...
    'raw bank command');
connectNamed(modelName,'Bank Command Limit/1','Command Filter/1', ...
    'limited bank command');
connectNamed(modelName,'Command Filter/1', ...
    'Protected Roll Controller and Aileron/1','filtered bank command');

add_line(modelName,'Aileron Bias/1','Pilot Aileron/1','autorouting','on');
add_line(modelName,'Aileron Pulse Start/1','Pilot Aileron/2','autorouting','on');
add_line(modelName,'Aileron Pulse End/1','Pilot Aileron/3','autorouting','on');
add_line(modelName,'Rudder Bias/1','Pilot Rudder/1','autorouting','on');
add_line(modelName,'Rudder Pulse Start/1','Pilot Rudder/2','autorouting','on');
add_line(modelName,'Rudder Pulse End/1','Pilot Rudder/3','autorouting','on');

connectNamed(modelName,'Pilot Aileron/1','Raw Total Aileron/1', ...
    'pilot aileron');
connectNamed(modelName,'Protected Roll Controller and Aileron/1', ...
    'Raw Total Aileron/2','automatic aileron');
connectNamed(modelName,'Raw Total Aileron/1','Physical Aileron Hard Stop/1', ...
    'raw total aileron');
connectNamed(modelName,'Physical Aileron Hard Stop/1','Control Mux/1', ...
    'protected total aileron');

connectNamed(modelName,'Pilot Rudder/1','Raw Total Rudder/1', ...
    'pilot rudder');
connectNamed(modelName,'Frozen Protected Yaw Damper V2/1', ...
    'Raw Total Rudder/2','automatic rudder');
connectNamed(modelName,'Raw Total Rudder/1','Physical Rudder Hard Stop/1', ...
    'raw total rudder');
connectNamed(modelName,'Physical Rudder Hard Stop/1','Control Mux/2', ...
    'protected total rudder');

connectNamed(modelName,'Control Mux/1', ...
    'C172S Lateral-Directional Plant/1', ...
    'u = [deltaA total, deltaR total]');
connectNamed(modelName,'C172S Lateral-Directional Plant/1','State Demux/1', ...
    'x = [beta p r phi psi]');
connectNamed(modelName,'State Demux/2', ...
    'Protected Roll Controller and Aileron/2','true roll rate');
connectNamed(modelName,'State Demux/4', ...
    'Protected Roll Controller and Aileron/3','true bank angle');
connectNamed(modelName,'State Demux/3', ...
    'Frozen Protected Yaw Damper V2/1','true yaw rate');

%% Verification signals (fixed order used by independent checker)

signalSources = { ...
    'State Demux/1','rah1_beta','Beta'; ...                         % 1
    'State Demux/2','rah1_p','p'; ...                              % 2
    'State Demux/3','rah1_r','r'; ...                              % 3
    'State Demux/4','rah1_phi','Phi'; ...                           % 4
    'State Demux/5','rah1_psi','Psi'; ...                           % 5
    'Bank Command/1','rah1_command_raw','Bank Command Raw'; ...     % 6
    'Bank Command Limit/1','rah1_command_limited','Bank Command Limited'; ... % 7
    'Command Filter/1','rah1_command_filtered','Bank Command Filtered'; ...   % 8
    'Pilot Aileron/1','rah1_aileron_pilot','Pilot Aileron Signal'; ...         % 9
    'Pilot Rudder/1','rah1_rudder_pilot','Pilot Rudder Signal'; ...            % 10
    'Frozen Protected Yaw Damper V2/2','rah1_r_delayed','Delayed r'; ...       % 11
    'Frozen Protected Yaw Damper V2/3','rah1_r_noise','Yaw Noise'; ...         % 12
    'Frozen Protected Yaw Damper V2/4','rah1_r_input','Yaw Sensor Input'; ...  % 13
    'Frozen Protected Yaw Damper V2/5','rah1_r_sensor','Filtered r'; ...       % 14
    'Frozen Protected Yaw Damper V2/6','rah1_r_washout','Washout r'; ...       % 15
    'Frozen Protected Yaw Damper V2/7','rah1_rudder_raw','Raw Auto Rudder'; ...% 16
    'Frozen Protected Yaw Damper V2/8','rah1_rudder_pos','Rudder Position Command'; ... % 17
    'Frozen Protected Yaw Damper V2/1','rah1_rudder_actual','Actual Auto Rudder'; ...    % 18
    'Frozen Protected Yaw Damper V2/9','rah1_rudder_rate_raw','Raw Rudder Rate'; ...     % 19
    'Frozen Protected Yaw Damper V2/10','rah1_rudder_rate','Limited Rudder Rate'; ...    % 20
    'Raw Total Rudder/1','rah1_rudder_total_raw','Raw Total Rudder Signal'; ...          % 21
    'Physical Rudder Hard Stop/1','rah1_rudder_total','Total Rudder Signal'; ...         % 22
    'Protected Roll Controller and Aileron/2','rah1_p_delayed','Delayed p'; ...          % 23
    'Protected Roll Controller and Aileron/3','rah1_p_noise','Roll-Rate Noise'; ...      % 24
    'Protected Roll Controller and Aileron/4','rah1_p_input','Roll-Rate Sensor Input'; ...% 25
    'Protected Roll Controller and Aileron/5','rah1_p_sensor','Filtered p'; ...           % 26
    'Protected Roll Controller and Aileron/6','rah1_phi_delayed','Delayed Phi'; ...       % 27
    'Protected Roll Controller and Aileron/7','rah1_phi_noise','Bank-Angle Noise'; ...    % 28
    'Protected Roll Controller and Aileron/8','rah1_phi_input','Bank-Angle Sensor Input'; ... % 29
    'Protected Roll Controller and Aileron/9','rah1_phi_sensor','Filtered Phi'; ...       % 30
    'Protected Roll Controller and Aileron/10','rah1_bank_error','Bank Error'; ...        % 31
    'Protected Roll Controller and Aileron/11','rah1_proportional','Proportional Contribution'; ... % 32
    'Protected Roll Controller and Aileron/12','rah1_xi','Integrator State'; ...          % 33
    'Protected Roll Controller and Aileron/13','rah1_integral','Integral Contribution'; ... % 34
    'Protected Roll Controller and Aileron/14','rah1_roll_rate_feedback','Roll-Rate Contribution'; ... % 35
    'Protected Roll Controller and Aileron/15','rah1_aileron_unsat','Unsaturated Aileron'; ... % 36
    'Protected Roll Controller and Aileron/16','rah1_aileron_pos','Aileron Position Command'; ... % 37
    'Protected Roll Controller and Aileron/1','rah1_aileron_actual','Actual Auto Aileron'; ... % 38
    'Protected Roll Controller and Aileron/17','rah1_aileron_rate_raw','Raw Aileron Rate'; ... % 39
    'Protected Roll Controller and Aileron/18','rah1_aileron_rate','Limited Aileron Rate'; ... % 40
    'Protected Roll Controller and Aileron/19','rah1_aileron_track','Tracking Aileron'; ... % 41
    'Protected Roll Controller and Aileron/20','rah1_aw_correction','Anti-Windup Correction'; ... % 42
    'Raw Total Aileron/1','rah1_aileron_total_raw','Raw Total Aileron Signal'; ... % 43
    'Physical Aileron Hard Stop/1','rah1_aileron_total','Total Aileron Signal'}; % 44

for k = 1:size(signalSources,1)
    x = 1660 + 155*mod(k-1,4);
    y = 40 + 31*floor((k-1)/4);
    addGlobalGoto(modelName,[signalSources{k,3} ' Tag'], ...
        signalSources{k,2},[x y x+125 y+18]);
end

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[2310 365 2470 435]);
clearDefaultSubsystem(verificationPath);
for k = 1:size(signalSources,1)
    y = 20 + 29*(k-1);
    addFrom(verificationPath,signalSources{k,3},signalSources{k,2}, ...
        [25 y 175 y+18]);
end
add_block('simulink/Signal Routing/Mux',[verificationPath '/Signal Mux'], ...
    'Inputs',num2str(size(signalSources,1)), ...
    'Position',[240 10 245 1290]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[305 635 335 655]);
for k = 1:size(signalSources,1)
    add_line(verificationPath,[signalSources{k,3} '/1'], ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Protected Closed-Loop Signals'], ...
    'Port','1','Position',[2525 390 2555 410]);
add_line(modelName,'Verification Signals/1', ...
    'Protected Closed-Loop Signals/1','autorouting','on');

for k = 1:size(signalSources,1)
    branchTo(modelName,signalSources{k,1},[signalSources{k,3} ' Tag/1']);
end

%% Traceability, compile and save

try
    note = Simulink.Annotation(modelName,[ ...
        'Roll-Attitude Hold V1 - protected implementation of RAH-V1-MATLAB-R1' newline ...
        'deltaA = 0.300*ePhi + 0.090*integral(ePhi) - 0.075*pSensor' newline ...
        '10-ms pure delays; 20-ms roll/yaw filters; frozen protected Yaw Damper V2' newline ...
        '+/-20-deg bank command; +/-5-deg auto aileron; +/-30-deg/s; +/-14-deg hard stop' newline ...
        'Servo, sensor and automatic-authority values are project assumptions, not identified hardware data']);
    note.Position = [35 20 1320 115];
catch
    % Annotation appearance is not part of executable equivalence.
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runRollAttitudeHoldSimulinkCheck to validate Roll-Attitude Hold V1.\n');

end

function buildRollSubsystem(path)
clearDefaultSubsystem(path);

addInport(path,'Filtered Command',1,[25 50 55 70]);
addInport(path,'True p',2,[25 190 55 210]);
addInport(path,'True Phi',3,[25 510 55 530]);

add_block('simulink/Discrete/Unit Delay',[path '/p Pure Delay'], ...
    'SampleTime','delaySampleTime_rah1', ...
    'InitialCondition','pDelay0_rah1_radps', ...
    'Position',[95 175 190 215]);
add_block('simulink/Sources/Sine Wave',[path '/p Sensor Noise'], ...
    'Amplitude','pNoiseAmplitude_rah1_radps','Bias','0', ...
    'Frequency','pNoiseFrequency_rah1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 255 190 295]);
add_block('simulink/Math Operations/Sum',[path '/p Sensor Input Sum'], ...
    'Inputs','++','Position',[235 190 265 250]);
add_block('simulink/Continuous/State-Space',[path '/p Sensor Filter'], ...
    'A','-1/TsRoll_rah1','B','1/TsRoll_rah1','C','1','D','0', ...
    'X0','pSensor0_rah1_radps','Position',[310 195 420 245]);
add_block('simulink/Math Operations/Gain',[path '/Roll-Rate Gain -Kp'], ...
    'Gain','-Kp_rah1','Position',[470 200 575 240]);

add_block('simulink/Discrete/Unit Delay',[path '/Phi Pure Delay'], ...
    'SampleTime','delaySampleTime_rah1', ...
    'InitialCondition','phiDelay0_rah1_rad', ...
    'Position',[95 495 190 535]);
add_block('simulink/Sources/Sine Wave',[path '/Phi Sensor Noise'], ...
    'Amplitude','phiNoiseAmplitude_rah1_rad','Bias','0', ...
    'Frequency','phiNoiseFrequency_rah1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 575 190 615]);
add_block('simulink/Math Operations/Sum',[path '/Phi Sensor Input Sum'], ...
    'Inputs','++','Position',[235 510 265 570]);
add_block('simulink/Continuous/State-Space',[path '/Phi Sensor Filter'], ...
    'A','-1/TsRoll_rah1','B','1/TsRoll_rah1','C','1','D','0', ...
    'X0','phiSensor0_rah1_rad','Position',[310 515 420 565]);
add_block('simulink/Math Operations/Sum',[path '/Bank Error'], ...
    'Inputs','+-','Position',[470 45 500 85]);
add_block('simulink/Math Operations/Gain',[path '/Bank Proportional Gain Kphi'], ...
    'Gain','Kphi_rah1','Position',[550 40 655 80]);

add_block('simulink/Math Operations/Sum',[path '/Integrator Input'], ...
    'Inputs','++','Position',[550 455 580 505]);
add_block('simulink/Continuous/Integrator',[path '/Error Integrator'], ...
    'InitialCondition','xi0_rah1_rad_s','Position',[625 460 655 500]);
add_block('simulink/Math Operations/Gain',[path '/Bank Integral Gain Ki'], ...
    'Gain','Ki_rah1','Position',[705 460 795 500]);

add_block('simulink/Math Operations/Sum',[path '/Unsaturated Aileron Command'], ...
    'Inputs','+++','Position',[845 185 875 265]);
add_block('simulink/Discontinuities/Saturation', ...
    [path '/Automatic Aileron Position Limit'], ...
    'LowerLimit','autoAileronLower_rah1_rad', ...
    'UpperLimit','autoAileronUpper_rah1_rad', ...
    'Position',[925 195 1065 255]);
add_block('simulink/Math Operations/Sum',[path '/Aileron Servo Position Error'], ...
    'Inputs','+-','Position',[1115 200 1145 250]);
add_block('simulink/Math Operations/Gain',[path '/Aileron Servo Inverse Tau'], ...
    'Gain','1/tauAileron_rah1','Position',[1190 205 1295 245]);
add_block('simulink/Discontinuities/Saturation',[path '/Aileron Servo Rate Limit'], ...
    'LowerLimit','aileronRateLower_rah1_radps', ...
    'UpperLimit','aileronRateUpper_rah1_radps', ...
    'Position',[1340 195 1470 255]);
add_block('simulink/Continuous/Integrator',[path '/Automatic Aileron Actuator'], ...
    'InitialCondition','deltaAAuto0_rah1_rad', ...
    'Position',[1520 205 1550 245]);

% Rate-aware tracking value: deltaATrack = deltaAActual + tauA*limitedRate.
add_block('simulink/Math Operations/Gain',[path '/Limited Rate Times Tau'], ...
    'Gain','tauAileron_rah1','Position',[1345 370 1470 410]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Aileron'], ...
    'Inputs','++','Position',[1520 355 1550 415]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Error'], ...
    'Inputs','+-','Position',[1115 455 1145 505]);
add_block('simulink/Math Operations/Gain',[path '/Anti-Windup Scale'], ...
    'Gain','1/(Ki_rah1*Tt_rah1)','Position',[1190 460 1325 500]);
add_block('simulink/Math Operations/Gain',[path '/Anti-Windup Enable'], ...
    'Gain','antiWindupEnable_rah1','Position',[1370 460 1490 500]);

add_line(path,'True p/1','p Pure Delay/1','autorouting','on');
add_line(path,'p Pure Delay/1','p Sensor Input Sum/1','autorouting','on');
add_line(path,'p Sensor Noise/1','p Sensor Input Sum/2','autorouting','on');
add_line(path,'p Sensor Input Sum/1','p Sensor Filter/1','autorouting','on');
add_line(path,'p Sensor Filter/1','Roll-Rate Gain -Kp/1','autorouting','on');

add_line(path,'True Phi/1','Phi Pure Delay/1','autorouting','on');
add_line(path,'Phi Pure Delay/1','Phi Sensor Input Sum/1','autorouting','on');
add_line(path,'Phi Sensor Noise/1','Phi Sensor Input Sum/2','autorouting','on');
add_line(path,'Phi Sensor Input Sum/1','Phi Sensor Filter/1','autorouting','on');
add_line(path,'Filtered Command/1','Bank Error/1','autorouting','on');
add_line(path,'Phi Sensor Filter/1','Bank Error/2','autorouting','on');
add_line(path,'Bank Error/1','Bank Proportional Gain Kphi/1','autorouting','on');
add_line(path,'Bank Error/1','Integrator Input/1','autorouting','on');
add_line(path,'Integrator Input/1','Error Integrator/1','autorouting','on');
add_line(path,'Error Integrator/1','Bank Integral Gain Ki/1','autorouting','on');

add_line(path,'Bank Proportional Gain Kphi/1', ...
    'Unsaturated Aileron Command/1','autorouting','on');
add_line(path,'Bank Integral Gain Ki/1', ...
    'Unsaturated Aileron Command/2','autorouting','on');
add_line(path,'Roll-Rate Gain -Kp/1', ...
    'Unsaturated Aileron Command/3','autorouting','on');
add_line(path,'Unsaturated Aileron Command/1', ...
    'Automatic Aileron Position Limit/1','autorouting','on');
add_line(path,'Automatic Aileron Position Limit/1', ...
    'Aileron Servo Position Error/1','autorouting','on');
add_line(path,'Automatic Aileron Actuator/1', ...
    'Aileron Servo Position Error/2','autorouting','on');
add_line(path,'Aileron Servo Position Error/1', ...
    'Aileron Servo Inverse Tau/1','autorouting','on');
add_line(path,'Aileron Servo Inverse Tau/1', ...
    'Aileron Servo Rate Limit/1','autorouting','on');
add_line(path,'Aileron Servo Rate Limit/1', ...
    'Automatic Aileron Actuator/1','autorouting','on');

add_line(path,'Aileron Servo Rate Limit/1', ...
    'Limited Rate Times Tau/1','autorouting','on');
add_line(path,'Automatic Aileron Actuator/1', ...
    'Tracking Aileron/1','autorouting','on');
add_line(path,'Limited Rate Times Tau/1','Tracking Aileron/2','autorouting','on');
add_line(path,'Tracking Aileron/1','Tracking Error/1','autorouting','on');
add_line(path,'Unsaturated Aileron Command/1', ...
    'Tracking Error/2','autorouting','on');
add_line(path,'Tracking Error/1','Anti-Windup Scale/1','autorouting','on');
add_line(path,'Anti-Windup Scale/1','Anti-Windup Enable/1','autorouting','on');
add_line(path,'Anti-Windup Enable/1','Integrator Input/2','autorouting','on');

rollOutputs = { ...
    'Automatic Aileron Actuator/1','Automatic Aileron'; ...
    'p Pure Delay/1','Delayed p'; ...
    'p Sensor Noise/1','p Noise'; ...
    'p Sensor Input Sum/1','p Sensor Input'; ...
    'p Sensor Filter/1','Filtered p'; ...
    'Phi Pure Delay/1','Delayed Phi'; ...
    'Phi Sensor Noise/1','Phi Noise'; ...
    'Phi Sensor Input Sum/1','Phi Sensor Input'; ...
    'Phi Sensor Filter/1','Filtered Phi'; ...
    'Bank Error/1','Bank Error Signal'; ...
    'Bank Proportional Gain Kphi/1','Proportional Contribution'; ...
    'Error Integrator/1','Integrator State Signal'; ...
    'Bank Integral Gain Ki/1','Integral Contribution'; ...
    'Roll-Rate Gain -Kp/1','Roll-Rate Contribution'; ...
    'Unsaturated Aileron Command/1','Unsaturated Aileron'; ...
    'Automatic Aileron Position Limit/1','Aileron Position Command'; ...
    'Aileron Servo Inverse Tau/1','Raw Aileron Rate'; ...
    'Aileron Servo Rate Limit/1','Limited Aileron Rate'; ...
    'Tracking Aileron/1','Tracking Aileron Signal'; ...
    'Anti-Windup Enable/1','Anti-Windup Correction'};
for k = 1:size(rollOutputs,1)
    y = 35 + 38*(k-1);
    addOutport(path,rollOutputs{k,2},k,[1640 y 1670 y+20]);
    add_line(path,rollOutputs{k,1},[rollOutputs{k,2} '/1'], ...
        'autorouting','on');
end
end

function buildYawSubsystem(path)
clearDefaultSubsystem(path);
addInport(path,'True r',1,[25 150 55 170]);
add_block('simulink/Discrete/Unit Delay',[path '/r Pure Delay'], ...
    'SampleTime','delaySampleTime_rah1', ...
    'InitialCondition','rDelay0_rah1_radps', ...
    'Position',[95 135 190 175]);
add_block('simulink/Sources/Sine Wave',[path '/Yaw Sensor Noise'], ...
    'Amplitude','yawNoiseAmplitude_rah1_radps','Bias','0', ...
    'Frequency','yawNoiseFrequency_rah1_radps','Phase','0','SampleTime','0', ...
    'Position',[95 225 190 265]);
add_block('simulink/Math Operations/Sum',[path '/Yaw Sensor Input Sum'], ...
    'Inputs','++','Position',[235 150 265 210]);
add_block('simulink/Continuous/State-Space',[path '/Yaw-Rate Sensor Filter'], ...
    'A','-1/TsRudder_rah1','B','1/TsRudder_rah1','C','1','D','0', ...
    'X0','rSensor0_rah1_radps','Position',[315 155 430 205]);
add_block('simulink/Continuous/State-Space',[path '/Yaw-Rate Washout'], ...
    'A','-1/Tw_rah1','B','1/Tw_rah1','C','-1','D','1', ...
    'X0','xw0_rah1_radps','Position',[480 155 595 205]);
add_block('simulink/Math Operations/Gain',[path '/Automatic Rudder Gain'], ...
    'Gain','-Kr_rah1','Position',[645 160 745 200]);
add_block('simulink/Discontinuities/Saturation', ...
    [path '/Automatic Rudder Position Limit'], ...
    'LowerLimit','autoRudderLower_rah1_rad', ...
    'UpperLimit','autoRudderUpper_rah1_rad', ...
    'Position',[795 150 930 210]);
add_block('simulink/Math Operations/Sum',[path '/Rudder Servo Position Error'], ...
    'Inputs','+-','Position',[980 155 1010 205]);
add_block('simulink/Math Operations/Gain',[path '/Rudder Servo Inverse Tau'], ...
    'Gain','1/tauRudder_rah1','Position',[1060 160 1170 200]);
add_block('simulink/Discontinuities/Saturation',[path '/Rudder Servo Rate Limit'], ...
    'LowerLimit','rudderRateLower_rah1_radps', ...
    'UpperLimit','rudderRateUpper_rah1_radps', ...
    'Position',[1220 150 1350 210]);
add_block('simulink/Continuous/Integrator',[path '/Automatic Rudder Actuator'], ...
    'InitialCondition','deltaRAuto0_rah1_rad', ...
    'Position',[1400 160 1430 200]);

add_line(path,'True r/1','r Pure Delay/1','autorouting','on');
add_line(path,'r Pure Delay/1','Yaw Sensor Input Sum/1','autorouting','on');
add_line(path,'Yaw Sensor Noise/1','Yaw Sensor Input Sum/2','autorouting','on');
add_line(path,'Yaw Sensor Input Sum/1','Yaw-Rate Sensor Filter/1','autorouting','on');
add_line(path,'Yaw-Rate Sensor Filter/1','Yaw-Rate Washout/1','autorouting','on');
add_line(path,'Yaw-Rate Washout/1','Automatic Rudder Gain/1','autorouting','on');
add_line(path,'Automatic Rudder Gain/1', ...
    'Automatic Rudder Position Limit/1','autorouting','on');
add_line(path,'Automatic Rudder Position Limit/1', ...
    'Rudder Servo Position Error/1','autorouting','on');
add_line(path,'Automatic Rudder Actuator/1', ...
    'Rudder Servo Position Error/2','autorouting','on');
add_line(path,'Rudder Servo Position Error/1', ...
    'Rudder Servo Inverse Tau/1','autorouting','on');
add_line(path,'Rudder Servo Inverse Tau/1', ...
    'Rudder Servo Rate Limit/1','autorouting','on');
add_line(path,'Rudder Servo Rate Limit/1', ...
    'Automatic Rudder Actuator/1','autorouting','on');

yawOutputs = { ...
    'Automatic Rudder Actuator/1','Automatic Rudder'; ...
    'r Pure Delay/1','Delayed r'; ...
    'Yaw Sensor Noise/1','Yaw Noise'; ...
    'Yaw Sensor Input Sum/1','Yaw Sensor Input'; ...
    'Yaw-Rate Sensor Filter/1','Filtered r'; ...
    'Yaw-Rate Washout/1','Washout r'; ...
    'Automatic Rudder Gain/1','Raw Automatic Rudder'; ...
    'Automatic Rudder Position Limit/1','Rudder Position Command'; ...
    'Rudder Servo Inverse Tau/1','Raw Rudder Rate'; ...
    'Rudder Servo Rate Limit/1','Limited Rudder Rate'};
for k = 1:size(yawOutputs,1)
    y = 35 + 40*(k-1);
    addOutport(path,yawOutputs{k,2},k,[1520 y 1550 y+20]);
    add_line(path,yawOutputs{k,1},[yawOutputs{k,2} '/1'], ...
        'autorouting','on');
end
end

function assertDependencies(data,yawController,rudder,controller,aileron)
assert(strcmp(data.model.version,controller.requiredPlantVersion), ...
    'Roll-Attitude Hold V1 plant dependency mismatch.');
assert(strcmp(yawController.artifactRevision, ...
    controller.requiredYawDamperRevision), ...
    'Roll-Attitude Hold V1 yaw-controller dependency mismatch.');
assert(strcmp(rudder.artifactRevision, ...
    controller.requiredRudderAuditRevision), ...
    'Roll-Attitude Hold V1 rudder-audit dependency mismatch.');
assert(strcmp(aileron.artifactRevision, ...
    controller.requiredAileronAuditRevision), ...
    'Roll-Attitude Hold V1 aileron-audit dependency mismatch.');
assert(abs(aileron.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms roll delay.');
assert(abs(rudder.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms yaw delay.');
end

function assignModelVariables(data,plant,yawController,rudder,controller,aileron)
assignin('base','rah1Data',data);
assignin('base','rah1Plant',plant);
assignin('base','rah1YawController',yawController);
assignin('base','rah1RudderActuator',rudder);
assignin('base','rah1Controller',controller);
assignin('base','rah1AileronActuator',aileron);
assignin('base','A_rah1',plant.A);
assignin('base','B_rah1',plant.B);
assignin('base','C_rah1',plant.C);
assignin('base','D_rah1',plant.D);
assignin('base','Kphi_rah1',controller.bankProportionalGain);
assignin('base','Ki_rah1',controller.bankIntegralGain_per_s);
assignin('base','Kp_rah1',controller.rollRateGain_s);
assignin('base','Tcmd_rah1',controller.commandFilterTimeConstant_s);
assignin('base','Kr_rah1',yawController.rudderGain_s);
assignin('base','Tw_rah1',yawController.washoutTimeConstant_s);
assignin('base','TsRudder_rah1',rudder.sensor.filterTimeConstant_s);
assignin('base','tauRudder_rah1',rudder.dynamics.timeConstant_s);
assignin('base','TsRoll_rah1',aileron.sensor.filterTimeConstant_s);
assignin('base','tauAileron_rah1',aileron.dynamics.timeConstant_s);
assignin('base','Tt_rah1',aileron.antiWindup.trackingTimeConstant_s);
assignin('base','delaySampleTime_rah1',aileron.sensor.nominalDelay_s);
assignin('base','bankCommandLower_rah1_rad', ...
    controller.commandAuthority.lowerLimit_rad);
assignin('base','bankCommandUpper_rah1_rad', ...
    controller.commandAuthority.upperLimit_rad);
assignin('base','autoAileronLower_rah1_rad',aileron.authority.lowerLimit_rad);
assignin('base','autoAileronUpper_rah1_rad',aileron.authority.upperLimit_rad);
assignin('base','aileronRateLower_rah1_radps', ...
    -deg2rad(aileron.dynamics.rateLimit_degps));
assignin('base','aileronRateUpper_rah1_radps', ...
    deg2rad(aileron.dynamics.rateLimit_degps));
assignin('base','totalAileronLower_rah1_rad', ...
    aileron.physicalTravel.lowerLimit_rad);
assignin('base','totalAileronUpper_rah1_rad', ...
    aileron.physicalTravel.upperLimit_rad);
assignin('base','autoRudderLower_rah1_rad',rudder.authority.lowerLimit_rad);
assignin('base','autoRudderUpper_rah1_rad',rudder.authority.upperLimit_rad);
assignin('base','rudderRateLower_rah1_radps', ...
    -deg2rad(rudder.dynamics.rateLimit_degps));
assignin('base','rudderRateUpper_rah1_radps', ...
    deg2rad(rudder.dynamics.rateLimit_degps));
assignin('base','totalRudderLower_rah1_rad', ...
    rudder.physicalTravel.lowerLimit_rad);
assignin('base','totalRudderUpper_rah1_rad', ...
    rudder.physicalTravel.upperLimit_rad);

assignin('base','bankCommand_rah1_rad',deg2rad(10));
assignin('base','pilotAileronBias_rah1_rad',0.0);
assignin('base','pilotAileronPulse_rah1_rad',0.0);
assignin('base','pilotRudderBias_rah1_rad',0.0);
assignin('base','pilotRudderPulse_rah1_rad',0.0);
assignin('base','aileronPulseStart_rah1_s',5.0);
assignin('base','aileronPulseEnd_rah1_s',6.0);
assignin('base','rudderPulseStart_rah1_s',5.0);
assignin('base','rudderPulseEnd_rah1_s',6.0);
assignin('base','pNoiseAmplitude_rah1_radps',0.0);
assignin('base','pNoiseFrequency_rah1_radps',50.0);
assignin('base','phiNoiseAmplitude_rah1_rad',0.0);
assignin('base','phiNoiseFrequency_rah1_radps',5.0);
assignin('base','yawNoiseAmplitude_rah1_radps',0.0);
assignin('base','yawNoiseFrequency_rah1_radps',50.0);
assignin('base','antiWindupEnable_rah1',1.0);
assignin('base','x0_rah1',zeros(5,1));
assignin('base','rDelay0_rah1_radps',0.0);
assignin('base','pDelay0_rah1_radps',0.0);
assignin('base','phiDelay0_rah1_rad',0.0);
assignin('base','rSensor0_rah1_radps',0.0);
assignin('base','xw0_rah1_radps',0.0);
assignin('base','deltaRAuto0_rah1_rad',0.0);
assignin('base','pSensor0_rah1_radps',0.0);
assignin('base','phiSensor0_rah1_rad',0.0);
assignin('base','xi0_rah1_rad_s',0.0);
assignin('base','deltaAAuto0_rah1_rad',0.0);
assignin('base','filteredCommand0_rah1_rad',0.0);
end

function clearDefaultSubsystem(path)
lines = find_system(path,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(path,'SearchDepth',1,'Type','Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end
end

function addInport(systemName,blockName,port,position)
add_block('simulink/Ports & Subsystems/In1',[systemName '/' blockName], ...
    'Port',num2str(port),'Position',position);
end

function addOutport(systemName,blockName,port,position)
add_block('simulink/Ports & Subsystems/Out1',[systemName '/' blockName], ...
    'Port',num2str(port),'Position',position);
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end
