function modelName = buildC172sAutopilotModeManagerSimulink(forceRebuild)
%BUILDC172SAUTOPILOTMODEMANAGERSIMULINK Build executable Mode Manager V1.
%
%   MODELNAME = BUILDC172SAUTOPILOTMODEMANAGERSIMULINK() creates or opens
%   C172S_AutopilotModeManager_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SAUTOPILOTMODEMANAGERSIMULINK(true) overwrites
%   only the generated SLX file. Every frozen plant and controller artifact
%   remains unchanged.
%
%   This model is the independently coded executable supervisor boundary.
%   It does not yet combine the separate longitudinal and lateral plants.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_AutopilotModeManager_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

manager = c172sAutopilotModeManagerData();
assertFrozenDependencies(manager);
assignin('base','amm1Manager',manager);
assignin('base','amm1InputSignal',defaultInputSignal(manager));

if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

try
    load_system('simulink');
catch ME
    error('buildC172sAutopilotModeManagerSimulink:SimulinkUnavailable', ...
        'Unable to load Simulink. MATLAB reported:\n%s',ME.message);
end

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','3', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

initCode = [ ...
    'amm1Manager = c172sAutopilotModeManagerData();' newline ...
    'if ~strcmp(amm1Manager.artifactRevision,''AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1''), error(''Mode Manager V1 artifact mismatch.''); end' newline ...
    'if ~exist(''amm1InputSignal'',''var''), error(''amm1InputSignal is required.''); end'];
set_param(modelName,'InitFcn',initCode);

%% Input schedule and independent executable state machine

add_block('simulink/Sources/From Workspace', ...
    [modelName '/Timed Supervisor Inputs'], ...
    'VariableName','amm1InputSignal', ...
    'Interpolate','off', ...
    'OutputAfterFinalValue','Holding final value', ...
    'SampleTime','0.01', ...
    'Position',[80 205 245 245]);

add_block('simulink/Signal Routing/Demux', ...
    [modelName '/Input Demux'], ...
    'Outputs','19', ...
    'Position',[300 55 305 570]);

managerPath = [modelName '/Independent Executable Mode Manager'];
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    managerPath,'Position',[440 145 780 475]);

root = sfroot;
chart = root.find('-isa','Stateflow.EMChart','Path',managerPath);
assert(~isempty(chart), ...
    'Unable to locate the generated MATLAB Function chart.');
chart.Script = executableSupervisorCode(manager);

% Updating after assigning the chart code materializes its 19 input and
% 20 output ports before the connecting lines are added.
set_param(modelName,'SimulationCommand','update');

add_block('simulink/Signal Routing/Mux', ...
    [modelName '/Output Mux'], ...
    'Inputs','20', ...
    'Position',[880 55 885 600]);
add_block('simulink/Sinks/Out1',[modelName '/Supervisor Signals'], ...
    'Port','1','Position',[965 305 995 325]);

for k = 1:19
    add_line(modelName,sprintf('Input Demux/%d',k), ...
        sprintf('Independent Executable Mode Manager/%d',k), ...
        'autorouting','on');
end
for k = 1:20
    add_line(modelName, ...
        sprintf('Independent Executable Mode Manager/%d',k), ...
        sprintf('Output Mux/%d',k),'autorouting','on');
end
add_line(modelName,'Timed Supervisor Inputs/1','Input Demux/1', ...
    'autorouting','on');
add_line(modelName,'Output Mux/1','Supervisor Signals/1', ...
    'autorouting','on');

%% Auditable signal-order annotations

inputText = sprintf([ ...
    'INPUT VECTOR (19)\n' ...
    '1 engage  2 disconnect  3 pilot override  4 trim stable\n' ...
    '5 core valid  6 heading valid  7 altitude valid\n' ...
    '8 aileron saturated  9 elevator saturated\n' ...
    '10 lateral request  11 vertical request\n' ...
    '12 update heading  13 update altitude\n' ...
    '14 bank deg  15 pitch deg  16 heading deg  17 altitude ft\n' ...
    '18 selected heading deg  19 selected altitude ft']);

outputText = sprintf([ ...
    'OUTPUT VECTOR (20)\n' ...
    '1 engaged  2 lateral mode  3 vertical mode\n' ...
    '4 ROLL enable  5 HEADING enable  6 PITCH enable  7 ALTITUDE enable\n' ...
    '8 bank cmd deg  9 pitch cmd deg  10 heading cmd deg  11 altitude cmd ft\n' ...
    '12 roll track  13 pitch track  14 disconnect tone  15 event code\n' ...
    '16 core-invalid timer  17 heading-invalid timer  18 altitude-invalid timer\n' ...
    '19 aileron-saturation timer  20 elevator-saturation timer']);

qualification = sprintf([ ...
    'Autopilot Mode Manager V1 - executable supervisor implementation\n' ...
    'Independent embedded logic; does not call the MATLAB reference step\n' ...
    '10-ms discrete execution; exact project timers and mode/event codes\n' ...
    'Phase qualification: supervisory equivalence only, not coupled 6-DOF dynamics']);

try
    note = Simulink.Annotation(modelName,qualification);
    note.Position = [50 15 1050 80];
    note = Simulink.Annotation(modelName,inputText);
    note.Position = [50 610 760 705];
    note = Simulink.Annotation(modelName,outputText);
    note.Position = [800 610 1510 705];
catch
    % Annotation appearance is not part of executable equivalence.
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf(['Run runAutopilotModeManagerSimulinkCheck to validate ', ...
    'Autopilot Mode Manager V1.\n']);
end

function signal = defaultInputSignal(manager)
row = zeros(1,19);
row(4:7) = 1.0;
row(10) = double(manager.codes.lateral.OFF);
row(11) = double(manager.codes.vertical.OFF);
row(17) = 4000.0;
row(19) = 4000.0;
signal = [0.0 row; 1.0 row];
end

function code = executableSupervisorCode(manager)
% This source is intentionally independent of
% c172sAutopilotModeManagerStep. Configuration values are injected from
% the audited ledger when the generated model is built.
lines = { ...
    'function [engaged,lateralMode,verticalMode,rollEnable,headingEnable,pitchEnable,altitudeEnable,bankCommand_deg,pitchCommand_deg,headingCommand_deg,altitudeCommand_ft,rollTrack,pitchTrack,disconnectTone,eventCode,coreTimer_s,headingTimer_s,altitudeTimer_s,aileronSatTimer_s,elevatorSatTimer_s] = supervisor(engageRequest,disconnectRequest,pilotOverride,trimStable,coreValid,headingValid,altitudeValid,aileronSaturated,elevatorSaturated,lateralRequest,verticalRequest,updateHeading,updateAltitude,bank_deg,pitch_deg,heading_deg,altitude_ft,selectedHeading_deg,selectedAltitude_ft)'; ...
    '%#codegen'; ...
    'persistent ap lat vert bankRef pitchRef headingRef altitudeRef'; ...
    'persistent coreTimer headingTimer altitudeTimer aileronTimer elevatorTimer'; ...
    'if isempty(ap)'; ...
    '    ap = false; lat = 0; vert = 0;'; ...
    '    bankRef = captureBank(bank_deg); pitchRef = capturePitch(pitch_deg);'; ...
    '    headingRef = normalizeHeading(heading_deg); altitudeRef = altitude_ft;'; ...
    '    coreTimer = 0.0; headingTimer = 0.0; altitudeTimer = 0.0;'; ...
    '    aileronTimer = 0.0; elevatorTimer = 0.0;'; ...
    'end'; ...
    'dt = 0.01;'; ...
    'eventCode = 0; rollTrack = 0; pitchTrack = 0; disconnectTone = 0;'; ...
    'wasEngaged = ap;'; ...
    'coreTimer = timerUpdate(coreValid < 0.5,coreTimer,dt);'; ...
    'headingTimer = timerUpdate(headingValid < 0.5,headingTimer,dt);'; ...
    'altitudeTimer = timerUpdate(altitudeValid < 0.5,altitudeTimer,dt);'; ...
    'aileronTimer = timerUpdate(aileronSaturated > 0.5,aileronTimer,dt);'; ...
    'elevatorTimer = timerUpdate(elevatorSaturated > 0.5,elevatorTimer,dt);'; ...
    'if ap'; ...
    '    if disconnectRequest > 0.5'; ...
    '        ap = false; lat = 0; vert = 0; eventCode = 7; disconnectTone = 1;'; ...
    '    elseif pilotOverride > 0.5'; ...
    '        ap = false; lat = 0; vert = 0; eventCode = 8; disconnectTone = 1;'; ...
    sprintf('    elseif abs(bank_deg) > %.17g || abs(pitch_deg) > %.17g', ...
        manager.protection.maximumAbsoluteBank_deg, ...
        manager.protection.maximumAbsolutePitch_deg); ...
    '        ap = false; lat = 0; vert = 0; eventCode = 11; disconnectTone = 1;'; ...
    sprintf('    elseif coreTimer + 1.0e-12 >= %.17g', ...
        manager.protection.coreSensorDisconnectDelay_s); ...
    '        ap = false; lat = 0; vert = 0; eventCode = 9; disconnectTone = 1;'; ...
    sprintf('    elseif max(aileronTimer,elevatorTimer) + 1.0e-12 >= %.17g', ...
        manager.protection.sustainedSaturationDisconnectDelay_s); ...
    '        ap = false; lat = 0; vert = 0; eventCode = 10; disconnectTone = 1;'; ...
    '    end'; ...
    'end'; ...
    'if ~ap'; ...
    '    if ~wasEngaged && engageRequest > 0.5'; ...
    '        permitted = trimStable > 0.5 && coreValid > 0.5 && pilotOverride < 0.5 && aileronSaturated < 0.5 && elevatorSaturated < 0.5;'; ...
    '        if lateralRequest == 2, permitted = permitted && headingValid > 0.5; end'; ...
    '        if verticalRequest == 2, permitted = permitted && altitudeValid > 0.5; end'; ...
    '        if permitted'; ...
    '            ap = true; eventCode = 1; rollTrack = 1; pitchTrack = 1;'; ...
    '            if lateralRequest == 2'; ...
    '                lat = 2; headingRef = normalizeHeading(selectedHeading_deg);'; ...
    '            else'; ...
    '                lat = 1; bankRef = captureBank(bank_deg);'; ...
    '            end'; ...
    '            if verticalRequest == 2'; ...
    '                vert = 2; altitudeRef = selectedAltitude_ft;'; ...
    '            else'; ...
    '                vert = 1; pitchRef = capturePitch(pitch_deg);'; ...
    '            end'; ...
    '        else'; ...
    '            eventCode = 4;'; ...
    '        end'; ...
    '    end'; ...
    'else'; ...
    sprintf('    if lat == 2 && headingTimer + 1.0e-12 >= %.17g', ...
        manager.protection.outerSensorFallbackDelay_s); ...
    '        lat = 1; bankRef = captureBank(bank_deg); rollTrack = 1; eventCode = 5;'; ...
    '    end'; ...
    sprintf('    if vert == 2 && altitudeTimer + 1.0e-12 >= %.17g', ...
        manager.protection.outerSensorFallbackDelay_s); ...
    '        vert = 1; pitchRef = capturePitch(pitch_deg); pitchTrack = 1; eventCode = 6;'; ...
    '    end'; ...
    '    if lateralRequest ~= 0'; ...
    '        if lateralRequest == 1'; ...
    '            lat = 1; bankRef = captureBank(bank_deg); rollTrack = 1; eventCode = 2;'; ...
    '        elseif lateralRequest == 2 && headingValid > 0.5'; ...
    '            lat = 2; headingRef = normalizeHeading(selectedHeading_deg); rollTrack = 1; eventCode = 2;'; ...
    '        else'; ...
    '            eventCode = 3;'; ...
    '        end'; ...
    '    end'; ...
    '    if verticalRequest ~= 0'; ...
    '        if verticalRequest == 1'; ...
    '            vert = 1; pitchRef = capturePitch(pitch_deg); pitchTrack = 1; eventCode = 2;'; ...
    '        elseif verticalRequest == 2 && altitudeValid > 0.5'; ...
    '            vert = 2; altitudeRef = selectedAltitude_ft; pitchTrack = 1; eventCode = 2;'; ...
    '        else'; ...
    '            eventCode = 3;'; ...
    '        end'; ...
    '    end'; ...
    '    if lat == 2 && updateHeading > 0.5 && headingValid > 0.5'; ...
    '        headingRef = normalizeHeading(selectedHeading_deg);'; ...
    '    end'; ...
    '    if vert == 2 && updateAltitude > 0.5 && altitudeValid > 0.5'; ...
    '        altitudeRef = selectedAltitude_ft;'; ...
    '    end'; ...
    'end'; ...
    'engaged = double(ap); lateralMode = lat; verticalMode = vert;'; ...
    'rollEnable = double(ap && lat == 1); headingEnable = double(ap && lat == 2);'; ...
    'pitchEnable = double(ap && vert == 1); altitudeEnable = double(ap && vert == 2);'; ...
    'bankCommand_deg = 0.0; pitchCommand_deg = 0.0;'; ...
    'if ap && lat == 1, bankCommand_deg = bankRef; end'; ...
    'if ap && vert == 1, pitchCommand_deg = pitchRef; end'; ...
    'headingCommand_deg = headingRef; altitudeCommand_ft = altitudeRef;'; ...
    'coreTimer_s = coreTimer; headingTimer_s = headingTimer; altitudeTimer_s = altitudeTimer;'; ...
    'aileronSatTimer_s = aileronTimer; elevatorSatTimer_s = elevatorTimer;'; ...
    'end'; ...
    'function value = captureBank(value)'; ...
    sprintf('if abs(value) < %.17g', ...
        manager.capture.rollWingsLevelThreshold_deg); ...
    '    value = 0.0;'; ...
    'else'; ...
    sprintf('    value = min(max(value,-%.17g),%.17g);', ...
        manager.capture.bankCommandLimit_deg, ...
        manager.capture.bankCommandLimit_deg); ...
    'end'; ...
    'end'; ...
    'function value = capturePitch(value)'; ...
    sprintf('value = min(max(value,-%.17g),%.17g);', ...
        manager.capture.pitchCommandLimit_deg, ...
        manager.capture.pitchCommandLimit_deg); ...
    'end'; ...
    'function value = normalizeHeading(value)'; ...
    'value = mod(value,360.0);'; ...
    'if value < 0.0, value = value + 360.0; end'; ...
    'end'; ...
    'function timer = timerUpdate(condition,timer,dt)'; ...
    'if condition, timer = timer + dt; else, timer = 0.0; end'; ...
    'end'};
code = strjoin(lines,newline);
end

function assertFrozenDependencies(manager)
longitudinal = c172sLongitudinalData();
pitchRate = c172sPitchRateDamperData();
pitchAttitude = c172sPitchAttitudeControllerData();
elevator = c172sElevatorActuatorData();
altitude = c172sAltitudeHoldControllerData();
lateral = c172sLateralDirectionalData();
yaw = c172sYawDamperData();
rudder = c172sRudderActuatorData();
aileron = c172sAileronActuatorData();
roll = c172sRollAttitudeControllerData();
headingSensor = c172sHeadingSensorData();
heading = c172sHeadingHoldControllerData();

checks = [ ...
    strcmp(longitudinal.model.version,manager.required.longitudinalPlant); ...
    strcmp(pitchRate.version,manager.required.pitchRateDamper); ...
    strcmp(pitchAttitude.version,manager.required.pitchAttitudeController); ...
    strcmp(elevator.integratedLoopVersion,manager.required.pitchLoop); ...
    strcmp(altitude.version,manager.required.altitudeLoop); ...
    strcmp(lateral.model.version,manager.required.lateralPlant); ...
    strcmp(yaw.artifactRevision,manager.required.yawController); ...
    strcmp(rudder.artifactRevision,manager.required.rudderAudit); ...
    strcmp(aileron.artifactRevision,manager.required.aileronAudit); ...
    strcmp(roll.artifactRevision,manager.required.rollController); ...
    strcmp(headingSensor.artifactRevision, ...
        manager.required.headingSensorAudit); ...
    strcmp(heading.artifactRevision,manager.required.headingController)];
assert(all(checks), ...
    'buildC172sAutopilotModeManagerSimulink:DependencyMismatch', ...
    'At least one frozen dependency does not match the manager ledger.');
end
