function modelName = buildC172sNonlinearAutopilotSimulink(forceRebuild)
%BUILDC172SNONLINEARAUTOPILOTSIMULINK Generate executable closed loop.
%
% The generated MATLAB Function block contains independent executable
% equations for the nonlinear aircraft, frozen controller stack, protected
% actuators, accepted sensor delays and Mode Manager V1. It does not call
% the MATLAB closed-loop reference simulator or nonlinear plant functions.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_NonlinearAutopilot_V1';
modelFile = fullfile(pwd,[modelName '.slx']);
model = c172sNonlinearAutopilotClosedLoopData();
assignin('base','na1Model',model);
assignin('base','na1InputSignal',defaultInputSignal(model));

if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile), delete(modelFile); end

load_system('simulink');
new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step','Solver','ode4','FixedStep','0.01', ...
    'StartTime','0','StopTime','120', ...
    'SaveTime','on','TimeSaveName','tout', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Array');
set_param(modelName,'InitFcn',[ ...
    'na1Model=c172sNonlinearAutopilotClosedLoopData();' newline ...
    'if ~strcmp(na1Model.artifactRevision,''NONLINEAR-AUTOPILOT-V1-CLOSED-LOOP-MATLAB-R1''), error(''Nonlinear-autopilot closed-loop revision mismatch.''); end' newline ...
    'if ~exist(''na1InputSignal'',''var''), error(''na1InputSignal is required.''); end']);

add_block('simulink/Sources/From Workspace', ...
    [modelName '/Requests Wind and Gust'], ...
    'VariableName','na1InputSignal','Interpolate','off', ...
    'OutputAfterFinalValue','Holding final value','SampleTime','0.01', ...
    'Position',[60 235 250 275]);

blockPath = [modelName '/Independent Executable Nonlinear Autopilot'];
add_block('simulink/User-Defined Functions/MATLAB Function',blockPath, ...
    'Position',[350 105 690 405]);
root = sfroot;
chart = root.find('-isa','Stateflow.EMChart','Path',blockPath);
assert(~isempty(chart),'Generated MATLAB Function chart was not found.');
chart.Script = executableClosedLoopCode(model);
configuration = get_param(blockPath,'MATLABFunctionConfiguration');
configuration.UpdateMethod = 'Discrete';
configuration.SampleTime = '0.01';

add_block('simulink/Sinks/Out1',[modelName '/Verification Signals'], ...
    'Port','1','Position',[800 245 830 265]);
add_line(modelName,'Requests Wind and Gust/1', ...
    'Independent Executable Nonlinear Autopilot/1','autorouting','on');
add_line(modelName,'Independent Executable Nonlinear Autopilot/1', ...
    'Verification Signals/1','autorouting','on');

try
    note = Simulink.Annotation(modelName,sprintf([ ...
        'C172S NONLINEAR AUTOPILOT V1 - RESEARCH EXECUTABLE\n' ...
        '26 propagated states: 13 aircraft + 13 controller\n' ...
        '58 verification signals; hybrid internal RK4 at 10 ms\n' ...
        'Frozen Mode Manager/controller releases + nonlinear plant V0.1\n' ...
        'Near-trim coefficients, ideal sensors and one-point throttle only']));
    note.Position = [45 20 870 90];
catch
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);
fprintf('Created Simulink model: %s\n',modelFile);
fprintf(['Run runNonlinearAutopilotSimulinkCheck to validate ', ...
    'Nonlinear Autopilot V1.\n']);
end

function signal = defaultInputSignal(model)
row = zeros(1,25);
row(4:7) = 1;
row(18) = model.dependencies.interface.initialization.heading_deg;
row(19) = model.dependencies.interface.trim.altitude_ft;
signal = [0 row;120 row];
end

function code = executableClosedLoopCode(model)
dep = model.dependencies;
plant = dep.plant;
trimModel = plant.trimModel;
kernel = trimModel.kernel;
aero = trimModel.aerodynamics;
air = aero.airDataModel.constants;
lon = aero.longitudinal.aero;
lat = aero.lateral.aero;
Ibody = kernel.inertia.matrix_kgm2;
fmt = @(value)sprintf('%.17g',value);

lines = { ...
'function signals = nonlinearAutopilot(input)'; ...
'%#codegen'; ...
'persistent initialized z managerInitialized engaged lateralMode verticalMode'; ...
'persistent bankRef pitchRef headingRef altitudeRef coreTimer headingTimer altitudeTimer'; ...
'persistent aileronTimer elevatorTimer delayR delayP delayPhi delayPsi'; ...
'persistent previousAileronSaturated previousElevatorSaturated'; ...
'if isempty(initialized)'; ...
sprintf('z=[%s;zeros(13,1)];',vectorLiteral(model.trim.state,fmt)); ...
'managerInitialized=false; engaged=false; lateralMode=uint8(0); verticalMode=uint8(0);'; ...
'bankRef=0.0; pitchRef=0.0; headingRef=0.0; altitudeRef=4000.0;'; ...
'coreTimer=0.0; headingTimer=0.0; altitudeTimer=0.0; aileronTimer=0.0; elevatorTimer=0.0;'; ...
'delayR=0.0; delayP=0.0; delayPhi=0.0; delayPsi=zeros(5,1);'; ...
'previousAileronSaturated=false; previousElevatorSaturated=false; initialized=true;'; ...
'end'; ...
'request=input(1:19); wind=input(20:22); gust=input(23:25);'; ...
'[phi0,theta0,psi0,qNorm0]=attitude(z(10:13));'; ...
'altitudeFt0=-z(9)/0.3048;'; ...
'coreValid0=all(isfinite(z(4:6))) && isfinite(qNorm0) && abs(qNorm0-1.0)<=1.0e-8;'; ...
'headingValid0=coreValid0 && isfinite(psi0); altitudeValid0=isfinite(altitudeFt0);'; ...
'if ~managerInitialized'; ...
'bankRef=captureBank(phi0*180/pi); pitchRef=clip(theta0*180/pi,-3.0,3.0);'; ...
'headingRef=normalizeHeading(psi0*180/pi); altitudeRef=altitudeFt0;'; ...
'delayR=z(6); delayP=z(4); delayPhi=phi0; delayPsi(:)=psi0; managerInitialized=true;'; ...
'end'; ...
'[engaged,lateralMode,verticalMode,bankRef,pitchRef,headingRef,altitudeRef,...'; ...
' coreTimer,headingTimer,altitudeTimer,aileronTimer,elevatorTimer,...'; ...
' rollTrack,pitchTrack,eventCode]=managerStep(engaged,lateralMode,verticalMode,...'; ...
' bankRef,pitchRef,headingRef,altitudeRef,coreTimer,headingTimer,altitudeTimer,...'; ...
' aileronTimer,elevatorTimer,request,phi0,theta0,coreValid0,...'; ...
' headingValid0,altitudeValid0,previousAileronSaturated,previousElevatorSaturated);'; ...
'headingEnable=engaged && lateralMode==uint8(2); altitudeEnable=engaged && verticalMode==uint8(2);'; ...
'bankCommand=0.0; pitchCommand=0.0;'; ...
'if engaged && lateralMode==uint8(1), bankCommand=bankRef; end'; ...
'if engaged && verticalMode==uint8(1), pitchCommand=pitchRef; end'; ...
'if pitchTrack'; ...
'z(14)=theta0; pitchError=z(14)-theta0;'; ...
sprintf('z(15)=(-%s*pitchError+%s*z(5)-z(16))/%s;', ...
    fmt(dep.pitch.Kp_radPerRad),fmt(dep.elevator.integration.Kq_s), ...
    fmt(dep.pitch.Ki_radPerRadPerS)); ...
'end'; ...
'if rollTrack'; ...
'z(25)=phi0; bankError=z(25)-z(22);'; ...
sprintf('z(23)=(z(24)-%s*bankError+%s*z(21))/%s;', ...
    fmt(dep.roll.bankProportionalGain),fmt(dep.roll.rollRateGain_s), ...
    fmt(dep.roll.bankIntegralGain_per_s)); ...
'end'; ...
'supervisor=[double(engaged);double(headingEnable);double(altitudeEnable);bankCommand;'; ...
' pitchCommand;headingRef;altitudeRef];'; ...
'delays=[delayR;delayP;delayPhi;delayPsi(1)];'; ...
'[k1,diagnostic]=closedRhs(z,supervisor,delays,wind,gust);'; ...
'signals=[z;diagnostic(1:18);double(engaged);double(lateralMode);double(verticalMode);'; ...
' double(rollTrack);double(pitchTrack);double(eventCode);bankCommand;pitchCommand;'; ...
' headingRef;altitudeRef;diagnostic(19);diagnostic(20);aileronTimer;elevatorTimer];'; ...
'previousAileronSaturated=diagnostic(19)~=0;'; ...
'previousElevatorSaturated=diagnostic(20)~=0;'; ...
'sampleR=z(6); sampleP=z(4); samplePhi=phi0; samplePsi=psi0;'; ...
'k2=closedRhs(z+0.005*k1,supervisor,delays,wind,gust);'; ...
'k3=closedRhs(z+0.005*k2,supervisor,delays,wind,gust);'; ...
'k4=closedRhs(z+0.01*k3,supervisor,delays,wind,gust);'; ...
'z=z+(0.01/6.0)*(k1+2.0*k2+2.0*k3+k4);'; ...
'z(10:13)=z(10:13)/sqrt(sum(z(10:13).^2));'; ...
'delayR=sampleR; delayP=sampleP; delayPhi=samplePhi; delayPsi=[delayPsi(2:5);samplePsi];'; ...
'end'; ...
''; ...
'function [engaged,lateralMode,verticalMode,bankRef,pitchRef,headingRef,altitudeRef,...'; ...
' coreTimer,headingTimer,altitudeTimer,aileronTimer,elevatorTimer,...'; ...
' rollTrack,pitchTrack,eventCode]=managerStep(engaged,lateralMode,verticalMode,...'; ...
' bankRef,pitchRef,headingRef,altitudeRef,coreTimer,headingTimer,altitudeTimer,...'; ...
' aileronTimer,elevatorTimer,r,phi,theta,coreValid,headingValid,...'; ...
' altitudeValid,previousASat,previousESat)'; ...
'dt=0.01; rollTrack=false; pitchTrack=false; eventCode=uint8(0); wasEngaged=engaged;'; ...
'inputCore=(r(5)~=0)&&coreValid; inputHeading=(r(6)~=0)&&headingValid;'; ...
'inputAltitude=(r(7)~=0)&&altitudeValid; inputASat=(r(8)~=0)||previousASat;'; ...
'inputESat=(r(9)~=0)||previousESat;'; ...
'coreTimer=timerUpdate(~inputCore,coreTimer,dt);'; ...
'headingTimer=timerUpdate(~inputHeading,headingTimer,dt);'; ...
'altitudeTimer=timerUpdate(~inputAltitude,altitudeTimer,dt);'; ...
'aileronTimer=timerUpdate(inputASat,aileronTimer,dt);'; ...
'elevatorTimer=timerUpdate(inputESat,elevatorTimer,dt);'; ...
'if engaged'; ...
'if r(2)~=0, engaged=false; eventCode=uint8(7);'; ...
'elseif r(3)~=0, engaged=false; eventCode=uint8(8);'; ...
'elseif abs(phi*180/pi)>30.0 || abs(theta*180/pi)>10.0, engaged=false; eventCode=uint8(11);'; ...
'elseif coreTimer+eps>=0.10, engaged=false; eventCode=uint8(9);'; ...
'elseif max(aileronTimer,elevatorTimer)+eps>=2.0, engaged=false; eventCode=uint8(10);'; ...
'end'; ...
'if ~engaged, lateralMode=uint8(0); verticalMode=uint8(0); end'; ...
'end'; ...
'if ~engaged'; ...
'if ~wasEngaged && r(1)~=0'; ...
'permitted=(r(4)~=0)&&inputCore&&(r(3)==0)&&~inputASat&&~inputESat;'; ...
'if r(10)==2, permitted=permitted&&inputHeading; end'; ...
'if r(11)==2, permitted=permitted&&inputAltitude; end'; ...
'if permitted'; ...
'engaged=true; eventCode=uint8(1); rollTrack=true; pitchTrack=true;'; ...
'if r(10)==2, lateralMode=uint8(2); headingRef=normalizeHeading(r(18));'; ...
'else, lateralMode=uint8(1); bankRef=captureBank(phi*180/pi); end'; ...
'if r(11)==2, verticalMode=uint8(2); altitudeRef=r(19);'; ...
'else, verticalMode=uint8(1); pitchRef=clip(theta*180/pi,-3.0,3.0); end'; ...
'else, eventCode=uint8(4);'; ...
'end'; ...
'end'; ...
'return'; ...
'end'; ...
'if lateralMode==uint8(2) && headingTimer+eps>=0.10'; ...
'lateralMode=uint8(1); bankRef=captureBank(phi*180/pi); rollTrack=true; eventCode=uint8(5);'; ...
'end'; ...
'if verticalMode==uint8(2) && altitudeTimer+eps>=0.10'; ...
'verticalMode=uint8(1); pitchRef=clip(theta*180/pi,-3.0,3.0); pitchTrack=true; eventCode=uint8(6);'; ...
'end'; ...
'if r(10)~=0'; ...
'if r(10)==1, lateralMode=uint8(1); bankRef=captureBank(phi*180/pi); rollTrack=true; eventCode=uint8(2);'; ...
'elseif r(10)==2 && inputHeading, lateralMode=uint8(2); headingRef=normalizeHeading(r(18)); rollTrack=true; eventCode=uint8(2);'; ...
'else, eventCode=uint8(3); end'; ...
'end'; ...
'if r(11)~=0'; ...
'if r(11)==1, verticalMode=uint8(1); pitchRef=clip(theta*180/pi,-3.0,3.0); pitchTrack=true; eventCode=uint8(2);'; ...
'elseif r(11)==2 && inputAltitude, verticalMode=uint8(2); altitudeRef=r(19); pitchTrack=true; eventCode=uint8(2);'; ...
'else, eventCode=uint8(3); end'; ...
'end'; ...
'if lateralMode==uint8(2) && r(12)~=0 && inputHeading, headingRef=normalizeHeading(r(18)); end'; ...
'if verticalMode==uint8(2) && r(13)~=0 && inputAltitude, altitudeRef=r(19); end'; ...
'end'; ...
''; ...
'function [zDot,d]=closedRhs(z,sup,delay,wind,gust)'; ...
'control=[z(16);z(24);z(20);0.65];'; ...
'[xDot,TAS,alpha,beta]=plantRhs(z(1:13),control,wind,gust);'; ...
'[phi,theta,psi,qNorm]=attitude(z(10:13)); altitudeFt=-z(9)/0.3048;'; ...
'altitudePerturbation=-z(9)-1219.2; verticalSpeed=-xDot(9);'; ...
'altitudeCommand=(sup(7)-4000.0)*0.3048;'; ...
sprintf('verticalCommand=clip(%s*(z(17)-altitudePerturbation),-%s,%s);', ...
    fmt(dep.altitude.altitudeGain_per_s), ...
    fmt(dep.altitude.verticalSpeedCommandLimit_mps), ...
    fmt(dep.altitude.verticalSpeedCommandLimit_mps)); ...
sprintf('thetaOuter=clip(%s*(verticalCommand-verticalSpeed),-%s,%s);', ...
    fmt(dep.altitude.verticalSpeedGain_radPerMps), ...
    fmt(dep.altitude.pitchCommandLimit_rad),fmt(dep.altitude.pitchCommandLimit_rad)); ...
'if sup(3)~=0, thetaSelected=thetaOuter; else, thetaSelected=sup(5)*pi/180; end'; ...
'pitchError=z(14)-theta;'; ...
sprintf('eUnsat=-%s*pitchError-%s*z(15)+%s*z(5);', ...
    fmt(dep.pitch.Kp_radPerRad),fmt(dep.pitch.Ki_radPerRadPerS), ...
    fmt(dep.elevator.integration.Kq_s)); ...
sprintf('eLimited=clip(eUnsat,%s,%s);', ...
    fmt(dep.elevator.authority.lowerLimit_rad), ...
    fmt(dep.elevator.authority.upperLimit_rad)); ...
'eTarget=sup(1)*eLimited;'; ...
sprintf('eRateRaw=(eTarget-z(16))/%s;',fmt(dep.elevator.dynamics.timeConstant_s)); ...
sprintf('eRate=clip(eRateRaw,-%s,%s);', ...
    fmt(deg2rad(dep.elevator.dynamics.rateLimit_degps)), ...
    fmt(deg2rad(dep.elevator.dynamics.rateLimit_degps))); ...
sprintf('eTrack=z(16)+%s*eRate;',fmt(dep.elevator.dynamics.timeConstant_s)); ...
sprintf('pitchAW=(eUnsat-eTrack)/(%s*%s);', ...
    fmt(dep.pitch.Ki_radPerRadPerS), ...
    fmt(dep.elevator.antiWindup.trackingTimeConstant_s)); ...
'headingError=wrapAngle(sup(6)*pi/180-z(26));'; ...
sprintf('bankOuter=clip(%s*headingError,-%s,%s);', ...
    fmt(dep.heading.headingErrorGain), ...
    fmt(deg2rad(dep.heading.bankCommandAuthority_deg)), ...
    fmt(deg2rad(dep.heading.bankCommandAuthority_deg))); ...
'if sup(2)~=0, bankSelected=bankOuter; else, bankSelected=sup(4)*pi/180; end'; ...
'yawWash=z(18)-z(19);'; ...
sprintf('rUnsat=-%s*yawWash;',fmt(dep.yaw.rudderGain_s)); ...
sprintf('rLimited=clip(rUnsat,%s,%s);', ...
    fmt(dep.rudder.authority.lowerLimit_rad),fmt(dep.rudder.authority.upperLimit_rad)); ...
'rTarget=sup(1)*rLimited;'; ...
sprintf('rRateRaw=(rTarget-z(20))/%s;',fmt(dep.rudder.dynamics.timeConstant_s)); ...
sprintf('rRate=clip(rRateRaw,-%s,%s);', ...
    fmt(deg2rad(dep.rudder.dynamics.rateLimit_degps)), ...
    fmt(deg2rad(dep.rudder.dynamics.rateLimit_degps))); ...
'bankError=z(25)-z(22);'; ...
sprintf('aUnsat=%s*bankError+%s*z(23)-%s*z(21);', ...
    fmt(dep.roll.bankProportionalGain),fmt(dep.roll.bankIntegralGain_per_s), ...
    fmt(dep.roll.rollRateGain_s)); ...
sprintf('aLimited=clip(aUnsat,%s,%s);', ...
    fmt(dep.aileron.authority.lowerLimit_rad),fmt(dep.aileron.authority.upperLimit_rad)); ...
'aTarget=sup(1)*aLimited;'; ...
sprintf('aRateRaw=(aTarget-z(24))/%s;',fmt(dep.aileron.dynamics.timeConstant_s)); ...
sprintf('aRate=clip(aRateRaw,-%s,%s);', ...
    fmt(deg2rad(dep.aileron.dynamics.rateLimit_degps)), ...
    fmt(deg2rad(dep.aileron.dynamics.rateLimit_degps))); ...
sprintf('aTrack=z(24)+%s*aRate;',fmt(dep.aileron.dynamics.timeConstant_s)); ...
sprintf('rollAW=(aTrack-aUnsat)/(%s*%s);', ...
    fmt(dep.roll.bankIntegralGain_per_s), ...
    fmt(dep.aileron.antiWindup.trackingTimeConstant_s)); ...
'cDot=zeros(13,1);'; ...
sprintf('cDot(1)=(thetaSelected-z(14))/%s;',fmt(dep.pitch.commandFilterTimeConstant_s)); ...
'cDot(2)=pitchError+pitchAW; cDot(3)=eRate;'; ...
sprintf('cDot(4)=(altitudeCommand-z(17))/%s;',fmt(dep.altitude.commandFilterTimeConstant_s)); ...
sprintf('cDot(5)=(delay(1)-z(18))/%s;',fmt(dep.rudder.sensor.filterTimeConstant_s)); ...
sprintf('cDot(6)=(z(18)-z(19))/%s;',fmt(dep.yaw.washoutTimeConstant_s)); ...
'cDot(7)=rRate;'; ...
sprintf('cDot(8)=(delay(2)-z(21))/%s;',fmt(dep.aileron.sensor.filterTimeConstant_s)); ...
sprintf('cDot(9)=(delay(3)-z(22))/%s;',fmt(dep.aileron.sensor.filterTimeConstant_s)); ...
'cDot(10)=bankError+rollAW; cDot(11)=aRate;'; ...
sprintf('cDot(12)=(bankSelected-z(25))/%s;',fmt(dep.roll.commandFilterTimeConstant_s)); ...
sprintf('cDot(13)=(delay(4)-z(26))/%s;',fmt(dep.headingSensor.filterTimeConstant_s)); ...
'zDot=[xDot;cDot];'; ...
'tol=1.0e-12; eSat=(sup(1)~=0)&&((abs(eUnsat-eLimited)>tol)||(abs(eRateRaw-eRate)>tol));'; ...
'aSat=(sup(1)~=0)&&((abs(aUnsat-aLimited)>tol)||(abs(aRateRaw-aRate)>tol));'; ...
'within=(TAS>=80*0.514444444444444)&&(TAS<=130*0.514444444444444)&&...'; ...
' (alpha>=-4*pi/180)&&(alpha<=10*pi/180)&&(beta>=-8*pi/180)&&(beta<=8*pi/180)&&...'; ...
' (phi>=-30*pi/180)&&(phi<=30*pi/180)&&(theta>=-10*pi/180)&&(theta<=10*pi/180);'; ...
'd=[control;eRate;aRate;rRate;phi;theta;psi;altitudeFt;altitudePerturbation;'; ...
' verticalSpeed;TAS;alpha;beta;qNorm;double(within);double(aSat);double(eSat)];'; ...
'end'; ...
''; ...
'function [xdot,TAS,alpha,beta]=plantRhs(x,u,steadyWind,gust)'; ...
'wind=steadyWind+gust;'; ...
'[f0,~,~,~,~,~,airVelocity,windBody]=evaluatePlant(x,u,wind,0.0);'; ...
'[f1,~,~,~,~,~,~,~]=evaluatePlant(x,u,wind,1.0);'; ...
'omega=x(4:6); a0=f0(1:3)+cross(omega,windBody); a1=f1(1:3)+cross(omega,windBody);'; ...
'r0=alphaRate(airVelocity,a0); r1=alphaRate(airVelocity,a1); alphaDot=r0/(1.0-(r1-r0));'; ...
'[xdot,TAS,alpha,beta,~,~,~,~]=evaluatePlant(x,u,wind,alphaDot);'; ...
'end'; ...
''; ...
'function rate=alphaRate(v,a)'; ...
'rate=(v(1)*a(3)-v(3)*a(1))/(v(1)^2+v(3)^2);'; ...
'end'; ...
''; ...
'function [xdot,TAS,alpha,beta,F,M,airVelocity,windBody]=evaluatePlant(x,u,wind,alphaDot)'; ...
sprintf('mass=%s; gravity=%s;',fmt(kernel.mass_kg),fmt(kernel.gravity_mps2)); ...
sprintf('I=[%s %s %s;%s %s %s;%s %s %s];', ...
    fmt(Ibody(1,1)),fmt(Ibody(1,2)),fmt(Ibody(1,3)), ...
    fmt(Ibody(2,1)),fmt(Ibody(2,2)),fmt(Ibody(2,3)), ...
    fmt(Ibody(3,1)),fmt(Ibody(3,2)),fmt(Ibody(3,3))); ...
'q=x(10:13); q=q/sqrt(sum(q.^2)); q0=q(1);q1=q(2);q2=q(3);q3=q(4);'; ...
'C=[q0^2+q1^2-q2^2-q3^2,2*(q1*q2-q0*q3),2*(q1*q3+q0*q2);'; ...
' 2*(q1*q2+q0*q3),q0^2-q1^2+q2^2-q3^2,2*(q2*q3-q0*q1);'; ...
' 2*(q1*q3-q0*q2),2*(q2*q3+q0*q1),q0^2-q1^2-q2^2+q3^2];'; ...
'windBody=C''*wind; airVelocity=x(1:3)-windBody; TAS=sqrt(sum(airVelocity.^2));'; ...
'alpha=atan2(airVelocity(3),airVelocity(1)); beta=asin(min(1,max(-1,airVelocity(2)/TAS)));'; ...
sprintf('temperature=%s-%s*(-x(9));',fmt(air.T0_K),fmt(air.lapse_Kpm)); ...
sprintf('pressure=%s*(temperature/%s)^(%s/(%s*%s));', ...
    fmt(air.p0_Pa),fmt(air.T0_K),fmt(air.g_mps2), ...
    fmt(air.Rair_JpkgK),fmt(air.lapse_Kpm)); ...
sprintf('rho=pressure/(%s*temperature);',fmt(air.Rair_JpkgK)); ...
sprintf('qbarS=0.5*rho*TAS^2*%s;',fmt(aero.geometry.S_m2)); ...
sprintf('pHat=x(4)*%s/(2*TAS);qHat=x(5)*%s/(2*TAS);rHat=x(6)*%s/(2*TAS);', ...
    fmt(aero.geometry.b_m),fmt(aero.geometry.cBar_m),fmt(aero.geometry.b_m)); ...
sprintf('adHat=alphaDot*%s/(2*TAS);',fmt(aero.geometry.cBar_m)); ...
sprintf('CL=%s+%s*alpha+%s*qHat+%s*adHat+%s*u(1);', ...
    fmt(aero.trim.CL),fmt(lon.CL_alpha),fmt(lon.CL_q), ...
    fmt(lon.CL_alphaDot),fmt(lon.CL_deltaE)); ...
sprintf('CD=%s+%s*alpha;',fmt(aero.trim.CD),fmt(lon.CD_alpha)); ...
sprintf('CY=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);', ...
    fmt(lat.CY_beta),fmt(lat.CY_p),fmt(lat.CY_r), ...
    fmt(lat.CY_deltaA),fmt(lat.CY_deltaR)); ...
sprintf('Cl=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);', ...
    fmt(lat.Cl_beta),fmt(lat.Cl_p),fmt(lat.Cl_r), ...
    fmt(lat.Cl_deltaA),fmt(lat.Cl_deltaR)); ...
sprintf('Cm=%s*alpha+%s*qHat+%s*adHat+%s*u(1);', ...
    fmt(lon.Cm_alpha),fmt(lon.Cm_q),fmt(lon.Cm_alphaDot),fmt(lon.Cm_deltaE)); ...
sprintf('Cn=%s*beta+%s*pHat+%s*rHat+%s*u(2)+%s*u(3);', ...
    fmt(lat.Cn_beta),fmt(lat.Cn_p),fmt(lat.Cn_r), ...
    fmt(lat.Cn_deltaA),fmt(lat.Cn_deltaR)); ...
sprintf('L=qbarS*CL;D=qbarS*CD;Y=qbarS*CY;thrust=u(4)*%s;', ...
    fmt(trimModel.propulsion.maximumThrustAtTrim_N)); ...
'Fa=[-D*cos(alpha)+L*sin(alpha);Y;-D*sin(alpha)-L*cos(alpha)];'; ...
'F=Fa+thrust*[cos(alpha);0;sin(alpha)];'; ...
sprintf('M=[qbarS*%s*Cl;qbarS*%s*Cm;qbarS*%s*Cn];', ...
    fmt(aero.geometry.b_m),fmt(aero.geometry.cBar_m),fmt(aero.geometry.b_m)); ...
'omega=x(4:6);gravityBody=C''*[0;0;gravity];'; ...
'vdot=F/mass+gravityBody-cross(omega,x(1:3));'; ...
'H=I*omega;odot=I\(M-cross(omega,H));pdot=C*x(1:3);'; ...
'qv=q(2:4);Q=[-qv'';q0*eye(3)+[0 -qv(3) qv(2);qv(3) 0 -qv(1);-qv(2) qv(1) 0]];'; ...
'qdot=0.5*Q*omega;xdot=[vdot;odot;pdot;qdot];'; ...
'end'; ...
''; ...
'function [phi,theta,psi,qNorm]=attitude(q)'; ...
'qNorm=sqrt(sum(q.^2));q=q/qNorm;q0=q(1);q1=q(2);q2=q(3);q3=q(4);'; ...
'phi=atan2(2*(q0*q1+q2*q3),1-2*(q1^2+q2^2));'; ...
'argument=min(1,max(-1,2*(q0*q2-q3*q1)));theta=asin(argument);'; ...
'psi=atan2(2*(q0*q3+q1*q2),1-2*(q2^2+q3^2));psi=mod(psi,2*pi);'; ...
'end'; ...
''; ...
'function value=timerUpdate(condition,previous,dt)'; ...
'if condition,value=previous+dt;else,value=0.0;end'; ...
'end'; ...
'function value=captureBank(bank)'; ...
'if abs(bank)<6.0,value=0.0;else,value=clip(bank,-20.0,20.0);end'; ...
'end'; ...
'function value=normalizeHeading(value)'; ...
'value=mod(value,360.0);if value<0.0,value=value+360.0;end'; ...
'end'; ...
'function value=wrapAngle(value)'; ...
'value=mod(value+pi,2*pi)-pi;'; ...
'end'; ...
'function value=clip(value,lower,upper)'; ...
'value=min(max(value,lower),upper);'; ...
'end'};
code = strjoin(lines,newline);
end

function text = vectorLiteral(vector,fmt)
entries = arrayfun(fmt,vector(:),'UniformOutput',false);
text = strjoin(entries,';');
end
