function modelName = buildC172sLongitudinalSimulink(forceRebuild)
%BUILDC172SLONGITUDINALSIMULINK Build the open-loop Simulink plant model.
%
%   MODELNAME = BUILDC172SLONGITUDINALSIMULINK() creates or opens
%   C172S_Longitudinal_OpenLoop.slx in the current folder.
%
%   MODELNAME = BUILDC172SLONGITUDINALSIMULINK(true) overwrites the
%   generated model. Use false to preserve an existing model.
%
%   The generated model retains SI/radian units internally and applies a
%   one-degree trailing-edge-up elevator step from t = 0 for verification.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_Longitudinal_OpenLoop';
modelFile = fullfile(pwd, [modelName '.slx']);

%% Initialize the plant variables used by the State-Space block

fcData = c172sLongitudinalData();
[~, fcPlant] = c172sLongitudinalPlant(fcData);

assignin('base','fcData',fcData);
assignin('base','fcPlant',fcPlant);
assignin('base','A_long',fcPlant.A);
assignin('base','B_long',fcPlant.B);
assignin('base','C_long',fcPlant.C);
assignin('base','D_long',fcPlant.D);
assignin('base','x0_long',zeros(4,1));
assignin('base','deltaE_step_rad',-deg2rad(1.0));

%% Preserve an existing generated model unless rebuilding was requested

if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n', modelFile);
    return;
end

if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the model

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','40', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Reinitialize model variables whenever the diagram is updated or run.
initCode = [ ...
    'fcData = c172sLongitudinalData();' newline ...
    '[~, fcPlant] = c172sLongitudinalPlant(fcData);' newline ...
    'A_long = fcPlant.A; B_long = fcPlant.B;' newline ...
    'C_long = fcPlant.C; D_long = fcPlant.D;' newline ...
    'x0_long = zeros(4,1);' newline ...
    'deltaE_step_rad = -deg2rad(1.0);'];
set_param(modelName,'InitFcn',initCode);

%% Add the source, plant, output and visualization blocks

add_block('simulink/Sources/Step', ...
    [modelName '/Elevator Step'], ...
    'Time','0.0', ...
    'Before','0.0', ...
    'After','deltaE_step_rad', ...
    'SampleTime','0', ...
    'Position',[40 145 100 175]);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Longitudinal Plant'], ...
    'A','A_long', ...
    'B','B_long', ...
    'C','C_long', ...
    'D','D_long', ...
    'X0','x0_long', ...
    'Position',[190 125 360 195]);

add_block('simulink/Signal Routing/Demux', ...
    [modelName '/State Demux'], ...
    'Outputs','4', ...
    'Position',[425 108 430 212]);

add_block('simulink/Sinks/Out1', ...
    [modelName '/State Vector'], ...
    'Port','1', ...
    'Position',[790 140 820 160]);

% Display u directly in m/s.
add_block('simulink/Sinks/Scope', ...
    [modelName '/Airspeed Scope'], ...
    'Position',[760 235 810 265]);

% Convert alpha to degrees only for display.
add_block('simulink/Math Operations/Gain', ...
    [modelName '/Alpha rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[500 285 560 315]);

add_block('simulink/Sinks/Scope', ...
    [modelName '/Alpha Scope'], ...
    'Position',[760 285 810 315]);

% Convert q and theta to degrees for a shared pitch-motion scope.
add_block('simulink/Math Operations/Gain', ...
    [modelName '/q rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[500 345 560 375]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Theta rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[500 405 560 435]);

add_block('simulink/Signal Routing/Mux', ...
    [modelName '/Pitch Display Mux'], ...
    'Inputs','2', ...
    'Position',[650 350 655 430]);

add_block('simulink/Sinks/Scope', ...
    [modelName '/Pitch Motion Scope'], ...
    'Position',[760 375 810 405]);

%% Connect and label the signals

h = add_line(modelName,'Elevator Step/1','C172S Longitudinal Plant/1', ...
    'autorouting','on');
set_param(h,'Name','delta_e rad, TE down positive');

h = add_line(modelName,'C172S Longitudinal Plant/1','State Vector/1', ...
    'autorouting','on');
set_param(h,'Name','x = [u alpha q theta]');
% The root State Vector outport supplies yout. Avoid release-dependent
% per-line logging parameters here.

add_line(modelName,'C172S Longitudinal Plant/1','State Demux/1', ...
    'autorouting','on');

h = add_line(modelName,'State Demux/1','Airspeed Scope/1','autorouting','on');
set_param(h,'Name','u m/s');

h = add_line(modelName,'State Demux/2','Alpha rad-to-deg/1','autorouting','on');
set_param(h,'Name','alpha rad');
add_line(modelName,'Alpha rad-to-deg/1','Alpha Scope/1','autorouting','on');

h = add_line(modelName,'State Demux/3','q rad-to-deg/1','autorouting','on');
set_param(h,'Name','q rad/s');
add_line(modelName,'q rad-to-deg/1','Pitch Display Mux/1','autorouting','on');

h = add_line(modelName,'State Demux/4','Theta rad-to-deg/1','autorouting','on');
set_param(h,'Name','theta rad');
add_line(modelName,'Theta rad-to-deg/1','Pitch Display Mux/2','autorouting','on');
add_line(modelName,'Pitch Display Mux/1','Pitch Motion Scope/1','autorouting','on');

%% Diagram note

% Avoid block BackgroundColor commands here. Their availability differs
% between ordinary and masked blocks across Simulink releases, and visual
% styling must never be allowed to interrupt model generation.

try
    note = Simulink.Annotation(modelName, ...
        ['Plant V1: x = [u, alpha, q, theta]^T' newline ...
         'SI/radians internally; elevator positive trailing-edge down' newline ...
         'Verification input: 1 deg trailing-edge up from t = 0']);
    note.Position = [40 25 560 75];
catch
    % Annotation appearance is nonessential to the executable model.
end

save_system(modelName,modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n', modelFile);
fprintf('Run runSimulinkPlantCheck to verify it against MATLAB lsim.\n');

end
