function modelName = buildC172sYawDamperSimulink(forceRebuild)
%BUILDC172SYAWDAMPERSIMULINK Build the C172S Yaw Damper V1 model.
%
%   MODELNAME = BUILDC172SYAWDAMPERSIMULINK() creates or opens
%   C172S_YawDamper_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SYAWDAMPERSIMULINK(true) overwrites the generated
%   model. The frozen dependencies are Lateral-Directional Plant V0.1 and
%   Yaw Damper V1 artifact YD-V1-MATLAB-R2.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_YawDamper_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize frozen plant and controller variables

yd1Data = c172sLateralDirectionalData();
[~,yd1Plant] = c172sLateralDirectionalPlant(yd1Data);
yd1Controller = c172sYawDamperData();
assertDependencies(yd1Data,yd1Controller);
assignModelVariables(yd1Data,yd1Plant,yd1Controller);

% An interrupted builder must not leave a partial in-memory diagram.
if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end

if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the executable model

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','30', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Reconstruct frozen data before every run while preserving checker
% overrides of commands and initial conditions.
initCode = [ ...
    'yd1Data = c172sLateralDirectionalData();' newline ...
    '[~,yd1Plant] = c172sLateralDirectionalPlant(yd1Data);' newline ...
    'yd1Controller = c172sYawDamperData();' newline ...
    'if ~strcmp(yd1Data.model.version,yd1Controller.requiredPlantVersion), error(''Yaw Damper plant dependency mismatch.''); end' newline ...
    'if ~strcmp(yd1Controller.artifactRevision,''YD-V1-MATLAB-R2''), error(''Yaw Damper artifact revision mismatch.''); end' newline ...
    'A_yd1 = yd1Plant.A; B_yd1 = yd1Plant.B;' newline ...
    'C_yd1 = yd1Plant.C; D_yd1 = yd1Plant.D;' newline ...
    'Kr_yd1 = yd1Controller.rudderGain_s;' newline ...
    'Tw_yd1 = yd1Controller.washoutTimeConstant_s;' newline ...
    'if ~exist(''deltaACommand_yd1_rad'',''var''), deltaACommand_yd1_rad = deg2rad(1.0); end' newline ...
    'if ~exist(''deltaRCommand_yd1_rad'',''var''), deltaRCommand_yd1_rad = deg2rad(1.0); end' newline ...
    'if ~exist(''x0_yd1'',''var''), x0_yd1 = zeros(5,1); end' newline ...
    'if ~exist(''xw0_yd1'',''var''), xw0_yd1 = 0.0; end'];
set_param(modelName,'InitFcn',initCode);

%% Pilot-command pulses

add_block('simulink/Sources/Step',[modelName '/Aileron Pulse Start'], ...
    'Time','0','Before','0','After','deltaACommand_yd1_rad', ...
    'SampleTime','0','Position',[35 125 105 155]);
add_block('simulink/Sources/Step',[modelName '/Aileron Pulse End'], ...
    'Time','1','Before','0','After','-deltaACommand_yd1_rad', ...
    'SampleTime','0','Position',[35 175 105 205]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Aileron Pilot Command'], ...
    'Inputs','++','Position',[145 140 175 190]);

add_block('simulink/Sources/Step',[modelName '/Rudder Pulse Start'], ...
    'Time','5','Before','0','After','deltaRCommand_yd1_rad', ...
    'SampleTime','0','Position',[35 295 105 325]);
add_block('simulink/Sources/Step',[modelName '/Rudder Pulse End'], ...
    'Time','6','Before','0','After','-deltaRCommand_yd1_rad', ...
    'SampleTime','0','Position',[35 345 105 375]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Rudder Pilot Command'], ...
    'Inputs','++','Position',[145 310 175 360]);

%% Yaw damper, control summation and frozen plant

% State xw follows xwDot = (r-xw)/Tw. The State-Space output is r-xw,
% which is exactly Tw*s/(Tw*s+1) applied to yaw rate.
add_block('simulink/Continuous/State-Space', ...
    [modelName '/Yaw-Rate Washout'], ...
    'A','-1/Tw_yd1','B','1/Tw_yd1','C','-1','D','1', ...
    'X0','xw0_yd1','Position',[665 270 800 330]);
add_block('simulink/Math Operations/Gain', ...
    [modelName '/Automatic Rudder Gain'], ...
    'Gain','-Kr_yd1','Position',[840 275 930 325]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Total Rudder Command'], ...
    'Inputs','++','Position',[980 305 1010 355]);

add_block('simulink/Signal Routing/Mux',[modelName '/Control Mux'], ...
    'Inputs','2','Position',[245 205 250 315]);
add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Lateral-Directional Plant'], ...
    'A','A_yd1','B','B_yd1','C','C_yd1','D','D_yd1','X0','x0_yd1', ...
    'Position',[320 220 525 300]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','5','Position',[590 130 595 350]);

%% Global signal tags

tagDefinitions = { ...
    'Aileron Pilot Tag','yd1_deltaA_pilot',[205 115 315 135]; ...
    'Rudder Pilot Tag','yd1_deltaR_pilot',[205 365 315 385]; ...
    'Beta Tag','yd1_beta',[650 115 730 135]; ...
    'p Tag','yd1_p',[650 155 730 175]; ...
    'r Tag','yd1_r',[650 195 730 215]; ...
    'Phi Tag','yd1_phi',[650 235 730 255]; ...
    'Psi Tag','yd1_psi',[650 345 730 365]; ...
    'Washout Tag','yd1_r_washout',[815 235 930 255]; ...
    'Automatic Rudder Tag','yd1_deltaR_auto',[945 265 1070 285]; ...
    'Total Rudder Tag','yd1_deltaR_total',[1030 350 1145 370]};

for k = 1:size(tagDefinitions,1)
    addGlobalGoto(modelName,tagDefinitions{k,1},tagDefinitions{k,2}, ...
        tagDefinitions{k,3});
end

%% Verification subsystem

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[1190 175 1345 245]);
clearDefaultSubsystem(verificationPath);

% Output order: [beta p r phi psi deltaA_pilot deltaR_pilot rWashout
%                deltaR_auto deltaR_total].
verificationTags = { ...
    'yd1_beta','yd1_p','yd1_r','yd1_phi','yd1_psi', ...
    'yd1_deltaA_pilot','yd1_deltaR_pilot','yd1_r_washout', ...
    'yd1_deltaR_auto','yd1_deltaR_total'};
verificationNames = { ...
    'Beta','p','r','Phi','Psi','Aileron Pilot','Rudder Pilot', ...
    'Washout Yaw Rate','Automatic Rudder','Total Rudder'};

for k = 1:numel(verificationTags)
    yPosition = 25 + 38*(k - 1);
    addFrom(verificationPath,verificationNames{k},verificationTags{k}, ...
        [25 yPosition 155 yPosition + 20]);
end

add_block('simulink/Signal Routing/Mux', ...
    [verificationPath '/Signal Mux'], ...
    'Inputs',num2str(numel(verificationTags)), ...
    'Position',[225 15 230 405]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[290 200 320 220]);
for k = 1:numel(verificationTags)
    add_line(verificationPath,sprintf('%s/1',verificationNames{k}), ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Closed-Loop Signals'], ...
    'Port','1','Position',[1395 195 1425 215]);
add_line(modelName,'Verification Signals/1','Closed-Loop Signals/1', ...
    'autorouting','on');

%% Display subsystem

displayPath = [modelName '/Display Scopes'];
add_block('simulink/Ports & Subsystems/Subsystem',displayPath, ...
    'Position',[1190 315 1345 385]);
clearDefaultSubsystem(displayPath);
buildDisplaySubsystem(displayPath);

%% Connect the executable path

add_line(modelName,'Aileron Pulse Start/1','Aileron Pilot Command/1', ...
    'autorouting','on');
add_line(modelName,'Aileron Pulse End/1','Aileron Pilot Command/2', ...
    'autorouting','on');
add_line(modelName,'Rudder Pulse Start/1','Rudder Pilot Command/1', ...
    'autorouting','on');
add_line(modelName,'Rudder Pulse End/1','Rudder Pilot Command/2', ...
    'autorouting','on');

connectNamed(modelName,'Aileron Pilot Command/1','Control Mux/1', ...
    'deltaA pilot rad, right-wing-down positive');
connectNamed(modelName,'Rudder Pilot Command/1', ...
    'Total Rudder Command/1','deltaR pilot rad, nose-right positive');
connectNamed(modelName,'Total Rudder Command/1','Control Mux/2', ...
    'deltaR total rad');
connectNamed(modelName,'Control Mux/1', ...
    'C172S Lateral-Directional Plant/1','u = [deltaA deltaR total]');
connectNamed(modelName,'C172S Lateral-Directional Plant/1', ...
    'State Demux/1','x = [beta p r phi psi]');
connectNamed(modelName,'State Demux/3','Yaw-Rate Washout/1', ...
    'yaw rate r rad/s');
connectNamed(modelName,'Yaw-Rate Washout/1','Automatic Rudder Gain/1', ...
    'washout yaw rate rad/s');
connectNamed(modelName,'Automatic Rudder Gain/1', ...
    'Total Rudder Command/2','negative-feedback automatic rudder rad');

% Feed every global tag only after every corresponding From block exists.
branchTo(modelName,'Aileron Pilot Command/1','Aileron Pilot Tag/1');
branchTo(modelName,'Rudder Pilot Command/1','Rudder Pilot Tag/1');
stateTagNames = {'Beta Tag','p Tag','r Tag','Phi Tag','Psi Tag'};
for k = 1:5
    branchTo(modelName,sprintf('State Demux/%d',k), ...
        [stateTagNames{k} '/1']);
end
branchTo(modelName,'Yaw-Rate Washout/1','Washout Tag/1');
branchTo(modelName,'Automatic Rudder Gain/1','Automatic Rudder Tag/1');
branchTo(modelName,'Total Rudder Command/1','Total Rudder Tag/1');

%% Traceability note and clean reload

try
    note = Simulink.Annotation(modelName, ...
        ['Yaw Damper V1 - artifact YD-V1-MATLAB-R2' newline ...
         'deltaR_YD = -Kr*(r-xw), xwDot = (r-xw)/Tw' newline ...
         'Kr = 0.280 s; Tw = 1.00 s; positive r and rudder are nose-right' newline ...
         'Frozen dependency: provisional Lateral-Directional Plant V0.1' newline ...
         'Ideal sensor and rudder path; actuator/protection remain future work']);
    note.Position = [35 25 940 105];
catch
    % Annotation appearance is nonessential to the executable model.
end

% Compile the complete diagram before saving. This catches unresolved tags,
% dimension errors, invalid parameters and algebraic-loop problems during
% the builder run rather than deferring them to the checker.
set_param(modelName,'SimulationCommand','update');

save_system(modelName,modelFile);
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runYawDamperSimulinkCheck to validate Yaw Damper V1.\n');

end

function assertDependencies(data,controller)
assert(strcmp(data.model.version,controller.requiredPlantVersion), ...
    'Yaw Damper V1 plant dependency mismatch.');
assert(strcmp(controller.artifactRevision,'YD-V1-MATLAB-R2'), ...
    'Yaw Damper V1 requires artifact YD-V1-MATLAB-R2.');
assert(controller.feedbackSign == -1.0, ...
    'Yaw Damper V1 requires explicit negative yaw-rate feedback.');
end

function assignModelVariables(data,plant,controller)
assignin('base','yd1Data',data);
assignin('base','yd1Plant',plant);
assignin('base','yd1Controller',controller);
assignin('base','A_yd1',plant.A);
assignin('base','B_yd1',plant.B);
assignin('base','C_yd1',plant.C);
assignin('base','D_yd1',plant.D);
assignin('base','Kr_yd1',controller.rudderGain_s);
assignin('base','Tw_yd1',controller.washoutTimeConstant_s);
assignin('base','deltaACommand_yd1_rad',deg2rad(1.0));
assignin('base','deltaRCommand_yd1_rad',deg2rad(1.0));
assignin('base','x0_yd1',zeros(5,1));
assignin('base','xw0_yd1',0.0);
end

function buildDisplaySubsystem(path)
tags = {'yd1_beta','yd1_p','yd1_r','yd1_phi','yd1_psi', ...
    'yd1_deltaA_pilot','yd1_deltaR_pilot','yd1_r_washout', ...
    'yd1_deltaR_auto','yd1_deltaR_total'};
names = {'Beta','p','r','Phi','Psi','Aileron Pilot','Rudder Pilot', ...
    'Washout Yaw Rate','Automatic Rudder','Total Rudder'};

for k = 1:numel(tags)
    yPosition = 25 + 38*(k - 1);
    addFrom(path,names{k},tags{k},[25 yPosition 155 yPosition + 20]);
    add_block('simulink/Math Operations/Gain', ...
        [path '/' names{k} ' rad-to-deg'], ...
        'Gain','180/pi','Position',[185 yPosition - 5 270 yPosition + 25]);
    add_line(path,[names{k} '/1'],[names{k} ' rad-to-deg/1'], ...
        'autorouting','on');
end

add_block('simulink/Signal Routing/Mux',[path '/State Mux'], ...
    'Inputs','5','Position',[330 15 335 210]);
add_block('simulink/Sinks/Scope',[path '/State Scope'], ...
    'Position',[395 90 440 125]);
for k = 1:5
    add_line(path,[names{k} ' rad-to-deg/1'],sprintf('State Mux/%d',k), ...
        'autorouting','on');
end
add_line(path,'State Mux/1','State Scope/1','autorouting','on');

add_block('simulink/Signal Routing/Mux',[path '/Controller Mux'], ...
    'Inputs','5','Position',[330 225 335 405]);
add_block('simulink/Sinks/Scope',[path '/Controller Scope'], ...
    'Position',[395 300 440 335]);
for k = 6:10
    add_line(path,[names{k} ' rad-to-deg/1'], ...
        sprintf('Controller Mux/%d',k - 5),'autorouting','on');
end
add_line(path,'Controller Mux/1','Controller Scope/1','autorouting','on');
end

function clearDefaultSubsystem(path)
lines = find_system(path,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(path,'SearchDepth',1,'Type','Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end
