function modelName = buildC172sPitchAttitudeHoldSimulink(forceRebuild)
%BUILDC172SPITCHATTITUDEHOLDSIMULINK Build Pitch-Attitude Hold V1.
%
%   MODELNAME = BUILDC172SPITCHATTITUDEHOLDSIMULINK() creates or opens
%   C172S_PitchAttitudeHold_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SPITCHATTITUDEHOLDSIMULINK(true) overwrites the
%   generated model. Use false to preserve an existing model.
%
%   Controller architecture:
%
%       eTheta        = thetaFilteredCommand - theta
%       xiDot         = eTheta
%       deltaECommand = -Kp*eTheta - Ki*xi
%       deltaE        = deltaECommand + Kq*q + deltaEBias
%
%   Positive elevator is trailing-edge down. Therefore a positive attitude
%   error must produce a negative, trailing-edge-up elevator command.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_PitchAttitudeHold_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize variables used by the generated diagram

paData = c172sLongitudinalData();
[~,paPlant] = c172sLongitudinalPlant(paData);
paDamper = c172sPitchRateDamperData();
paController = c172sPitchAttitudeControllerData();

assignin('base','paData',paData);
assignin('base','paPlant',paPlant);
assignin('base','paDamper',paDamper);
assignin('base','paController',paController);
assignin('base','A_pa',paPlant.A);
assignin('base','B_pa',paPlant.B);
assignin('base','C_pa',paPlant.C);
assignin('base','D_pa',paPlant.D);
assignin('base','Kq_pa_s',paDamper.Kq_s);
assignin('base','Kp_pa',paController.Kp_radPerRad);
assignin('base','Ki_pa_per_s',paController.Ki_radPerRadPerS);
assignin('base','tauThetaCommand_pa_s', ...
    paController.commandFilterTimeConstant_s);
assignin('base','thetaCommandStep_pa_rad', ...
    deg2rad(paController.validation.commandStep_deg));
assignin('base','deltaEBias_pa_rad',0.0);
assignin('base','x0_pa',zeros(4,1));
assignin('base','xi0_pa',0.0);

%% Preserve an existing generated model unless rebuilding was requested

if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end

if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the model

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','60', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Reinitialize the nominal design whenever the diagram runs.
initCode = [ ...
    'paData = c172sLongitudinalData();' newline ...
    '[~, paPlant] = c172sLongitudinalPlant(paData);' newline ...
    'paDamper = c172sPitchRateDamperData();' newline ...
    'paController = c172sPitchAttitudeControllerData();' newline ...
    'A_pa = paPlant.A; B_pa = paPlant.B;' newline ...
    'C_pa = paPlant.C; D_pa = paPlant.D;' newline ...
    'Kq_pa_s = paDamper.Kq_s;' newline ...
    'Kp_pa = paController.Kp_radPerRad;' newline ...
    'Ki_pa_per_s = paController.Ki_radPerRadPerS;' newline ...
    'tauThetaCommand_pa_s = paController.commandFilterTimeConstant_s;' newline ...
    'thetaCommandStep_pa_rad = deg2rad(paController.validation.commandStep_deg);' newline ...
    'deltaEBias_pa_rad = 0.0;' newline ...
    'x0_pa = zeros(4,1); xi0_pa = 0.0;'];
set_param(modelName,'InitFcn',initCode);

%% Command filter, attitude PI, q damper and plant

add_block('simulink/Sources/Step', ...
    [modelName '/Pitch-Attitude Command'], ...
    'Time','0.0', ...
    'Before','0.0', ...
    'After','thetaCommandStep_pa_rad', ...
    'SampleTime','0', ...
    'Position',[35 145 105 175]);

add_block('simulink/Continuous/Transfer Fcn', ...
    [modelName '/Command Filter'], ...
    'Numerator','1', ...
    'Denominator','[tauThetaCommand_pa_s 1]', ...
    'Position',[145 137 255 183]);

add_block('simulink/Math Operations/Sum', ...
    [modelName '/Attitude Error'], ...
    'Inputs','+-', ...
    'Position',[300 142 330 178]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Proportional Gain -Kp'], ...
    'Gain','-Kp_pa', ...
    'Position',[380 100 485 135]);

add_block('simulink/Continuous/Integrator', ...
    [modelName '/Attitude Error Integrator'], ...
    'InitialCondition','xi0_pa', ...
    'Position',[380 205 410 235]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Integral Gain -Ki'], ...
    'Gain','-Ki_pa_per_s', ...
    'Position',[455 202 560 238]);

add_block('simulink/Math Operations/Sum', ...
    [modelName '/PI Elevator Command'], ...
    'Inputs','++', ...
    'Position',[610 140 640 180]);

add_block('simulink/Sources/Constant', ...
    [modelName '/Elevator Bias'], ...
    'Value','deltaEBias_pa_rad', ...
    'SampleTime','0', ...
    'Position',[610 265 680 295]);

add_block('simulink/Math Operations/Sum', ...
    [modelName '/Total Elevator Sum'], ...
    'Inputs','+++', ...
    'Position',[720 137 750 183]);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Longitudinal Plant'], ...
    'A','A_pa', ...
    'B','B_pa', ...
    'C','C_pa', ...
    'D','D_pa', ...
    'X0','x0_pa', ...
    'Position',[800 120 970 190]);

add_block('simulink/Signal Routing/Demux', ...
    [modelName '/State Demux'], ...
    'Outputs','4', ...
    'Position',[1025 92 1030 218]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Pitch-Rate Gain Kq'], ...
    'Gain','Kq_pa_s', ...
    'Position',[825 285 930 320]);

%% Tagged signal access, equivalence output and display subsystems

% Short local Goto/From connections keep the control architecture visible
% while moving verification and display plumbing out of the main diagram.
addGlobalGoto(modelName,'Command Tag','pa_theta_command',[45 230 125 250]);
addGlobalGoto(modelName,'Filtered Command Tag','pa_theta_filtered', ...
    [165 230 270 250]);
addGlobalGoto(modelName,'Integrator Tag','pa_xi',[445 260 510 280]);
addGlobalGoto(modelName,'PI Command Tag','pa_deltae_command', ...
    [585 225 700 245]);
addGlobalGoto(modelName,'Total Elevator Tag','pa_deltae_total', ...
    [720 225 825 245]);
addGlobalGoto(modelName,'u Tag','pa_u',[1060 75 1120 95]);
addGlobalGoto(modelName,'alpha Tag','pa_alpha',[1060 110 1120 130]);
addGlobalGoto(modelName,'q Tag','pa_q',[1060 145 1120 165]);
addGlobalGoto(modelName,'theta Tag','pa_theta',[1060 180 1120 200]);

addFrom(modelName,'Theta Feedback','pa_theta',[245 195 300 215]);
addFrom(modelName,'q Feedback','pa_q',[735 300 790 320]);

% Output order:
%   [u, alpha, q, theta, thetaFilteredCommand, xi,
%    deltaECommand, deltaETotal]
verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[1170 105 1305 165]);
delete_line(verificationPath,'In1/1','Out1/1');
delete_block([verificationPath '/In1']);
delete_block([verificationPath '/Out1']);

verificationTags = { ...
    'pa_u','pa_alpha','pa_q','pa_theta','pa_theta_filtered','pa_xi', ...
    'pa_deltae_command','pa_deltae_total'};
verificationNames = { ...
    'u','alpha','q','theta','Filtered Command','Integrator State', ...
    'PI Command','Total Elevator'};
for k = 1:numel(verificationTags)
    yPosition = 35 + 45*(k - 1);
    addFrom(verificationPath,verificationNames{k},verificationTags{k}, ...
        [35 yPosition 145 yPosition + 20]);
end
add_block('simulink/Signal Routing/Mux', ...
    [verificationPath '/Closed-Loop Signal Mux'], ...
    'Inputs','8','Position',[215 25 220 385]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[275 195 305 215]);
for k = 1:numel(verificationTags)
    add_line(verificationPath,sprintf('%s/1',verificationNames{k}), ...
        sprintf('Closed-Loop Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Closed-Loop Signal Mux/1','Signals/1', ...
    'autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Closed-Loop Signals'], ...
    'Port','1','Position',[1360 125 1390 145]);
add_line(modelName,'Verification Signals/1','Closed-Loop Signals/1', ...
    'autorouting','on');

displayPath = [modelName '/Display Scopes'];
add_block('simulink/Ports & Subsystems/Subsystem',displayPath, ...
    'Position',[1170 245 1305 305]);
delete_line(displayPath,'In1/1','Out1/1');
delete_block([displayPath '/In1']);
delete_block([displayPath '/Out1']);

addFrom(displayPath,'Command','pa_theta_command',[30 45 130 65]);
addFrom(displayPath,'Filtered Command','pa_theta_filtered',[30 95 130 115]);
addFrom(displayPath,'Theta','pa_theta',[30 145 130 165]);
addFrom(displayPath,'Pitch Rate','pa_q',[30 245 130 265]);
addFrom(displayPath,'Total Elevator','pa_deltae_total',[30 345 130 365]);

add_block('simulink/Math Operations/Gain',[displayPath '/Command rad-to-deg'], ...
    'Gain','180/pi','Position',[175 40 250 70]);
add_block('simulink/Math Operations/Gain', ...
    [displayPath '/Filtered Command rad-to-deg'], ...
    'Gain','180/pi','Position',[175 90 280 120]);
add_block('simulink/Math Operations/Gain',[displayPath '/Theta rad-to-deg'], ...
    'Gain','180/pi','Position',[175 140 250 170]);
add_block('simulink/Signal Routing/Mux',[displayPath '/Attitude Display Mux'], ...
    'Inputs','3','Position',[330 35 335 175]);
add_block('simulink/Sinks/Scope',[displayPath '/Attitude Tracking Scope'], ...
    'Position',[390 90 440 120]);
add_block('simulink/Math Operations/Gain',[displayPath '/q rad-to-deg'], ...
    'Gain','180/pi','Position',[175 240 250 270]);
add_block('simulink/Sinks/Scope',[displayPath '/Pitch-Rate Scope'], ...
    'Position',[390 240 440 270]);
add_block('simulink/Math Operations/Gain',[displayPath '/Elevator rad-to-deg'], ...
    'Gain','180/pi','Position',[175 340 260 370]);
add_block('simulink/Sinks/Scope',[displayPath '/Elevator Scope'], ...
    'Position',[390 340 440 370]);

add_line(displayPath,'Command/1','Command rad-to-deg/1','autorouting','on');
add_line(displayPath,'Command rad-to-deg/1','Attitude Display Mux/1', ...
    'autorouting','on');
add_line(displayPath,'Filtered Command/1','Filtered Command rad-to-deg/1', ...
    'autorouting','on');
add_line(displayPath,'Filtered Command rad-to-deg/1', ...
    'Attitude Display Mux/2','autorouting','on');
add_line(displayPath,'Theta/1','Theta rad-to-deg/1','autorouting','on');
add_line(displayPath,'Theta rad-to-deg/1','Attitude Display Mux/3', ...
    'autorouting','on');
add_line(displayPath,'Attitude Display Mux/1','Attitude Tracking Scope/1', ...
    'autorouting','on');
add_line(displayPath,'Pitch Rate/1','q rad-to-deg/1','autorouting','on');
add_line(displayPath,'q rad-to-deg/1','Pitch-Rate Scope/1', ...
    'autorouting','on');
add_line(displayPath,'Total Elevator/1','Elevator rad-to-deg/1', ...
    'autorouting','on');
add_line(displayPath,'Elevator rad-to-deg/1','Elevator Scope/1', ...
    'autorouting','on');

%% Connect and label the signals

h = add_line(modelName,'Pitch-Attitude Command/1','Command Filter/1', ...
    'autorouting','on');
set_param(h,'Name','theta command rad');

h = add_line(modelName,'Command Filter/1','Attitude Error/1', ...
    'autorouting','on');
set_param(h,'Name','filtered theta command rad');

h = add_line(modelName,'Attitude Error/1','Proportional Gain -Kp/1', ...
    'autorouting','on');
set_param(h,'Name','e theta rad');
add_line(modelName,'Attitude Error/1','Attitude Error Integrator/1', ...
    'autorouting','on');

add_line(modelName,'Proportional Gain -Kp/1','PI Elevator Command/1', ...
    'autorouting','on');
add_line(modelName,'Attitude Error Integrator/1','Integral Gain -Ki/1', ...
    'autorouting','on');
add_line(modelName,'Integral Gain -Ki/1','PI Elevator Command/2', ...
    'autorouting','on');

h = add_line(modelName,'PI Elevator Command/1','Total Elevator Sum/1', ...
    'autorouting','on');
set_param(h,'Name','delta_e command rad');

add_line(modelName,'Pitch-Rate Gain Kq/1','Total Elevator Sum/2', ...
    'autorouting','on');
add_line(modelName,'Elevator Bias/1','Total Elevator Sum/3', ...
    'autorouting','on');

h = add_line(modelName,'Total Elevator Sum/1', ...
    'C172S Longitudinal Plant/1','autorouting','on');
set_param(h,'Name','delta_e total rad, TE down positive');

h = add_line(modelName,'C172S Longitudinal Plant/1','State Demux/1', ...
    'autorouting','on');
set_param(h,'Name','x = [u alpha q theta]');

h = add_line(modelName,'Theta Feedback/1','Attitude Error/2', ...
    'autorouting','on');
set_param(h,'Name','theta feedback rad');

h = add_line(modelName,'q Feedback/1','Pitch-Rate Gain Kq/1', ...
    'autorouting','on');
set_param(h,'Name','q feedback rad/s');

% Feed the global signal tags with short branches from their sources.
add_line(modelName,'Pitch-Attitude Command/1','Command Tag/1', ...
    'autorouting','on');
add_line(modelName,'Command Filter/1','Filtered Command Tag/1', ...
    'autorouting','on');
add_line(modelName,'Attitude Error Integrator/1','Integrator Tag/1', ...
    'autorouting','on');
add_line(modelName,'PI Elevator Command/1','PI Command Tag/1', ...
    'autorouting','on');
add_line(modelName,'Total Elevator Sum/1','Total Elevator Tag/1', ...
    'autorouting','on');
add_line(modelName,'State Demux/1','u Tag/1','autorouting','on');
add_line(modelName,'State Demux/2','alpha Tag/1','autorouting','on');
add_line(modelName,'State Demux/3','q Tag/1','autorouting','on');
add_line(modelName,'State Demux/4','theta Tag/1','autorouting','on');

%% Diagram note

try
    note = Simulink.Annotation(modelName, ...
        ['Pitch-Attitude Hold V1: filtered-command PI around frozen q damper' newline ...
         'Kp = 0.450, Ki = 0.450 1/s, Kq = 0.110 s, tauCmd = 2.0 s' newline ...
         '1 deg sustained command; |u|/Vtrim and |alpha| envelope gates enabled' newline ...
         'Positive attitude error commands trailing-edge-up elevator']);
    note.Position = [35 25 850 100];
catch
    % Annotation appearance is nonessential to the executable model.
end

save_system(modelName,modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runPitchAttitudeHoldSimulinkCheck to validate the loop.\n');

end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end
