function modelName = buildC172sPitchRateDamperSimulink(forceRebuild)
%BUILDC172SPITCHRATEDAMPERSIMULINK Build the inner-loop q-damper model.
%
%   MODELNAME = BUILDC172SPITCHRATEDAMPERSIMULINK() creates or opens
%   C172S_PitchRateDamper_V1.slx in the current folder.
%
%   MODELNAME = BUILDC172SPITCHRATEDAMPERSIMULINK(true) overwrites the
%   generated model. Use false to preserve an existing model.
%
%   Feedback law, using the project sign convention:
%
%       deltaE = deltaECommand + Kq*q
%
%   Positive elevator is trailing-edge down. The verification case uses
%   zero commanded elevator and an initial pitch rate of +5 deg/s.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_PitchRateDamper_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize the variables used by the generated diagram

qdData = c172sLongitudinalData();
[~,qdPlant] = c172sLongitudinalPlant(qdData);
qdDamper = c172sPitchRateDamperData();

assignin('base','qdData',qdData);
assignin('base','qdPlant',qdPlant);
assignin('base','qdDamper',qdDamper);
assignin('base','A_qd',qdPlant.A);
assignin('base','B_qd',qdPlant.B);
assignin('base','C_qd',qdPlant.C);
assignin('base','D_qd',qdPlant.D);
assignin('base','Kq_pitchRate_s',qdDamper.Kq_s);
assignin('base','qd_deltaECommand_rad',0.0);
assignin('base','x0_qd',[0;0;deg2rad(5.0);0]);

%% Preserve an existing generated model unless rebuilding was requested

if bdIsLoaded(modelName)
    close_system(modelName,0);
end

if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end

if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the model

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.01', ...
    'StartTime','0', ...
    'StopTime','12', ...
    'SaveTime','on', ...
    'TimeSaveName','tout', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Array');

% Reinitialize the nominal plant and controller whenever the diagram runs.
initCode = [ ...
    'qdData = c172sLongitudinalData();' newline ...
    '[~, qdPlant] = c172sLongitudinalPlant(qdData);' newline ...
    'qdDamper = c172sPitchRateDamperData();' newline ...
    'A_qd = qdPlant.A; B_qd = qdPlant.B;' newline ...
    'C_qd = qdPlant.C; D_qd = qdPlant.D;' newline ...
    'Kq_pitchRate_s = qdDamper.Kq_s;' newline ...
    'qd_deltaECommand_rad = 0.0;' newline ...
    'x0_qd = [0; 0; deg2rad(5.0); 0];'];
set_param(modelName,'InitFcn',initCode);

%% Command, q-feedback loop and longitudinal plant

add_block('simulink/Sources/Constant', ...
    [modelName '/Elevator Command'], ...
    'Value','qd_deltaECommand_rad', ...
    'SampleTime','0', ...
    'Position',[35 128 95 162]);

add_block('simulink/Math Operations/Sum', ...
    [modelName '/Elevator Sum'], ...
    'Inputs','++', ...
    'Position',[155 123 185 167]);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Longitudinal Plant'], ...
    'A','A_qd', ...
    'B','B_qd', ...
    'C','C_qd', ...
    'D','D_qd', ...
    'X0','x0_qd', ...
    'Position',[250 110 420 180]);

add_block('simulink/Signal Routing/Demux', ...
    [modelName '/State Demux'], ...
    'Outputs','4', ...
    'Position',[485 90 490 200]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Pitch-Rate Gain Kq'], ...
    'Gain','Kq_pitchRate_s', ...
    'Position',[315 285 415 325]);

add_block('simulink/Sinks/Out1', ...
    [modelName '/State Vector'], ...
    'Port','1', ...
    'Position',[850 125 880 145]);

%% Display paths

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Applied Elevator rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[250 215 335 245]);

add_block('simulink/Sinks/Scope', ...
    [modelName '/Applied Elevator Scope'], ...
    'Position',[385 215 435 245]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/q rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[565 250 635 280]);

add_block('simulink/Math Operations/Gain', ...
    [modelName '/Theta rad-to-deg'], ...
    'Gain','180/pi', ...
    'Position',[565 315 635 345]);

add_block('simulink/Signal Routing/Mux', ...
    [modelName '/Pitch Display Mux'], ...
    'Inputs','2', ...
    'Position',[705 260 710 340]);

add_block('simulink/Sinks/Scope', ...
    [modelName '/Pitch Motion Scope'], ...
    'Position',[790 285 840 315]);

%% Connect and label the signals

h = add_line(modelName,'Elevator Command/1','Elevator Sum/1', ...
    'autorouting','on');
set_param(h,'Name','delta_e command rad');

h = add_line(modelName,'Elevator Sum/1','C172S Longitudinal Plant/1', ...
    'autorouting','on');
set_param(h,'Name','delta_e applied rad, TE down positive');

add_line(modelName,'Elevator Sum/1','Applied Elevator rad-to-deg/1', ...
    'autorouting','on');
add_line(modelName,'Applied Elevator rad-to-deg/1', ...
    'Applied Elevator Scope/1','autorouting','on');

h = add_line(modelName,'C172S Longitudinal Plant/1','State Vector/1', ...
    'autorouting','on');
set_param(h,'Name','x = [u alpha q theta]');

add_line(modelName,'C172S Longitudinal Plant/1','State Demux/1', ...
    'autorouting','on');

h = add_line(modelName,'State Demux/3','Pitch-Rate Gain Kq/1', ...
    'autorouting','on');
set_param(h,'Name','q rad/s');

h = add_line(modelName,'Pitch-Rate Gain Kq/1','Elevator Sum/2', ...
    'autorouting','on');
set_param(h,'Name','Kq q, damping elevator rad');

add_line(modelName,'State Demux/3','q rad-to-deg/1', ...
    'autorouting','on');
add_line(modelName,'q rad-to-deg/1','Pitch Display Mux/1', ...
    'autorouting','on');

add_line(modelName,'State Demux/4','Theta rad-to-deg/1', ...
    'autorouting','on');
add_line(modelName,'Theta rad-to-deg/1','Pitch Display Mux/2', ...
    'autorouting','on');
add_line(modelName,'Pitch Display Mux/1','Pitch Motion Scope/1', ...
    'autorouting','on');

%% Diagram note

try
    note = Simulink.Annotation(modelName, ...
        ['Pitch-Rate Damper V1: deltaE = deltaECommand + Kq*q' newline ...
         'Kq = 0.110 s; positive elevator is trailing-edge down' newline ...
         'Verification: q(0) = +5 deg/s; deltaECommand = 0']);
    note.Position = [35 25 600 78];
catch
    % Annotation appearance is nonessential to the executable model.
end

save_system(modelName,modelFile);
open_system(modelName);

fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runPitchRateDamperSimulinkCheck to validate the loop.\n');

end
