function modelName = buildC172sAltitudeHoldSimulink(forceRebuild)
%BUILDC172SALTITUDEHOLDSIMULINK Build the validated Altitude Hold V1 model.
%
%   The generated model wraps the frozen actuator-protected Pitch-Attitude
%   Hold V2 inner loop with the validated filtered altitude-reference,
%   bounded vertical-speed-command and bounded pitch-command outer loop.

arguments
    forceRebuild (1,1) logical = false
end

modelName = 'C172S_AltitudeHold_V1';
modelFile = fullfile(pwd,[modelName '.slx']);

%% Initialize model variables

ah1Data = c172sLongitudinalData();
[~,ah1Plant] = c172sLongitudinalPlant(ah1Data);
ah1PitchController = c172sPitchAttitudeControllerData();
ah1Actuator = c172sElevatorActuatorData();
ah1AltitudeController = c172sAltitudeHoldControllerData();

assignModelVariables(ah1Data,ah1Plant,ah1PitchController, ...
    ah1Actuator,ah1AltitudeController);

% Always close the in-memory diagram first. This prevents an interrupted
% earlier builder run from leaving a partial model loaded.
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
if isfile(modelFile) && ~forceRebuild
    load_system(modelFile);
    open_system(modelName);
    fprintf('Opened existing model: %s\n',modelFile);
    return;
end
if isfile(modelFile) && forceRebuild
    delete(modelFile);
end

%% Create and configure the model

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step','Solver','ode4','FixedStep','0.02', ...
    'StartTime','0','StopTime','180','SaveTime','on', ...
    'TimeSaveName','tout','SaveOutput','on','OutputSaveName','yout', ...
    'SaveFormat','Array');

initCode = [ ...
    'ah1Data = c172sLongitudinalData();' newline ...
    '[~,ah1Plant] = c172sLongitudinalPlant(ah1Data);' newline ...
    'ah1PitchController = c172sPitchAttitudeControllerData();' newline ...
    'ah1Actuator = c172sElevatorActuatorData();' newline ...
    'ah1AltitudeController = c172sAltitudeHoldControllerData();' newline ...
    'A_ah1 = ah1Plant.A; B_ah1 = ah1Plant.B;' newline ...
    'C_ah1 = ah1Plant.C; D_ah1 = ah1Plant.D;' newline ...
    'Vtrim_ah1_mps = ah1Data.trim.V_mps;' newline ...
    'Kh_ah1_per_s = ah1AltitudeController.altitudeGain_per_s;' newline ...
    'Kv_ah1_radPerMps = ah1AltitudeController.verticalSpeedGain_radPerMps;' newline ...
    'tauAltitude_ah1_s = ah1AltitudeController.commandFilterTimeConstant_s;' newline ...
    'hDotLimit_ah1_mps = ah1AltitudeController.verticalSpeedCommandLimit_mps;' newline ...
    'thetaLimit_ah1_rad = ah1AltitudeController.pitchCommandLimit_rad;' newline ...
    'Kp_ah1 = ah1PitchController.Kp_radPerRad;' newline ...
    'Ki_ah1_per_s = ah1PitchController.Ki_radPerRadPerS;' newline ...
    'Kq_ah1_s = ah1Actuator.integration.Kq_s;' newline ...
    'tauTheta_ah1_s = ah1PitchController.commandFilterTimeConstant_s;' newline ...
    'tauActuator_ah1_s = ah1Actuator.dynamics.timeConstant_s;' newline ...
    'Tt_ah1_s = ah1Actuator.antiWindup.trackingTimeConstant_s;' newline ...
    'deltaELower_ah1_rad = ah1Actuator.authority.lowerLimit_rad;' newline ...
    'deltaEUpper_ah1_rad = ah1Actuator.authority.upperLimit_rad;' newline ...
    'deltaERate_ah1_radps = deg2rad(ah1Actuator.dynamics.rateLimit_degps);' newline ...
    'if ~exist(''hCommand_ah1_m'',''var''), hCommand_ah1_m = ah1AltitudeController.validation.operationalCommand_m; end' newline ...
    'if ~exist(''antiWindupEnable_ah1'',''var''), antiWindupEnable_ah1 = 1.0; end' newline ...
    'if ~exist(''x0_ah1'',''var''), x0_ah1 = zeros(4,1); end' newline ...
    'if ~exist(''xi0_ah1'',''var''), xi0_ah1 = 0.0; end' newline ...
    'if ~exist(''deltaE0_ah1'',''var''), deltaE0_ah1 = 0.0; end' newline ...
    'if ~exist(''h0_ah1_m'',''var''), h0_ah1_m = 0.0; end'];
set_param(modelName,'InitFcn',initCode);

%% Altitude and vertical-speed outer loop

add_block('simulink/Sources/Step',[modelName '/Altitude Command'], ...
    'Time','0','Before','0','After','hCommand_ah1_m', ...
    'SampleTime','0','Position',[35 125 105 155]);
add_block('simulink/Continuous/Transfer Fcn', ...
    [modelName '/Altitude Command Filter'], ...
    'Numerator','1','Denominator','[tauAltitude_ah1_s 1]', ...
    'Position',[145 115 275 165]);
add_block('simulink/Math Operations/Sum',[modelName '/Altitude Error'], ...
    'Inputs','+-','Position',[325 120 355 160]);
add_block('simulink/Math Operations/Gain',[modelName '/Altitude Gain Kh'], ...
    'Gain','Kh_ah1_per_s','Position',[400 110 510 150]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Vertical-Speed Command Limit'], ...
    'UpperLimit','hDotLimit_ah1_mps','LowerLimit','-hDotLimit_ah1_mps', ...
    'Position',[560 105 690 155]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Vertical-Speed Error'], ...
    'Inputs','+-','Position',[740 110 770 150]);
add_block('simulink/Math Operations/Gain', ...
    [modelName '/Vertical-Speed Gain Kv'], ...
    'Gain','Kv_ah1_radPerMps','Position',[815 105 940 155]);
add_block('simulink/Discontinuities/Saturation', ...
    [modelName '/Pitch-Command Limit'], ...
    'UpperLimit','thetaLimit_ah1_rad','LowerLimit','-thetaLimit_ah1_rad', ...
    'Position',[990 105 1110 155]);

%% Frozen Pitch-Attitude Hold V2 inner loop

add_block('simulink/Continuous/Transfer Fcn', ...
    [modelName '/Pitch Command Filter'], ...
    'Numerator','1','Denominator','[tauTheta_ah1_s 1]', ...
    'Position',[1160 105 1280 155]);
add_block('simulink/Math Operations/Sum',[modelName '/Attitude Error'], ...
    'Inputs','+-','Position',[1330 110 1360 150]);
add_block('simulink/Math Operations/Gain',[modelName '/Proportional Gain -Kp'], ...
    'Gain','-Kp_ah1','Position',[1410 65 1520 100]);
add_block('simulink/Math Operations/Sum',[modelName '/Integrator Input'], ...
    'Inputs','++','Position',[1405 205 1435 245]);
add_block('simulink/Continuous/Integrator',[modelName '/Error Integrator'], ...
    'InitialCondition','xi0_ah1','Position',[1480 210 1510 240]);
add_block('simulink/Math Operations/Gain',[modelName '/Integral Gain -Ki'], ...
    'Gain','-Ki_ah1_per_s','Position',[1555 205 1665 245]);
add_block('simulink/Math Operations/Sum',[modelName '/PI Elevator Command'], ...
    'Inputs','++','Position',[1710 110 1740 150]);
add_block('simulink/Math Operations/Gain',[modelName '/Pitch-Rate Gain Kq'], ...
    'Gain','Kq_ah1_s','Position',[1560 310 1670 345]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Unsaturated Total Command'], ...
    'Inputs','++','Position',[1790 110 1820 150]);

actuatorPath = [modelName '/Actuator and Anti-Windup'];
add_block('simulink/Ports & Subsystems/Subsystem',actuatorPath, ...
    'Position',[1870 95 2010 165]);
buildActuatorSubsystem(actuatorPath);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/C172S Longitudinal Plant'], ...
    'A','A_ah1','B','B_ah1','C','C_ah1','D','D_ah1','X0','x0_ah1', ...
    'Position',[2060 95 2220 165]);
add_block('simulink/Signal Routing/Demux',[modelName '/State Demux'], ...
    'Outputs','4','Position',[2270 65 2275 195]);

%% Altitude kinematics

add_block('simulink/Math Operations/Sum',[modelName '/Flight-Path Angle'], ...
    'Inputs','+-','Position',[2320 285 2350 325]);
add_block('simulink/Math Operations/Gain',[modelName '/Vertical Speed'], ...
    'Gain','Vtrim_ah1_mps','Position',[2400 280 2510 330]);
add_block('simulink/Continuous/Integrator',[modelName '/Altitude'], ...
    'InitialCondition','h0_ah1_m','Position',[2570 290 2600 320]);

%% Global signal tags and feedback access

tagDefinitions = { ...
    'Altitude Command Tag','ah1_h_command',[45 210 145 230]; ...
    'Filtered Altitude Tag','ah1_h_filtered',[165 210 285 230]; ...
    'Altitude Tag','ah1_h',[2635 290 2700 310]; ...
    'Raw Vertical-Speed Command Tag','ah1_hdot_raw',[430 190 565 210]; ...
    'Vertical-Speed Command Tag','ah1_hdot_command',[580 190 720 210]; ...
    'Vertical Speed Tag','ah1_hdot',[2430 360 2520 380]; ...
    'Raw Pitch Command Tag','ah1_theta_raw',[820 190 950 210]; ...
    'Pitch Command Tag','ah1_theta_command',[995 190 1115 210]; ...
    'Filtered Pitch Command Tag','ah1_theta_filtered',[1160 190 1300 210]; ...
    'Integrator Tag','ah1_xi',[1480 275 1560 295]; ...
    'Unsaturated Command Tag','ah1_unsat',[1785 205 1900 225]; ...
    'Position Command Tag','ah1_position_command',[1875 250 2015 270]; ...
    'Actual Elevator Tag','ah1_actual',[2030 225 2130 245]; ...
    'Elevator Rate Tag','ah1_rate',[2030 270 2130 290]; ...
    'Anti-Windup Tag','ah1_aw',[1750 300 1840 320]; ...
    'u Tag','ah1_u',[2310 35 2370 55]; ...
    'alpha Tag','ah1_alpha',[2310 75 2370 95]; ...
    'q Tag','ah1_q',[2310 115 2370 135]; ...
    'theta Tag','ah1_theta',[2310 155 2370 175]};
for k = 1:size(tagDefinitions,1)
    addGlobalGoto(modelName,tagDefinitions{k,1},tagDefinitions{k,2}, ...
        tagDefinitions{k,3});
end

addFrom(modelName,'Altitude Feedback','ah1_h',[285 175 355 195]);
addFrom(modelName,'Vertical-Speed Feedback','ah1_hdot',[690 175 770 195]);
addFrom(modelName,'Theta Feedback','ah1_theta',[1280 165 1360 185]);
addFrom(modelName,'q Feedback','ah1_q',[1485 315 1540 335]);
addFrom(modelName,'Anti-Windup Feedback','ah1_aw',[1310 220 1405 240]);
addFrom(modelName,'Theta Kinematics','ah1_theta',[2180 285 2260 305]);
addFrom(modelName,'Alpha Kinematics','ah1_alpha',[2180 325 2260 345]);

%% Connect the main diagram

connectNamed(modelName,'Altitude Command/1','Altitude Command Filter/1', ...
    'altitude command m');
connectNamed(modelName,'Altitude Command Filter/1','Altitude Error/1', ...
    'filtered altitude command m');
add_line(modelName,'Altitude Feedback/1','Altitude Error/2','autorouting','on');
connectNamed(modelName,'Altitude Error/1','Altitude Gain Kh/1', ...
    'altitude error m');
add_line(modelName,'Altitude Gain Kh/1','Vertical-Speed Command Limit/1', ...
    'autorouting','on');
connectNamed(modelName,'Vertical-Speed Command Limit/1', ...
    'Vertical-Speed Error/1','vertical-speed command m/s');
add_line(modelName,'Vertical-Speed Feedback/1','Vertical-Speed Error/2', ...
    'autorouting','on');
add_line(modelName,'Vertical-Speed Error/1','Vertical-Speed Gain Kv/1', ...
    'autorouting','on');
add_line(modelName,'Vertical-Speed Gain Kv/1','Pitch-Command Limit/1', ...
    'autorouting','on');
connectNamed(modelName,'Pitch-Command Limit/1','Pitch Command Filter/1', ...
    'pitch command rad');
add_line(modelName,'Pitch Command Filter/1','Attitude Error/1', ...
    'autorouting','on');
add_line(modelName,'Theta Feedback/1','Attitude Error/2','autorouting','on');
add_line(modelName,'Attitude Error/1','Proportional Gain -Kp/1', ...
    'autorouting','on');
add_line(modelName,'Attitude Error/1','Integrator Input/1','autorouting','on');
add_line(modelName,'Anti-Windup Feedback/1','Integrator Input/2', ...
    'autorouting','on');
add_line(modelName,'Integrator Input/1','Error Integrator/1','autorouting','on');
add_line(modelName,'Error Integrator/1','Integral Gain -Ki/1','autorouting','on');
add_line(modelName,'Proportional Gain -Kp/1','PI Elevator Command/1', ...
    'autorouting','on');
add_line(modelName,'Integral Gain -Ki/1','PI Elevator Command/2', ...
    'autorouting','on');
add_line(modelName,'q Feedback/1','Pitch-Rate Gain Kq/1','autorouting','on');
add_line(modelName,'PI Elevator Command/1','Unsaturated Total Command/1', ...
    'autorouting','on');
add_line(modelName,'Pitch-Rate Gain Kq/1','Unsaturated Total Command/2', ...
    'autorouting','on');
connectNamed(modelName,'Unsaturated Total Command/1', ...
    'Actuator and Anti-Windup/1','delta e unsaturated rad');
connectNamed(modelName,'Actuator and Anti-Windup/1', ...
    'C172S Longitudinal Plant/1','delta e actual rad');
connectNamed(modelName,'C172S Longitudinal Plant/1','State Demux/1', ...
    'x = [u alpha q theta]');
add_line(modelName,'Theta Kinematics/1','Flight-Path Angle/1', ...
    'autorouting','on');
add_line(modelName,'Alpha Kinematics/1','Flight-Path Angle/2', ...
    'autorouting','on');
connectNamed(modelName,'Flight-Path Angle/1','Vertical Speed/1', ...
    'gamma = theta - alpha rad');
connectNamed(modelName,'Vertical Speed/1','Altitude/1','h dot m/s');

% Local branches into the global signal-tag network.
branchTo(modelName,'Altitude Command/1','Altitude Command Tag/1');
branchTo(modelName,'Altitude Command Filter/1','Filtered Altitude Tag/1');
branchTo(modelName,'Altitude Gain Kh/1','Raw Vertical-Speed Command Tag/1');
branchTo(modelName,'Vertical-Speed Command Limit/1', ...
    'Vertical-Speed Command Tag/1');
branchTo(modelName,'Vertical-Speed Gain Kv/1','Raw Pitch Command Tag/1');
branchTo(modelName,'Pitch-Command Limit/1','Pitch Command Tag/1');
branchTo(modelName,'Pitch Command Filter/1','Filtered Pitch Command Tag/1');
branchTo(modelName,'Error Integrator/1','Integrator Tag/1');
branchTo(modelName,'Unsaturated Total Command/1','Unsaturated Command Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/2','Anti-Windup Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/3','Position Command Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/1','Actual Elevator Tag/1');
branchTo(modelName,'Actuator and Anti-Windup/4','Elevator Rate Tag/1');
branchTo(modelName,'Vertical Speed/1','Vertical Speed Tag/1');
branchTo(modelName,'Altitude/1','Altitude Tag/1');
stateTagBlockNames = {'u Tag','alpha Tag','q Tag','theta Tag'};
for k = 1:4
    branchTo(modelName,sprintf('State Demux/%d',k), ...
        [stateTagBlockNames{k} '/1']);
end

%% Verification and display subsystems

verificationPath = [modelName '/Verification Signals'];
add_block('simulink/Ports & Subsystems/Subsystem',verificationPath, ...
    'Position',[2750 80 2900 150]);
clearDefaultSubsystem(verificationPath);
verificationTags = {'ah1_u','ah1_alpha','ah1_q','ah1_theta','ah1_xi', ...
    'ah1_theta_filtered','ah1_actual','ah1_h','ah1_h_filtered', ...
    'ah1_hdot','ah1_hdot_raw','ah1_hdot_command','ah1_theta_raw', ...
    'ah1_theta_command','ah1_unsat','ah1_position_command', ...
    'ah1_rate','ah1_aw'};
verificationNames = {'u','alpha','q','theta','Integrator State', ...
    'Filtered Pitch Command','Actual Elevator','Altitude', ...
    'Filtered Altitude Command','Vertical Speed', ...
    'Raw Vertical-Speed Command','Vertical-Speed Command', ...
    'Raw Pitch Command','Pitch Command','Unsaturated Command', ...
    'Position Command','Elevator Rate','AW Correction'};
for k = 1:numel(verificationTags)
    yPosition = 20 + 32*(k - 1);
    addFrom(verificationPath,verificationNames{k},verificationTags{k}, ...
        [20 yPosition 155 yPosition + 20]);
end
add_block('simulink/Signal Routing/Mux',[verificationPath '/Signal Mux'], ...
    'Inputs',num2str(numel(verificationTags)), ...
    'Position',[235 10 240 590]);
add_block('simulink/Sinks/Out1',[verificationPath '/Signals'], ...
    'Port','1','Position',[300 285 330 305]);
for k = 1:numel(verificationTags)
    add_line(verificationPath,sprintf('%s/1',verificationNames{k}), ...
        sprintf('Signal Mux/%d',k),'autorouting','on');
end
add_line(verificationPath,'Signal Mux/1','Signals/1','autorouting','on');

add_block('simulink/Sinks/Out1',[modelName '/Closed-Loop Signals'], ...
    'Port','1','Position',[2960 100 2990 120]);
add_line(modelName,'Verification Signals/1','Closed-Loop Signals/1', ...
    'autorouting','on');

displayPath = [modelName '/Display Scopes'];
add_block('simulink/Ports & Subsystems/Subsystem',displayPath, ...
    'Position',[2750 230 2900 300]);
clearDefaultSubsystem(displayPath);
buildDisplaySubsystem(displayPath);

%% Diagram note and save

try
    note = Simulink.Annotation(modelName, ...
        ['Altitude Hold V1: bounded outer loop around frozen Pitch-Attitude Hold V2' newline ...
         'hDot = Vtrim*(theta - alpha); Kh = 0.600 1/s; Kv = 0.020 rad/(m/s)' newline ...
         'Altitude filter = 5 s; hDot command = +/-300 ft/min; pitch command = +/-3 deg' newline ...
         'Outer-loop and actuator parameters are transparent project engineering assumptions']);
    note.Position = [35 20 1120 85];
catch
end

save_system(modelName,modelFile);
open_system(modelName);
fprintf('Created Simulink model: %s\n',modelFile);
fprintf('Run runAltitudeHoldSimulinkCheck to validate Altitude Hold V1.\n');

end

function assignModelVariables(data,plant,pitchController,actuator,altitude)
assignin('base','ah1Data',data);
assignin('base','ah1Plant',plant);
assignin('base','ah1PitchController',pitchController);
assignin('base','ah1Actuator',actuator);
assignin('base','ah1AltitudeController',altitude);
assignin('base','A_ah1',plant.A);
assignin('base','B_ah1',plant.B);
assignin('base','C_ah1',plant.C);
assignin('base','D_ah1',plant.D);
assignin('base','Vtrim_ah1_mps',data.trim.V_mps);
assignin('base','Kh_ah1_per_s',altitude.altitudeGain_per_s);
assignin('base','Kv_ah1_radPerMps',altitude.verticalSpeedGain_radPerMps);
assignin('base','tauAltitude_ah1_s',altitude.commandFilterTimeConstant_s);
assignin('base','hDotLimit_ah1_mps',altitude.verticalSpeedCommandLimit_mps);
assignin('base','thetaLimit_ah1_rad',altitude.pitchCommandLimit_rad);
assignin('base','Kp_ah1',pitchController.Kp_radPerRad);
assignin('base','Ki_ah1_per_s',pitchController.Ki_radPerRadPerS);
assignin('base','Kq_ah1_s',actuator.integration.Kq_s);
assignin('base','tauTheta_ah1_s',pitchController.commandFilterTimeConstant_s);
assignin('base','tauActuator_ah1_s',actuator.dynamics.timeConstant_s);
assignin('base','Tt_ah1_s',actuator.antiWindup.trackingTimeConstant_s);
assignin('base','deltaELower_ah1_rad',actuator.authority.lowerLimit_rad);
assignin('base','deltaEUpper_ah1_rad',actuator.authority.upperLimit_rad);
assignin('base','deltaERate_ah1_radps', ...
    deg2rad(actuator.dynamics.rateLimit_degps));
assignin('base','hCommand_ah1_m',altitude.validation.operationalCommand_m);
assignin('base','antiWindupEnable_ah1',1.0);
assignin('base','x0_ah1',zeros(4,1));
assignin('base','xi0_ah1',0.0);
assignin('base','deltaE0_ah1',0.0);
assignin('base','h0_ah1_m',0.0);
end

function buildActuatorSubsystem(path)
clearDefaultSubsystem(path);
add_block('simulink/Sources/In1',[path '/Unsaturated Command'], ...
    'Port','1','Position',[25 70 55 90]);
add_block('simulink/Discontinuities/Saturation',[path '/Position Authority'], ...
    'UpperLimit','deltaEUpper_ah1_rad','LowerLimit','deltaELower_ah1_rad', ...
    'Position',[100 60 205 100]);
add_block('simulink/Math Operations/Sum',[path '/Position Error'], ...
    'Inputs','+-','Position',[245 65 275 95]);
add_block('simulink/Math Operations/Gain',[path '/Raw Rate'], ...
    'Gain','1/tauActuator_ah1_s','Position',[315 60 405 100]);
add_block('simulink/Discontinuities/Saturation',[path '/Rate Limit'], ...
    'UpperLimit','deltaERate_ah1_radps','LowerLimit','-deltaERate_ah1_radps', ...
    'Position',[445 60 535 100]);
add_block('simulink/Continuous/Integrator',[path '/Actual Elevator'], ...
    'InitialCondition','deltaE0_ah1','Position',[585 65 615 95]);
add_block('simulink/Math Operations/Gain',[path '/Reachable Increment'], ...
    'Gain','tauActuator_ah1_s','Position',[445 165 540 195]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Reference'], ...
    'Inputs','++','Position',[585 160 615 200]);
add_block('simulink/Math Operations/Sum',[path '/Tracking Mismatch'], ...
    'Inputs','+-','Position',[660 160 690 200]);
add_block('simulink/Math Operations/Gain',[path '/Back Calculation'], ...
    'Gain','antiWindupEnable_ah1/(Ki_ah1_per_s*Tt_ah1_s)', ...
    'Position',[735 155 875 205]);
add_block('simulink/Sinks/Out1',[path '/Actual'], ...
    'Port','1','Position',[930 55 960 75]);
add_block('simulink/Sinks/Out1',[path '/AW Correction'], ...
    'Port','2','Position',[930 155 960 175]);
add_block('simulink/Sinks/Out1',[path '/Position Command'], ...
    'Port','3','Position',[930 105 960 125]);
add_block('simulink/Sinks/Out1',[path '/Limited Rate'], ...
    'Port','4','Position',[930 205 960 225]);

add_line(path,'Unsaturated Command/1','Position Authority/1','autorouting','on');
add_line(path,'Position Authority/1','Position Error/1','autorouting','on');
add_line(path,'Position Error/1','Raw Rate/1','autorouting','on');
add_line(path,'Raw Rate/1','Rate Limit/1','autorouting','on');
add_line(path,'Rate Limit/1','Actual Elevator/1','autorouting','on');
add_line(path,'Actual Elevator/1','Position Error/2','autorouting','on');
add_line(path,'Rate Limit/1','Reachable Increment/1','autorouting','on');
add_line(path,'Actual Elevator/1','Tracking Reference/1','autorouting','on');
add_line(path,'Reachable Increment/1','Tracking Reference/2','autorouting','on');
add_line(path,'Unsaturated Command/1','Tracking Mismatch/1','autorouting','on');
add_line(path,'Tracking Reference/1','Tracking Mismatch/2','autorouting','on');
add_line(path,'Tracking Mismatch/1','Back Calculation/1','autorouting','on');
add_line(path,'Actual Elevator/1','Actual/1','autorouting','on');
add_line(path,'Back Calculation/1','AW Correction/1','autorouting','on');
add_line(path,'Position Authority/1','Position Command/1','autorouting','on');
add_line(path,'Rate Limit/1','Limited Rate/1','autorouting','on');
end

function buildDisplaySubsystem(path)
tags = {'ah1_h_command','ah1_h_filtered','ah1_h','ah1_hdot_command', ...
    'ah1_hdot','ah1_theta_command','ah1_theta','ah1_unsat','ah1_actual'};
names = {'Altitude Command','Filtered Altitude','Altitude', ...
    'Vertical-Speed Command','Vertical Speed','Pitch Command','Pitch', ...
    'Elevator Demand','Actual Elevator'};
for k = 1:numel(tags)
    yPosition = 20 + 35*(k - 1);
    addFrom(path,names{k},tags{k},[20 yPosition 145 yPosition + 20]);
end
add_block('simulink/Signal Routing/Mux',[path '/Altitude Mux'], ...
    'Inputs','3','Position',[210 20 215 115]);
add_block('simulink/Sinks/Scope',[path '/Altitude Scope'], ...
    'Position',[275 55 305 85]);
for k = 1:3
    add_line(path,sprintf('%s/1',names{k}),sprintf('Altitude Mux/%d',k), ...
        'autorouting','on');
end
add_line(path,'Altitude Mux/1','Altitude Scope/1','autorouting','on');

add_block('simulink/Signal Routing/Mux',[path '/Outer Loop Mux'], ...
    'Inputs','4','Position',[210 125 215 250]);
add_block('simulink/Sinks/Scope',[path '/Outer Loop Scope'], ...
    'Position',[275 175 305 205]);
for k = 4:7
    add_line(path,sprintf('%s/1',names{k}), ...
        sprintf('Outer Loop Mux/%d',k - 3),'autorouting','on');
end
add_line(path,'Outer Loop Mux/1','Outer Loop Scope/1','autorouting','on');

add_block('simulink/Signal Routing/Mux',[path '/Elevator Mux'], ...
    'Inputs','2','Position',[210 265 215 330]);
add_block('simulink/Sinks/Scope',[path '/Elevator Scope'], ...
    'Position',[275 285 305 315]);
for k = 8:9
    add_line(path,sprintf('%s/1',names{k}), ...
        sprintf('Elevator Mux/%d',k - 7),'autorouting','on');
end
add_line(path,'Elevator Mux/1','Elevator Scope/1','autorouting','on');
end

function clearDefaultSubsystem(path)
lines = find_system(path,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines)
    delete_line(lines);
end
blocks = find_system(path,'SearchDepth',1,'Type','Block');
for k = 2:numel(blocks)
    delete_block(blocks{k});
end
end

function addGlobalGoto(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/Goto',[systemName '/' blockName], ...
    'GotoTag',tagName,'TagVisibility','global','Position',position);
end

function addFrom(systemName,blockName,tagName,position)
add_block('simulink/Signal Routing/From',[systemName '/' blockName], ...
    'GotoTag',tagName,'Position',position);
end

function connectNamed(systemName,source,destination,name)
h = add_line(systemName,source,destination,'autorouting','on');
set_param(h,'Name',name);
end

function branchTo(systemName,source,destination)
add_line(systemName,source,destination,'autorouting','on');
end