function integration = c172sIntegratedAutopilotData()
%C172SINTEGRATEDAUTOPILOTDATA Integrated Autopilot V1 release contract.
%
% This ledger defines the boundary for joining the already validated
% longitudinal, lateral-directional and supervisory artifacts. It does not
% introduce a new gain or claim a coupled six-degree-of-freedom aircraft.

integration.version = 'Integrated Autopilot V1';
integration.artifactRevision = ...
    'INTEGRATED-AUTOPILOT-V1-INTERFACE-AUDIT-MATLAB-R1';
integration.architecture = [ ...
    'One deterministic Mode Manager commanding frozen longitudinal and ', ...
    'lateral-directional stacks on simultaneous but uncoupled single-trim plants'];

integration.required.modeManager = ...
    'AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1';
integration.required.longitudinalPlant = 'Longitudinal Plant V1';
integration.required.pitchRateDamper = 'Pitch-Rate Damper V1';
integration.required.pitchAttitudeController = 'Pitch-Attitude Hold V1';
integration.required.pitchLoop = 'Pitch-Attitude Hold V2';
integration.required.altitudeLoop = 'Altitude Hold V1';
integration.required.lateralPlant = 'Lateral-Directional Plant V0.1';
integration.required.yawController = 'YD-V1-MATLAB-R2';
integration.required.rudderAudit = 'YD-V2-AUDIT-MATLAB-R1';
integration.required.aileronAudit = 'AILERON-V1-AUDIT-MATLAB-R1';
integration.required.rollController = 'RAH-V1-MATLAB-R1';
integration.required.headingSensorAudit = ...
    'HEADING-SENSOR-V1-AUDIT-MATLAB-R1';
integration.required.headingController = 'HH-V1-MATLAB-R1';

integration.execution.fixedStep_s = 0.010;
integration.execution.solver = 'ode4';
integration.execution.supervisorRate_s = 0.010;
integration.execution.plantsAreDynamicallyCoupled = false;

% Commands deliberately remain inside the frozen outer-loop test envelopes.
integration.commands.simultaneousHeadingStep_deg = 30.0;
integration.commands.simultaneousAltitudeStep_ft = 100.0;

% Project release gates. These quantify actuator-path continuity, not just
% the one-sample tracking requests already audited in Mode Manager V1.
integration.requirements.maximumTransferAileronStep_deg = 0.10;
integration.requirements.maximumTransferElevatorStep_deg = 0.10;
integration.requirements.maximumDisconnectAileronStep_deg = 0.10;
integration.requirements.maximumDisconnectElevatorStep_deg = 0.10;
integration.requirements.maximumImplementationError = 1.0e-5;
integration.requirements.maximumHeadingFinalError_deg = 0.05;
integration.requirements.maximumAltitudeFinalError_ft = 1.0;
integration.requirements.maximumBankCommand_deg = 20.0;
integration.requirements.maximumPitchCommand_deg = 3.0;
integration.requirements.requireOneSampleTrackingPulse = true;
integration.requirements.requireDeterministicReplay = true;

integration.scenarios = { ...
    'disengaged trim'; ...
    'ROLL plus PITCH capture engagement'; ...
    'simultaneous HEADING plus ALTITUDE acquisition'; ...
    'HEADING to ROLL transfer'; ...
    'ALTITUDE to PITCH transfer'; ...
    'confirmed heading-source fallback'; ...
    'confirmed altitude-source fallback'; ...
    'pilot disconnect and release'; ...
    'disconnect then re-engage'; ...
    'pilot override'; ...
    'sustained aileron saturation'; ...
    'sustained elevator saturation'; ...
    'deterministic replay'};

integration.validation.minimumScenarioCount = 13;
integration.validation.normalStopTime_s = 120.0;
integration.validation.altitudeStopTime_s = 180.0;

integration.assumptions = { ...
    'Longitudinal and lateral plants share time but have no cross-axis aerodynamic coupling.'; ...
    'Thrust remains fixed at the longitudinal trim value.'; ...
    'Mode Manager Boolean sensor and actuator-status inputs are ideal interfaces.'; ...
    'The 0.10-deg actuator-step gates are project engineering selections.'};
integration.limitations = [ ...
    'This stage is integrated control-system validation at one trim point. ', ...
    'It is not a nonlinear six-DOF simulation, flight-envelope validation, ', ...
    'hardware-in-the-loop test or aircraft approval.'];
end
