function matrix = c172sNonlinearAutopilotResultMatrix(result)
%C172SNONLINEARAUTOPILOTRESULTMATRIX Pack the frozen 58-signal interface.
%
%   MATRIX = C172SNONLINEARAUTOPILOTRESULTMATRIX(RESULT) converts either a
%   MATLAB-reference or executable-Simulink result into the common numeric
%   verification interface: 26 states followed by 32 diagnostics.

required = { ...
    'plantState','controllerState','control','surfaceRate_radps', ...
    'euler_rad','altitude_ft','altitudePerturbation_m', ...
    'verticalSpeed_mps','TAS_mps','alpha_rad','beta_rad', ...
    'quaternionNorm','withinEnvelope','engaged','lateralMode', ...
    'verticalMode','rollTrackRequest','pitchTrackRequest','eventCode', ...
    'bankCommand_deg','pitchCommand_deg','headingCommand_deg', ...
    'altitudeCommand_ft','aileronSaturated','elevatorSaturated', ...
    'aileronSaturationTime_s','elevatorSaturationTime_s'};
assert(isstruct(result) && all(isfield(result,required)), ...
    'c172sNonlinearAutopilotResultMatrix:InvalidResult', ...
    'Result does not satisfy the frozen nonlinear-autopilot interface.');

matrix = [ ...
    result.plantState, ...
    result.controllerState, ...
    result.control, ...
    result.surfaceRate_radps, ...
    result.euler_rad, ...
    result.altitude_ft, ...
    result.altitudePerturbation_m, ...
    result.verticalSpeed_mps, ...
    result.TAS_mps, ...
    result.alpha_rad, ...
    result.beta_rad, ...
    result.quaternionNorm, ...
    double(result.withinEnvelope), ...
    double(result.engaged), ...
    double(result.lateralMode), ...
    double(result.verticalMode), ...
    double(result.rollTrackRequest), ...
    double(result.pitchTrackRequest), ...
    double(result.eventCode), ...
    result.bankCommand_deg, ...
    result.pitchCommand_deg, ...
    result.headingCommand_deg, ...
    result.altitudeCommand_ft, ...
    double(result.aileronSaturated), ...
    double(result.elevatorSaturated), ...
    result.aileronSaturationTime_s, ...
    result.elevatorSaturationTime_s];
assert(size(matrix,2) == 58, ...
    'c172sNonlinearAutopilotResultMatrix:InterfaceWidth', ...
    'Expected the frozen 58-signal interface; received %d columns.', ...
    size(matrix,2));
end
