function controller = c172sHeadingHoldControllerData()
%C172SHEADINGHOLDCONTROLLERDATA Heading Hold V1 definition and gates.
%
%   Project signs:
%     * positive psi and r are nose-right;
%     * positive phi is right-wing-down;
%     * positive bank command produces a nose-right turn;
%     * ePsi is the shortest signed circular heading error.
%
%   Outer-loop control law:
%
%     ePsi          = wrapToPi(psiCommand - psiSensor)
%     phiCommandRaw = Kpsi*ePsi
%     phiCommand    = sat(phiCommandRaw,+/-20 deg)
%
%   The bounded bank command is passed into frozen RAH-V1-MATLAB-R1.

controller.version = 'Heading Hold V1';
controller.artifactRevision = 'HH-V1-MATLAB-R1';
controller.requiredPlantVersion = 'Lateral-Directional Plant V0.1';
controller.requiredYawDamperRevision = 'YD-V1-MATLAB-R2';
controller.requiredRudderAuditRevision = 'YD-V2-AUDIT-MATLAB-R1';
controller.requiredAileronAuditRevision = ...
    'AILERON-V1-AUDIT-MATLAB-R1';
controller.requiredRollControllerRevision = 'RAH-V1-MATLAB-R1';
controller.requiredHeadingSensorRevision = ...
    'HEADING-SENSOR-V1-AUDIT-MATLAB-R1';
controller.architecture = [ ...
    'Circular proportional heading-error outer loop commanding the ', ...
    'frozen protected Roll-Attitude Hold V1 bank-command interface'];

%% Frozen V1 outer-loop gain

controller.headingErrorGain = 0.575;
controller.feedback.headingErrorSign = 1.0;
controller.feedback.headingErrorDefinition = ...
    'ePsi = atan2(sin(psiCommand-psiSensor),cos(...))';
controller.controlLaw = ...
    'phiCommand = sat(Kpsi*ePsi,+/-20 deg)';

%% Reproducible gain-search policy

controller.design.gainSearchRange = [0.400,0.650];
controller.design.gainIncrement = 0.025;
controller.design.minimumDynamicDecayRate_per_s = 0.100;
controller.design.minimumOscillatoryDampingRatio = 0.350;
controller.design.minimumBalancedDiskPhaseMargin_deg = 60.0;
controller.design.minimumBalancedDiskGainMargin_dB = 12.0;
controller.design.selectionPolicy = [ ...
    'Select the largest Kpsi on the declared grid that satisfies all ', ...
    '729 plant x 3 aileron-actuator modal gates and every exact-delay ', ...
    'disk-margin gate through the accepted 0.200-s heading-delay ', ...
    'envelope. The next grid point must fail at least one gate.'];

%% Inherited structured uncertainty family

controller.uncertainty.derivativeScaleValues = [0.80,1.00,1.20];
controller.uncertainty.inertiaScaleValues = [0.80,1.00,1.20];
controller.uncertainty.IxzNormalizedValues = [-0.10,0.00,0.10];
controller.uncertainty.caseCount = 729;
controller.uncertainty.groups = { ...
    'CY_beta, CY_p and CY_r scaled together'; ...
    'Cl_beta, Cl_p and Cl_r scaled together'; ...
    'Cn_beta, Cn_p and Cn_r scaled together'; ...
    'CY_deltaA, Cl_deltaA and Cn_deltaA scaled together'; ...
    'Ixx and Izz scaled together'; ...
    'Ixz/sqrt(Ixx*Izz) varied independently'};
controller.uncertainty.interpretation = [ ...
    'Inherited RAH-V1 structured, non-probabilistic single-trim ', ...
    'robustness family. Rudder-effectiveness uncertainty remains covered ', ...
    'by the separately frozen YD-V2 audit.'];

%% Linear and operational release gates

controller.requirements.minimumDynamicDecayRate_per_s = 0.100;
controller.requirements.minimumOscillatoryDampingRatio = 0.350;
controller.requirements.minimumBalancedDiskPhaseMargin_deg = 60.0;
controller.requirements.minimumBalancedDiskGainMargin_dB = 12.0;
controller.requirements.minimumRiseTime_s = 14.0;
controller.requirements.maximumRiseTime_s = 20.0;
controller.requirements.maximumStepOvershoot_pct = 2.0;
controller.requirements.maximumSettlingTime_s = 40.0;
controller.requirements.maximumFinalHeadingError_deg = 0.050;
controller.requirements.maximumOperationalBank_deg = 18.0;
controller.requirements.maximumOperationalRollRate_degps = 7.0;
controller.requirements.maximumOperationalYawRate_degps = 3.0;
controller.requirements.maximumOperationalSideslip_deg = 1.0;
controller.requirements.maximumAutomaticAileron_deg = 2.0;
controller.requirements.maximumAutomaticRudder_deg = 0.50;
controller.requirements.maximumOperationalAileronRate_degps = 10.0;

%% Command-authority and large-turn gates

controller.bankCommandAuthority_deg = 20.0;
controller.largeTurn.maximumActualBank_deg = 22.0;
controller.largeTurn.maximumRollRate_degps = 8.0;
controller.largeTurn.maximumYawRate_degps = 4.0;
controller.largeTurn.maximumSideslip_deg = 1.0;
controller.largeTurn.maximumFinalHeadingError_deg = 0.10;
controller.largeTurn.maximumSettlingTime_s = 80.0;

%% Validation definitions

controller.validation.commandStep_deg = 30.0;
controller.validation.largeCommandStep_deg = 90.0;
controller.validation.timeStep_s = 0.020;
controller.validation.stopTime_s = 100.0;
controller.validation.nonlinearTimeStep_s = 0.002;
controller.validation.nonlinearStopTime_s = 120.0;
controller.validation.wrapRightInitial_deg = 350.0;
controller.validation.wrapRightCommand_deg = 10.0;
controller.validation.wrapLeftInitial_deg = 10.0;
controller.validation.wrapLeftCommand_deg = 350.0;
controller.validation.diskMarginFrequencyRange_radps = [1.0e-4,1.0e4];
controller.validation.diskMarginGridPointCount = 2001;

%% Turn-performance reference at the frozen trim speed

controller.turnReference.standardRate_degps = 3.0;
controller.turnReference.standardRateDefinition = [ ...
    'FAA Airplane Flying Handbook glossary: 3 deg/s, completing ', ...
    '360 deg in two minutes'];
controller.turnReference.faaSourceUrl = [ ...
    'https://www.faa.gov/sites/faa.gov/files/regulations_policies/', ...
    'handbooks_manuals/aviation/airplane_handbook/20_afh_glossary.pdf'];
controller.turnReference.coordinatedTurnModel = ...
    'psiDot = g*tan(phi)/Vtrue';
controller.turnReference.classification = [ ...
    'Analytical coordinated-level-turn reference only; the Plant V0.1 ', ...
    'state response, not this formula, is used for release metrics.'];

%% Evidence, assumptions and limitations

controller.references.modeArchitecture = [ ...
    'Garmin G1000 Cessna Nav III CRG P/N 190-00384-09 Rev. A, ', ...
    'Sec. 6-19: Heading Select captures and maintains Selected Heading.'];
controller.references.bankArchitecture = [ ...
    'The same guide, Sec. 6-18, documents a 22-deg Roll Hold limit; ', ...
    'the project retains its previously frozen conservative 20-deg ', ...
    'bank-command authority.'];
controller.references.controlStructure = [ ...
    'The proportional circular-error law and gain are project classical-', ...
    'control selections, not a reverse-engineered Garmin control law.'];

controller.assumptions = { ...
    'Kpsi = 0.575 is a project gain selected by the declared audit.'; ...
    'The heading loop commands bank only; it has no direct rudder output.'; ...
    [ 'No heading integral term is used because heading kinematics ', ...
      'already supply the loop integrator.' ]; ...
    [ 'Natural aircraft response plus frozen yaw damping provide the ', ...
      'modeled turn coordination; there is no sideslip feedback or ', ...
      'rudder feedforward.' ]; ...
    'The frozen 20-deg RAH bank-command limit is reused unchanged.'};

controller.limitations = [ ...
    'Valid only with the frozen protected lateral stack and provisional ', ...
    'Plant V0.1 at 4000 ft ISA, 110 KTAS and 2550 lb. This is heading ', ...
    'hold, not ground-track hold: wind, crosswind correction and GPS ', ...
    'course guidance are absent. Heading-source failures, magnetic ', ...
    'disturbances, knob-event turn history, turn-coordination control, ', ...
    'altitude loss in bank, envelope scheduling and nonlinear full-aircraft ', ...
    'dynamics remain outside V1. Pure transport delays are audited exactly ', ...
    'in frequency response but omitted from time-domain captures. This ', ...
    'educational research controller is ', ...
    'not approved for aircraft installation or operation.'];

end
