function comparison = compareC172sFlightControlRuns( ...
    autopilotRun,manualRun,showPlot)
%COMPAREC172SFLIGHTCONTROLRUNS Compare autopilot-on and autopilot-off runs.

if nargin < 3 || isempty(showPlot)
    showPlot = true;
end
assert(isstruct(autopilotRun) && isfield(autopilotRun,'metrics') && ...
    isstruct(manualRun) && isfield(manualRun,'metrics'), ...
    'compareC172sFlightControlRuns:InvalidRuns', ...
    'Both inputs must be laboratory run structures.');
assert(isequal(autopilotRun.result.time_s,manualRun.result.time_s), ...
    'compareC172sFlightControlRuns:TimeMismatch', ...
    'Comparison runs must use the same time grid.');
assert(strcmp(autopilotRun.executionBackend,manualRun.executionBackend), ...
    'compareC172sFlightControlRuns:BackendMismatch', ...
    'Autopilot ON/OFF runs must use the same execution backend.');

comparison.autopilotHeadingError_deg = ...
    abs(autopilotRun.metrics.final.headingError_deg);
comparison.manualHeadingError_deg = ...
    abs(manualRun.metrics.final.headingError_deg);
comparison.headingErrorReduction_deg = ...
    comparison.manualHeadingError_deg- ...
    comparison.autopilotHeadingError_deg;
comparison.autopilotAltitudeError_ft = ...
    abs(autopilotRun.metrics.final.altitudeError_ft);
comparison.manualAltitudeError_ft = ...
    abs(manualRun.metrics.final.altitudeError_ft);
comparison.altitudeErrorReduction_ft = ...
    comparison.manualAltitudeError_ft- ...
    comparison.autopilotAltitudeError_ft;
comparison.autopilotHealthPass = autopilotRun.metrics.health.pass;
comparison.manualHealthPass = manualRun.metrics.health.pass;
comparison.executionBackend = autopilotRun.executionBackend;

fprintf('============================================================\n');
fprintf('%-38s: %s\n','Execution backend',comparison.executionBackend);
fprintf(' C172S FLIGHT-CONTROL LAB - AUTOPILOT ON/OFF COMPARISON\n');
fprintf('============================================================\n');
fprintf('%-38s: %.6f / %.6f deg\n', ...
    'Final heading error AP ON / OFF', ...
    comparison.autopilotHeadingError_deg,comparison.manualHeadingError_deg);
fprintf('%-38s: %.6f deg\n','Heading-error reduction', ...
    comparison.headingErrorReduction_deg);
fprintf('%-38s: %.6f / %.6f ft\n', ...
    'Final altitude error AP ON / OFF', ...
    comparison.autopilotAltitudeError_ft,comparison.manualAltitudeError_ft);
fprintf('%-38s: %.6f ft\n','Altitude-error reduction', ...
    comparison.altitudeErrorReduction_ft);

comparison.figure = gobjects(0,1);
if showPlot
    t = autopilotRun.result.time_s;
    comparison.figure = figure('Name', ...
        'C172S Flight-Control Lab - Autopilot ON versus OFF', ...
        'Color','w','NumberTitle','off');
    tiledlayout(2,1,'TileSpacing','compact','Padding','compact');
    nexttile;
    plot(t,mod(rad2deg(autopilotRun.result.euler_rad(:,3)),360), ...
        'LineWidth',1.3);
    hold on;
    plot(t,mod(rad2deg(manualRun.result.euler_rad(:,3)),360),'--', ...
        'LineWidth',1.2);
    yline(autopilotRun.scenario.selectedHeading_deg,':','Command');
    grid on; xlabel('Time (s)'); ylabel('Heading (deg)');
    title('Heading response'); legend('Autopilot ON','Autopilot OFF');
    nexttile;
    plot(t,autopilotRun.result.altitude_ft,'LineWidth',1.3);
    hold on;
    plot(t,manualRun.result.altitude_ft,'--','LineWidth',1.2);
    yline(autopilotRun.scenario.selectedAltitude_ft,':','Command');
    grid on; xlabel('Time (s)'); ylabel('Altitude (ft)');
    title('Altitude response'); legend('Autopilot ON','Autopilot OFF');
end
end
