function release = prepareC172sNonlinear6DofRelease(versionTag)
%PREPAREC172SNONLINEAR6DOFRELEASE Package research-plant release V0.1.
%
%   RELEASE = PREPAREC172SNONLINEAR6DOFRELEASE('v0.1.0') requires a current
%   Nonlinear6DofRegressionReport.txt proving 7/7 nonlinear gates and the
%   external FlightControlRegressionReport.txt proving the frozen controller
%   release remains 18/18. It creates a versioned folder and ZIP beneath:
%
%     release/C172S_Nonlinear6Dof_v0.1.0/
%     release/C172S_Nonlinear6Dof_v0.1.0.zip
%
%   Existing targets are never overwritten. Source files and the frozen
%   v1.0.0 controller release are never modified or cleaned in place.

if nargin < 1 || isempty(versionTag)
    versionTag = 'v0.1.0';
end
if isstring(versionTag) && isscalar(versionTag)
    versionTag = char(versionTag);
end
assert(ischar(versionTag) && isrow(versionTag), ...
    'prepareC172sNonlinear6DofRelease:InvalidVersion', ...
    'versionTag must be a character vector or scalar string.');
assert(~isempty(regexp(versionTag,'^v[0-9]+\.[0-9]+\.[0-9]+$', ...
    'once')), ...
    'prepareC172sNonlinear6DofRelease:InvalidVersion', ...
    'Use a semantic-style version tag such as v0.1.0.');

projectRoot = fileparts(mfilename('fullpath'));
nonlinearReport = fullfile(projectRoot, ...
    'Nonlinear6DofRegressionReport.txt');
flightReport = fullfile(projectRoot,'FlightControlRegressionReport.txt');

assert(isfile(nonlinearReport), ...
    'prepareC172sNonlinear6DofRelease:MissingRegressionReport', ...
    ['Nonlinear6DofRegressionReport.txt is missing. Run ', ...
     'runAllNonlinear6DofChecks before packaging.']);
assert(isfile(flightReport), ...
    'prepareC172sNonlinear6DofRelease:MissingFlightControlEvidence', ...
    ['FlightControlRegressionReport.txt is missing. Preserve the ', ...
     'v1.0.0 18/18 evidence beside this packager.']);

nonlinearText = fileread(nonlinearReport);
flightText = fileread(flightReport);
assert(~isempty(regexp(nonlinearText, ...
    'Nonlinear gates passed:\s*7/7','once')) && ...
    ~isempty(regexp(nonlinearText, ...
    'Nonlinear gates failed:\s*0/7','once')) && ...
    ~isempty(regexp(nonlinearText, ...
    'Combined project evidence:\s*25/25 PASS','once')), ...
    'prepareC172sNonlinear6DofRelease:RegressionNotPassing', ...
    ['The nonlinear report does not prove 7/7 and combined 25/25 PASS. ', ...
     'Run runAllNonlinear6DofChecks and resolve every failure.']);
assert(~isempty(regexp(flightText,'Passed:\s*18/18','once')) && ...
    ~isempty(regexp(flightText,'Failed:\s*0/18','once')), ...
    'prepareC172sNonlinear6DofRelease:FlightControlEvidenceNotPassing', ...
    'The frozen flight-controls report does not prove 18/18 PASS.');

requiredFiles = frozenReleaseLedger();
assert(numel(unique(requiredFiles)) == numel(requiredFiles), ...
    'prepareC172sNonlinear6DofRelease:DuplicateLedgerEntry', ...
    'The frozen release ledger contains duplicate filenames.');
missing = requiredFiles(~cellfun(@(name) ...
    isfile(fullfile(projectRoot,name)),requiredFiles));
assert(isempty(missing), ...
    'prepareC172sNonlinear6DofRelease:MissingArtifact', ...
    'Required release artifact(s) missing: %s',strjoin(missing,', '));

releaseRoot = fullfile(projectRoot,'release');
releaseName = ['C172S_Nonlinear6Dof_' versionTag];
releaseFolder = fullfile(releaseRoot,releaseName);
zipPath = fullfile(releaseRoot,[releaseName '.zip']);

assert(~isfolder(releaseFolder) && ~isfile(zipPath), ...
    'prepareC172sNonlinear6DofRelease:TargetExists', ...
    ['Release target already exists. Preserve it and use a new version ', ...
     'tag, or move it outside the project before retrying.']);

if ~isfolder(releaseRoot)
    [made,message] = mkdir(releaseRoot);
    assert(made,'prepareC172sNonlinear6DofRelease:CreateFailed', ...
        'Could not create release directory: %s',message);
end
[made,message] = mkdir(releaseFolder);
assert(made,'prepareC172sNonlinear6DofRelease:CreateFailed', ...
    'Could not create release staging folder: %s',message);

for k = 1:numel(requiredFiles)
    sourcePath = fullfile(projectRoot,requiredFiles{k});
    destinationPath = fullfile(releaseFolder,requiredFiles{k});
    [copied,message] = copyfile(sourcePath,destinationPath,'f');
    assert(copied,'prepareC172sNonlinear6DofRelease:CopyFailed', ...
        'Could not copy %s: %s',requiredFiles{k},message);
end

assert(all(cellfun(@(name) isfile(fullfile(releaseFolder,name)), ...
    requiredFiles)), ...
    'prepareC172sNonlinear6DofRelease:IncompleteStage', ...
    'The staged release does not contain every frozen artifact.');

forbiddenPatterns = {'*.slxc','*.asv','*.autosave','*.zip','*.m~'};
for k = 1:numel(forbiddenPatterns)
    assert(isempty(dir(fullfile(releaseFolder,forbiddenPatterns{k}))), ...
        'prepareC172sNonlinear6DofRelease:ForbiddenArtifact', ...
        'The staged release contains forbidden pattern %s.', ...
        forbiddenPatterns{k});
end
assert(~isfolder(fullfile(releaseFolder,'slprj')) && ...
    ~isfolder(fullfile(releaseFolder,'codegen')) && ...
    ~isfile(fullfile(releaseFolder,'untitled.m')), ...
    'prepareC172sNonlinear6DofRelease:ForbiddenArtifact', ...
    'The staged release contains generated cache or scratch content.');

manifestPath = fullfile(releaseFolder,'RELEASE_MANIFEST.txt');
writeManifest(manifestPath,versionTag,requiredFiles,releaseFolder);

zip(zipPath,{releaseName},releaseRoot);
assert(isfile(zipPath), ...
    'prepareC172sNonlinear6DofRelease:ZipFailed', ...
    'MATLAB did not create the expected ZIP file.');

folderInfo = dir(releaseFolder);
folderInfo = folderInfo(~[folderInfo.isdir]);
zipInfo = dir(zipPath);

release = struct();
release.version = versionTag;
release.folder = releaseFolder;
release.zip = zipPath;
release.fileCount = numel(folderInfo);
release.zipBytes = zipInfo.bytes;
release.nonlinearRegression = '7/7 PASS';
release.flightControlsEvidence = '18/18 PASS (external frozen release)';
release.combinedEvidence = '25/25 PASS';
release.sourceModified = false;

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR 6-DOF V0.1 - RELEASE PACKAGE COMPLETE\n');
fprintf('============================================================\n');
fprintf('%-38s: %s\n','Version',release.version);
fprintf('%-38s: %s\n','Nonlinear regression', ...
    release.nonlinearRegression);
fprintf('%-38s: %s\n','Frozen flight-controls evidence', ...
    release.flightControlsEvidence);
fprintf('%-38s: %s\n','Combined project evidence', ...
    release.combinedEvidence);
fprintf('%-38s: %d\n','Packaged files',release.fileCount);
fprintf('%-38s: %s\n','Release folder',release.folder);
fprintf('%-38s: %s\n','ZIP package',release.zip);
fprintf('PASS: source files and controller release were not modified in place.\n');
fprintf(['NOTE: this is a near-trim research validation plant with ', ...
    'one-point thrust; it is not aircraft approval.\n']);
end

function required = frozenReleaseLedger()
required = { ...
    'NONLINEAR_6DOF_V0_1_RELEASE.md'; ...
    'runAllNonlinear6DofChecks.m'; ...
    'prepareC172sNonlinear6DofRelease.m'; ...
    'Nonlinear6DofRegressionReport.txt'; ...
    'FlightControlRegressionReport.txt'; ...
    'c172sNonlinear6DofSourceData.m'; ...
    'auditC172sNonlinear6DofSources.m'; ...
    'c172sRigidBody6DofData.m'; ...
    'c172sRigidBody6DofEom.m'; ...
    'auditC172sRigidBody6DofEom.m'; ...
    'c172sAtmosphereAirDataData.m'; ...
    'c172sAtmosphereAirData.m'; ...
    'auditC172sAtmosphereAirData.m'; ...
    'c172sNearTrimAerodynamicsData.m'; ...
    'c172sNearTrimAerodynamics.m'; ...
    'auditC172sNearTrimAerodynamics.m'; ...
    'c172sTrimTotalForceData.m'; ...
    'c172sTrimTotalForces.m'; ...
    'solveC172sNonlinearTrim.m'; ...
    'auditC172sNonlinearTrim.m'; ...
    'c172sIntegratedNonlinearDynamicsData.m'; ...
    'c172sIntegratedNonlinearDynamics.m'; ...
    'linearizeC172sIntegratedNonlinearDynamics.m'; ...
    'auditC172sIntegratedNonlinearDynamics.m'; ...
    'buildC172sNonlinear6DofSimulink.m'; ...
    'runNonlinear6DofSimulinkCheck.m'; ...
    'C172S_Nonlinear6Dof_V1.slx'; ...
    'c172sLongitudinalData.m'; ...
    'c172sLongitudinalPlant.m'; ...
    'c172sLateralDirectionalData.m'; ...
    'c172sLateralDirectionalPlant.m'; ...
    'c172sElevatorActuatorData.m'};
end

function writeManifest(path,versionTag,fileNames,releaseFolder)
fid = fopen(path,'w');
assert(fid >= 0, ...
    'prepareC172sNonlinear6DofRelease:ManifestWriteFailed', ...
    'Unable to write release manifest: %s',path);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

generated = datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss''Z''');
fprintf(fid,'C172S NONLINEAR 6-DOF RESEARCH PLANT - RELEASE MANIFEST\n');
fprintf(fid,'Version: %s\n',versionTag);
fprintf(fid,'Generated UTC: %s\n',char(generated));
fprintf(fid,'MATLAB: %s\n',version);
fprintf(fid,'Nonlinear regression: 7/7 PASS\n');
fprintf(fid,'Frozen flight-controls evidence: 18/18 PASS (external)\n');
fprintf(fid,'Combined project evidence: 25/25 PASS\n');
fprintf(fid,['Scope: 13-state coupled rigid-body research validation ', ...
    'plant, atmosphere/air data, near-trim aerodynamics, bounded trim, ', ...
    'linearization and independent executable Simulink equivalence.\n']);
fprintf(fid,['Qualification: 80-130 KTAS, alpha -4 to +10 deg, beta ', ...
    '+/-8 deg, flaps up, near-trim attached flow, provisional mass ', ...
    'properties, one-point thrust; no stall/spin or aircraft-truth ', ...
    'claim; not aircraft approval.\n\n']);
fprintf(fid,'Packaged files:\n');

allNames = sort([fileNames; {'RELEASE_MANIFEST.txt'}]);
for k = 1:numel(allNames)
    info = dir(fullfile(releaseFolder,allNames{k}));
    if isempty(info)
        bytes = 0;
    else
        bytes = info(1).bytes;
    end
    fprintf(fid,'%10d  %s\n',bytes,allNames{k});
end
end
