function release = prepareC172sFlightControlsRelease(versionTag)
%PREPAREC172SFLIGHTCONTROLSRELEASE Validate and package release v1.0.0.
%
%   RELEASE = PREPAREC172SFLIGHTCONTROLSRELEASE() requires a current
%   FlightControlRegressionReport.txt containing an 18/18 PASS result,
%   verifies the frozen source/model/checker ledger, and creates:
%
%     release/C172S_Flight_Controls_v1.0.0/
%     release/C172S_Flight_Controls_v1.0.0.zip
%
%   RELEASE = PREPAREC172SFLIGHTCONTROLSRELEASE(VERSIONTAG) uses the given
%   semantic-style tag, for example 'v1.0.1'. Existing release targets are
%   never overwritten. Source files are never modified or deleted.

if nargin < 1 || isempty(versionTag)
    versionTag = 'v1.0.0';
end
if isstring(versionTag) && isscalar(versionTag)
    versionTag = char(versionTag);
end
assert(ischar(versionTag) && isrow(versionTag), ...
    'prepareC172sFlightControlsRelease:InvalidVersion', ...
    'versionTag must be a character vector or scalar string.');
assert(~isempty(regexp(versionTag,'^v[0-9]+\.[0-9]+\.[0-9]+$', ...
    'once')), ...
    'prepareC172sFlightControlsRelease:InvalidVersion', ...
    'Use a semantic-style version tag such as v1.0.0.');

projectRoot = fileparts(mfilename('fullpath'));
reportPath = fullfile(projectRoot,'FlightControlRegressionReport.txt');
assert(isfile(reportPath), ...
    'prepareC172sFlightControlsRelease:MissingRegressionReport', ...
    ['FlightControlRegressionReport.txt is missing. Run ', ...
     'runAllFlightControlChecks before packaging.']);

reportText = fileread(reportPath);
assert(~isempty(regexp(reportText,'Passed:\s*18/18','once')) && ...
       ~isempty(regexp(reportText,'Failed:\s*0/18','once')), ...
    'prepareC172sFlightControlsRelease:RegressionNotPassing', ...
    ['The saved regression report does not prove 18/18 PASS. Run ', ...
     'runAllFlightControlChecks and resolve every failure first.']);

requiredFiles = frozenReleaseLedger();
missing = requiredFiles(~cellfun(@(name) ...
    isfile(fullfile(projectRoot,name)),requiredFiles));
assert(isempty(missing), ...
    'prepareC172sFlightControlsRelease:MissingArtifact', ...
    'Required release artifact(s) missing: %s',strjoin(missing,', '));

releaseRoot = fullfile(projectRoot,'release');
releaseName = ['C172S_Flight_Controls_' versionTag];
releaseFolder = fullfile(releaseRoot,releaseName);
zipPath = fullfile(releaseRoot,[releaseName '.zip']);

assert(~isfolder(releaseFolder) && ~isfile(zipPath), ...
    'prepareC172sFlightControlsRelease:TargetExists', ...
    ['Release target already exists. Preserve it and use a new version ', ...
     'tag, or move it outside the project before retrying.']);

if ~isfolder(releaseRoot)
    [made,message] = mkdir(releaseRoot);
    assert(made,'prepareC172sFlightControlsRelease:CreateFailed', ...
        'Could not create release directory: %s',message);
end
[made,message] = mkdir(releaseFolder);
assert(made,'prepareC172sFlightControlsRelease:CreateFailed', ...
    'Could not create release staging folder: %s',message);

sourceEntries = dir(projectRoot);
copiedNames = {};
for k = 1:numel(sourceEntries)
    entry = sourceEntries(k);
    if entry.isdir || ~isReleaseableFile(entry.name)
        continue;
    end
    sourcePath = fullfile(projectRoot,entry.name);
    destinationPath = fullfile(releaseFolder,entry.name);
    [copied,message] = copyfile(sourcePath,destinationPath,'f');
    assert(copied,'prepareC172sFlightControlsRelease:CopyFailed', ...
        'Could not copy %s: %s',entry.name,message);
    copiedNames{end+1,1} = entry.name; %#ok<AGROW>
end

% Some platforms do not return dotfiles from DIR. Copy this repository
% control file explicitly when needed so packaging stays cross-platform.
gitignoreSource = fullfile(projectRoot,'.gitignore');
gitignoreDestination = fullfile(releaseFolder,'.gitignore');
if isfile(gitignoreSource) && ~isfile(gitignoreDestination)
    [copied,message] = copyfile(gitignoreSource,gitignoreDestination,'f');
    assert(copied,'prepareC172sFlightControlsRelease:CopyFailed', ...
        'Could not copy .gitignore: %s',message);
    copiedNames{end+1,1} = '.gitignore'; %#ok<AGROW>
end

assert(all(cellfun(@(name) isfile(fullfile(releaseFolder,name)), ...
    requiredFiles)), ...
    'prepareC172sFlightControlsRelease:IncompleteStage', ...
    'The staged release does not contain every frozen artifact.');

forbiddenPatterns = {'*.slxc','*.asv','*.autosave','*.zip','*.m~'};
for k = 1:numel(forbiddenPatterns)
    assert(isempty(dir(fullfile(releaseFolder,forbiddenPatterns{k}))), ...
        'prepareC172sFlightControlsRelease:ForbiddenArtifact', ...
        'The staged release contains forbidden pattern %s.', ...
        forbiddenPatterns{k});
end
assert(~isfolder(fullfile(releaseFolder,'slprj')) && ...
       ~isfile(fullfile(releaseFolder,'untitled.m')), ...
    'prepareC172sFlightControlsRelease:ForbiddenArtifact', ...
    'The staged release contains a generated cache or scratch artifact.');

copiedNames = sort(copiedNames);
manifestPath = fullfile(releaseFolder,'RELEASE_MANIFEST.txt');
writeManifest(manifestPath,versionTag,copiedNames,releaseFolder);

zip(zipPath,{releaseName},releaseRoot);
assert(isfile(zipPath), ...
    'prepareC172sFlightControlsRelease:ZipFailed', ...
    'MATLAB did not create the expected ZIP file.');

folderInfo = dir(releaseFolder);
folderInfo = folderInfo(~[folderInfo.isdir]);
zipInfo = dir(zipPath);

release = struct();
release.version = versionTag;
release.folder = releaseFolder;
release.zip = zipPath;
release.fileCount = numel(folderInfo);
release.zipBytes = zipInfo.bytes;
release.regression = '18/18 PASS';
release.sourceModified = false;

fprintf('============================================================\n');
fprintf(' C172S FLIGHT CONTROLS - RELEASE PACKAGE COMPLETE\n');
fprintf('============================================================\n');
fprintf('%-37s: %s\n','Version',release.version);
fprintf('%-37s: %s\n','Regression evidence',release.regression);
fprintf('%-37s: %d\n','Packaged files',release.fileCount);
fprintf('%-37s: %s\n','Release folder',release.folder);
fprintf('%-37s: %s\n','ZIP package',release.zip);
fprintf('PASS: the source project was not modified or cleaned in place.\n');
fprintf(['NOTE: this is an educational single-trim engineering model; ', ...
    'it is not aircraft approval.\n']);
end

function keep = isReleaseableFile(name)
% Top-level allowlist. Generated folders and existing archives are omitted.
if strcmp(name,'untitled.m')
    keep = false;
    return;
end
if strcmp(name,'.gitignore')
    keep = true;
    return;
end
[~,~,extension] = fileparts(name);
keep = any(strcmpi(extension,{'.m','.slx','.md','.txt','.csv'}));
end

function required = frozenReleaseLedger()
% Minimum files needed to establish, rebuild, and verify the final release.
required = { ...
    'README.md'; ...
    'INTEGRATED_AUTOPILOT_V1_RELEASE.md'; ...
    '.gitignore'; ...
    'prepareC172sFlightControlsRelease.m'; ...
    'FlightControlRegressionReport.txt'; ...
    'runAllFlightControlChecks.m'; ...
    'c172sIntegratedAutopilotData.m'; ...
    'auditIntegratedAutopilotInterfaces.m'; ...
    'buildC172sIntegratedAutopilotSimulink.m'; ...
    'runIntegratedAutopilotSimulinkCheck.m'; ...
    'C172S_IntegratedAutopilot_V1.slx'; ...
    'c172sAutopilotModeManagerData.m'; ...
    'c172sAutopilotModeManagerStep.m'; ...
    'auditAutopilotModeManager.m'; ...
    'buildC172sAutopilotModeManagerSimulink.m'; ...
    'runAutopilotModeManagerSimulinkCheck.m'; ...
    'C172S_AutopilotModeManager_V1.slx'; ...
    'c172sLongitudinalData.m'; ...
    'c172sLongitudinalPlant.m'; ...
    'c172sPitchRateDamperData.m'; ...
    'c172sPitchAttitudeControllerData.m'; ...
    'c172sElevatorActuatorData.m'; ...
    'c172sAltitudeHoldControllerData.m'; ...
    'designPitchRateDamper.m'; ...
    'designPitchAttitudeController.m'; ...
    'designPitchAttitudeActuatorProtection.m'; ...
    'designAltitudeHoldController.m'; ...
    'buildC172sLongitudinalSimulink.m'; ...
    'buildC172sPitchRateDamperSimulink.m'; ...
    'buildC172sPitchAttitudeHoldSimulink.m'; ...
    'buildC172sPitchAttitudeActuatorSimulink.m'; ...
    'buildC172sAltitudeHoldSimulink.m'; ...
    'C172S_Longitudinal_OpenLoop.slx'; ...
    'C172S_PitchRateDamper_V1.slx'; ...
    'C172S_PitchAttitudeHold_V1.slx'; ...
    'C172S_PitchAttitudeHold_V2_Actuator.slx'; ...
    'C172S_AltitudeHold_V1.slx'; ...
    'runSimulinkPlantCheck.m'; ...
    'runPitchRateDamperSimulinkCheck.m'; ...
    'runPitchAttitudeHoldSimulinkCheck.m'; ...
    'runPitchAttitudeActuatorSimulinkCheck.m'; ...
    'runAltitudeHoldSimulinkCheck.m'; ...
    'c172sLateralDirectionalData.m'; ...
    'c172sLateralDirectionalPlant.m'; ...
    'c172sYawDamperData.m'; ...
    'c172sRudderActuatorData.m'; ...
    'c172sAileronActuatorData.m'; ...
    'c172sRollAttitudeControllerData.m'; ...
    'c172sHeadingSensorData.m'; ...
    'c172sHeadingHoldControllerData.m'; ...
    'buildC172sLateralDirectionalSimulink.m'; ...
    'buildC172sYawDamperSimulink.m'; ...
    'buildC172sYawDamperActuatorSimulink.m'; ...
    'buildC172sRollAttitudeHoldSimulink.m'; ...
    'buildC172sHeadingHoldSimulink.m'; ...
    'C172S_LateralDirectionalPlant_V01.slx'; ...
    'C172S_YawDamper_V1.slx'; ...
    'C172S_YawDamper_V2_Actuator.slx'; ...
    'C172S_RollAttitudeHold_V1.slx'; ...
    'C172S_HeadingHold_V1.slx'; ...
    'runLateralDirectionalPlantValidation.m'; ...
    'runLateralDirectionalSimulinkCheck.m'; ...
    'designYawDamper.m'; ...
    'runYawDamperSimulinkCheck.m'; ...
    'designYawDamperActuatorProtection.m'; ...
    'runYawDamperActuatorSimulinkCheck.m'; ...
    'designRollAttitudeHold.m'; ...
    'runRollAttitudeHoldSimulinkCheck.m'; ...
    'designHeadingHold.m'; ...
    'runHeadingHoldSimulinkCheck.m'};
end

function writeManifest(path,versionTag,fileNames,releaseFolder)
fid = fopen(path,'w');
assert(fid >= 0,'prepareC172sFlightControlsRelease:ManifestWriteFailed', ...
    'Unable to write release manifest: %s',path);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

generated = datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss''Z''');
fprintf(fid,'C172S FLIGHT CONTROLS - RELEASE MANIFEST\n');
fprintf(fid,'Version: %s\n',versionTag);
fprintf(fid,'Generated UTC: %s\n',char(generated));
fprintf(fid,'MATLAB: %s\n',version);
fprintf(fid,'Regression: 18/18 PASS\n');
fprintf(fid,['Scope: frozen longitudinal and lateral stacks through ', ...
    'executable Integrated Autopilot V1\n']);
fprintf(fid,['Qualification: simultaneous uncoupled single-trim plants; ', ...
    'educational engineering model; not aircraft approval.\n\n']);
fprintf(fid,'Packaged files:\n');

allNames = sort([fileNames; {'RELEASE_MANIFEST.txt'}]);
for k = 1:numel(allNames)
    info = dir(fullfile(releaseFolder,allNames{k}));
    if isempty(info)
        bytes = 0;
    else
        bytes = info(1).bytes;
    end
    fprintf(fid,'%10d  %s\n',bytes,allNames{k});
end
end
