function release = prepareC172sNonlinearAutopilotRelease(versionTag)
%PREPAREC172SNONLINEARAUTOPILOTRELEASE Package integration release V0.1.
%
%   RELEASE = PREPAREC172SNONLINEARAUTOPILOTRELEASE('v0.1.0') requires a
%   current NonlinearAutopilotRegressionReport.txt proving 3/3 new gates
%   and combined 28/28 project evidence. It creates:
%
%     release/C172S_NonlinearAutopilot_v0.1.0/
%     release/C172S_NonlinearAutopilot_v0.1.0.zip
%
%   Existing targets are never overwritten. The flight-controls v1.0.0,
%   nonlinear-plant v0.1.0 and source project are never modified or cleaned
%   in place.

if nargin < 1 || isempty(versionTag)
    versionTag = 'v0.1.0';
end
if isstring(versionTag) && isscalar(versionTag)
    versionTag = char(versionTag);
end
assert(ischar(versionTag) && isrow(versionTag), ...
    'prepareC172sNonlinearAutopilotRelease:InvalidVersion', ...
    'versionTag must be a character vector or scalar string.');
assert(~isempty(regexp(versionTag,'^v[0-9]+\.[0-9]+\.[0-9]+$', ...
    'once')), ...
    'prepareC172sNonlinearAutopilotRelease:InvalidVersion', ...
    'Use a semantic-style version tag such as v0.1.0.');

projectRoot = fileparts(mfilename('fullpath'));
autopilotReport = fullfile(projectRoot, ...
    'NonlinearAutopilotRegressionReport.txt');
flightReport = fullfile(projectRoot,'FlightControlRegressionReport.txt');
nonlinearReport = fullfile(projectRoot, ...
    'Nonlinear6DofRegressionReport.txt');

assert(isfile(autopilotReport), ...
    'prepareC172sNonlinearAutopilotRelease:MissingRegressionReport', ...
    ['NonlinearAutopilotRegressionReport.txt is missing. Run ', ...
     'runAllNonlinearAutopilotChecks before packaging.']);
assert(isfile(flightReport) && isfile(nonlinearReport), ...
    'prepareC172sNonlinearAutopilotRelease:MissingExternalEvidence', ...
    ['The frozen controller and nonlinear-plant regression reports must ', ...
     'remain beside this packager.']);

autopilotText = fileread(autopilotReport);
flightText = fileread(flightReport);
nonlinearText = fileread(nonlinearReport);
assert(~isempty(regexp(autopilotText, ...
    'Nonlinear-autopilot gates passed:\s*3/3','once')) && ...
    ~isempty(regexp(autopilotText, ...
    'Nonlinear-autopilot gates failed:\s*0/3','once')) && ...
    ~isempty(regexp(autopilotText, ...
    'Combined project evidence:\s*28/28 PASS','once')), ...
    'prepareC172sNonlinearAutopilotRelease:RegressionNotPassing', ...
    ['The nonlinear-autopilot report does not prove 3/3 and combined ', ...
     '28/28 PASS. Run runAllNonlinearAutopilotChecks first.']);
assert(~isempty(regexp(flightText,'Passed:\s*18/18','once')) && ...
    ~isempty(regexp(flightText,'Failed:\s*0/18','once')), ...
    'prepareC172sNonlinearAutopilotRelease:FlightEvidenceNotPassing', ...
    'The frozen flight-controls report does not prove 18/18 PASS.');
assert(~isempty(regexp(nonlinearText, ...
    'Nonlinear gates passed:\s*7/7','once')) && ...
    ~isempty(regexp(nonlinearText, ...
    'Nonlinear gates failed:\s*0/7','once')) && ...
    ~isempty(regexp(nonlinearText, ...
    'Combined project evidence:\s*25/25 PASS','once')), ...
    'prepareC172sNonlinearAutopilotRelease:NonlinearEvidenceNotPassing', ...
    'The frozen nonlinear-plant report does not prove 7/7 PASS.');

requiredFiles = frozenReleaseLedger();
assert(numel(unique(requiredFiles)) == numel(requiredFiles), ...
    'prepareC172sNonlinearAutopilotRelease:DuplicateLedgerEntry', ...
    'The frozen release ledger contains duplicate filenames.');
missing = requiredFiles(~cellfun(@(name) ...
    isfile(fullfile(projectRoot,name)),requiredFiles));
assert(isempty(missing), ...
    'prepareC172sNonlinearAutopilotRelease:MissingArtifact', ...
    'Required release artifact(s) missing: %s',strjoin(missing,', '));

releaseRoot = fullfile(projectRoot,'release');
releaseName = ['C172S_NonlinearAutopilot_' versionTag];
releaseFolder = fullfile(releaseRoot,releaseName);
zipPath = fullfile(releaseRoot,[releaseName '.zip']);
assert(~isfolder(releaseFolder) && ~isfile(zipPath), ...
    'prepareC172sNonlinearAutopilotRelease:TargetExists', ...
    ['Release target already exists. Preserve it and use a new version ', ...
     'tag, or move it outside the project before retrying.']);

if ~isfolder(releaseRoot)
    [made,message] = mkdir(releaseRoot);
    assert(made, ...
        'prepareC172sNonlinearAutopilotRelease:CreateFailed', ...
        'Could not create release directory: %s',message);
end
[made,message] = mkdir(releaseFolder);
assert(made,'prepareC172sNonlinearAutopilotRelease:CreateFailed', ...
    'Could not create release staging folder: %s',message);

sourceEntries = dir(projectRoot);
copiedNames = cell(0,1);
for k = 1:numel(sourceEntries)
    entry = sourceEntries(k);
    if entry.isdir || ~isReleaseableFile(entry.name)
        continue;
    end
    sourcePath = fullfile(projectRoot,entry.name);
    destinationPath = fullfile(releaseFolder,entry.name);
    [copied,message] = copyfile(sourcePath,destinationPath,'f');
    assert(copied, ...
        'prepareC172sNonlinearAutopilotRelease:CopyFailed', ...
        'Could not copy %s: %s',entry.name,message);
    copiedNames{end+1,1} = entry.name; %#ok<AGROW>
end

gitignoreSource = fullfile(projectRoot,'.gitignore');
gitignoreDestination = fullfile(releaseFolder,'.gitignore');
if isfile(gitignoreSource) && ~isfile(gitignoreDestination)
    [copied,message] = copyfile(gitignoreSource,gitignoreDestination,'f');
    assert(copied, ...
        'prepareC172sNonlinearAutopilotRelease:CopyFailed', ...
        'Could not copy .gitignore: %s',message);
    copiedNames{end+1,1} = '.gitignore'; %#ok<AGROW>
end

assert(all(cellfun(@(name) isfile(fullfile(releaseFolder,name)), ...
    requiredFiles)), ...
    'prepareC172sNonlinearAutopilotRelease:IncompleteStage', ...
    'The staged release does not contain every frozen artifact.');

forbiddenPatterns = {'*.slxc','*.asv','*.autosave','*.zip','*.m~'};
for k = 1:numel(forbiddenPatterns)
    assert(isempty(dir(fullfile(releaseFolder,forbiddenPatterns{k}))), ...
        'prepareC172sNonlinearAutopilotRelease:ForbiddenArtifact', ...
        'The staged release contains forbidden pattern %s.', ...
        forbiddenPatterns{k});
end
assert(~isfolder(fullfile(releaseFolder,'slprj')) && ...
    ~isfolder(fullfile(releaseFolder,'codegen')) && ...
    ~isfile(fullfile(releaseFolder,'untitled.m')), ...
    'prepareC172sNonlinearAutopilotRelease:ForbiddenArtifact', ...
    'The staged release contains generated cache or scratch content.');

copiedNames = sort(unique(copiedNames));
manifestPath = fullfile(releaseFolder,'RELEASE_MANIFEST.txt');
writeManifest(manifestPath,versionTag,copiedNames,releaseFolder);

zip(zipPath,{releaseName},releaseRoot);
assert(isfile(zipPath), ...
    'prepareC172sNonlinearAutopilotRelease:ZipFailed', ...
    'MATLAB did not create the expected ZIP file.');

folderInfo = dir(releaseFolder);
folderInfo = folderInfo(~[folderInfo.isdir]);
zipInfo = dir(zipPath);
release = struct();
release.version = versionTag;
release.folder = releaseFolder;
release.zip = zipPath;
release.fileCount = numel(folderInfo);
release.zipBytes = zipInfo.bytes;
release.nonlinearAutopilotRegression = '3/3 PASS';
release.flightControlsEvidence = '18/18 PASS (external frozen release)';
release.nonlinearPlantEvidence = '7/7 PASS (external frozen release)';
release.combinedEvidence = '28/28 PASS';
release.sourceModified = false;

fprintf('============================================================\n');
fprintf(' C172S NONLINEAR AUTOPILOT V0.1 - RELEASE PACKAGE COMPLETE\n');
fprintf('============================================================\n');
fprintf('%-38s: %s\n','Version',release.version);
fprintf('%-38s: %s\n','Nonlinear-autopilot regression', ...
    release.nonlinearAutopilotRegression);
fprintf('%-38s: %s\n','Frozen flight-controls evidence', ...
    release.flightControlsEvidence);
fprintf('%-38s: %s\n','Frozen nonlinear-plant evidence', ...
    release.nonlinearPlantEvidence);
fprintf('%-38s: %s\n','Combined project evidence', ...
    release.combinedEvidence);
fprintf('%-38s: %d\n','Packaged files',release.fileCount);
fprintf('%-38s: %s\n','Release folder',release.folder);
fprintf('%-38s: %s\n','ZIP package',release.zip);
fprintf('PASS: source files and both dependency releases were preserved.\n');
fprintf(['NOTE: this is a near-trim research integration with ideal ', ...
    'sensors and one-point throttle; it is not aircraft approval.\n']);
end

function keep = isReleaseableFile(name)
if any(strcmp(name,{'untitled.m','RELEASE_MANIFEST.txt'}))
    keep = false;
    return;
end
if strcmp(name,'.gitignore')
    keep = true;
    return;
end
[~,~,extension] = fileparts(name);
keep = any(strcmpi(extension,{'.m','.slx','.md','.txt','.csv'}));
end

function required = frozenReleaseLedger()
required = { ...
    'runAllNonlinearAutopilotChecks.m'; ...
    'prepareC172sNonlinearAutopilotRelease.m'; ...
    'NonlinearAutopilotRegressionReport.txt'; ...
    'FlightControlRegressionReport.txt'; ...
    'Nonlinear6DofRegressionReport.txt'; ...
    'c172sNonlinearAutopilotInterfaceData.m'; ...
    'auditC172sNonlinearAutopilotInterfaces.m'; ...
    'c172sNonlinearAutopilotClosedLoopData.m'; ...
    'simulateC172sNonlinearAutopilot.m'; ...
    'auditC172sNonlinearAutopilotClosedLoop.m'; ...
    'buildC172sNonlinearAutopilotSimulink.m'; ...
    'runNonlinearAutopilotSimulinkCheck.m'; ...
    'C172S_NonlinearAutopilot_V1.slx'; ...
    'c172sIntegratedAutopilotData.m'; ...
    'c172sAutopilotModeManagerData.m'; ...
    'c172sAutopilotModeManagerStep.m'; ...
    'c172sIntegratedNonlinearDynamicsData.m'; ...
    'c172sIntegratedNonlinearDynamics.m'; ...
    'c172sTrimTotalForceData.m'; ...
    'c172sTrimTotalForces.m'; ...
    'solveC172sNonlinearTrim.m'; ...
    'c172sAtmosphereAirDataData.m'; ...
    'c172sAtmosphereAirData.m'; ...
    'c172sRigidBody6DofData.m'; ...
    'c172sRigidBody6DofEom.m'; ...
    'c172sLongitudinalData.m'; ...
    'c172sLateralDirectionalData.m'; ...
    'c172sElevatorActuatorData.m'; ...
    'c172sAileronActuatorData.m'; ...
    'c172sRudderActuatorData.m'};
end

function writeManifest(path,versionTag,fileNames,releaseFolder)
fid = fopen(path,'w');
assert(fid >= 0, ...
    'prepareC172sNonlinearAutopilotRelease:ManifestWriteFailed', ...
    'Unable to write release manifest: %s',path);
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

generated = datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss''Z''');
fprintf(fid,'C172S NONLINEAR AUTOPILOT - RELEASE MANIFEST\n');
fprintf(fid,'Version: %s\n',versionTag);
fprintf(fid,'Generated UTC: %s\n',char(generated));
fprintf(fid,'MATLAB: %s\n',version);
fprintf(fid,'Nonlinear-autopilot regression: 3/3 PASS\n');
fprintf(fid,'Frozen flight-controls evidence: 18/18 PASS (external)\n');
fprintf(fid,'Frozen nonlinear-plant evidence: 7/7 PASS (external)\n');
fprintf(fid,'Combined project evidence: 28/28 PASS\n');
fprintf(fid,['Scope: frozen flight-controls v1.0.0 operating one coupled ', ...
    'nonlinear 13-state research plant v0.1.0 through the frozen Mode ', ...
    'Manager, protected controller stack and executable Simulink model.\n']);
fprintf(fid,['Qualification: 80-130 KTAS, alpha -4 to +10 deg, beta ', ...
    '+/-8 deg, flaps up, near-trim attached flow, provisional mass ', ...
    'properties, ideal sensors and one-point throttle; no stall/spin, ', ...
    'autothrottle or aircraft-truth claim; not aircraft approval.\n\n']);
fprintf(fid,'Packaged files:\n');

allNames = sort([fileNames; {'RELEASE_MANIFEST.txt'}]);
for k = 1:numel(allNames)
    info = dir(fullfile(releaseFolder,allNames{k}));
    if isempty(info)
        bytes = 0;
    else
        bytes = info(1).bytes;
    end
    fprintf(fid,'%10d  %s\n',bytes,allNames{k});
end
end
