function results = runAllFlightControlChecks()
%RUNALLFLIGHTCONTROLCHECKS Execute the complete flight-controls release gate.
%
%   RESULTS = RUNALLFLIGHTCONTROLCHECKS runs the frozen longitudinal V1
%   release checks followed by the complete lateral-directional chain and
%   executable Autopilot Mode Manager V1 and Integrated Autopilot V1. The
%   release manifest includes MATLAB design/audit gates and independent
%   Simulink implementation checks.
%
%   Each script is executed in the base workspace by its resolved full path.
%   This isolates the runner from the CLEAR commands intentionally used by
%   the individual release scripts. A complete text record is written beside
%   this file as FlightControlRegressionReport.txt. Structured results are
%   also assigned to flightControlRegressionResults in the base workspace.
%
%   Frozen project dependencies verified by the called release scripts:
%     Lateral-Directional Plant V0.1
%     YD-V1-MATLAB-R2
%     YD-V2-AUDIT-MATLAB-R1
%     AILERON-V1-AUDIT-MATLAB-R1
%     RAH-V1-MATLAB-R1
%     HEADING-SENSOR-V1-AUDIT-MATLAB-R1
%     HH-V1-MATLAB-R1
%     AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1
%     INTEGRATED-AUTOPILOT-V1-INTERFACE-AUDIT-MATLAB-R1

clc;

projectRoot = fileparts(mfilename('fullpath'));
checks = regressionManifest();
nCheck = numel(checks);

emptyResult = struct( ...
    'Domain','', ...
    'Name','', ...
    'Artifact','', ...
    'Checker','', ...
    'Path','', ...
    'Status','NOT RUN', ...
    'Duration_s',NaN, ...
    'Identifier','', ...
    'Message','', ...
    'Output','');
results = repmat(emptyResult,nCheck,1);

fprintf('============================================================\n');
fprintf('       C172S FLIGHT CONTROLS - MASTER REGRESSION GATE\n');
fprintf('============================================================\n');
fprintf('Longitudinal release checks          : %d\n', ...
    sum(strcmp({checks.Domain},'Longitudinal')));
fprintf('Lateral-directional release checks   : %d\n', ...
    sum(strcmp({checks.Domain},'Lateral-directional')));
fprintf('Supervisory release checks           : %d\n', ...
    sum(strcmp({checks.Domain},'Supervisory')));
fprintf('Integrated release checks            : %d\n\n', ...
    sum(strcmp({checks.Domain},'Integrated')));

for k = 1:nCheck
    results(k).Domain = checks(k).Domain;
    results(k).Name = checks(k).Name;
    results(k).Artifact = checks(k).Artifact;
    results(k).Checker = checks(k).Checker;

    % Prefer the checker beside this runner. Falling back to WHICH supports
    % deliberately shared checkers while preventing an older path entry from
    % silently shadowing the current project copy.
    localCandidate = fullfile(projectRoot,[checks(k).Checker '.m']);
    if isfile(localCandidate)
        checkerPath = localCandidate;
    else
        checkerPath = which(checks(k).Checker);
    end

    if isempty(checkerPath)
        results(k).Status = 'FAIL';
        results(k).Identifier = ...
            'runAllFlightControlChecks:MissingChecker';
        results(k).Message = sprintf( ...
            'MATLAB could not locate %s.m.',checks(k).Checker);
        fprintf('[FAIL] %2d/%d %-45s checker not found\n', ...
            k,nCheck,checks(k).Name);
        continue;
    end

    results(k).Path = checkerPath;
    escapedPath = strrep(checkerPath,'''','''''');
    checkCommand = sprintf('run(''%s'');',escapedPath); %#ok<NASGU>

    fprintf('Running %2d/%d [%s] %s ...\n', ...
        k,nCheck,checks(k).Domain,checks(k).Name);
    startTime = tic;
    try
        results(k).Output = evalc( ...
            'evalin(''base'',checkCommand);');
        results(k).Duration_s = toc(startTime);
        results(k).Status = 'PASS';
        fprintf('[PASS] %s (%.2f s)\n\n', ...
            checks(k).Name,results(k).Duration_s);
    catch ME
        results(k).Duration_s = toc(startTime);
        results(k).Status = 'FAIL';
        results(k).Identifier = ME.identifier;
        results(k).Message = ME.message;
        results(k).Output = getReport(ME,'extended', ...
            'hyperlinks','off');
        fprintf('[FAIL] %s (%.2f s)\n', ...
            checks(k).Name,results(k).Duration_s);
        fprintf('       %s\n\n',oneLine(ME.message));
    end
end

status = {results.Status};
passCount = sum(strcmp(status,'PASS'));
failCount = sum(strcmp(status,'FAIL'));
reportFile = fullfile(projectRoot,'FlightControlRegressionReport.txt');
writeRegressionReport(reportFile,results,passCount,failCount);

assignin('base','flightControlRegressionResults',results);
assignin('base','flightControlRegressionReport',reportFile);

fprintf('============================================================\n');
fprintf('                    CONSOLIDATED RESULT\n');
fprintf('============================================================\n');
for k = 1:nCheck
    fprintf('%-21s %-46s : %s\n', ...
        results(k).Domain,results(k).Name,results(k).Status);
end
fprintf('------------------------------------------------------------\n');
fprintf('Passed                               : %d/%d\n', ...
    passCount,nCheck);
fprintf('Regression report                    : %s\n',reportFile);

if failCount == 0
    fprintf(['\nPASS: the frozen longitudinal release and lateral stack ', ...
        'through executable Integrated Autopilot V1 satisfy every ', ...
        'master regression gate.\n']);
    fprintf(['NOTE: the lateral result remains limited to Plant V0.1 and ', ...
        'declared project assumptions; it is not aircraft approval.\n']);
else
    fprintf('\nFAIL: %d release gate(s) did not pass.\n',failCount);
    error('runAllFlightControlChecks:ReleaseGateFailure', ...
        '%d of %d master regression checks failed. See %s.', ...
        failCount,nCheck,reportFile);
end
end

function checks = regressionManifest()
% Keep this ordered list as the auditable definition of the master gate.
checks = [ ...
    makeCheck('Longitudinal','Longitudinal plant', ...
        'Longitudinal Plant V1','runSimulinkPlantCheck'); ...
    makeCheck('Longitudinal','Pitch-rate damper V1', ...
        'Pitch-Rate Damper V1','runPitchRateDamperSimulinkCheck'); ...
    makeCheck('Longitudinal','Pitch-attitude hold V1', ...
        'Pitch-Attitude Hold V1','runPitchAttitudeHoldSimulinkCheck'); ...
    makeCheck('Longitudinal', ...
        'Pitch-attitude hold V2 actuator protection', ...
        'Pitch-Attitude Hold V2', ...
        'runPitchAttitudeActuatorSimulinkCheck'); ...
    makeCheck('Longitudinal','Altitude hold V1', ...
        'Altitude Hold V1','runAltitudeHoldSimulinkCheck'); ...
    makeCheck('Lateral-directional', ...
        'Lateral plant V0.1 MATLAB audit', ...
        'Lateral-Directional Plant V0.1', ...
        'runLateralDirectionalPlantValidation'); ...
    makeCheck('Lateral-directional', ...
        'Lateral plant V0.1 Simulink implementation', ...
        'Lateral-Directional Plant V0.1', ...
        'runLateralDirectionalSimulinkCheck'); ...
    makeCheck('Lateral-directional','Yaw Damper V1 MATLAB audit', ...
        'YD-V1-MATLAB-R2','designYawDamper'); ...
    makeCheck('Lateral-directional', ...
        'Yaw Damper V1 Simulink implementation', ...
        'YD-V1-MATLAB-R2','runYawDamperSimulinkCheck'); ...
    makeCheck('Lateral-directional', ...
        'Yaw Damper V2 actuator/protection audit', ...
        'YD-V2-AUDIT-MATLAB-R1', ...
        'designYawDamperActuatorProtection'); ...
    makeCheck('Lateral-directional', ...
        'Yaw Damper V2 protected Simulink implementation', ...
        'YD-V2-AUDIT-MATLAB-R1', ...
        'runYawDamperActuatorSimulinkCheck'); ...
    makeCheck('Lateral-directional', ...
        'Roll-Attitude Hold V1 MATLAB audit', ...
        'RAH-V1-MATLAB-R1','designRollAttitudeHold'); ...
    makeCheck('Lateral-directional', ...
        'Roll-Attitude Hold V1 protected Simulink implementation', ...
        'RAH-V1-MATLAB-R1','runRollAttitudeHoldSimulinkCheck'); ...
    makeCheck('Lateral-directional', ...
        'Heading Hold V1 protected Simulink implementation', ...
        'HH-V1-MATLAB-R1','runHeadingHoldSimulinkCheck'); ...
    makeCheck('Supervisory', ...
        'Autopilot Mode Manager V1 MATLAB logic audit', ...
        'AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1', ...
        'auditAutopilotModeManager'); ...
    makeCheck('Supervisory', ...
        'Autopilot Mode Manager V1 executable Simulink implementation', ...
        'AUTOPILOT-MODE-MANAGER-V1-AUDIT-MATLAB-R1', ...
        'runAutopilotModeManagerSimulinkCheck'); ...
    makeCheck('Integrated', ...
        'Integrated Autopilot V1 interface/scenario audit', ...
        'INTEGRATED-AUTOPILOT-V1-INTERFACE-AUDIT-MATLAB-R1', ...
        'auditIntegratedAutopilotInterfaces'); ...
    makeCheck('Integrated', ...
        'Integrated Autopilot V1 executable Simulink implementation', ...
        'INTEGRATED-AUTOPILOT-V1-INTERFACE-AUDIT-MATLAB-R1', ...
        'runIntegratedAutopilotSimulinkCheck')];
end

function check = makeCheck(domain,name,artifact,checker)
check = struct('Domain',domain,'Name',name, ...
    'Artifact',artifact,'Checker',checker);
end

function writeRegressionReport(reportFile,results,passCount,failCount)
fid = fopen(reportFile,'w');
if fid < 0
    error('runAllFlightControlChecks:ReportWriteFailed', ...
        'Unable to write regression report: %s',reportFile);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid,'C172S FLIGHT CONTROLS - MASTER REGRESSION REPORT\n');
fprintf(fid,'Generated: %s\n',datestr(now,31)); %#ok<DATST>
fprintf(fid,'MATLAB: %s\n',version);
fprintf(fid,['Scope: longitudinal release plus lateral stack through ', ...
    'executable Integrated Autopilot V1\n']);
fprintf(fid,'Passed: %d/%d\n',passCount,numel(results));
fprintf(fid,'Failed: %d/%d\n\n',failCount,numel(results));

domains = unique({results.Domain},'stable');
for iDomain = 1:numel(domains)
    selected = strcmp({results.Domain},domains{iDomain});
    fprintf(fid,'%s: %d/%d passed\n',domains{iDomain}, ...
        sum(strcmp({results(selected).Status},'PASS')),sum(selected));
end
fprintf(fid,['\nQualification: lateral dynamics use provisional Plant V0.1; ', ...
    'supervisory thresholds, timers and other declared values remain ', ...
    'project assumptions. This report is not aircraft approval.\n\n']);

for k = 1:numel(results)
    fprintf(fid,'============================================================\n');
    fprintf(fid,'%d. [%s] %s\n',k,results(k).Domain,results(k).Name);
    fprintf(fid,'Artifact: %s\n',results(k).Artifact);
    fprintf(fid,'Checker: %s.m\n',results(k).Checker);
    fprintf(fid,'Path: %s\n',results(k).Path);
    fprintf(fid,'Status: %s\n',results(k).Status);
    fprintf(fid,'Duration: %.3f s\n',results(k).Duration_s);
    if ~isempty(results(k).Identifier)
        fprintf(fid,'Identifier: %s\n',results(k).Identifier);
    end
    if ~isempty(results(k).Message)
        fprintf(fid,'Message: %s\n',results(k).Message);
    end
    fprintf(fid,'\nCaptured output:\n%s\n\n',results(k).Output);
end
end

function text = oneLine(text)
text = regexprep(text,'\s+',' ');
text = strtrim(text);
end
