%% C172S Heading Hold V1 - protected Simulink equivalence check

clc;
clear;
close all;

try
    load_system('simulink');
catch ME
    error('runHeadingHoldSimulinkCheck:SimulinkUnavailable', ...
        'Unable to load Simulink. MATLAB reported:\n%s',ME.message);
end

data = c172sLateralDirectionalData();
[~,plant] = c172sLateralDirectionalPlant(data);
yawController = c172sYawDamperData();
rudder = c172sRudderActuatorData();
rollController = c172sRollAttitudeControllerData();
aileron = c172sAileronActuatorData();
headingSensor = c172sHeadingSensorData();
headingController = c172sHeadingHoldControllerData();
assertDependencies(data,yawController,rudder,rollController,aileron, ...
    headingSensor,headingController);

% Rebuild the generated diagram so a stale or hand-edited SLX cannot
% influence the implementation-equivalence result.
modelName = buildC172sHeadingHoldSimulink(true);

%% Ten independent executable captures

commandCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'command');
largeTurnCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'largeTurn');
wrapRightCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'wrapRight');
wrapLeftCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'wrapLeft');
biasCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'bias');
aileronPulseCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'aileronPulse');
rudderPulseCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'rudderPulse');
stressCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'stressAw');
stressNoAwCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'stressNoAw');
noiseCapture = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,'noise');

captureNames = {'Command','Large turn','Wrap right','Wrap left','Bias', ...
    'Aileron pulse','Rudder pulse','Stress AW','Stress no-AW','Noise'};
captures = {commandCapture,largeTurnCapture,wrapRightCapture, ...
    wrapLeftCapture,biasCapture,aileronPulseCapture,rudderPulseCapture, ...
    stressCapture,stressNoAwCapture,noiseCapture};

%% Independent hybrid-equivalence gates

tolerance = 1.0e-5;
for k = 1:numel(captures)
    assert(captures{k}.maxError < tolerance, ...
        '%s-capture error %.6g exceeds %.6g.', ...
        captureNames{k},captures{k}.maxError,tolerance);
end

assert(strcmp(get_param(modelName,'SolverType'),'Fixed-step'), ...
    'The generated model must use a fixed-step solver.');
assert(strcmp(get_param(modelName,'Solver'),'ode4'), ...
    'The generated model must use ode4.');
assert(abs(str2double(get_param(modelName,'FixedStep'))-0.01) < eps, ...
    'The generated model fixed step must be 0.01 s.');
assert(strcmp(get_param([modelName '/Command Filter'],'A'), ...
    '-1/Tcmd_hh1'),'The bank-command filter changed.');

headingPath = [modelName '/Heading Sensor and Outer Loop'];
rollPath = [modelName '/Frozen Protected Roll-Attitude Hold V1'];
yawPath = [modelName '/Frozen Protected Yaw Damper V2'];
for k = 1:5
    delayBlock = sprintf('%s/Heading Pure Delay %d',headingPath,k);
    assert(strcmp(get_param(delayBlock,'SampleTime'), ...
        'headingDelaySampleTime_hh1'), ...
        'The 50-ms heading-delay chain changed.');
end
assert(strcmp(get_param([headingPath '/Heading Sensor Filter'],'A'), ...
    '-1/TsHeading_hh1'),'The heading-sensor filter changed.');
assert(strcmp(get_param([headingPath '/Circular Error'],'Expr'), ...
    'atan2(sin(u),cos(u))'),'The circular-error law changed.');
assert(strcmp(get_param([headingPath '/Heading Gain Kpsi'],'Gain'), ...
    'Kpsi_hh1'),'The heading-error gain changed.');
assert(strcmp(get_param([headingPath '/Bank Command Limit'], ...
    'UpperLimit'),'bankCommandUpper_hh1_rad'), ...
    'The bank-command authority changed.');
assert(strcmp(get_param([rollPath '/p Pure Delay'],'SampleTime'), ...
    'delaySampleTime_hh1'),'The p-channel pure delay changed.');
assert(strcmp(get_param([rollPath '/Phi Pure Delay'],'SampleTime'), ...
    'delaySampleTime_hh1'),'The phi-channel pure delay changed.');
assert(strcmp(get_param([yawPath '/r Pure Delay'],'SampleTime'), ...
    'delaySampleTime_hh1'),'The yaw-channel pure delay changed.');
assert(strcmp(get_param([rollPath '/p Sensor Filter'],'A'), ...
    '-1/TsRoll_hh1'),'The p sensor filter changed.');
assert(strcmp(get_param([rollPath '/Phi Sensor Filter'],'A'), ...
    '-1/TsRoll_hh1'),'The phi sensor filter changed.');
assert(strcmp(get_param([rollPath '/Bank Proportional Gain Kphi'],'Gain'), ...
    'Kphi_hh1'),'The bank proportional gain changed.');
assert(strcmp(get_param([rollPath '/Bank Integral Gain Ki'],'Gain'), ...
    'Ki_hh1'),'The bank integral gain changed.');
assert(strcmp(get_param([rollPath '/Roll-Rate Gain -Kp'],'Gain'), ...
    '-Kp_hh1'),'The roll-rate feedback sign or gain changed.');
assert(strcmp(get_param([rollPath '/Automatic Aileron Position Limit'], ...
    'UpperLimit'),'autoAileronUpper_hh1_rad'), ...
    'The automatic-aileron authority changed.');
assert(strcmp(get_param([rollPath '/Aileron Servo Rate Limit'], ...
    'UpperLimit'),'aileronRateUpper_hh1_radps'), ...
    'The aileron rate limit changed.');
assert(strcmp(get_param([rollPath '/Anti-Windup Scale'],'Gain'), ...
    '1/(Ki_hh1*Tt_hh1)'), ...
    'The anti-windup tracking law changed.');
assert(strcmp(get_param([yawPath '/Automatic Rudder Gain'],'Gain'), ...
    '-Kr_hh1'),'The frozen yaw-damper sign or gain changed.');
assert(strcmp(get_param([modelName '/Physical Aileron Hard Stop'], ...
    'UpperLimit'),'totalAileronUpper_hh1_rad'), ...
    'The physical aileron hard stop changed.');
assert(strcmp(get_param([modelName '/Physical Rudder Hard Stop'], ...
    'UpperLimit'),'totalRudderUpper_hh1_rad'), ...
    'The physical rudder hard stop changed.');

%% Exact signal identities, signs and summations

I = signalIndices();
for k = 1:numel(captures)
    y = captures{k}.ySim;
    cfg = captures{k}.configuration;

    assert(max(abs(y(:,I.headingInput)-(y(:,I.psiDelayed)+ ...
        y(:,I.headingBias)+y(:,I.headingNoise)))) < 1.0e-12, ...
        'Heading-sensor summation is inconsistent.');
    assert(max(abs(y(:,I.headingDifference)-(y(:,I.headingCommand)- ...
        y(:,I.headingSensor)))) < 1.0e-12, ...
        'The raw heading-difference sign is inconsistent.');
    assert(max(abs(y(:,I.headingError)-wrapAngle( ...
        y(:,I.headingDifference)))) < 1.0e-12, ...
        'The circular heading-error law is inconsistent.');
    assert(max(abs(y(:,I.bankCommandRaw)- ...
        headingController.headingErrorGain*y(:,I.headingError))) < ...
        1.0e-12,'The heading gain is inconsistent.');
    bankLimit = deg2rad(headingController.bankCommandAuthority_deg);
    assert(max(abs(y(:,I.bankCommandLimited)-clip( ...
        y(:,I.bankCommandRaw),-bankLimit,bankLimit))) < 1.0e-12, ...
        'Bank-command limiting is inconsistent.');
    assert(max(abs(y(:,I.rInput)-(y(:,I.rDelayed)+y(:,I.rNoise)))) < ...
        1.0e-12,'Yaw sensor summation is inconsistent.');
    assert(max(abs(y(:,I.pInput)-(y(:,I.pDelayed)+y(:,I.pNoise)))) < ...
        1.0e-12,'Roll-rate sensor summation is inconsistent.');
    assert(max(abs(y(:,I.phiInput)-(y(:,I.phiDelayed)+ ...
        y(:,I.phiNoise)))) < 1.0e-12, ...
        'Bank-angle sensor summation is inconsistent.');
    assert(max(abs(y(:,I.bankError)-(y(:,I.bankCommandFiltered)- ...
        y(:,I.phiSensor)))) < 1.0e-12, ...
        'The bank-error sign or summation is inconsistent.');
    assert(max(abs(y(:,I.proportional)- ...
        rollController.bankProportionalGain*y(:,I.bankError))) < 1.0e-12, ...
        'The proportional contribution is inconsistent.');
    assert(max(abs(y(:,I.integral)- ...
        rollController.bankIntegralGain_per_s*y(:,I.xi))) < 1.0e-12, ...
        'The integral contribution is inconsistent.');
    assert(max(abs(y(:,I.rollRateContribution)+ ...
        rollController.rollRateGain_s*y(:,I.pSensor))) < 1.0e-12, ...
        'The roll-rate damping contribution is inconsistent.');
    assert(max(abs(y(:,I.aileronUnsat)-(y(:,I.proportional)+ ...
        y(:,I.integral)+y(:,I.rollRateContribution)))) < 1.0e-12, ...
        'The unsaturated automatic-aileron sum is inconsistent.');
    assert(max(abs(y(:,I.aileronPosition)-clip(y(:,I.aileronUnsat), ...
        aileron.authority.lowerLimit_rad, ...
        aileron.authority.upperLimit_rad))) < 1.0e-12, ...
        'Automatic-aileron position limiting is inconsistent.');
    assert(max(abs(y(:,I.aileronRateRaw)-(y(:,I.aileronPosition)- ...
        y(:,I.aileronActual))/aileron.dynamics.timeConstant_s)) < 1.0e-10, ...
        'The raw aileron-servo rate is inconsistent.');
    assert(max(abs(y(:,I.aileronRate)-clip(y(:,I.aileronRateRaw), ...
        -deg2rad(aileron.dynamics.rateLimit_degps), ...
        deg2rad(aileron.dynamics.rateLimit_degps)))) < 1.0e-12, ...
        'Aileron-servo rate limiting is inconsistent.');
    assert(max(abs(y(:,I.aileronTrack)-(y(:,I.aileronActual)+ ...
        aileron.dynamics.timeConstant_s*y(:,I.aileronRate)))) < 1.0e-12, ...
        'The rate-aware aileron tracking value is inconsistent.');
    expectedAw = cfg.antiWindupEnable*(y(:,I.aileronTrack)- ...
        y(:,I.aileronUnsat))/(rollController.bankIntegralGain_per_s* ...
        aileron.antiWindup.trackingTimeConstant_s);
    assert(max(abs(y(:,I.antiWindup)-expectedAw)) < 1.0e-10, ...
        'The anti-windup correction is inconsistent.');
    assert(max(abs(y(:,I.aileronTotalRaw)-(y(:,I.aileronPilot)+ ...
        y(:,I.aileronActual)))) < 1.0e-12, ...
        'Pilot plus automatic aileron summation is inconsistent.');
    assert(max(abs(y(:,I.aileronTotal)-clip(y(:,I.aileronTotalRaw), ...
        aileron.physicalTravel.lowerLimit_rad, ...
        aileron.physicalTravel.upperLimit_rad))) < 1.0e-12, ...
        'Physical aileron limiting is inconsistent.');

    assert(max(abs(y(:,I.rudderPosition)-clip(y(:,I.rudderRaw), ...
        rudder.authority.lowerLimit_rad,rudder.authority.upperLimit_rad))) < ...
        1.0e-12,'Automatic-rudder position limiting is inconsistent.');
    assert(max(abs(y(:,I.rudderRate)-clip(y(:,I.rudderRateRaw), ...
        -deg2rad(rudder.dynamics.rateLimit_degps), ...
        deg2rad(rudder.dynamics.rateLimit_degps)))) < 1.0e-12, ...
        'Rudder-servo rate limiting is inconsistent.');
    assert(max(abs(y(:,I.rudderTotalRaw)-(y(:,I.rudderPilot)+ ...
        y(:,I.rudderActual)))) < 1.0e-12, ...
        'Pilot plus automatic rudder summation is inconsistent.');
    assert(max(abs(y(:,I.rudderTotal)-clip(y(:,I.rudderTotalRaw), ...
        rudder.physicalTravel.lowerLimit_rad, ...
        rudder.physicalTravel.upperLimit_rad))) < 1.0e-12, ...
        'Physical rudder limiting is inconsistent.');
end

positiveError = find(commandCapture.ySim(:,I.bankError) > deg2rad(0.01), ...
    1,'first');
assert(~isempty(positiveError) && ...
    commandCapture.ySim(positiveError,I.proportional) > 0 && ...
    commandCapture.ySim(positiveError,I.aileronUnsat) > 0, ...
    'Positive bank error did not command positive right-wing-down aileron.');
positiveRollRate = find(commandCapture.ySim(:,I.pSensor) > ...
    deg2rad(0.01),1,'first');
assert(~isempty(positiveRollRate) && ...
    commandCapture.ySim(positiveRollRate,I.rollRateContribution) < 0, ...
    'Positive roll rate did not produce negative damping aileron.');
positiveYawRate = find(commandCapture.ySim(:,I.rSensor) > ...
    deg2rad(0.01),1,'first');
assert(~isempty(positiveYawRate) && ...
    commandCapture.ySim(positiveYawRate,I.rudderRaw) < 0, ...
    'Positive yaw rate did not produce negative damping rudder.');

%% Heading acquisition, wrap, bias and pilot-interaction gates

req = headingController.requirements;
command_rad = deg2rad(headingController.validation.commandStep_deg);
commandMetrics = positiveStepMetrics(commandCapture.t, ...
    commandCapture.ySim(:,I.psi),command_rad);
commandFinalError_deg = abs(rad2deg(wrapAngle(command_rad- ...
    commandCapture.ySim(end,I.psi))));
commandPeakBank_deg = max(abs(rad2deg(commandCapture.ySim(:,I.phi))));
commandPeakRollRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.p))));
commandPeakYawRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.r))));
commandPeakBeta_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.beta))));
commandPeakAileron_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.aileronActual))));
commandPeakRudder_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.rudderActual))));
commandPeakAileronRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.aileronRate))));

assert(commandMetrics.riseTime_s >= req.minimumRiseTime_s && ...
    commandMetrics.riseTime_s <= req.maximumRiseTime_s, ...
    'The executable heading rise time failed its gate.');
assert(commandMetrics.overshoot_pct <= req.maximumStepOvershoot_pct, ...
    'The executable heading overshoot failed its gate.');
assert(commandMetrics.settlingTime_s <= req.maximumSettlingTime_s, ...
    'The executable heading settling time failed its gate.');
assert(commandFinalError_deg <= req.maximumFinalHeadingError_deg, ...
    ['The executable final heading error %.6f deg exceeds the ', ...
     '%.6f-deg gate.'],commandFinalError_deg, ...
    req.maximumFinalHeadingError_deg);
assert(commandPeakBank_deg <= req.maximumOperationalBank_deg, ...
    'The executable command exceeded the bank-angle gate.');
assert(commandPeakRollRate_degps <= ...
    req.maximumOperationalRollRate_degps, ...
    'The executable command exceeded the roll-rate gate.');
assert(commandPeakYawRate_degps <= req.maximumOperationalYawRate_degps, ...
    'The executable command exceeded the yaw-rate gate.');
assert(commandPeakBeta_deg <= req.maximumOperationalSideslip_deg, ...
    'The executable command exceeded the sideslip gate.');
assert(commandPeakAileron_deg <= req.maximumAutomaticAileron_deg, ...
    'The executable command exceeded automatic-aileron effort.');
assert(commandPeakRudder_deg <= req.maximumAutomaticRudder_deg, ...
    'The executable command exceeded automatic-rudder effort.');
assert(commandPeakAileronRate_degps <= ...
    req.maximumOperationalAileronRate_degps, ...
    'The executable command exceeded the aileron-rate gate.');

positiveHeadingError = find(commandCapture.ySim(:,I.headingError) > ...
    deg2rad(0.01),1,'first');
assert(~isempty(positiveHeadingError) && ...
    commandCapture.ySim(positiveHeadingError,I.bankCommandRaw) > 0, ...
    'Positive heading error did not command right-wing-down bank.');
assert(wrapRightCapture.ySim(1,I.bankCommandLimited) > 0 && ...
    wrapLeftCapture.ySim(1,I.bankCommandLimited) < 0, ...
    'The north-crossing cases selected the wrong turn directions.');

largeCommand_rad = deg2rad( ...
    headingController.validation.largeCommandStep_deg);
largeCommandLimitActive = any(abs( ...
    largeTurnCapture.ySim(:,I.bankCommandRaw)- ...
    largeTurnCapture.ySim(:,I.bankCommandLimited)) > 1.0e-10);
largeMaximumBankCommand_deg = max(abs(rad2deg( ...
    largeTurnCapture.ySim(:,I.bankCommandLimited))));
largePeakBank_deg = max(abs(rad2deg(largeTurnCapture.ySim(:,I.phi))));
largePeakRollRate_degps = max(abs(rad2deg( ...
    largeTurnCapture.ySim(:,I.p))));
largePeakYawRate_degps = max(abs(rad2deg( ...
    largeTurnCapture.ySim(:,I.r))));
largePeakBeta_deg = max(abs(rad2deg( ...
    largeTurnCapture.ySim(:,I.beta))));
largeFinalError_deg = abs(rad2deg(wrapAngle(largeCommand_rad- ...
    largeTurnCapture.ySim(end,I.psi))));
largeSettlingTime_s = wrappedSettlingTime(largeTurnCapture.t, ...
    largeTurnCapture.ySim(:,I.psi),largeCommand_rad,0.02);
assert(largeCommandLimitActive, ...
    'The 90-deg heading command did not activate bank limiting.');
assert(abs(largeMaximumBankCommand_deg- ...
    headingController.bankCommandAuthority_deg) < 1.0e-9, ...
    'The executable bank-command authority is incorrect.');
assert(largePeakBank_deg <= ...
    headingController.largeTurn.maximumActualBank_deg, ...
    'The large-turn actual bank exceeded its gate.');
assert(largePeakRollRate_degps <= ...
    headingController.largeTurn.maximumRollRate_degps, ...
    'The large-turn roll rate exceeded its gate.');
assert(largePeakYawRate_degps <= ...
    headingController.largeTurn.maximumYawRate_degps, ...
    'The large-turn yaw rate exceeded its gate.');
assert(largePeakBeta_deg <= headingController.largeTurn.maximumSideslip_deg, ...
    'The large-turn sideslip exceeded its gate.');
assert(largeFinalError_deg <= ...
    headingController.largeTurn.maximumFinalHeadingError_deg, ...
    'The large-turn final heading error exceeded its gate.');
assert(largeSettlingTime_s <= ...
    headingController.largeTurn.maximumSettlingTime_s, ...
    'The large-turn settling time exceeded its gate.');

wrapRightFinalError_deg = abs(rad2deg(wrapAngle( ...
    deg2rad(headingController.validation.wrapRightCommand_deg)- ...
    wrapRightCapture.ySim(end,I.psi))));
wrapLeftFinalError_deg = abs(rad2deg(wrapAngle( ...
    deg2rad(headingController.validation.wrapLeftCommand_deg)- ...
    wrapLeftCapture.ySim(end,I.psi))));
assert(wrapRightFinalError_deg <= ...
    headingSensor.requirements.maximumWrapCaptureError_deg && ...
    wrapLeftFinalError_deg <= ...
    headingSensor.requirements.maximumWrapCaptureError_deg, ...
    'A north-crossing wrap capture failed.');

biasMeasuredError_deg = rad2deg(wrapAngle( ...
    biasCapture.ySim(end,I.headingCommand)- ...
    biasCapture.ySim(end,I.headingSensor)));
biasTrueError_deg = rad2deg(wrapAngle( ...
    biasCapture.ySim(end,I.headingCommand)- ...
    biasCapture.ySim(end,I.psi)));
assert(abs(biasMeasuredError_deg) <= ...
    headingSensor.requirements.maximumMeasuredBiasCaseError_deg, ...
    'The heading-bias case did not null measured error.');
assert(abs(abs(biasTrueError_deg)-headingSensor.biasStress_deg) <= ...
    headingSensor.requirements.maximumBiasResidualMismatch_deg, ...
    'The heading-bias case did not expose the true-heading residual.');

aileronPulsePeakHeading_deg = max(abs(rad2deg( ...
    aileronPulseCapture.ySim(:,I.psi))));
rudderPulsePeakHeading_deg = max(abs(rad2deg( ...
    rudderPulseCapture.ySim(:,I.psi))));
aileronPulseFinalError_deg = abs(rad2deg(wrapAngle( ...
    aileronPulseCapture.ySim(end,I.headingCommand)- ...
    aileronPulseCapture.ySim(end,I.psi))));
rudderPulseFinalError_deg = abs(rad2deg(wrapAngle( ...
    rudderPulseCapture.ySim(end,I.headingCommand)- ...
    rudderPulseCapture.ySim(end,I.psi))));
assert(aileronPulseFinalError_deg <= req.maximumFinalHeadingError_deg && ...
    rudderPulseFinalError_deg <= req.maximumFinalHeadingError_deg, ...
    'A pilot pulse did not return to selected heading.');

operationalCaptures = {commandCapture,largeTurnCapture,wrapRightCapture, ...
    wrapLeftCapture,biasCapture,aileronPulseCapture,rudderPulseCapture};
for k = 1:numel(operationalCaptures)
    assert(~aileronPositionLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~aileronRateLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~aileronPhysicalLimitActive(operationalCaptures{k}.ySim,I), ...
        'Aileron protection unexpectedly activated operationally.');
    assert(~rudderPositionLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~rudderRateLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~rudderPhysicalLimitActive(operationalCaptures{k}.ySim,I), ...
        'Rudder protection unexpectedly activated operationally.');
end

%% Actuator-stress, anti-windup, heading-noise and delay gates

stressMetrics = protectedStressMetrics(stressCapture,I,aileron);
stressNoAwMetrics = protectedStressMetrics(stressNoAwCapture,I,aileron);
antiWindupIntegratorRatio = stressMetrics.peakIntegratorMagnitude/ ...
    stressNoAwMetrics.peakIntegratorMagnitude;
stressFinalHeadingError_deg = abs(rad2deg(wrapAngle( ...
    stressCapture.ySim(end,I.headingCommand)- ...
    stressCapture.ySim(end,I.psi))));
assert(stressMetrics.positionLimitActive && stressMetrics.rateLimitActive, ...
    'The initial-bank stress did not activate both aileron limits.');
assert(~stressMetrics.physicalLimitActive, ...
    'The logic stress unexpectedly reached the physical aileron stop.');
assert(stressMetrics.peakAutomaticAileron_deg <= ...
    aileron.authority.rightWingDown_deg+1.0e-9, ...
    'The stress case exceeded automatic-aileron authority.');
assert(stressMetrics.peakAileronRate_degps <= ...
    aileron.dynamics.rateLimit_degps+1.0e-9, ...
    'The stress case exceeded the aileron-rate limit.');
assert(abs(stressMetrics.finalBank_deg) <= ...
    aileron.stress.maximumFinalBank_deg, ...
    'The stress-case final bank residual is excessive.');
assert(stressFinalHeadingError_deg <= ...
    headingController.largeTurn.maximumFinalHeadingError_deg, ...
    'The stress case did not recapture selected heading.');
assert(abs(stressMetrics.finalAutomaticAileron_deg) <= ...
    aileron.requirements.maximumReleasedAileron_deg, ...
    'The automatic aileron did not release after the stress.');
assert(antiWindupIntegratorRatio <= ...
    aileron.stress.maximumAntiWindupIntegratorRatio, ...
    'Simulink anti-windup did not sufficiently reduce integrator growth.');

noiseRows = noiseCapture.t >= headingSensor.noiseDiscardTime_s;
noiseBank_deg = rad2deg(noiseCapture.ySim(noiseRows,I.phi));
noiseAileron_deg = rad2deg( ...
    noiseCapture.ySim(noiseRows,I.aileronActual));
noiseHeadingRms_deg = sqrt(mean(rad2deg( ...
    noiseCapture.ySim(noiseRows,I.headingNoise)).^2));
noiseBankRms_deg = sqrt(mean(noiseBank_deg.^2));
noiseAileronRms_deg = sqrt(mean(noiseAileron_deg.^2));
noiseAileronPeak_deg = max(abs(noiseAileron_deg));
assert(noiseBankRms_deg <= ...
    headingSensor.requirements.maximumNoiseBankRms_deg, ...
    'Heading noise drove excessive bank response.');
assert(noiseAileronRms_deg <= ...
    headingSensor.requirements.maximumNoiseAileronRms_deg, ...
    'Heading noise drove excessive aileron RMS.');
assert(noiseAileronPeak_deg <= ...
    headingSensor.requirements.maximumNoiseAileronPeak_deg, ...
    'Heading noise drove excessive peak aileron.');
assert(~aileronPositionLimitActive(noiseCapture.ySim,I) && ...
    ~aileronRateLimitActive(noiseCapture.ySim,I), ...
    'Heading noise unexpectedly activated aileron protection.');

assert(headingSensor.nominalDelay_s <= ...
    headingSensor.maximumAcceptedDelay_s, ...
    'The executable heading delay exceeds the accepted 200-ms envelope.');
assert(aileron.sensor.nominalDelay_s <= ...
    aileron.sensor.maximumAcceptedDelay_s, ...
    'The executable roll delay exceeds the accepted 40-ms envelope.');
assert(rudder.sensor.nominalDelay_s <= ...
    rudder.sensor.maximumAcceptedDelay_s, ...
    'The executable yaw delay exceeds the accepted 60-ms envelope.');
%% Console release report

fprintf('============================================================\n');
fprintf(' C172S HEADING HOLD V1 - PROTECTED SIMULINK CHECK\n');
fprintf('============================================================\n\n');
fprintf('Model                                : %s\n',modelName);
fprintf('Controller artifact                  : %s\n', ...
    headingController.artifactRevision);
fprintf('Heading-sensor audit                 : %s\n', ...
    headingSensor.artifactRevision);
fprintf('Frozen roll controller               : %s\n', ...
    rollController.artifactRevision);
fprintf('Frozen yaw controller/audit          : %s / %s\n', ...
    yawController.artifactRevision,rudder.artifactRevision);
fprintf('Aileron/source audit                 : %s\n', ...
    aileron.artifactRevision);
fprintf('Frozen plant                          : %s\n',data.model.version);
fprintf('Control law                           : phiCmd = sat(Kpsi*wrap(ePsi),+/-20 deg)\n');
fprintf('Kpsi                                  : %.3f rad/rad\n', ...
    headingController.headingErrorGain);
fprintf('Heading filter / nominal pure delay   : %.3f s / %.0f ms\n', ...
    headingSensor.filterTimeConstant_s, ...
    1000*headingSensor.nominalDelay_s);
fprintf('Roll filter / nominal pure delay      : %.3f s / %.0f ms\n', ...
    aileron.sensor.filterTimeConstant_s, ...
    1000*aileron.sensor.nominalDelay_s);
fprintf('Bank-command authority                : +/-%.1f deg\n', ...
    headingController.bankCommandAuthority_deg);
fprintf('Aileron tau / authority / rate        : %.3f s / +/-%.1f deg / +/-%.1f deg/s\n', ...
    aileron.dynamics.timeConstant_s,aileron.authority.rightWingDown_deg, ...
    aileron.dynamics.rateLimit_degps);
fprintf('Solver / fixed step                   : ode4 / 0.0100 s\n\n');

for k = 1:numel(captures)
    fprintf('%-20s maximum error       : %.9g\n', ...
        captureNames{k},captures{k}.maxError);
    fprintf('%-20s RMS error           : %.9g\n', ...
        captureNames{k},captures{k}.rmsError);
end
fprintf('Allowed implementation error         : %.3g\n\n',tolerance);

fprintf('30-deg heading rise time              : %.3f s\n', ...
    commandMetrics.riseTime_s);
fprintf('30-deg heading overshoot              : %.4f %%\n', ...
    commandMetrics.overshoot_pct);
fprintf('30-deg heading settling time          : %.3f s\n', ...
    commandMetrics.settlingTime_s);
fprintf('30-deg final heading error            : %.6f deg\n', ...
    commandFinalError_deg);
fprintf('Peak bank / roll rate                 : %.4f deg / %.4f deg/s\n', ...
    commandPeakBank_deg,commandPeakRollRate_degps);
fprintf('Peak yaw rate / sideslip              : %.4f deg/s / %.4f deg\n', ...
    commandPeakYawRate_degps,commandPeakBeta_deg);
fprintf('Peak automatic aileron / rate         : %.4f deg / %.4f deg/s\n', ...
    commandPeakAileron_deg,commandPeakAileronRate_degps);
fprintf('Peak automatic rudder                 : %.4f deg\n\n', ...
    commandPeakRudder_deg);

fprintf('90-deg bank-command limit active      : %d\n', ...
    largeCommandLimitActive);
fprintf('90-deg bank command limited to        : %.4f deg\n', ...
    largeMaximumBankCommand_deg);
fprintf('90-deg peak bank / roll rate          : %.4f deg / %.4f deg/s\n', ...
    largePeakBank_deg,largePeakRollRate_degps);
fprintf('90-deg peak yaw rate / sideslip       : %.4f deg/s / %.4f deg\n', ...
    largePeakYawRate_degps,largePeakBeta_deg);
fprintf('90-deg settling / final error         : %.3f s / %.6f deg\n', ...
    largeSettlingTime_s,largeFinalError_deg);
fprintf('North-wrap final errors, right / left : %.6f / %.6f deg\n', ...
    wrapRightFinalError_deg,wrapLeftFinalError_deg);
fprintf('2-deg bias measured / true error      : %.6f / %.6f deg\n', ...
    biasMeasuredError_deg,biasTrueError_deg);
fprintf('Aileron/rudder pulse peak heading     : %.4f / %.4f deg\n', ...
    aileronPulsePeakHeading_deg,rudderPulsePeakHeading_deg);
fprintf('Aileron/rudder pulse final error      : %.6f / %.6f deg\n\n', ...
    aileronPulseFinalError_deg,rudderPulseFinalError_deg);

fprintf('Stress initial bank                   : %.1f deg\n', ...
    aileron.stress.initialBank_deg);
fprintf('Stress peak automatic aileron         : %.4f deg\n', ...
    stressMetrics.peakAutomaticAileron_deg);
fprintf('Stress peak actuator rate             : %.4f deg/s\n', ...
    stressMetrics.peakAileronRate_degps);
fprintf('Stress position/rate limits active    : %d / %d\n', ...
    stressMetrics.positionLimitActive,stressMetrics.rateLimitActive);
fprintf('Stress physical hard stop active      : %d\n', ...
    stressMetrics.physicalLimitActive);
fprintf('Stress final bank / heading error     : %.6f / %.6f deg\n', ...
    stressMetrics.finalBank_deg,stressFinalHeadingError_deg);
fprintf('Stress final automatic aileron        : %.6f deg\n', ...
    stressMetrics.finalAutomaticAileron_deg);
fprintf('Anti-windup peak-integrator ratio     : %.4f\n\n', ...
    antiWindupIntegratorRatio);

fprintf('Deterministic heading-noise RMS       : %.5f deg\n', ...
    noiseHeadingRms_deg);
fprintf('Noise-driven bank / aileron RMS       : %.5f / %.5f deg\n', ...
    noiseBankRms_deg,noiseAileronRms_deg);
fprintf('Noise-driven automatic-aileron peak   : %.5f deg\n\n', ...
    noiseAileronPeak_deg);

fprintf('PASS: Simulink matches ten independent hybrid RK4 references.\n');
fprintf('PASS: circular heading error, filtering, delay and signs are correct.\n');
fprintf('PASS: frozen protected roll/yaw loops and pilot summations are preserved.\n');
fprintf('PASS: 30-deg acquisition, 90-deg authority and both wrap captures pass.\n');
fprintf('PASS: heading-bias behavior and pilot-interaction gates pass.\n');
fprintf('PASS: aileron position/rate/hard-stop and anti-windup gates pass.\n');
fprintf('PASS: deterministic heading-noise amplification remains below its gates.\n');
fprintf(['NOTE: this validates the nominal executable implementation against ', ...
    'Plant V0.1 and declared assumptions; it is not aircraft approval.\n']);

%% Executable-equivalence and protection figures

figure('Name','C172S Heading Hold V1 Simulink Equivalence','Color','w');
tiledlayout(2,3,'TileSpacing','compact','Padding','compact');
nexttile;
plotComparison(commandCapture.t,commandCapture.ySim(:,I.psi), ...
    commandCapture.yReference(:,I.psi),'Heading (deg)');
title('30-deg Heading Command');
nexttile;
plotComparison(commandCapture.t, ...
    commandCapture.ySim(:,I.bankCommandLimited), ...
    commandCapture.yReference(:,I.bankCommandLimited), ...
    'Bank command (deg)');
title('Protected Bank Command');
nexttile;
plotComparison(largeTurnCapture.t,largeTurnCapture.ySim(:,I.psi), ...
    largeTurnCapture.yReference(:,I.psi),'Heading (deg)');
title('90-deg Acquisition');
nexttile;
plotWrappedComparison(wrapRightCapture.t, ...
    wrapRightCapture.ySim(:,I.psi),wrapRightCapture.yReference(:,I.psi));
title('350-to-10 Wrap');
nexttile;
plotWrappedComparison(wrapLeftCapture.t, ...
    wrapLeftCapture.ySim(:,I.psi),wrapLeftCapture.yReference(:,I.psi));
title('10-to-350 Wrap');
nexttile;
plotComparison(noiseCapture.t, ...
    noiseCapture.ySim(:,I.aileronActual), ...
    noiseCapture.yReference(:,I.aileronActual), ...
    'Automatic aileron (deg)');
title('Heading-Noise Stress');
sgtitle('Heading Hold V1: Simulink vs Independent Hybrid RK4');

figure('Name','C172S Heading Hold V1 Protection','Color','w');
tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
nexttile;
plot(largeTurnCapture.t,rad2deg( ...
    largeTurnCapture.ySim(:,I.bankCommandRaw)),'--','LineWidth',1.2);
hold on;
plot(largeTurnCapture.t,rad2deg( ...
    largeTurnCapture.ySim(:,I.bankCommandLimited)),'LineWidth',1.3);
plot(largeTurnCapture.t,rad2deg( ...
    largeTurnCapture.ySim(:,I.phi)),'LineWidth',1.5);
grid on; xlabel('Time (s)'); ylabel('Angle (deg)');
legend('Raw bank command','Limited bank command','Bank', ...
    'Location','best');
title('90-deg Bank Authority');
nexttile;
plot(stressCapture.t,rad2deg(stressCapture.ySim(:,I.phi)), ...
    'LineWidth',1.5,'DisplayName','Anti-windup');
hold on;
plot(stressNoAwCapture.t,rad2deg( ...
    stressNoAwCapture.ySim(:,I.phi)),'--','LineWidth',1.2, ...
    'DisplayName','No anti-windup');
grid on; xlabel('Time (s)'); ylabel('Bank angle (deg)');
legend('Location','best'); title('30-deg Initial-Bank Stress');
nexttile;
yyaxis left;
plot(stressCapture.t,rad2deg( ...
    stressCapture.ySim(:,I.aileronActual)),'LineWidth',1.5);
ylabel('Automatic aileron (deg)');
yyaxis right;
plot(stressCapture.t,rad2deg( ...
    stressCapture.ySim(:,I.aileronRate)),'LineWidth',1.2);
ylabel('Aileron rate (deg/s)');
grid on; xlabel('Time (s)'); title('Aileron Position and Rate Protection');
nexttile;
plot(biasCapture.t,rad2deg(biasCapture.ySim(:,I.psi)), ...
    'LineWidth',1.4);
hold on;
plot(biasCapture.t,rad2deg( ...
    biasCapture.ySim(:,I.headingSensor)),'--','LineWidth',1.2);
grid on; xlabel('Time (s)'); ylabel('Heading (deg)');
legend('True heading','Measured heading','Location','best');
title('2-deg Heading Bias');
sgtitle('Heading Hold V1: Executable Logic and Protection');

%% Refresh saved model after simulations

modelFile = get_param(modelName,'FileName');
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);
fprintf('Reloaded generated model to clear transient editor diagnostics.\n');

%% Local helpers

function result = runCapture(modelName,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController,caseName)
cfg = captureConfiguration(caseName,rollController,aileron, ...
    headingSensor,headingController);

simInput = Simulink.SimulationInput(modelName);
simInput = simInput.setVariable('headingCommand_hh1_rad', ...
    cfg.headingCommand_rad);
simInput = simInput.setVariable('headingBias_hh1_rad', ...
    cfg.headingBias_rad);
simInput = simInput.setVariable('headingNoiseAmplitude_hh1_rad', ...
    cfg.headingNoiseAmplitude_rad);
simInput = simInput.setVariable('headingNoiseFrequency_hh1_radps', ...
    cfg.headingNoiseFrequency_radps);
simInput = simInput.setVariable('pilotAileronBias_hh1_rad', ...
    cfg.aileronBias_rad);
simInput = simInput.setVariable('pilotAileronPulse_hh1_rad', ...
    cfg.aileronPulse_rad);
simInput = simInput.setVariable('pilotRudderBias_hh1_rad', ...
    cfg.rudderBias_rad);
simInput = simInput.setVariable('pilotRudderPulse_hh1_rad', ...
    cfg.rudderPulse_rad);
simInput = simInput.setVariable('aileronPulseStart_hh1_s', ...
    cfg.aileronPulseStart_s);
simInput = simInput.setVariable('aileronPulseEnd_hh1_s', ...
    cfg.aileronPulseEnd_s);
simInput = simInput.setVariable('rudderPulseStart_hh1_s', ...
    cfg.rudderPulseStart_s);
simInput = simInput.setVariable('rudderPulseEnd_hh1_s', ...
    cfg.rudderPulseEnd_s);
simInput = simInput.setVariable('pNoiseAmplitude_hh1_radps', ...
    cfg.pNoiseAmplitude_radps);
simInput = simInput.setVariable('pNoiseFrequency_hh1_radps', ...
    cfg.pNoiseFrequency_radps);
simInput = simInput.setVariable('phiNoiseAmplitude_hh1_rad', ...
    cfg.phiNoiseAmplitude_rad);
simInput = simInput.setVariable('phiNoiseFrequency_hh1_radps', ...
    cfg.phiNoiseFrequency_radps);
simInput = simInput.setVariable('yawNoiseAmplitude_hh1_radps',0.0);
simInput = simInput.setVariable('yawNoiseFrequency_hh1_radps',50.0);
simInput = simInput.setVariable('antiWindupEnable_hh1', ...
    cfg.antiWindupEnable);
simInput = simInput.setVariable('x0_hh1',cfg.x0);
simInput = simInput.setVariable('rDelay0_hh1_radps',cfg.x0(3));
simInput = simInput.setVariable('pDelay0_hh1_radps',cfg.x0(2));
simInput = simInput.setVariable('phiDelay0_hh1_rad',cfg.x0(4));
simInput = simInput.setVariable('psiDelay0_hh1_rad',cfg.x0(5));
simInput = simInput.setVariable('rSensor0_hh1_radps',0.0);
simInput = simInput.setVariable('xw0_hh1_radps',0.0);
simInput = simInput.setVariable('deltaRAuto0_hh1_rad',0.0);
simInput = simInput.setVariable('pSensor0_hh1_radps',0.0);
simInput = simInput.setVariable('phiSensor0_hh1_rad',0.0);
simInput = simInput.setVariable('psiSensor0_hh1_rad', ...
    cfg.x0(5)+cfg.headingBias_rad);
simInput = simInput.setVariable('xi0_hh1_rad_s',0.0);
simInput = simInput.setVariable('deltaAAuto0_hh1_rad',0.0);
simInput = simInput.setVariable('filteredCommand0_hh1_rad',0.0);
simInput = simInput.setModelParameter('StopTime',num2str(cfg.stopTime_s));

simOut = sim(simInput);
[tSim,ySim] = extractArrayOutput(simOut,52);
dt = median(diff(tSim));
assert(max(abs(diff(tSim)-dt)) < 1.0e-10, ...
    'The independent reference requires uniform sampling.');
assert(abs(dt-0.01) < 1.0e-12, ...
    'The executable sample grid differs from the declared 0.01-s grid.');

yReference = independentReference(tSim,cfg,plant,yawController, ...
    rudder,rollController,aileron,headingSensor,headingController);
errorSignal = ySim-yReference;
result.t = tSim;
result.ySim = ySim;
result.yReference = yReference;
result.maxError = max(abs(errorSignal),[],'all');
result.rmsError = sqrt(mean(errorSignal(:).^2));
result.configuration = cfg;
end

function cfg = captureConfiguration(caseName,~,aileron, ...
    headingSensor,headingController)
cfg.name = caseName;
cfg.headingCommand_rad = 0.0;
cfg.headingBias_rad = 0.0;
cfg.headingNoiseAmplitude_rad = 0.0;
cfg.headingNoiseFrequency_radps = headingSensor.noiseFrequency_radps;
cfg.aileronBias_rad = 0.0;
cfg.aileronPulse_rad = 0.0;
cfg.rudderBias_rad = 0.0;
cfg.rudderPulse_rad = 0.0;
cfg.aileronPulseStart_s = 5.0;
cfg.aileronPulseEnd_s = 6.0;
cfg.rudderPulseStart_s = 5.0;
cfg.rudderPulseEnd_s = 6.0;
cfg.pNoiseAmplitude_radps = 0.0;
cfg.pNoiseFrequency_radps = aileron.noise.rollRateFrequency_radps;
cfg.phiNoiseAmplitude_rad = 0.0;
cfg.phiNoiseFrequency_radps = aileron.noise.bankAngleFrequency_radps;
cfg.antiWindupEnable = 1.0;
cfg.x0 = zeros(5,1);
cfg.stopTime_s = headingController.validation.stopTime_s;

switch caseName
    case 'command'
        cfg.headingCommand_rad = deg2rad( ...
            headingController.validation.commandStep_deg);
    case 'largeTurn'
        cfg.headingCommand_rad = deg2rad( ...
            headingController.validation.largeCommandStep_deg);
        cfg.stopTime_s = headingController.validation.nonlinearStopTime_s;
    case 'wrapRight'
        cfg.x0(5) = deg2rad( ...
            headingController.validation.wrapRightInitial_deg);
        cfg.headingCommand_rad = deg2rad( ...
            headingController.validation.wrapRightCommand_deg);
    case 'wrapLeft'
        cfg.x0(5) = deg2rad( ...
            headingController.validation.wrapLeftInitial_deg);
        cfg.headingCommand_rad = deg2rad( ...
            headingController.validation.wrapLeftCommand_deg);
    case 'bias'
        cfg.headingBias_rad = deg2rad(headingSensor.biasStress_deg);
    case 'aileronPulse'
        cfg.aileronPulse_rad = deg2rad(1.0);
    case 'rudderPulse'
        cfg.rudderPulse_rad = deg2rad(1.0);
    case 'stressAw'
        cfg.x0(4) = deg2rad(aileron.stress.initialBank_deg);
        cfg.antiWindupEnable = 1.0;
    case 'stressNoAw'
        cfg.x0(4) = deg2rad(aileron.stress.initialBank_deg);
        cfg.antiWindupEnable = 0.0;
    case 'noise'
        cfg.headingNoiseAmplitude_rad = deg2rad( ...
            sqrt(2)*headingSensor.noiseStressRms_deg);
        cfg.stopTime_s = headingSensor.noiseStopTime_s;
    otherwise
        error('Unknown capture name: %s',caseName);
end
end

function y = independentReference(t,cfg,plant,yawController,rudder, ...
    rollController,aileron,headingSensor,headingController)
% Continuous z = [beta p r phi psi rSensor xw deltaR pSensor phiSensor
%                 xi deltaA filteredCommand headingSensor].
z = [cfg.x0;zeros(8,1);cfg.x0(5)+cfg.headingBias_rad];
delay.r = cfg.x0(3);
delay.p = cfg.x0(2);
delay.phi = cfg.x0(4);
delay.psi = repmat(cfg.x0(5),5,1);
y = zeros(numel(t),52);
for k = 1:numel(t)
    d = protectedSignals(t(k),z,delay,cfg,yawController,rudder, ...
        rollController,aileron,headingController);
    y(k,:) = outputVector(z,d).';
    if k < numel(t)
        h = t(k+1)-t(k);
        sampled.r = z(3);
        sampled.p = z(2);
        sampled.phi = z(4);
        sampled.psi = z(5);
        k1 = protectedDerivative(t(k),z,delay,cfg,plant, ...
            yawController,rudder,rollController,aileron,headingSensor, ...
            headingController);
        k2 = protectedDerivative(t(k)+0.5*h,z+0.5*h*k1,delay,cfg, ...
            plant,yawController,rudder,rollController,aileron, ...
            headingSensor,headingController);
        k3 = protectedDerivative(t(k)+0.5*h,z+0.5*h*k2,delay,cfg, ...
            plant,yawController,rudder,rollController,aileron, ...
            headingSensor,headingController);
        k4 = protectedDerivative(t(k)+h,z+h*k3,delay,cfg,plant, ...
            yawController,rudder,rollController,aileron,headingSensor, ...
            headingController);
        z = z+(h/6)*(k1+2*k2+2*k3+k4);
        delay.r = sampled.r;
        delay.p = sampled.p;
        delay.phi = sampled.phi;
        delay.psi = [delay.psi(2:end);sampled.psi];
    end
end
end

function zDot = protectedDerivative(t,z,delay,cfg,plant, ...
    yawController,rudder,rollController,aileron,headingSensor, ...
    headingController)
d = protectedSignals(t,z,delay,cfg,yawController,rudder, ...
    rollController,aileron,headingController);
zDot = zeros(14,1);
zDot(1:5) = plant.A*z(1:5)+plant.B*[d.totalAileron;d.totalRudder];
zDot(6) = (d.rInput-z(6))/rudder.sensor.filterTimeConstant_s;
zDot(7) = (z(6)-z(7))/yawController.washoutTimeConstant_s;
zDot(8) = d.rudderRate;
zDot(9) = (d.pInput-z(9))/aileron.sensor.filterTimeConstant_s;
zDot(10) = (d.phiInput-z(10))/aileron.sensor.filterTimeConstant_s;
zDot(11) = d.bankError+d.antiWindup;
zDot(12) = d.aileronRate;
zDot(13) = (d.bankCommandLimited-z(13))/ ...
    rollController.commandFilterTimeConstant_s;
zDot(14) = (d.headingInput-z(14))/ ...
    headingSensor.filterTimeConstant_s;
end

function d = protectedSignals(t,z,delay,cfg,yawController,rudder, ...
    rollController,aileron,headingController)
d.headingCommand = cfg.headingCommand_rad;
d.psiDelayed = delay.psi(1);
d.headingBias = cfg.headingBias_rad;
d.headingNoise = cfg.headingNoiseAmplitude_rad* ...
    sin(cfg.headingNoiseFrequency_radps*t);
d.headingInput = d.psiDelayed+d.headingBias+d.headingNoise;
d.headingDifference = d.headingCommand-z(14);
d.headingError = wrapAngle(d.headingDifference);
d.bankCommandRaw = headingController.headingErrorGain*d.headingError;
bankLimit = deg2rad(headingController.bankCommandAuthority_deg);
d.bankCommandLimited = clip(d.bankCommandRaw,-bankLimit,bankLimit);
[d.aileronPilot,d.rudderPilot] = pilotInputs(t,cfg);
d.rNoise = 0.0;
d.pNoise = cfg.pNoiseAmplitude_radps*sin(cfg.pNoiseFrequency_radps*t);
d.phiNoise = cfg.phiNoiseAmplitude_rad*sin(cfg.phiNoiseFrequency_radps*t);
d.rDelayed = delay.r;
d.pDelayed = delay.p;
d.phiDelayed = delay.phi;
d.rInput = d.rDelayed+d.rNoise;
d.pInput = d.pDelayed+d.pNoise;
d.phiInput = d.phiDelayed+d.phiNoise;

d.rWashout = z(6)-z(7);
d.rudderRaw = -yawController.rudderGain_s*d.rWashout;
d.rudderPosition = clip(d.rudderRaw,rudder.authority.lowerLimit_rad, ...
    rudder.authority.upperLimit_rad);
d.rudderRateRaw = (d.rudderPosition-z(8))/ ...
    rudder.dynamics.timeConstant_s;
d.rudderRate = clip(d.rudderRateRaw, ...
    -deg2rad(rudder.dynamics.rateLimit_degps), ...
    deg2rad(rudder.dynamics.rateLimit_degps));
d.rudderTotalRaw = d.rudderPilot+z(8);
d.totalRudder = clip(d.rudderTotalRaw, ...
    rudder.physicalTravel.lowerLimit_rad, ...
    rudder.physicalTravel.upperLimit_rad);

d.bankError = z(13)-z(10);
d.proportional = rollController.bankProportionalGain*d.bankError;
d.integral = rollController.bankIntegralGain_per_s*z(11);
d.rollRateContribution = -rollController.rollRateGain_s*z(9);
d.aileronUnsat = d.proportional+d.integral+d.rollRateContribution;
d.aileronPosition = clip(d.aileronUnsat, ...
    aileron.authority.lowerLimit_rad,aileron.authority.upperLimit_rad);
d.aileronRateRaw = (d.aileronPosition-z(12))/ ...
    aileron.dynamics.timeConstant_s;
d.aileronRate = clip(d.aileronRateRaw, ...
    -deg2rad(aileron.dynamics.rateLimit_degps), ...
    deg2rad(aileron.dynamics.rateLimit_degps));
d.aileronTrack = z(12)+ ...
    aileron.dynamics.timeConstant_s*d.aileronRate;
d.antiWindup = cfg.antiWindupEnable*(d.aileronTrack-d.aileronUnsat)/( ...
    rollController.bankIntegralGain_per_s* ...
    aileron.antiWindup.trackingTimeConstant_s);
d.aileronTotalRaw = d.aileronPilot+z(12);
d.totalAileron = clip(d.aileronTotalRaw, ...
    aileron.physicalTravel.lowerLimit_rad, ...
    aileron.physicalTravel.upperLimit_rad);
end

function y = outputVector(z,d)
y = [z(1:5);d.headingCommand;d.psiDelayed;d.headingBias; ...
    d.headingNoise;d.headingInput;z(14);d.headingDifference; ...
    d.headingError;d.bankCommandRaw;d.bankCommandLimited;z(13); ...
    d.aileronPilot;d.rudderPilot;d.rDelayed;d.rNoise;d.rInput;z(6); ...
    d.rWashout;d.rudderRaw;d.rudderPosition;z(8);d.rudderRateRaw; ...
    d.rudderRate;d.rudderTotalRaw;d.totalRudder;d.pDelayed;d.pNoise; ...
    d.pInput;z(9);d.phiDelayed;d.phiNoise;d.phiInput;z(10); ...
    d.bankError;d.proportional;z(11);d.integral; ...
    d.rollRateContribution;d.aileronUnsat;d.aileronPosition;z(12); ...
    d.aileronRateRaw;d.aileronRate;d.aileronTrack;d.antiWindup; ...
    d.aileronTotalRaw;d.totalAileron];
end

function [aileronInput,rudderInput] = pilotInputs(t,cfg)
t = snapToEdges(t,[cfg.aileronPulseStart_s,cfg.aileronPulseEnd_s, ...
    cfg.rudderPulseStart_s,cfg.rudderPulseEnd_s]);
aileronInput = cfg.aileronBias_rad;
rudderInput = cfg.rudderBias_rad;
if t >= cfg.aileronPulseStart_s && t < cfg.aileronPulseEnd_s
    aileronInput = aileronInput+cfg.aileronPulse_rad;
end
if t >= cfg.rudderPulseStart_s && t < cfg.rudderPulseEnd_s
    rudderInput = rudderInput+cfg.rudderPulse_rad;
end
end

function t = snapToEdges(t,edges)
for k = 1:numel(edges)
    if abs(t-edges(k)) <= 1.0e-12
        t = edges(k);
        return;
    end
end
end

function I = signalIndices()
names = {'beta','p','r','phi','psi','headingCommand','psiDelayed', ...
    'headingBias','headingNoise','headingInput','headingSensor', ...
    'headingDifference','headingError','bankCommandRaw', ...
    'bankCommandLimited','bankCommandFiltered','aileronPilot', ...
    'rudderPilot','rDelayed','rNoise', ...
    'rInput','rSensor','rWashout','rudderRaw','rudderPosition', ...
    'rudderActual','rudderRateRaw','rudderRate','rudderTotalRaw', ...
    'rudderTotal','pDelayed','pNoise','pInput','pSensor','phiDelayed', ...
    'phiNoise','phiInput','phiSensor','bankError','proportional','xi', ...
    'integral','rollRateContribution','aileronUnsat','aileronPosition', ...
    'aileronActual','aileronRateRaw','aileronRate','aileronTrack', ...
    'antiWindup','aileronTotalRaw','aileronTotal'};
for k = 1:numel(names)
    I.(names{k}) = k;
end
end

function metrics = protectedStressMetrics(capture,I,aileron)
y = capture.ySim;
metrics.positionLimitActive = aileronPositionLimitActive(y,I);
metrics.rateLimitActive = aileronRateLimitActive(y,I);
metrics.physicalLimitActive = aileronPhysicalLimitActive(y,I);
metrics.peakAutomaticAileron_deg = max(abs(rad2deg(y(:,I.aileronActual))));
metrics.peakAileronRate_degps = max(abs(rad2deg(y(:,I.aileronRate))));
metrics.peakIntegratorMagnitude = max(abs(y(:,I.xi)));
metrics.finalBank_deg = rad2deg(y(end,I.phi));
metrics.finalAutomaticAileron_deg = rad2deg(y(end,I.aileronActual));
inside = abs(rad2deg(y(:,I.phi))) <= aileron.stress.recoveryThreshold_deg;
lastOutside = find(~inside,1,'last');
if isempty(lastOutside)
    metrics.recoveryTime_s = capture.t(1);
elseif lastOutside < numel(capture.t)
    metrics.recoveryTime_s = capture.t(lastOutside+1);
else
    metrics.recoveryTime_s = inf;
end
end

function active = aileronPositionLimitActive(y,I)
active = any(abs(y(:,I.aileronUnsat)-y(:,I.aileronPosition)) > 1.0e-10);
end

function active = aileronRateLimitActive(y,I)
active = any(abs(y(:,I.aileronRateRaw)-y(:,I.aileronRate)) > 1.0e-10);
end

function active = aileronPhysicalLimitActive(y,I)
active = any(abs(y(:,I.aileronTotalRaw)-y(:,I.aileronTotal)) > 1.0e-10);
end

function active = rudderPositionLimitActive(y,I)
active = any(abs(y(:,I.rudderRaw)-y(:,I.rudderPosition)) > 1.0e-10);
end

function active = rudderRateLimitActive(y,I)
active = any(abs(y(:,I.rudderRateRaw)-y(:,I.rudderRate)) > 1.0e-10);
end

function active = rudderPhysicalLimitActive(y,I)
active = any(abs(y(:,I.rudderTotalRaw)-y(:,I.rudderTotal)) > 1.0e-10);
end

function metrics = positiveStepMetrics(t,response,command)
i10 = find(response >= 0.10*command,1,'first');
i90 = find(response >= 0.90*command,1,'first');
if isempty(i10) || isempty(i90)
    metrics.riseTime_s = inf;
else
    metrics.riseTime_s = t(i90)-t(i10);
end
metrics.overshoot_pct = max(0,100*(max(response)-command)/command);
outside = find(abs(response-command) > 0.02*abs(command));
if isempty(outside)
    metrics.settlingTime_s = 0;
elseif outside(end) == numel(t)
    metrics.settlingTime_s = inf;
else
    metrics.settlingTime_s = t(outside(end)+1);
end
end

function settlingTime_s = wrappedSettlingTime(t,response,command, ...
    toleranceFraction)
errorMagnitude = abs(wrapAngle(command-response));
outside = find(errorMagnitude > toleranceFraction*abs(command));
if isempty(outside)
    settlingTime_s = 0.0;
elseif outside(end) == numel(t)
    settlingTime_s = inf;
else
    settlingTime_s = t(outside(end)+1);
end
end

function value = wrapAngle(value)
value = atan2(sin(value),cos(value));
end

function value = clip(value,lowerLimit,upperLimit)
value = min(max(value,lowerLimit),upperLimit);
end

function assertDependencies(data,yawController,rudder,rollController, ...
    aileron,headingSensor,headingController)
assert(strcmp(data.model.version,headingController.requiredPlantVersion), ...
    'Heading Hold V1 plant dependency mismatch.');
assert(strcmp(yawController.artifactRevision, ...
    headingController.requiredYawDamperRevision), ...
    'Heading Hold V1 yaw-controller dependency mismatch.');
assert(strcmp(rudder.artifactRevision, ...
    headingController.requiredRudderAuditRevision), ...
    'Heading Hold V1 rudder-audit dependency mismatch.');
assert(strcmp(aileron.artifactRevision, ...
    headingController.requiredAileronAuditRevision), ...
    'Heading Hold V1 aileron-audit dependency mismatch.');
assert(strcmp(rollController.artifactRevision, ...
    headingController.requiredRollControllerRevision), ...
    'Heading Hold V1 roll-controller dependency mismatch.');
assert(strcmp(headingSensor.artifactRevision, ...
    headingController.requiredHeadingSensorRevision), ...
    'Heading Hold V1 heading-sensor dependency mismatch.');
assert(abs(aileron.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms roll delay.');
assert(abs(rudder.sensor.nominalDelay_s-0.010) < 1.0e-12, ...
    'The executable baseline requires the audited 10-ms yaw delay.');
assert(abs(headingSensor.nominalDelay_s-0.050) < 1.0e-12, ...
    'The executable baseline requires the audited 50-ms heading delay.');
assert(abs(headingController.bankCommandAuthority_deg- ...
    rollController.commandAuthority.rightWingDown_deg) < 1.0e-12, ...
    'Heading Hold V1 must reuse the frozen RAH bank authority.');
end

function [t,y] = extractArrayOutput(simOut,nSignal)
t = simOut.tout;
y = simOut.yout;
if isa(y,'timeseries')
    y = y.Data;
elseif isa(y,'Simulink.SimulationData.Dataset')
    y = y.getElement(1).Values.Data;
end
y = squeeze(y);
if size(y,1) ~= numel(t) && size(y,2) == numel(t)
    y = y.';
end
assert(size(y,2) == nSignal, ...
    'Expected %d logged signals but received %d.',nSignal,size(y,2));
end

function plotComparison(t,ySim,yReference,yLabel)
plot(t,rad2deg(ySim),'LineWidth',1.3);
hold on;
plot(t,rad2deg(yReference),'--','LineWidth',1.0);
grid on;
xlabel('Time (s)');
ylabel(yLabel);
legend('Simulink','Independent RK4','Location','best');
end

function plotWrappedComparison(t,ySim,yReference)
plot(t,mod(rad2deg(ySim),360),'LineWidth',1.3);
hold on;
plot(t,mod(rad2deg(yReference),360),'--','LineWidth',1.0);
grid on;
xlabel('Time (s)');
ylabel('Wrapped heading (deg)');
legend('Simulink','Independent RK4','Location','best');
end