%% C172S Roll-Attitude Hold V1 - protected Simulink equivalence check

clc;
clear;
close all;

try
    load_system('simulink');
catch ME
    error('runRollAttitudeHoldSimulinkCheck:SimulinkUnavailable', ...
        'Unable to load Simulink. MATLAB reported:\n%s',ME.message);
end

data = c172sLateralDirectionalData();
[~,plant] = c172sLateralDirectionalPlant(data);
yawController = c172sYawDamperData();
rudder = c172sRudderActuatorData();
controller = c172sRollAttitudeControllerData();
aileron = c172sAileronActuatorData();
assertDependencies(data,yawController,rudder,controller,aileron);

% Rebuild the generated diagram so a stale or hand-edited SLX cannot
% influence the implementation-equivalence result.
modelName = buildC172sRollAttitudeHoldSimulink(true);

%% Nine independent executable captures

commandCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'command');
initialCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'initial');
biasCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'bias');
aileronPulseCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'aileronPulse');
rudderPulseCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'rudderPulse');
commandLimitCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'commandLimit');
stressCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'stressAw');
stressNoAwCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'stressNoAw');
noiseCapture = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,'noise');

captureNames = {'Command','Initial','Bias','Aileron pulse', ...
    'Rudder pulse','Command limit','Stress AW','Stress no-AW','Noise'};
captures = {commandCapture,initialCapture,biasCapture, ...
    aileronPulseCapture,rudderPulseCapture,commandLimitCapture, ...
    stressCapture,stressNoAwCapture,noiseCapture};

%% Independent hybrid-equivalence gates

tolerance = 1.0e-5;
for k = 1:numel(captures)
    assert(captures{k}.maxError < tolerance, ...
        '%s-capture error %.6g exceeds %.6g.', ...
        captureNames{k},captures{k}.maxError,tolerance);
end

assert(strcmp(get_param(modelName,'SolverType'),'Fixed-step'), ...
    'The generated model must use a fixed-step solver.');
assert(strcmp(get_param(modelName,'Solver'),'ode4'), ...
    'The generated model must use ode4.');
assert(abs(str2double(get_param(modelName,'FixedStep'))-0.01) < eps, ...
    'The generated model fixed step must be 0.01 s.');
assert(strcmp(get_param([modelName '/Bank Command Limit'],'UpperLimit'), ...
    'bankCommandUpper_rah1_rad'),'The bank-command authority changed.');
assert(strcmp(get_param([modelName '/Command Filter'],'A'), ...
    '-1/Tcmd_rah1'),'The bank-command filter changed.');

rollPath = [modelName '/Protected Roll Controller and Aileron'];
yawPath = [modelName '/Frozen Protected Yaw Damper V2'];
assert(strcmp(get_param([rollPath '/p Pure Delay'],'SampleTime'), ...
    'delaySampleTime_rah1'),'The p-channel pure delay changed.');
assert(strcmp(get_param([rollPath '/Phi Pure Delay'],'SampleTime'), ...
    'delaySampleTime_rah1'),'The phi-channel pure delay changed.');
assert(strcmp(get_param([yawPath '/r Pure Delay'],'SampleTime'), ...
    'delaySampleTime_rah1'),'The yaw-channel pure delay changed.');
assert(strcmp(get_param([rollPath '/p Sensor Filter'],'A'), ...
    '-1/TsRoll_rah1'),'The p sensor filter changed.');
assert(strcmp(get_param([rollPath '/Phi Sensor Filter'],'A'), ...
    '-1/TsRoll_rah1'),'The phi sensor filter changed.');
assert(strcmp(get_param([rollPath '/Bank Proportional Gain Kphi'],'Gain'), ...
    'Kphi_rah1'),'The bank proportional gain changed.');
assert(strcmp(get_param([rollPath '/Bank Integral Gain Ki'],'Gain'), ...
    'Ki_rah1'),'The bank integral gain changed.');
assert(strcmp(get_param([rollPath '/Roll-Rate Gain -Kp'],'Gain'), ...
    '-Kp_rah1'),'The roll-rate feedback sign or gain changed.');
assert(strcmp(get_param([rollPath '/Automatic Aileron Position Limit'], ...
    'UpperLimit'),'autoAileronUpper_rah1_rad'), ...
    'The automatic-aileron authority changed.');
assert(strcmp(get_param([rollPath '/Aileron Servo Rate Limit'], ...
    'UpperLimit'),'aileronRateUpper_rah1_radps'), ...
    'The aileron rate limit changed.');
assert(strcmp(get_param([rollPath '/Anti-Windup Scale'],'Gain'), ...
    '1/(Ki_rah1*Tt_rah1)'), ...
    'The anti-windup tracking law changed.');
assert(strcmp(get_param([yawPath '/Automatic Rudder Gain'],'Gain'), ...
    '-Kr_rah1'),'The frozen yaw-damper sign or gain changed.');
assert(strcmp(get_param([modelName '/Physical Aileron Hard Stop'], ...
    'UpperLimit'),'totalAileronUpper_rah1_rad'), ...
    'The physical aileron hard stop changed.');
assert(strcmp(get_param([modelName '/Physical Rudder Hard Stop'], ...
    'UpperLimit'),'totalRudderUpper_rah1_rad'), ...
    'The physical rudder hard stop changed.');

%% Exact signal identities, signs and summations

I = signalIndices();
for k = 1:numel(captures)
    y = captures{k}.ySim;
    cfg = captures{k}.configuration;

    assert(max(abs(y(:,I.commandLimited)-clip(y(:,I.commandRaw), ...
        controller.commandAuthority.lowerLimit_rad, ...
        controller.commandAuthority.upperLimit_rad))) < 1.0e-12, ...
        'Bank-command limiting is inconsistent.');
    assert(max(abs(y(:,I.rInput)-(y(:,I.rDelayed)+y(:,I.rNoise)))) < ...
        1.0e-12,'Yaw sensor summation is inconsistent.');
    assert(max(abs(y(:,I.pInput)-(y(:,I.pDelayed)+y(:,I.pNoise)))) < ...
        1.0e-12,'Roll-rate sensor summation is inconsistent.');
    assert(max(abs(y(:,I.phiInput)-(y(:,I.phiDelayed)+ ...
        y(:,I.phiNoise)))) < 1.0e-12, ...
        'Bank-angle sensor summation is inconsistent.');
    assert(max(abs(y(:,I.bankError)-(y(:,I.commandFiltered)- ...
        y(:,I.phiSensor)))) < 1.0e-12, ...
        'The bank-error sign or summation is inconsistent.');
    assert(max(abs(y(:,I.proportional)- ...
        controller.bankProportionalGain*y(:,I.bankError))) < 1.0e-12, ...
        'The proportional contribution is inconsistent.');
    assert(max(abs(y(:,I.integral)- ...
        controller.bankIntegralGain_per_s*y(:,I.xi))) < 1.0e-12, ...
        'The integral contribution is inconsistent.');
    assert(max(abs(y(:,I.rollRateContribution)+ ...
        controller.rollRateGain_s*y(:,I.pSensor))) < 1.0e-12, ...
        'The roll-rate damping contribution is inconsistent.');
    assert(max(abs(y(:,I.aileronUnsat)-(y(:,I.proportional)+ ...
        y(:,I.integral)+y(:,I.rollRateContribution)))) < 1.0e-12, ...
        'The unsaturated automatic-aileron sum is inconsistent.');
    assert(max(abs(y(:,I.aileronPosition)-clip(y(:,I.aileronUnsat), ...
        aileron.authority.lowerLimit_rad, ...
        aileron.authority.upperLimit_rad))) < 1.0e-12, ...
        'Automatic-aileron position limiting is inconsistent.');
    assert(max(abs(y(:,I.aileronRateRaw)-(y(:,I.aileronPosition)- ...
        y(:,I.aileronActual))/aileron.dynamics.timeConstant_s)) < 1.0e-10, ...
        'The raw aileron-servo rate is inconsistent.');
    assert(max(abs(y(:,I.aileronRate)-clip(y(:,I.aileronRateRaw), ...
        -deg2rad(aileron.dynamics.rateLimit_degps), ...
        deg2rad(aileron.dynamics.rateLimit_degps)))) < 1.0e-12, ...
        'Aileron-servo rate limiting is inconsistent.');
    assert(max(abs(y(:,I.aileronTrack)-(y(:,I.aileronActual)+ ...
        aileron.dynamics.timeConstant_s*y(:,I.aileronRate)))) < 1.0e-12, ...
        'The rate-aware aileron tracking value is inconsistent.');
    expectedAw = cfg.antiWindupEnable*(y(:,I.aileronTrack)- ...
        y(:,I.aileronUnsat))/(controller.bankIntegralGain_per_s* ...
        aileron.antiWindup.trackingTimeConstant_s);
    assert(max(abs(y(:,I.antiWindup)-expectedAw)) < 1.0e-10, ...
        'The anti-windup correction is inconsistent.');
    assert(max(abs(y(:,I.aileronTotalRaw)-(y(:,I.aileronPilot)+ ...
        y(:,I.aileronActual)))) < 1.0e-12, ...
        'Pilot plus automatic aileron summation is inconsistent.');
    assert(max(abs(y(:,I.aileronTotal)-clip(y(:,I.aileronTotalRaw), ...
        aileron.physicalTravel.lowerLimit_rad, ...
        aileron.physicalTravel.upperLimit_rad))) < 1.0e-12, ...
        'Physical aileron limiting is inconsistent.');

    assert(max(abs(y(:,I.rudderPosition)-clip(y(:,I.rudderRaw), ...
        rudder.authority.lowerLimit_rad,rudder.authority.upperLimit_rad))) < ...
        1.0e-12,'Automatic-rudder position limiting is inconsistent.');
    assert(max(abs(y(:,I.rudderRate)-clip(y(:,I.rudderRateRaw), ...
        -deg2rad(rudder.dynamics.rateLimit_degps), ...
        deg2rad(rudder.dynamics.rateLimit_degps)))) < 1.0e-12, ...
        'Rudder-servo rate limiting is inconsistent.');
    assert(max(abs(y(:,I.rudderTotalRaw)-(y(:,I.rudderPilot)+ ...
        y(:,I.rudderActual)))) < 1.0e-12, ...
        'Pilot plus automatic rudder summation is inconsistent.');
    assert(max(abs(y(:,I.rudderTotal)-clip(y(:,I.rudderTotalRaw), ...
        rudder.physicalTravel.lowerLimit_rad, ...
        rudder.physicalTravel.upperLimit_rad))) < 1.0e-12, ...
        'Physical rudder limiting is inconsistent.');
end

positiveError = find(commandCapture.ySim(:,I.bankError) > deg2rad(0.01), ...
    1,'first');
assert(~isempty(positiveError) && ...
    commandCapture.ySim(positiveError,I.proportional) > 0 && ...
    commandCapture.ySim(positiveError,I.aileronUnsat) > 0, ...
    'Positive bank error did not command positive right-wing-down aileron.');
positiveRollRate = find(commandCapture.ySim(:,I.pSensor) > ...
    deg2rad(0.01),1,'first');
assert(~isempty(positiveRollRate) && ...
    commandCapture.ySim(positiveRollRate,I.rollRateContribution) < 0, ...
    'Positive roll rate did not produce negative damping aileron.');
positiveYawRate = find(commandCapture.ySim(:,I.rSensor) > ...
    deg2rad(0.01),1,'first');
assert(~isempty(positiveYawRate) && ...
    commandCapture.ySim(positiveYawRate,I.rudderRaw) < 0, ...
    'Positive yaw rate did not produce negative damping rudder.');

%% Command, regulation and pilot-interaction gates

req = controller.requirements;
command_rad = deg2rad(controller.validation.commandStep_deg);
commandMetrics = positiveStepMetrics(commandCapture.t, ...
    commandCapture.ySim(:,I.phi),command_rad);
commandFinalError_deg = abs(rad2deg(command_rad- ...
    commandCapture.ySim(end,I.phi)));
commandPeakRollRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.p))));
commandPeakAileron_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.aileronActual))));
commandPeakRudder_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.rudderActual))));
commandPeakBeta_deg = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.beta))));
commandPeakYawRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.r))));
commandPeakAileronRate_degps = max(abs(rad2deg( ...
    commandCapture.ySim(:,I.aileronRate))));

assert(commandMetrics.riseTime_s >= req.minimumRiseTime_s && ...
    commandMetrics.riseTime_s <= req.maximumRiseTime_s, ...
    'The executable command rise time failed its gate.');
assert(commandMetrics.overshoot_pct <= req.maximumStepOvershoot_pct, ...
    'The executable command overshoot failed its gate.');
assert(commandMetrics.settlingTime_s <= req.maximumSettlingTime_s, ...
    'The executable command settling time failed its gate.');
assert(commandFinalError_deg <= req.maximumFinalBankError_deg, ...
    'The executable final bank error failed its gate.');
assert(commandPeakRollRate_degps <= req.maximumRollRate_degps, ...
    'The executable command exceeded the roll-rate gate.');
assert(commandPeakAileron_deg <= req.maximumAutomaticAileron_deg, ...
    'The executable command exceeded automatic-aileron effort.');
assert(commandPeakRudder_deg <= req.maximumAutomaticRudder_deg, ...
    'The executable command exceeded automatic-rudder effort.');
assert(commandPeakBeta_deg <= req.maximumSideslip_deg, ...
    'The executable command exceeded the sideslip gate.');
assert(commandPeakYawRate_degps <= req.maximumYawRate_degps, ...
    'The executable command exceeded the yaw-rate gate.');
assert(commandPeakAileronRate_degps <= ...
    aileron.requirements.maximumOperationalActuatorRate_degps, ...
    'The executable command exceeded the operational aileron-rate gate.');
assert(~aileronPositionLimitActive(commandCapture.ySim,I) && ...
    ~aileronRateLimitActive(commandCapture.ySim,I), ...
    'Aileron protection unexpectedly activated for the 10-deg command.');

initialFinalBank_deg = abs(rad2deg(initialCapture.ySim(end,I.phi)));
initialPeakAutomaticAileron_deg = max(abs(rad2deg( ...
    initialCapture.ySim(:,I.aileronActual))));
initialPeakAileronRate_degps = max(abs(rad2deg( ...
    initialCapture.ySim(:,I.aileronRate))));
biasFinalBank_deg = abs(rad2deg(biasCapture.ySim(end,I.phi)));
biasFinalAutomaticAileron_deg = rad2deg( ...
    biasCapture.ySim(end,I.aileronActual));
assert(initialFinalBank_deg <= req.maximumRegulationResidual_deg, ...
    'Initial-bank regulation failed.');
assert(initialPeakAutomaticAileron_deg <= ...
    aileron.authority.rightWingDown_deg+1.0e-9 && ...
    initialPeakAileronRate_degps <= ...
    aileron.dynamics.rateLimit_degps+1.0e-9, ...
    'Initial-bank recovery exceeded protected aileron capability.');
assert(biasFinalBank_deg <= req.maximumRegulationResidual_deg, ...
    'Constant pilot-aileron-bias regulation failed.');
assert(abs(biasFinalAutomaticAileron_deg+ ...
    controller.validation.constantAileronBias_deg) <= 0.01, ...
    'The integrator did not cancel the constant pilot-aileron bias.');

aileronPulsePeakBank_deg = max(abs(rad2deg( ...
    aileronPulseCapture.ySim(:,I.phi))));
rudderPulsePeakBank_deg = max(abs(rad2deg( ...
    rudderPulseCapture.ySim(:,I.phi))));
aileronPulseFinalBank_deg = abs(rad2deg( ...
    aileronPulseCapture.ySim(end,I.phi)));
rudderPulseFinalBank_deg = abs(rad2deg( ...
    rudderPulseCapture.ySim(end,I.phi)));
assert(aileronPulseFinalBank_deg <= req.maximumRegulationResidual_deg && ...
    rudderPulseFinalBank_deg <= req.maximumRegulationResidual_deg, ...
    'A pilot-pulse capture did not return to the commanded bank.');
operationalCaptures = {commandCapture,initialCapture,biasCapture, ...
    aileronPulseCapture,rudderPulseCapture};
for k = 1:numel(operationalCaptures)
    assert(~aileronPositionLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~aileronRateLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~aileronPhysicalLimitActive(operationalCaptures{k}.ySim,I), ...
        'Aileron protection unexpectedly activated operationally.');
    assert(~rudderPositionLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~rudderRateLimitActive(operationalCaptures{k}.ySim,I) && ...
        ~rudderPhysicalLimitActive(operationalCaptures{k}.ySim,I), ...
        'Rudder protection unexpectedly activated operationally.');
end

%% Command-limit, actuator-stress, anti-windup and noise gates

commandLimitActive = any(abs(commandLimitCapture.ySim(:,I.commandRaw)- ...
    commandLimitCapture.ySim(:,I.commandLimited)) > 1.0e-10);
commandLimitMaximum_deg = max(abs(rad2deg( ...
    commandLimitCapture.ySim(:,I.commandLimited))));
commandLimitFinalBank_deg = rad2deg( ...
    commandLimitCapture.ySim(end,I.phi));
assert(commandLimitActive, ...
    'The 30-deg bank command did not activate command limiting.');
assert(abs(commandLimitMaximum_deg- ...
    controller.commandAuthority.rightWingDown_deg) < 1.0e-9, ...
    'The executable bank-command authority is incorrect.');
assert(abs(commandLimitFinalBank_deg- ...
    controller.commandAuthority.rightWingDown_deg) <= ...
    req.maximumFinalBankError_deg, ...
    'The command-limited capture did not settle at 20 deg.');

stressMetrics = protectedStressMetrics(stressCapture,I,aileron);
stressNoAwMetrics = protectedStressMetrics(stressNoAwCapture,I,aileron);
antiWindupIntegratorRatio = stressMetrics.peakIntegratorMagnitude/ ...
    stressNoAwMetrics.peakIntegratorMagnitude;
assert(stressMetrics.positionLimitActive && stressMetrics.rateLimitActive, ...
    'The 30-deg initial-bank stress did not activate both aileron limits.');
assert(~stressMetrics.physicalLimitActive, ...
    'The logic stress unexpectedly reached the physical aileron stop.');
assert(stressMetrics.peakAutomaticAileron_deg <= ...
    aileron.authority.rightWingDown_deg+1.0e-9, ...
    'The stress case exceeded automatic-aileron authority.');
assert(stressMetrics.peakAileronRate_degps <= ...
    aileron.dynamics.rateLimit_degps+1.0e-9, ...
    'The stress case exceeded the aileron-rate limit.');
assert(stressMetrics.recoveryTime_s <= ...
    aileron.stress.maximumRecoveryTime_s, ...
    'The stress case recovered too slowly.');
assert(abs(stressMetrics.finalBank_deg) <= ...
    aileron.stress.maximumFinalBank_deg, ...
    'The stress-case final bank residual is excessive.');
assert(abs(stressMetrics.finalAutomaticAileron_deg) <= ...
    aileron.requirements.maximumReleasedAileron_deg, ...
    'The automatic aileron did not release after the stress.');
assert(antiWindupIntegratorRatio <= ...
    aileron.stress.maximumAntiWindupIntegratorRatio, ...
    'Simulink anti-windup did not sufficiently reduce integrator growth.');

noiseRows = noiseCapture.t >= aileron.noise.discardTime_s;
noiseAileron_deg = rad2deg(noiseCapture.ySim(noiseRows,I.aileronActual));
noiseAileronRms_deg = sqrt(mean(noiseAileron_deg.^2));
noiseAileronPeak_deg = max(abs(noiseAileron_deg));
pNoiseRms_degps = sqrt(mean(rad2deg( ...
    noiseCapture.ySim(noiseRows,I.pNoise)).^2));
phiNoiseRms_deg = sqrt(mean(rad2deg( ...
    noiseCapture.ySim(noiseRows,I.phiNoise)).^2));
assert(noiseAileronRms_deg <= ...
    aileron.requirements.maximumNoiseActuatorRms_deg, ...
    'Roll-sensor noise exceeded the automatic-aileron RMS gate.');
assert(noiseAileronPeak_deg <= ...
    aileron.requirements.maximumNoiseActuatorPeak_deg, ...
    'Roll-sensor noise exceeded the automatic-aileron peak gate.');
assert(~aileronPositionLimitActive(noiseCapture.ySim,I) && ...
    ~aileronRateLimitActive(noiseCapture.ySim,I), ...
    'Sensor noise unexpectedly activated aileron protection.');

assert(aileron.sensor.nominalDelay_s <= ...
    aileron.sensor.maximumAcceptedDelay_s, ...
    'The executable roll delay exceeds the accepted 40-ms envelope.');
assert(rudder.sensor.nominalDelay_s <= ...
    rudder.sensor.maximumAcceptedDelay_s, ...
    'The executable yaw delay exceeds the accepted 60-ms envelope.');

%% Console release report

fprintf('============================================================\n');
fprintf(' C172S ROLL-ATTITUDE HOLD V1 - PROTECTED SIMULINK CHECK\n');
fprintf('============================================================\n\n');
fprintf('Model                                : %s\n',modelName);
fprintf('Controller artifact                  : %s\n', ...
    controller.artifactRevision);
fprintf('Frozen yaw controller                : %s\n', ...
    yawController.artifactRevision);
fprintf('Frozen rudder actuator audit          : %s\n', ...
    rudder.artifactRevision);
fprintf('Aileron/source audit                  : %s\n', ...
    aileron.artifactRevision);
fprintf('Frozen plant                          : %s\n', ...
    data.model.version);
fprintf('Control law                           : deltaA = Kphi*ePhi + Ki*xi - Kp*pSensor\n');
fprintf('Kphi / Ki / Kp                        : %.3f / %.3f 1/s / %.3f s\n', ...
    controller.bankProportionalGain, ...
    controller.bankIntegralGain_per_s,controller.rollRateGain_s);
fprintf('Command filter / bank authority       : %.2f s / +/-%.1f deg\n', ...
    controller.commandFilterTimeConstant_s, ...
    controller.commandAuthority.rightWingDown_deg);
fprintf('Roll filter / nominal pure delay      : %.3f s / %.0f ms\n', ...
    aileron.sensor.filterTimeConstant_s, ...
    1000*aileron.sensor.nominalDelay_s);
fprintf('Aileron tau / authority / rate        : %.3f s / +/-%.1f deg / +/-%.1f deg/s\n', ...
    aileron.dynamics.timeConstant_s,aileron.authority.rightWingDown_deg, ...
    aileron.dynamics.rateLimit_degps);
fprintf('Equivalent aileron hard stop          : +/-%.1f deg\n', ...
    aileron.physicalTravel.equivalentMagnitude_deg);
fprintf('Solver / fixed step                   : ode4 / 0.0100 s\n\n');

for k = 1:numel(captures)
    fprintf('%-20s maximum error       : %.9g\n', ...
        captureNames{k},captures{k}.maxError);
    fprintf('%-20s RMS error           : %.9g\n', ...
        captureNames{k},captures{k}.rmsError);
end
fprintf('Allowed implementation error         : %.3g\n\n',tolerance);

fprintf('10-deg command rise time              : %.3f s\n', ...
    commandMetrics.riseTime_s);
fprintf('10-deg command overshoot              : %.4f %%\n', ...
    commandMetrics.overshoot_pct);
fprintf('10-deg command settling time          : %.3f s\n', ...
    commandMetrics.settlingTime_s);
fprintf('Final bank error                      : %.6f deg\n', ...
    commandFinalError_deg);
fprintf('Peak roll rate                        : %.4f deg/s\n', ...
    commandPeakRollRate_degps);
fprintf('Peak automatic aileron / rate         : %.4f deg / %.4f deg/s\n', ...
    commandPeakAileron_deg,commandPeakAileronRate_degps);
fprintf('Peak automatic rudder                 : %.4f deg\n', ...
    commandPeakRudder_deg);
fprintf('Peak sideslip / yaw rate              : %.4f deg / %.4f deg/s\n\n', ...
    commandPeakBeta_deg,commandPeakYawRate_degps);

fprintf('Initial-bank final residual           : %.6f deg\n', ...
    initialFinalBank_deg);
fprintf('Initial-bank peak aileron / rate      : %.4f deg / %.4f deg/s\n', ...
    initialPeakAutomaticAileron_deg,initialPeakAileronRate_degps);
fprintf('Aileron-bias final bank               : %.6f deg\n', ...
    biasFinalBank_deg);
fprintf('Aileron-bias final automatic aileron  : %.6f deg\n', ...
    biasFinalAutomaticAileron_deg);
fprintf('Aileron/rudder pulse peak bank        : %.4f / %.4f deg\n', ...
    aileronPulsePeakBank_deg,rudderPulsePeakBank_deg);
fprintf('Aileron/rudder pulse final bank       : %.6f / %.6f deg\n\n', ...
    aileronPulseFinalBank_deg,rudderPulseFinalBank_deg);

fprintf('30-deg raw command limited to         : %.4f deg\n', ...
    commandLimitMaximum_deg);
fprintf('Command-limited final bank            : %.6f deg\n\n', ...
    commandLimitFinalBank_deg);

fprintf('Stress initial bank                   : %.1f deg\n', ...
    aileron.stress.initialBank_deg);
fprintf('Stress peak automatic aileron         : %.4f deg\n', ...
    stressMetrics.peakAutomaticAileron_deg);
fprintf('Stress peak actuator rate             : %.4f deg/s\n', ...
    stressMetrics.peakAileronRate_degps);
fprintf('Stress position/rate limits active    : %d / %d\n', ...
    stressMetrics.positionLimitActive,stressMetrics.rateLimitActive);
fprintf('Stress physical hard stop active      : %d\n', ...
    stressMetrics.physicalLimitActive);
fprintf('Stress recovery / final bank          : %.3f s / %.6f deg\n', ...
    stressMetrics.recoveryTime_s,stressMetrics.finalBank_deg);
fprintf('Stress final automatic aileron        : %.6f deg\n', ...
    stressMetrics.finalAutomaticAileron_deg);
fprintf('Anti-windup peak-integrator ratio     : %.4f\n\n', ...
    antiWindupIntegratorRatio);

fprintf('Deterministic p / phi noise RMS       : %.5f deg/s / %.5f deg\n', ...
    pNoiseRms_degps,phiNoiseRms_deg);
fprintf('Noise-driven automatic-aileron RMS    : %.5f deg\n', ...
    noiseAileronRms_deg);
fprintf('Noise-driven automatic-aileron peak   : %.5f deg\n\n', ...
    noiseAileronPeak_deg);

fprintf('PASS: Simulink matches nine independent hybrid RK4 references.\n');
fprintf('PASS: command limiting, sensor delays/filters and feedback signs are correct.\n');
fprintf('PASS: pilot summation and frozen protected yaw damping are preserved.\n');
fprintf('PASS: command, regulation and pilot-interaction gates pass.\n');
fprintf('PASS: aileron position/rate/hard-stop protection enforces every limit.\n');
fprintf('PASS: anti-windup and simultaneous roll-sensor noise gates pass.\n');
fprintf(['NOTE: this validates the nominal executable implementation against ', ...
    'Plant V0.1 and the declared project assumptions; it is not aircraft approval.\n']);

%% Equivalence and protection figures

figure('Name','C172S Roll-Attitude Hold V1 Simulink Equivalence','Color','w');
tiledlayout(2,3,'TileSpacing','compact','Padding','compact');
nexttile;
plotComparison(commandCapture.t,commandCapture.ySim(:,I.phi), ...
    commandCapture.yReference(:,I.phi),'Bank angle (deg)');
title('10-deg Bank Command');
nexttile;
plotComparison(commandCapture.t,commandCapture.ySim(:,I.aileronActual), ...
    commandCapture.yReference(:,I.aileronActual),'Automatic aileron (deg)');
title('Protected Aileron');
nexttile;
plotComparison(initialCapture.t,initialCapture.ySim(:,I.phi), ...
    initialCapture.yReference(:,I.phi),'Bank angle (deg)');
title('5-deg Initial Bank');
nexttile;
plotComparison(biasCapture.t,biasCapture.ySim(:,I.phi), ...
    biasCapture.yReference(:,I.phi),'Bank angle (deg)');
title('0.2-deg Aileron Bias');
nexttile;
plotComparison(aileronPulseCapture.t, ...
    aileronPulseCapture.ySim(:,I.phi), ...
    aileronPulseCapture.yReference(:,I.phi),'Bank angle (deg)');
title('1-deg Aileron Pulse');
nexttile;
plotComparison(rudderPulseCapture.t, ...
    rudderPulseCapture.ySim(:,I.beta), ...
    rudderPulseCapture.yReference(:,I.beta),'Sideslip (deg)');
title('1-deg Rudder Pulse');
sgtitle('Roll-Attitude Hold V1: Simulink vs Independent Hybrid RK4');

figure('Name','C172S Roll-Attitude Hold V1 Protection','Color','w');
tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
nexttile;
plot(commandLimitCapture.t,rad2deg( ...
    commandLimitCapture.ySim(:,I.commandRaw)),'--','LineWidth',1.2);
hold on;
plot(commandLimitCapture.t,rad2deg( ...
    commandLimitCapture.ySim(:,I.commandLimited)),'LineWidth',1.3);
plot(commandLimitCapture.t,rad2deg( ...
    commandLimitCapture.ySim(:,I.phi)),'LineWidth',1.5);
grid on; xlabel('Time (s)'); ylabel('Bank angle (deg)');
legend('Raw command','Limited command','Bank','Location','best');
title('30-deg Command Protection');
nexttile;
plot(stressCapture.t,rad2deg(stressCapture.ySim(:,I.phi)), ...
    'LineWidth',1.5,'DisplayName','Anti-windup');
hold on;
plot(stressNoAwCapture.t,rad2deg( ...
    stressNoAwCapture.ySim(:,I.phi)),'--','LineWidth',1.2, ...
    'DisplayName','No anti-windup');
yline(aileron.stress.recoveryThreshold_deg,':');
yline(-aileron.stress.recoveryThreshold_deg,':');
grid on; xlabel('Time (s)'); ylabel('Bank angle (deg)');
legend('Location','best'); title('30-deg Initial-Bank Stress');
nexttile;
yyaxis left;
plot(stressCapture.t,rad2deg( ...
    stressCapture.ySim(:,I.aileronActual)),'LineWidth',1.5);
ylabel('Automatic aileron (deg)');
yyaxis right;
plot(stressCapture.t,rad2deg( ...
    stressCapture.ySim(:,I.aileronRate)),'LineWidth',1.2);
ylabel('Aileron rate (deg/s)');
grid on; xlabel('Time (s)'); title('Aileron Position and Rate Protection');
nexttile;
plotComparison(noiseCapture.t,noiseCapture.ySim(:,I.aileronActual), ...
    noiseCapture.yReference(:,I.aileronActual),'Automatic aileron (deg)');
title('Simultaneous p and \phi Sensor Noise');
sgtitle('Roll-Attitude Hold V1: Executable Protection Captures');

%% Refresh saved model after simulations

modelFile = get_param(modelName,'FileName');
close_system(modelName,0);
load_system(modelFile);
open_system(modelName);
fprintf('Reloaded generated model to clear transient editor diagnostics.\n');

%% Local helpers

function result = runCapture(modelName,plant,yawController,rudder, ...
    controller,aileron,caseName)
cfg = captureConfiguration(caseName,controller,aileron);

simInput = Simulink.SimulationInput(modelName);
simInput = simInput.setVariable('bankCommand_rah1_rad',cfg.bankCommand_rad);
simInput = simInput.setVariable('pilotAileronBias_rah1_rad', ...
    cfg.aileronBias_rad);
simInput = simInput.setVariable('pilotAileronPulse_rah1_rad', ...
    cfg.aileronPulse_rad);
simInput = simInput.setVariable('pilotRudderBias_rah1_rad', ...
    cfg.rudderBias_rad);
simInput = simInput.setVariable('pilotRudderPulse_rah1_rad', ...
    cfg.rudderPulse_rad);
simInput = simInput.setVariable('aileronPulseStart_rah1_s', ...
    cfg.aileronPulseStart_s);
simInput = simInput.setVariable('aileronPulseEnd_rah1_s', ...
    cfg.aileronPulseEnd_s);
simInput = simInput.setVariable('rudderPulseStart_rah1_s', ...
    cfg.rudderPulseStart_s);
simInput = simInput.setVariable('rudderPulseEnd_rah1_s', ...
    cfg.rudderPulseEnd_s);
simInput = simInput.setVariable('pNoiseAmplitude_rah1_radps', ...
    cfg.pNoiseAmplitude_radps);
simInput = simInput.setVariable('pNoiseFrequency_rah1_radps', ...
    cfg.pNoiseFrequency_radps);
simInput = simInput.setVariable('phiNoiseAmplitude_rah1_rad', ...
    cfg.phiNoiseAmplitude_rad);
simInput = simInput.setVariable('phiNoiseFrequency_rah1_radps', ...
    cfg.phiNoiseFrequency_radps);
simInput = simInput.setVariable('yawNoiseAmplitude_rah1_radps',0.0);
simInput = simInput.setVariable('yawNoiseFrequency_rah1_radps',50.0);
simInput = simInput.setVariable('antiWindupEnable_rah1', ...
    cfg.antiWindupEnable);
simInput = simInput.setVariable('x0_rah1',cfg.x0);
simInput = simInput.setVariable('rDelay0_rah1_radps',cfg.x0(3));
simInput = simInput.setVariable('pDelay0_rah1_radps',cfg.x0(2));
simInput = simInput.setVariable('phiDelay0_rah1_rad',cfg.x0(4));
simInput = simInput.setVariable('rSensor0_rah1_radps',0.0);
simInput = simInput.setVariable('xw0_rah1_radps',0.0);
simInput = simInput.setVariable('deltaRAuto0_rah1_rad',0.0);
simInput = simInput.setVariable('pSensor0_rah1_radps',0.0);
simInput = simInput.setVariable('phiSensor0_rah1_rad',0.0);
simInput = simInput.setVariable('xi0_rah1_rad_s',0.0);
simInput = simInput.setVariable('deltaAAuto0_rah1_rad',0.0);
simInput = simInput.setVariable('filteredCommand0_rah1_rad',0.0);
simInput = simInput.setModelParameter('StopTime',num2str(cfg.stopTime_s));

simOut = sim(simInput);
[tSim,ySim] = extractArrayOutput(simOut,44);
dt = median(diff(tSim));
assert(max(abs(diff(tSim)-dt)) < 1.0e-10, ...
    'The independent reference requires uniform sampling.');
assert(abs(dt-0.01) < 1.0e-12, ...
    'The executable sample grid differs from the declared 0.01-s grid.');

yReference = independentReference(tSim,cfg,plant,yawController, ...
    rudder,controller,aileron);
errorSignal = ySim-yReference;
result.t = tSim;
result.ySim = ySim;
result.yReference = yReference;
result.maxError = max(abs(errorSignal),[],'all');
result.rmsError = sqrt(mean(errorSignal(:).^2));
result.configuration = cfg;
end

function cfg = captureConfiguration(caseName,controller,aileron)
cfg.name = caseName;
cfg.bankCommand_rad = 0.0;
cfg.aileronBias_rad = 0.0;
cfg.aileronPulse_rad = 0.0;
cfg.rudderBias_rad = 0.0;
cfg.rudderPulse_rad = 0.0;
cfg.aileronPulseStart_s = 5.0;
cfg.aileronPulseEnd_s = 6.0;
cfg.rudderPulseStart_s = 5.0;
cfg.rudderPulseEnd_s = 6.0;
cfg.pNoiseAmplitude_radps = 0.0;
cfg.pNoiseFrequency_radps = aileron.noise.rollRateFrequency_radps;
cfg.phiNoiseAmplitude_rad = 0.0;
cfg.phiNoiseFrequency_radps = aileron.noise.bankAngleFrequency_radps;
cfg.antiWindupEnable = 1.0;
cfg.x0 = zeros(5,1);
cfg.stopTime_s = controller.validation.stopTime_s;

switch caseName
    case 'command'
        cfg.bankCommand_rad = deg2rad(controller.validation.commandStep_deg);
    case 'initial'
        cfg.x0(4) = deg2rad(controller.validation.initialBankDisturbance_deg);
    case 'bias'
        cfg.aileronBias_rad = ...
            deg2rad(controller.validation.constantAileronBias_deg);
    case 'aileronPulse'
        cfg.aileronPulse_rad = deg2rad(1.0);
        cfg.stopTime_s = 30.0;
    case 'rudderPulse'
        cfg.rudderPulse_rad = deg2rad(1.0);
        cfg.stopTime_s = 30.0;
    case 'commandLimit'
        cfg.bankCommand_rad = deg2rad(30.0);
    case 'stressAw'
        cfg.x0(4) = deg2rad(aileron.stress.initialBank_deg);
        cfg.antiWindupEnable = 1.0;
        cfg.stopTime_s = aileron.stress.stopTime_s;
    case 'stressNoAw'
        cfg.x0(4) = deg2rad(aileron.stress.initialBank_deg);
        cfg.antiWindupEnable = 0.0;
        cfg.stopTime_s = aileron.stress.stopTime_s;
    case 'noise'
        multiplier = aileron.sensor.noiseStressMultiplier;
        cfg.pNoiseAmplitude_radps = deg2rad(sqrt(2)*multiplier* ...
            aileron.sensor.rollRateNoiseRms_degps);
        cfg.phiNoiseAmplitude_rad = deg2rad(sqrt(2)*multiplier* ...
            aileron.sensor.bankAngleNoiseRms_deg);
        cfg.stopTime_s = aileron.noise.stopTime_s;
    otherwise
        error('Unknown capture name: %s',caseName);
end
end

function y = independentReference(t,cfg,plant,yawController,rudder, ...
    controller,aileron)
% Continuous z = [beta p r phi psi rSensor xw deltaR pSensor phiSensor
%                 xi deltaA filteredCommand].
z = [cfg.x0;zeros(8,1)];
delay.r = cfg.x0(3);
delay.p = cfg.x0(2);
delay.phi = cfg.x0(4);
y = zeros(numel(t),44);
for k = 1:numel(t)
    d = protectedSignals(t(k),z,delay,cfg,yawController,rudder, ...
        controller,aileron);
    y(k,:) = outputVector(z,d).';
    if k < numel(t)
        h = t(k+1)-t(k);
        sampled.r = z(3);
        sampled.p = z(2);
        sampled.phi = z(4);
        k1 = protectedDerivative(t(k),z,delay,cfg,plant, ...
            yawController,rudder,controller,aileron);
        k2 = protectedDerivative(t(k)+0.5*h,z+0.5*h*k1,delay,cfg, ...
            plant,yawController,rudder,controller,aileron);
        k3 = protectedDerivative(t(k)+0.5*h,z+0.5*h*k2,delay,cfg, ...
            plant,yawController,rudder,controller,aileron);
        k4 = protectedDerivative(t(k)+h,z+h*k3,delay,cfg,plant, ...
            yawController,rudder,controller,aileron);
        z = z+(h/6)*(k1+2*k2+2*k3+k4);
        delay = sampled;
    end
end
end

function zDot = protectedDerivative(t,z,delay,cfg,plant, ...
    yawController,rudder,controller,aileron)
d = protectedSignals(t,z,delay,cfg,yawController,rudder, ...
    controller,aileron);
zDot = zeros(13,1);
zDot(1:5) = plant.A*z(1:5)+plant.B*[d.totalAileron;d.totalRudder];
zDot(6) = (d.rInput-z(6))/rudder.sensor.filterTimeConstant_s;
zDot(7) = (z(6)-z(7))/yawController.washoutTimeConstant_s;
zDot(8) = d.rudderRate;
zDot(9) = (d.pInput-z(9))/aileron.sensor.filterTimeConstant_s;
zDot(10) = (d.phiInput-z(10))/aileron.sensor.filterTimeConstant_s;
zDot(11) = d.bankError+d.antiWindup;
zDot(12) = d.aileronRate;
zDot(13) = (d.commandLimited-z(13))/ ...
    controller.commandFilterTimeConstant_s;
end

function d = protectedSignals(t,z,delay,cfg,yawController,rudder, ...
    controller,aileron)
d.commandRaw = cfg.bankCommand_rad;
d.commandLimited = clip(d.commandRaw, ...
    controller.commandAuthority.lowerLimit_rad, ...
    controller.commandAuthority.upperLimit_rad);
[d.aileronPilot,d.rudderPilot] = pilotInputs(t,cfg);
d.rNoise = 0.0;
d.pNoise = cfg.pNoiseAmplitude_radps*sin(cfg.pNoiseFrequency_radps*t);
d.phiNoise = cfg.phiNoiseAmplitude_rad*sin(cfg.phiNoiseFrequency_radps*t);
d.rDelayed = delay.r;
d.pDelayed = delay.p;
d.phiDelayed = delay.phi;
d.rInput = d.rDelayed+d.rNoise;
d.pInput = d.pDelayed+d.pNoise;
d.phiInput = d.phiDelayed+d.phiNoise;

d.rWashout = z(6)-z(7);
d.rudderRaw = -yawController.rudderGain_s*d.rWashout;
d.rudderPosition = clip(d.rudderRaw,rudder.authority.lowerLimit_rad, ...
    rudder.authority.upperLimit_rad);
d.rudderRateRaw = (d.rudderPosition-z(8))/ ...
    rudder.dynamics.timeConstant_s;
d.rudderRate = clip(d.rudderRateRaw, ...
    -deg2rad(rudder.dynamics.rateLimit_degps), ...
    deg2rad(rudder.dynamics.rateLimit_degps));
d.rudderTotalRaw = d.rudderPilot+z(8);
d.totalRudder = clip(d.rudderTotalRaw, ...
    rudder.physicalTravel.lowerLimit_rad, ...
    rudder.physicalTravel.upperLimit_rad);

d.bankError = z(13)-z(10);
d.proportional = controller.bankProportionalGain*d.bankError;
d.integral = controller.bankIntegralGain_per_s*z(11);
d.rollRateContribution = -controller.rollRateGain_s*z(9);
d.aileronUnsat = d.proportional+d.integral+d.rollRateContribution;
d.aileronPosition = clip(d.aileronUnsat, ...
    aileron.authority.lowerLimit_rad,aileron.authority.upperLimit_rad);
d.aileronRateRaw = (d.aileronPosition-z(12))/ ...
    aileron.dynamics.timeConstant_s;
d.aileronRate = clip(d.aileronRateRaw, ...
    -deg2rad(aileron.dynamics.rateLimit_degps), ...
    deg2rad(aileron.dynamics.rateLimit_degps));
d.aileronTrack = z(12)+ ...
    aileron.dynamics.timeConstant_s*d.aileronRate;
d.antiWindup = cfg.antiWindupEnable*(d.aileronTrack-d.aileronUnsat)/( ...
    controller.bankIntegralGain_per_s* ...
    aileron.antiWindup.trackingTimeConstant_s);
d.aileronTotalRaw = d.aileronPilot+z(12);
d.totalAileron = clip(d.aileronTotalRaw, ...
    aileron.physicalTravel.lowerLimit_rad, ...
    aileron.physicalTravel.upperLimit_rad);
end

function y = outputVector(z,d)
y = [z(1:5);d.commandRaw;d.commandLimited;z(13); ...
    d.aileronPilot;d.rudderPilot;d.rDelayed;d.rNoise;d.rInput;z(6); ...
    d.rWashout;d.rudderRaw;d.rudderPosition;z(8);d.rudderRateRaw; ...
    d.rudderRate;d.rudderTotalRaw;d.totalRudder;d.pDelayed;d.pNoise; ...
    d.pInput;z(9);d.phiDelayed;d.phiNoise;d.phiInput;z(10); ...
    d.bankError;d.proportional;z(11);d.integral; ...
    d.rollRateContribution;d.aileronUnsat;d.aileronPosition;z(12); ...
    d.aileronRateRaw;d.aileronRate;d.aileronTrack;d.antiWindup; ...
    d.aileronTotalRaw;d.totalAileron];
end

function [aileronInput,rudderInput] = pilotInputs(t,cfg)
t = snapToEdges(t,[cfg.aileronPulseStart_s,cfg.aileronPulseEnd_s, ...
    cfg.rudderPulseStart_s,cfg.rudderPulseEnd_s]);
aileronInput = cfg.aileronBias_rad;
rudderInput = cfg.rudderBias_rad;
if t >= cfg.aileronPulseStart_s && t < cfg.aileronPulseEnd_s
    aileronInput = aileronInput+cfg.aileronPulse_rad;
end
if t >= cfg.rudderPulseStart_s && t < cfg.rudderPulseEnd_s
    rudderInput = rudderInput+cfg.rudderPulse_rad;
end
end

function t = snapToEdges(t,edges)
for k = 1:numel(edges)
    if abs(t-edges(k)) <= 1.0e-12
        t = edges(k);
        return;
    end
end
end

function I = signalIndices()
names = {'beta','p','r','phi','psi','commandRaw','commandLimited', ...
    'commandFiltered','aileronPilot','rudderPilot','rDelayed','rNoise', ...
    'rInput','rSensor','rWashout','rudderRaw','rudderPosition', ...
    'rudderActual','rudderRateRaw','rudderRate','rudderTotalRaw', ...
    'rudderTotal','pDelayed','pNoise','pInput','pSensor','phiDelayed', ...
    'phiNoise','phiInput','phiSensor','bankError','proportional','xi', ...
    'integral','rollRateContribution','aileronUnsat','aileronPosition', ...
    'aileronActual','aileronRateRaw','aileronRate','aileronTrack', ...
    'antiWindup','aileronTotalRaw','aileronTotal'};
for k = 1:numel(names)
    I.(names{k}) = k;
end
end

function metrics = protectedStressMetrics(capture,I,aileron)
y = capture.ySim;
metrics.positionLimitActive = aileronPositionLimitActive(y,I);
metrics.rateLimitActive = aileronRateLimitActive(y,I);
metrics.physicalLimitActive = aileronPhysicalLimitActive(y,I);
metrics.peakAutomaticAileron_deg = max(abs(rad2deg(y(:,I.aileronActual))));
metrics.peakAileronRate_degps = max(abs(rad2deg(y(:,I.aileronRate))));
metrics.peakIntegratorMagnitude = max(abs(y(:,I.xi)));
metrics.finalBank_deg = rad2deg(y(end,I.phi));
metrics.finalAutomaticAileron_deg = rad2deg(y(end,I.aileronActual));
inside = abs(rad2deg(y(:,I.phi))) <= aileron.stress.recoveryThreshold_deg;
lastOutside = find(~inside,1,'last');
if isempty(lastOutside)
    metrics.recoveryTime_s = capture.t(1);
elseif lastOutside < numel(capture.t)
    metrics.recoveryTime_s = capture.t(lastOutside+1);
else
    metrics.recoveryTime_s = inf;
end
end

function active = aileronPositionLimitActive(y,I)
active = any(abs(y(:,I.aileronUnsat)-y(:,I.aileronPosition)) > 1.0e-10);
end

function active = aileronRateLimitActive(y,I)
active = any(abs(y(:,I.aileronRateRaw)-y(:,I.aileronRate)) > 1.0e-10);
end

function active = aileronPhysicalLimitActive(y,I)
active = any(abs(y(:,I.aileronTotalRaw)-y(:,I.aileronTotal)) > 1.0e-10);
end

function active = rudderPositionLimitActive(y,I)
active = any(abs(y(:,I.rudderRaw)-y(:,I.rudderPosition)) > 1.0e-10);
end

function active = rudderRateLimitActive(y,I)
active = any(abs(y(:,I.rudderRateRaw)-y(:,I.rudderRate)) > 1.0e-10);
end

function active = rudderPhysicalLimitActive(y,I)
active = any(abs(y(:,I.rudderTotalRaw)-y(:,I.rudderTotal)) > 1.0e-10);
end

function metrics = positiveStepMetrics(t,response,command)
i10 = find(response >= 0.10*command,1,'first');
i90 = find(response >= 0.90*command,1,'first');
if isempty(i10) || isempty(i90)
    metrics.riseTime_s = inf;
else
    metrics.riseTime_s = t(i90)-t(i10);
end
metrics.overshoot_pct = max(0,100*(max(response)-command)/command);
outside = find(abs(response-command) > 0.02*abs(command));
if isempty(outside)
    metrics.settlingTime_s = 0;
elseif outside(end) == numel(t)
    metrics.settlingTime_s = inf;
else
    metrics.settlingTime_s = t(outside(end)+1);
end
end

function value = clip(value,lowerLimit,upperLimit)
value = min(max(value,lowerLimit),upperLimit);
end

function assertDependencies(data,yawController,rudder,controller,aileron)
assert(strcmp(data.model.version,controller.requiredPlantVersion), ...
    'Roll-Attitude Hold V1 plant dependency mismatch.');
assert(strcmp(yawController.artifactRevision, ...
    controller.requiredYawDamperRevision), ...
    'Roll-Attitude Hold V1 yaw-controller dependency mismatch.');
assert(strcmp(rudder.artifactRevision, ...
    controller.requiredRudderAuditRevision), ...
    'Roll-Attitude Hold V1 rudder-audit dependency mismatch.');
assert(strcmp(aileron.artifactRevision, ...
    controller.requiredAileronAuditRevision), ...
    'Roll-Attitude Hold V1 aileron-audit dependency mismatch.');
end

function [t,y] = extractArrayOutput(simOut,nSignal)
t = simOut.tout;
y = simOut.yout;
if isa(y,'timeseries')
    y = y.Data;
elseif isa(y,'Simulink.SimulationData.Dataset')
    y = y.getElement(1).Values.Data;
end
y = squeeze(y);
if size(y,1) ~= numel(t) && size(y,2) == numel(t)
    y = y.';
end
assert(size(y,2) == nSignal, ...
    'Expected %d logged signals but received %d.',nSignal,size(y,2));
end

function plotComparison(t,ySim,yReference,yLabel)
plot(t,rad2deg(ySim),'LineWidth',1.3);
hold on;
plot(t,rad2deg(yReference),'--','LineWidth',1.0);
grid on;
xlabel('Time (s)');
ylabel(yLabel);
legend('Simulink','Independent RK4','Location','best');
end
