function report = verifyC172sFlightDynamicsAutopilotLabInstallation()
%VERIFYC172SFLIGHTDYNAMICSAUTOPILOTLABINSTALLATION Static release preflight.
%
%   REPORT = VERIFYC172SFLIGHTDYNAMICSAUTOPILOTLABINSTALLATION verifies the
%   public entry points, executable model, frozen revision chain, and saved
%   28/28 external evidence. It does not run a simulation or replace the
%   authoritative laboratory and public-backend runtime audits.

releaseRoot = fileparts(mfilename('fullpath'));
requiredFiles = { ...
    'mainC172sFlightControlLab.m'; ...
    'c172sFlightControlLabData.m'; ...
    'createC172sFlightControlScenario.m'; ...
    'runC172sFlightControlScenario.m'; ...
    'simulateC172sNonlinearAutopilotSimulink.m'; ...
    'c172sNonlinearAutopilotResultMatrix.m'; ...
    'compareC172sNonlinearAutopilotBackends.m'; ...
    'plotC172sFlightControlBackendComparison.m'; ...
    'analyzeC172sFlightControlScenario.m'; ...
    'plotC172sFlightControlScenario.m'; ...
    'exportC172sFlightControlRun.m'; ...
    'auditC172sFlightControlLab.m'; ...
    'auditC172sFlightControlLabBackends.m'; ...
    'runAllNonlinearAutopilotChecks.m'; ...
    'simulateC172sNonlinearAutopilot.m'; ...
    'c172sNonlinearAutopilotClosedLoopData.m'; ...
    'C172S_NonlinearAutopilot_V1.slx'; ...
    'FlightControlRegressionReport.txt'; ...
    'Nonlinear6DofRegressionReport.txt'; ...
    'NonlinearAutopilotRegressionReport.txt'};

present = cellfun(@(name) isfile(fullfile(releaseRoot,name)),requiredFiles);
missing = requiredFiles(~present);
assert(isempty(missing), ...
    'verifyC172sFlightDynamicsAutopilotLabInstallation:MissingFile', ...
    'Release file(s) missing: %s',strjoin(missing,', '));

lab = c172sFlightControlLabData();
assert(strcmp(lab.artifactRevision, ...
    'C172S-FLIGHT-CONTROL-LAB-V1-MATLAB-R4'), ...
    'verifyC172sFlightDynamicsAutopilotLabInstallation:LabRevision', ...
    'Unexpected laboratory artifact revision %s.',lab.artifactRevision);
assert(strcmp(lab.required.closedLoopArtifact, ...
    'NONLINEAR-AUTOPILOT-V1-CLOSED-LOOP-MATLAB-R1'), ...
    'verifyC172sFlightDynamicsAutopilotLabInstallation:BackendRevision', ...
    'Unexpected nonlinear-autopilot backend revision %s.', ...
    lab.required.closedLoopArtifact);

flightText = fileread(fullfile(releaseRoot, ...
    'FlightControlRegressionReport.txt'));
nonlinearText = fileread(fullfile(releaseRoot, ...
    'Nonlinear6DofRegressionReport.txt'));
autopilotText = fileread(fullfile(releaseRoot, ...
    'NonlinearAutopilotRegressionReport.txt'));

flightPass = ~isempty(regexp(flightText,'Passed:\s*18/18','once')) && ...
    ~isempty(regexp(flightText,'Failed:\s*0/18','once'));
nonlinearPass = ~isempty(regexp(nonlinearText, ...
    'Nonlinear gates passed:\s*7/7','once')) && ...
    ~isempty(regexp(nonlinearText, ...
    'Nonlinear gates failed:\s*0/7','once'));
autopilotPass = ~isempty(regexp(autopilotText, ...
    'Nonlinear-autopilot gates passed:\s*3/3','once')) && ...
    ~isempty(regexp(autopilotText, ...
    'Combined project evidence:\s*28/28 PASS','once'));
assert(flightPass && nonlinearPass && autopilotPass, ...
    'verifyC172sFlightDynamicsAutopilotLabInstallation:Evidence', ...
    'Saved regression evidence does not establish the frozen 28/28 chain.');

report = struct();
report.release = lab.release;
report.labArtifact = lab.artifactRevision;
report.backendArtifact = lab.required.closedLoopArtifact;
report.requiredFiles = numel(requiredFiles);
report.missingFiles = missing;
report.externalEvidence = '28/28 PASS';
report.simulinkAvailable = ~isempty(which('sim'));
report.controlSystemToolboxAvailable = ~isempty(which('ss'));
report.status = 'PASS';
report.publicBackends = strjoin(lab.execution.backends,', ');

fprintf('============================================================\n');
fprintf(' C172S FLIGHT DYNAMICS/AUTOPILOT LAB - INSTALLATION CHECK\n');
fprintf('============================================================\n');
fprintf('%-38s: %s\n','Release',report.release);
fprintf('%-38s: %s\n','Laboratory artifact',report.labArtifact);
fprintf('%-38s: %s\n','Frozen backend',report.backendArtifact);
fprintf('%-38s: %s\n','Public execution backends', ...
    report.publicBackends);
fprintf('%-38s: %d/%d present\n','Required release files', ...
    report.requiredFiles,report.requiredFiles);
fprintf('%-38s: %s\n','Saved external evidence', ...
    report.externalEvidence);
fprintf('%-38s: %s\n','Simulink available', ...
    yesNo(report.simulinkAvailable));
fprintf('%-38s: %s\n','Control System Toolbox available', ...
    yesNo(report.controlSystemToolboxAvailable));
fprintf('%-38s: %s\n\n','Installation preflight',report.status);
end

function text = yesNo(value)
if value
    text = 'YES';
else
    text = 'NO - some models/design audits will be unavailable';
end
end
